force-app/main/default/objects/SalesAccountSummary__c/SalesAccountSummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(고객별)</label>
    <nameField>
        <label>SalesAccountSummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAccountSummary__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>&quot;날짜&quot;+&quot;_&quot;+&quot;고객번호&quot;</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesAccountSummary__c/fields/TotalSalesProfit__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesProfit__c</fullName>
    <description>총 매출이익</description>
    <label>TotalSalesProfit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesMonthOfMASummary__c/SalesMonthOfMASummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(MA별)</label>
    <nameField>
        <label>SalesMonthOfMASummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/TotalSalesAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesAmount__c</fullName>
    <label>TotalSalesAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/TotalSalesProfit__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesProfit__c</fullName>
    <label>TotalSalesProfit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesProductSummary__c/SalesProductSummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(상품별)</label>
    <nameField>
        <label>SalesProductSummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesProductSummary__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <description>고객경로코드_상품대분류코드_상품중분류코드_상품소분류코드</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesProductSummary__c/fields/SalesDate__c.field-meta.xml
<CustomField>
    <fullName>SalesDate__c</fullName>
    <label>SalesDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesProductSummary__c/fields/TotalNetAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalNetAmount__c</fullName>
    <label>TotalNetAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesProductSummary__c/fields/TotalSalesAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesAmount__c</fullName>
    <description>총 매출액</description>
    <label>TotalSalesAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SalesSummaryDel_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-10-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class SalesSummaryDel_test {
    @TestSetup
    static void testSetup(){
        Account objAccount = TestObjectCreator.objExAccount;

        insert objAccount;

        SalesAccountSummary__c objSales = new SalesAccountSummary__c();

        //objSales.CRG_MA_ID__c = objUser.EmployeeNumber;
        objSales.SalesDate__c = Date.today().addMonths(-14);
        objSales.TotalNetAmount__c = 1000;
        objSales.TotalSalesAmount__c = 1100;
        objSales.TotalSalesProfit__c = 100;
        objSales.ExtId__c = 'test1234';

        insert objSales;

        SalesProductSummary__c objPro = new SalesProductSummary__c();

        //objPro.CRG_MA_ID__c = objUser.EmployeeNumber;
        objPro.SalesDate__c = Date.today().addMonths(-14);
        objPro.TotalNetAmount__c = 1000;
        objPro.TotalSalesAmount__c = 1100;
        objPro.TotalSalesProfit__c = 100;
        objPro.ExtId__c = 'test1234';

        insert objPro;

        SalesMonthOfMASummary__c objMA = new SalesMonthOfMASummary__c();

        //objMA.CRG_MA_ID__c = objUser.EmployeeNumber;
        objMA.SalesDate__c = Date.today().addMonths(-14);
        objMA.TotalNetAmount__c = 1000;
        objMA.TotalSalesAmount__c = 1100;
        objMA.TotalSalesProfit__c = 100;
        objMA.ExtId__c = 'test1234';

        insert objMA;

        User objUser = new User();
        objUser.Id = UserInfo.getUserId();
        objUser.EmployeeNumber = 'test1234';

        update objUser;


    }

    @isTest
    static void itShouldSC() {
        Test.startTest();

        String CRON_EXP = '0 45 0 1 * ? *';
        SalesSummaryDel_sc sc = new SalesSummaryDel_sc();
        System.schedule('매출합계(고객/상품/MA별) 데이터 삭제(SalesSummaryDel_ba) 매월 1일 00:45 Test', CRON_EXP, sc);
    }

    
    @isTest
    static void itShould() {
        Test.startTest();

        SalesSummaryDel_ba ba = new SalesSummaryDel_ba(null, null);
        Database.executeBatch(ba, 1000);

        Test.stopTest();
    }
}