force-app/main/default/objects/SalesAccountSummary__c/SalesAccountSummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(고객별)</label>
    <nameField>
        <label>SalesAccountSummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/ORDR_REAL_BUY_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>ORDR_REAL_BUY_UNPRC__c</fullName>
    <label>Operating Price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/RLSTK_UNIT_RLSTK_QTY__c.field-meta.xml
<CustomField>
    <fullName>RLSTK_UNIT_RLSTK_QTY__c</fullName>
    <label>Billing quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALE_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>SALE_UNPRC__c</fullName>
    <label>Operating unit price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_AT__c</fullName>
    <label>net sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLST__c.field-meta.xml
<CustomField>
    <fullName>SLST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesLedgerAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesAccountSummary_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-27-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class SalesAccountSummary_test {
    @TestSetup
    static void testSetup(){
        Account objAccount = TestObjectCreator.objExAccount;

        insert objAccount;

        SalesLedgerInformation__c objSales = new SalesLedgerInformation__c();

        objSales.SLST__c = objAccount.Id;
        objSales.SALES_YMD__c = Date.today().addDays(-1);
        objSales.SALE_UNPRC__c = 1000;
        objSales.ORDR_REAL_BUY_UNPRC__c = 500;
        objSales.RLSTK_UNIT_RLSTK_QTY__c = 1;
        objSales.SALES_AT__c = 500;

        insert objSales;
    }

    @isTest
    static void itShouldSC() {
        Test.startTest();

        String CRON_EXP1 = '0 0 1 * * ? *'; 
        SalesAccountSummary_sc sc = new SalesAccountSummary_sc(50);
        System.schedule('매출원장정보 고객 Summary(SalesAccountSummary__c) 01:00', CRON_EXP1, sc);
        Test.stopTest();
    }

    /*
    @isTest
    static void itShould() {
        Test.startTest();

        SalesAccountSummary_ba ba = new SalesAccountSummary_ba(null, null);
        Database.executeBatch(ba);

        Test.stopTest();
    }
    */
}