force-app/main/default/objects/API_Authenticationkey__mdt/API_Authenticationkey__mdt.object-meta.xml
<CustomObject>
    <label>API 인증키</label>
</CustomObject>

force-app/main/default/objects/API_Authenticationkey__mdt/fields/DateRange__c.field-meta.xml
<CustomField>
    <fullName>DateRange__c</fullName>
    <description>나라장터 입찰정보 호출 날짜 범위지정</description>
    <inlineHelpText>나라장터 입찰정보 호출 날짜 범위지정</inlineHelpText>
    <label>호출 날짜 범위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <default>true</default>
                <label>7</label>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Authenticationkey__mdt/fields/KeyValue__c.field-meta.xml
<CustomField>
    <fullName>KeyValue__c</fullName>
    <label>키값</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_SFDC_DATA_EAT_BID.cls
/**
 * @description       : 
 * @author            : AhnTaeJin(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 11-14-2022
 * @last modified by  : AhnTaeJin(tj.ahn@daeunextier.com)
**/
global with sharing class IF_SFDC_DATA_EAT_BID {
    global IF_SFDC_DATA_EAT_BID() {

    }

    global class Input {
        public Response response;
    }

    global class Response {
        public Header header;
        public Body body;
    }

    global class Header {
        public String resultCode;
        public String resultMsg;
        public String supOrganNm;
        public String supOrganCd;
        public String svcNm;
        public String supDt;
    }

    global class Body {
        public list<Item> items;
        public String numOfRows;
        public String pageNo;
        public String totalCount;
    }

    // global class Items {
    //     public List<Item> item;
    // }

    global class Item {
        public String etnBidNo;
        public String g2bYn;
        public String bidNm;
        public String etnBidSttNm;
        public String ancmDt;
        public String ancmHh;
        public String bizSortNm;
        public String etnBidYn;
        public String cntrctFormNm;
        public String limitConditionNm;
        public String purrNm;
        public String dmdOrganNm;
        public String bidOpenDt;
        public String bidOpenHh;
        public String bidOpenPlc;
        public String dmRegDt;
    }

    global class Output {
        public Result result;
        public ResultData resultData;
    }

    global class Result {
        public String resultCode;
        public String resultMessage;
    }

    global class ResultData {
    }
    public Output callOut(){
        IFUtil objIf = new IFUtil('IF_SFDC_DATA_EAT_BID');
        Output objOutput = new Output();
        Result objResult = new Result();
        ResultData objResultData = new ResultData();

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = 'callout success';
        String result = '';
        String getParameter = '';

        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        try {
            IFMaster__c ifMasterObj = [SELECT Id, Name, ContentType__c, Endpoint__c, Method__c FROM IFMaster__c WHERE Name = 'IF_SFDC_DATA_EAT_BID'];
            API_Authenticationkey__mdt authKey = [select KeyValue__c, DateRange__c, MasterLabel from API_Authenticationkey__mdt where MasterLabel = '공공데이터_Key'];
            Datetime strDate = system.today().addDays(-60);
            Datetime endDate = system.today();
            getParameter += 'eaTBidList';
            getParameter += '?numOfRows=2000';
            getParameter += '&pageNo=10';
            // getParameter += '&ancmStsrDt=20221004';
            // getParameter += '&ancmEndDt=20221114';
            getParameter += '&ancmStsrDt=' + strDate.format('yyyyMMdd');
            getParameter += '&ancmEndDt=' + endDate.format('yyyyMMdd');
            String encodedString = EncodingUtil.urlEncode('조달청', 'UTF-8');
            getParameter += '&useOrganNm=' + encodedString;
            getParameter += '&useOrganCd=1230000';
            getParameter += '&ServiceKey=' + authKey.KeyValue__c;
            System.debug(getParameter);
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(ifMasterObj.Endpoint__c + getParameter);
            System.debug(request.getEndpoint());
            request.setHeader('content-type', ifMasterObj.ContentType__c);
            request.setMethod(ifMasterObj.Method__c);
            request.setTimeout(110000);
            HttpResponse res = http.send(request);
            System.debug('res.getStatusCode(): ' + res.getStatusCode());
            if(res.getStatusCode() == 200) {
                String strJSON = XMLParser.xmlToJson(res.getBody());
                LogWrapper.responseBody = strJSON;
                System.debug('=======================calloutResult:::' + strJSON);
                Input input = (Input) JSON.deserialize(strJSON, Input.class);
                System.debug('input: ' + input);
            }
            
            
        } catch (Exception e) {
            strCode = '-1';
            strStatus = 'ERROR';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage();
            System.debug(strMessage);
        } finally {
            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = strMessage;
            LogWrapper.responseTime = Datetime.now();

            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            objOutput.result = objResult;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);
            
            objIf.setLog(LogWrapper);
        }

        return objOutput;
    }
}