force-app/main/default/objects/API_Authenticationkey__mdt/API_Authenticationkey__mdt.object-meta.xml
<CustomObject>
    <label>API 인증키</label>
</CustomObject>

force-app/main/default/objects/API_Authenticationkey__mdt/fields/DateRange__c.field-meta.xml
<CustomField>
    <fullName>DateRange__c</fullName>
    <description>나라장터 입찰정보 호출 날짜 범위지정</description>
    <inlineHelpText>나라장터 입찰정보 호출 날짜 범위지정</inlineHelpText>
    <label>호출 날짜 범위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7</fullName>
                <default>true</default>
                <label>7</label>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Authenticationkey__mdt/fields/KeyValue__c.field-meta.xml
<CustomField>
    <fullName>KeyValue__c</fullName>
    <label>키값</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_API_NARA_TENDER_INFO_TEST.cls
/**
 * @description       : 
 * @author            : AhnTaeJin(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 08-08-2022
 * @last modified by  : AhnTaeJin(tj.ahn@daeunextier.com)
**/
public with sharing class IF_API_NARA_TENDER_INFO_TEST {
    public IF_API_NARA_TENDER_INFO_TEST() {}
    public class Input{
        public Res response;
    }

    public class Output {
        public Result result;
    }

    public class Result {
        public String resultCode;
        public String resultMessage;
        public List<Items> resultItems;
    }

    public class Res{
        public Body body;
    }

    public class Body{
        public String totalCount;
        public String pageNo;
        public String numOfRows;
        public List<Items> items;
    }

    public class Items{
        public String ntceKindNm;
        public String bidNtceNo;
        public String bidNtceNm;
        public String ntceInsttNm;
        public String ntceInsttOfclNm;
        public String ntceInsttOfclTelNo;
        public String ntceInsttOfclEmailAdrs;
        public String bidMethdNm;
        public String cntrctCnclsMthdNm;
        public String rbidPermsnYn;
        public String bidBeginDt;
        public String opengDt;
        public String bidClseDt;
        public String opengPlce;
        public String bidQlfctRgstDt;
        public String prearngPrceDcsnMthdNm;
        public String asignBdgtAmt;
        public String cmmnSpldmdCorpRgnLmtYn;
        public String indstrytyLmtYn;
        public String bidNtceDtlUrl;
    }
    public Output callOut(){
        Result objResult = new Result();
        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();


        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = 'callout success';
        String result = '';
        String getRquest = '';
        String today = String.valueOf(Datetime.now().format('yyyyMMdd')) + '0000';
        Datetime endDt = Datetime.now();
        System.debug('=====================today:::'+today);
        
        try {
            IFMaster__c i = [SELECT Id, Name, ContentType__c, Endpoint__c, Method__c FROM IFMaster__c WHERE Name = 'IF_API_NARA_TENDER_INFO_TEST'];
            API_Authenticationkey__mdt authKey = [select KeyValue__c, DateRange__c, MasterLabel from API_Authenticationkey__mdt where MasterLabel = '공공데이터_Key'];
            endDt += Integer.valueof(authKey.DateRange__c);
            System.debug('==================enddt:::' + endDt.format('yyyyMMdd'));

            getRquest += '/getBidPblancListInfoThngPPSSrch';
            getRquest += '?inqryDiv=2';
            getRquest += '&type=json';
            getRquest += '&inqryBgnDt=' + today;
            getRquest += '&inqryEndDt=' + endDt.format('yyyyMMdd')+'0000';
            String encodedString = EncodingUtil.urlEncode('식자재', 'UTF-8');
            System.debug('=====================encodedString:::'+encodedString);
            getRquest += '&bidNtceNm=' + encodedString;
            getRquest += '&pageNo=1';
            getRquest += '&numOfRows=500';
            getRquest += '&ServiceKey=' + authKey.KeyValue__c;
            System.debug('======================getRquest:::' + getRquest);

            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(i.Endpoint__c + getRquest);
            request.setHeader('content-type', i.ContentType__c);
            request.setMethod(i.Method__c);
            request.setTimeout(110000);
            HttpResponse res = http.send(request);

            if(res.getStatusCode() == 200) {
                // System.debug('=============================getbody:::' + res.getBody());
                result = res.getBody();
                Input input = (Input) JSON.deserialize(res.getBody(), Input.class);
                result = String.valueof(input);
                System.debug('==========================totalCount:::'+input.response.body.totalCount);
                for (Items item : input.response.body.items) {
                    System.debug('======================item:::'+ item);
                }
                objResult.resultItems = input.response.body.items;
            }else {
                strCode = '-1';
                strStatus = 'ERROR';
                strMessage = 'httpcallout error';
            }

        } catch (Exception e) {
            strCode = '-1';
            strStatus = 'ERROR';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage();
            System.debug(strMessage);
        } finally {
            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            
            objOutput.result = objResult;

            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = 'strMessage:::' + strMessage;
            LogWrapper.responseTime = Datetime.now();
            LogWrapper.requestBody = getRquest;
            LogWrapper.responseBody = result;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);
            
            IFUtil objIF = new IFUtil('IF_API_NARA_TENDER_INFO_TEST');
            objIF.setLog(LogWrapper);
        }
        return objOutput;
    }
}