force-app/main/default/objects/ORDER_D__c/ORDER_D__c.object-meta.xml
<CustomObject>
    <label>주문내역상세</label>
    <nameField>
        <label>주문내역상세 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ORDER_D__c/fields/ORDER_H__c.field-meta.xml
<CustomField>
    <fullName>ORDER_H__c</fullName>
    <label>주문내역</label>
    <referenceTo>ORDER_H__c</referenceTo>
    <relationshipLabel>주문내역상세</relationshipLabel>
    <relationshipName>ORDER_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/ORDER_H__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>OH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_D__c/RELEASE_D__c.object-meta.xml
<CustomObject>
    <label>출고내역상세</label>
    <nameField>
        <label>상품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_D__c/fields/RELEASE_H__c.field-meta.xml
<CustomField>
    <fullName>RELEASE_H__c</fullName>
    <label>출고내역</label>
    <referenceTo>RELEASE_H__c</referenceTo>
    <relationshipLabel>출고내역상세</relationshipLabel>
    <relationshipName>RELEASE_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/RELEASE_H__c.object-meta.xml
<CustomObject>
    <label>출고내역</label>
    <nameField>
        <displayFormat>RH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/STOCK__c/STOCK__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StockChangeLog__c/StockChangeLog__c.object-meta.xml
<CustomObject>
    <label>재고변경내역</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>재고변경내역번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StockChangeLog__c/fields/STOCK__c.field-meta.xml
<CustomField>
    <fullName>STOCK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>재고</label>
    <referenceTo>STOCK__c</referenceTo>
    <relationshipLabel>재고변경내역</relationshipLabel>
    <relationshipName>StockChangeLog</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestObjectCreator_test.cls
/************************************************************************************
 * File Name   : TestObjectCreator_test.cls
 * Author      : Yohan.Kang
 * Date        : 2019.10.24
 * Target      : TestObjectCreator.cls
 * Description : 테스트 클래스에서 사용하는 테스트용 오브젝트 반환
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
   1.0      2019.10.24      Yohan.Kang      Create
*************************************************************************************/

@isTest
private class TestObjectCreator_test {
        @isTest
        static void dotest() {

                // 입고
                Order_H__c objOrder_H = TestObjectCreator.getobjOrder_H('2165209086');
                insert objOrder_H;
                Order_D__c objOrder_D = TestObjectCreator.getobjOrder_D('백설 밀가루(강력_1등 20Kg/EA)', '100070', '10', objOrder_H);
                
                // 출고
                Release_H__c objRelease_H = TestObjectCreator.getObjRelease_H('2000000154');
                insert objRelease_H;
                Release_D__c objRelease_D = TestObjectCreator.getObjRelease_D('백설 밀가루(강력_1등 20Kg/EA)', '100070', '10', objRelease_H);

                // 재고
                Stock__c objStock = TestObjectCreator.getObjStock_D('test', '1000012');
                insert objStock;
                StockChangeLog__c objstcLog = TestObjectCreator.getObjStockChangeLog(objStock);
	}

        @isTest
        static void itShould() {
                System.debug(TestObjectCreator.objExAccount);
                System.debug(TestObjectCreator.objHealthAccount);
                System.debug(TestObjectCreator.objSchoolAccount);
                System.debug(TestObjectCreator.objPricebook);
                System.debug(TestObjectCreator.objProduct);
                System.debug(TestObjectCreator.objVOC);
                System.debug(TestObjectCreator.objVOCLineItem);
                System.debug(TestObjectCreator.objPricebookEntry);
                System.debug(TestObjectCreator.objOpenBalance);
                System.debug(TestObjectCreator.objSuggestBalance);
                
                
	}
}