force-app/main/default/objects/ORDER_D__c/ORDER_D__c.object-meta.xml
<CustomObject>
    <label>주문내역상세</label>
    <nameField>
        <label>주문내역상세 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ORDER_D__c/fields/BUDAT__c.field-meta.xml
<CustomField>
    <fullName>BUDAT__c</fullName>
    <label>전표 전기 일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <label>주문번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELN_R__c.field-meta.xml
<CustomField>
    <fullName>EBELN_R__c</fullName>
    <label>3000to5000 STO번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELP__c.field-meta.xml
<CustomField>
    <fullName>EBELP__c</fullName>
    <label>주문항번</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EINDT__c.field-meta.xml
<CustomField>
    <fullName>EINDT__c</fullName>
    <label>납품일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/LOEKZ__c.field-meta.xml
<CustomField>
    <fullName>LOEKZ__c</fullName>
    <label>삭제 표시</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>자재번호</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>오더단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>오더수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/ORDER_H__c.field-meta.xml
<CustomField>
    <fullName>ORDER_H__c</fullName>
    <label>주문내역</label>
    <referenceTo>ORDER_H__c</referenceTo>
    <relationshipLabel>주문내역상세</relationshipLabel>
    <relationshipName>ORDER_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/RETPO__c.field-meta.xml
<CustomField>
    <fullName>RETPO__c</fullName>
    <label>반품품목</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/WERKS__c.field-meta.xml
<CustomField>
    <fullName>WERKS__c</fullName>
    <label>플랜트</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WERKS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/ORDER_H__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>OH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ORDER_H__c/fields/CHECK__c.field-meta.xml
<CustomField>
    <fullName>CHECK__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>입고확인</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/CONFIRM__c.field-meta.xml
<CustomField>
    <fullName>CONFIRM__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>확정</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <externalId>true</externalId>
    <label>주문번호_3000센터</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/EBELN_R__c.field-meta.xml
<CustomField>
    <fullName>EBELN_R__c</fullName>
    <label>주문번호_5000센터</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>전송일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/RESWK__c.field-meta.xml
<CustomField>
    <fullName>RESWK__c</fullName>
    <label>출고플랜트</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/SHIP_TYP__c.field-meta.xml
<CustomField>
    <fullName>SHIP_TYP__c</fullName>
    <label>직배송여부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>배송</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>직송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/SND_YN__c.field-meta.xml
<CustomField>
    <fullName>SND_YN__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>전송성공여부 S/E</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/XDATS__c.field-meta.xml
<CustomField>
    <fullName>XDATS__c</fullName>
    <label>호출날짜 (YYYYMMDD)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/XTIMS__c.field-meta.xml
<CustomField>
    <fullName>XTIMS__c</fullName>
    <label>호출시간 (HHMISS)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/RELEASE_D__c.object-meta.xml
<CustomObject>
    <label>출고내역상세</label>
    <nameField>
        <label>상품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_D__c/fields/CHARG__c.field-meta.xml
<CustomField>
    <fullName>CHARG__c</fullName>
    <label>배치번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <label>이체오더번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/EBELP__c.field-meta.xml
<CustomField>
    <fullName>EBELP__c</fullName>
    <label>이체오더품목</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>전송일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재 내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>자재 번호</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>구매 오더 단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>구매 오더 수량</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RAUBE__c.field-meta.xml
<CustomField>
    <fullName>RAUBE__c</fullName>
    <label>저장조건</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RAUBE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RELEASE_H__c.field-meta.xml
<CustomField>
    <fullName>RELEASE_H__c</fullName>
    <label>출고내역</label>
    <referenceTo>RELEASE_H__c</referenceTo>
    <relationshipLabel>출고내역상세</relationshipLabel>
    <relationshipName>RELEASE_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RETPO__c.field-meta.xml
<CustomField>
    <fullName>RETPO__c</fullName>
    <label>반품 품목</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/RELEASE_H__c.object-meta.xml
<CustomObject>
    <label>출고내역</label>
    <nameField>
        <displayFormat>RH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_H__c/fields/CHECK__c.field-meta.xml
<CustomField>
    <fullName>CHECK__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>출고확인</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/CONFIRM__c.field-meta.xml
<CustomField>
    <fullName>CONFIRM__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>확정</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <externalId>true</externalId>
    <label>이체오더번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>수신일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/SND_YN__c.field-meta.xml
<CustomField>
    <fullName>SND_YN__c</fullName>
    <label>전송성공여부 S/E</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/XDATS__c.field-meta.xml
<CustomField>
    <fullName>XDATS__c</fullName>
    <label>수신날짜 (YYYYMMDD)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/XTIMS__c.field-meta.xml
<CustomField>
    <fullName>XTIMS__c</fullName>
    <label>수신시간 (HHMMSS)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/STOCK__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/STOCK__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>상품코드</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>재고수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/WERKS__c.field-meta.xml
<CustomField>
    <fullName>WERKS__c</fullName>
    <label>플랜트</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WERKS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LGORT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>상온 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>냉장 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>냉동 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>원자재 불량 창고</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>제품 장기재고 창고</label>
    </customValue>
    <customValue>
        <fullName>3100</fullName>
        <label>상온 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3200</fullName>
        <label>냉장 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3300</fullName>
        <label>냉동 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3900</fullName>
        <label>제품 불량창고</label>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
        <label>정상품창고</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>불량품창고</label>
    </customValue>
    <customValue>
        <fullName>L091</fullName>
        <label>센트럴키친중부세척센터근태점</label>
    </customValue>
    <masterLabel>저장위치</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RAUBE.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>실온</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>냉장</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>냉동</label>
    </customValue>
    <masterLabel>저장조건</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WERKS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5000</fullName>
        <label>센트럴키친중부점</label>
    </customValue>
    <customValue>
        <fullName>2600</fullName>
        <label>이천물류센터</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>FS점포</label>
    </customValue>
    <masterLabel>플랜트</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CK_InAndOutMgmtController.cls
/*
* ==================================================================================
*   File Name   : CK_InAndOutMgmtController.cls
*   Author      : Minje.kim
*   Date        : 2022.05.09
*   Tester      : CK_InAndOutMgmtController_test.cls
*   Description : CK 입출고 관리 Controller
*   Modification Log
* ==================================================================================
*   Ver     Date          Author          Modification
* ==================================================================================
*   1.0     2022.05.09    Minje.kim       Create
* ==================================================================================
*/

public with sharing class CK_InAndOutMgmtController {


    @AuraEnabled
    public static List<SObject> doGetData(Map<String, Object> mapParam) {

        try{
            
            Map<String, Object> mapInitData = new Map<String, Object>{            
                'SHIP_TYP__c' => getPicklistValues('ORDER_H__c', 'SHIP_TYP__c', true, false)
            };

            List<SObject> listData;

            String screenStatus = String.valueOf(mapParam.get('screenStatus')) ;
            
            String Query = '';
            // 입고
            if(screenStatus == 'Import'){
                Query += 'SELECT  Id, Name, tolabel(SHIP_TYP__c), IFDATE__c, EBELN__c, EBELN_R__c, RESWK__c, CHECK__c, CONFIRM__c, SND_YN__c, XDATS__c, XTIMS__c, ';
                Query += '(SELECT Id, Name, EBELN__c, EBELP__c, LOEKZ__c, WERKS__c, LGORT__c, MATNR__c, MAKTX__c, MENGE__c, MEINS__c, RAUBE__c, EINDT__c, RETPO__c, BUDAT__c, ORDER_H__c FROM ORDER_D__r WHERE MENGE__c > 0 ORDER BY EBELP__c)  ';
                Query += 'FROM   ORDER_H__c  ';
                Query += 'WHERE  CONFIRM__c = \'N\'  ';
                Query += ' ORDER BY  EBELN__c' ;
            }
            // 입고
            else if (screenStatus == 'Export'){
                Query += 'SELECT  Id, Name, EBELN__c, CHECK__c, CONFIRM__c, SND_YN__c, XDATS__c, XTIMS__c, ';
                Query += '(SELECT Id, Name, EBELN__c, EBELP__c, WERKS__c, LGORT__c, MATNR__c, MAKTX__c, CHARG__c, MENGE__c, MEINS__c, RAUBE__c, EINDT__c, RETPO__c FROM RELEASE_D__r WHERE MENGE__c > 0 ORDER BY EBELP__c)  ';
                Query += 'FROM   RELEASE_H__c ';
                Query += 'WHERE  CONFIRM__c = \'N\'  ';
                Query += ' ORDER BY  EBELN__c' ;
            }
            system.debug('Query ::::: ' +Query);
            listData = Database.query(Query);
            
            return listData;
        }
        catch(Exception e){
            system.debug('CK_InAndOutMgmtController doGetData error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')');
            throw new AuraHandledException(e.getMessage() + ' (Line : ' + e.getLineNumber() + ')');
        }
        
    }

    
    // @AuraEnabled
    // public static List<Object> doSaveData(Map<String, Object> mapParam) {

    @AuraEnabled
    public static void doSaveData(List<SObject> listData, List<SObject> listSubData) {
        system.debug('listData ::::: ' + listData);
        system.debug('listSubData ::::: ' + listSubData);

        try{
            database.update(listData);
            database.update(listSubData); 
        }
        catch(Exception e){
            system.debug('CK_InAndOutMgmtController doGetData error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')');
            throw new AuraHandledException(e.getMessage() + ' (Line : ' + e.getLineNumber() + ')');
        }
    }

    
    @AuraEnabled
    public static Map<String, Object> doConfirmData(String screenStatus) {

        String resultCode = '';
        String resultMessage = '';
        try{
            if (screenStatus == 'Import'){
                IF_SFDC_SAP_SAND_ORDER.Output outputObj = new IF_SFDC_SAP_SAND_ORDER.Output();
                IF_SFDC_SAP_SAND_ORDER ifORDER = new IF_SFDC_SAP_SAND_ORDER();

                List<Order_H__C> listCheckOrder_H = [
                    SELECT IFDATE__c, EBELN__c, EBELN_R__c, RESWK__c, CHECK__c, SHIP_TYP__c, CONFIRM__c, SND_YN__c, XDATS__c, XTIMS__c
                    FROM Order_H__C
                    WHERE CHECK__c = 'Y' AND EBELN_R__c = ''
                ];

                if( listCheckOrder_H.isEmpty()){
                    resultCode = '-1';
                    resultMessage = '확정대상이 없습니다.';
                }
                else{
                    if(!Test.isRunningTest()) {
                        outputObj = ifORDER.callOut();
                    }
                    system.debug('Import outputObj ::' + outputObj);
    
                    resultCode = outputObj.result.resultCode;
                    resultMessage = outputObj.result.resultMessage;
                }
            }
            else if (screenStatus == 'Export'){
                IF_SFDC_SAP_SAND_RELEASE.Output outputObj = new IF_SFDC_SAP_SAND_RELEASE.Output();
                IF_SFDC_SAP_SAND_RELEASE ifRELEASE = new IF_SFDC_SAP_SAND_RELEASE();

                if(!Test.isRunningTest()) {
                    outputObj = ifRELEASE.callOut();
                }
                system.debug('Export outputObj ::' + outputObj);

                resultCode = outputObj.result.resultCode;
                resultMessage = outputObj.result.resultMessage;
            }
            else {
                resultCode = '-1';
                resultMessage = 'Unknown Error';
            }
        }
        catch(Exception e){
            system.debug('CK_InAndOutMgmtController doConfirmData error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')');    
            resultCode = '-1';
            resultMessage ='CK_InAndOutMgmtController doConfirmData error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')';
        }

        Map<String, object> mapResult = new Map<String, object>{
            'resultCode' => resultCode,
            'resultMessage' => resultMessage
        };
        return mapResult;
    }

    // @InvocableMethod(label='Send STOCK to SAP')
    // public static void doSendStock(List<STOCK__c> listTarget) {


    //     String resultCode = '';
    //     String resultMessage = '';
    //     try{
    //         IF_SFDC_SAP_SAND_STOCK.Output outputObj = new IF_SFDC_SAP_SAND_STOCK.Output();
    //         IF_SFDC_SAP_SAND_STOCK ifSTOCK = new IF_SFDC_SAP_SAND_STOCK();
            
    //         outputObj = ifSTOCK.callOut(listTarget);
    //         system.debug('Stock outputObj ::' + outputObj);

    //         resultCode = outputObj.result.resultCode;
    //         resultMessage = outputObj.result.resultMessage;
    //     }
    //     catch(Exception e){
    //         resultCode = '-1';
    //         resultMessage ='CK_InAndOutMgmtController doSendStock error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')';
    //         system.debug('CODE :: ' + resultCode + ' : ' + resultMessage);    
    //     }
    // }


    @AuraEnabled
	public static List<Map<String, String>> getPicklistValues(String ObjectApi_name, String Field_name, Boolean isNone, Boolean isLabelToValue){
		List<Map<String, String>> lstPickvals = new List<Map<String, String>>();

		//String strNoneLabel = Label.Text_None;

		String strNoneLabel = 'None';

		if(isNone) {
			lstPickvals.add(new Map<String, String>{'value' => '', 'label' => '-- '+strNoneLabel+' --'});
		}

		Schema.SObjectType targetType = Schema.getGlobalDescribe().get(ObjectApi_name);
		Sobject Object_name = targetType.newSObject();
		Schema.sObjectType sobject_type = Object_name.getSObjectType();
		Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
		Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
		List<Schema.PicklistEntry> pick_list_values = field_map.get(Field_name).getDescribe().getPickListValues();    

		for (Schema.PicklistEntry a : pick_list_values) {

			if(isLabelToValue) {
				lstPickvals.add(new Map<String, String>{'value' => a.getValue(), 'label' => a.getValue()});
			}else {
				lstPickvals.add(new Map<String, String>{'value' => a.getValue(), 'label' => a.getLabel()});
			}      
		}

		return lstPickvals;
	}
}