force-app/main/default/objects/ORDER_D__c/ORDER_D__c.object-meta.xml
<CustomObject>
    <label>주문내역상세</label>
    <nameField>
        <label>주문내역상세 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ORDER_D__c/fields/BUDAT__c.field-meta.xml
<CustomField>
    <fullName>BUDAT__c</fullName>
    <label>전표 전기 일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <label>주문번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELN_R__c.field-meta.xml
<CustomField>
    <fullName>EBELN_R__c</fullName>
    <label>3000to5000 STO번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELP__c.field-meta.xml
<CustomField>
    <fullName>EBELP__c</fullName>
    <label>주문항번</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EBELP_R__c.field-meta.xml
<CustomField>
    <fullName>EBELP_R__c</fullName>
    <label>3000to5000 STO품목번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/EINDT__c.field-meta.xml
<CustomField>
    <fullName>EINDT__c</fullName>
    <label>납품일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/LIFNR__c.field-meta.xml
<CustomField>
    <fullName>LIFNR__c</fullName>
    <label>공급업체</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/LOEKZ__c.field-meta.xml
<CustomField>
    <fullName>LOEKZ__c</fullName>
    <label>삭제 표시</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>자재번호</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>오더단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>오더수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/ORDER_H__c.field-meta.xml
<CustomField>
    <fullName>ORDER_H__c</fullName>
    <label>주문내역</label>
    <referenceTo>ORDER_H__c</referenceTo>
    <relationshipLabel>주문내역상세</relationshipLabel>
    <relationshipName>ORDER_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/ORDERDKEY__c.field-meta.xml
<CustomField>
    <fullName>ORDERDKEY__c</fullName>
    <externalId>true</externalId>
    <label>ckwms키</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/RETPO__c.field-meta.xml
<CustomField>
    <fullName>RETPO__c</fullName>
    <label>반품품목</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/WERKS__c.field-meta.xml
<CustomField>
    <fullName>WERKS__c</fullName>
    <label>플랜트</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WERKS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_D__c/fields/xmsgs__c.field-meta.xml
<CustomField>
    <fullName>xmsgs__c</fullName>
    <label>메세지</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/ORDER_H__c.object-meta.xml
<CustomObject>
    <label>주문내역</label>
    <nameField>
        <displayFormat>OH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ORDER_H__c/fields/CHECK__c.field-meta.xml
<CustomField>
    <fullName>CHECK__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>입고확인</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/CONFIRM__c.field-meta.xml
<CustomField>
    <fullName>CONFIRM__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>확정</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <externalId>true</externalId>
    <label>주문번호_3000센터</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/EBELN_R__c.field-meta.xml
<CustomField>
    <fullName>EBELN_R__c</fullName>
    <label>주문번호_5000센터</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>전송일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/RESWK__c.field-meta.xml
<CustomField>
    <fullName>RESWK__c</fullName>
    <label>출고플랜트</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/SHIP_TYP__c.field-meta.xml
<CustomField>
    <fullName>SHIP_TYP__c</fullName>
    <label>직배송여부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>배송</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>직송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/SND_YN__c.field-meta.xml
<CustomField>
    <fullName>SND_YN__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>전송성공여부 S/E</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/XDATS__c.field-meta.xml
<CustomField>
    <fullName>XDATS__c</fullName>
    <label>호출날짜 (YYYYMMDD)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORDER_H__c/fields/XTIMS__c.field-meta.xml
<CustomField>
    <fullName>XTIMS__c</fullName>
    <label>호출시간 (HHMISS)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WERKS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5000</fullName>
        <label>센트럴키친중부점</label>
    </customValue>
    <customValue>
        <fullName>2600</fullName>
        <label>이천물류센터</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>FS점포</label>
    </customValue>
    <masterLabel>플랜트</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IF_SFDC_SAP_SAND_ORDER.cls
/**
 * @description       : 
 * @author            : 안태진
 * @group             : 
 * @last modified on  : 06-24-2022
 * @last modified by  : 안태진(tj.ahn@daeunextier.com)
**/
public class IF_SFDC_SAP_SAND_ORDER {

    callCjCkSoapVer_2.sapCkInParameter inputData = new callCjCkSoapVer_2.sapCkInParameter();
    
    public class Input {
        public List<OrderH> header;
        public List<OrderD> detail;
    }

    public class Output {
        public Result result;
    }

    public class Result {
        public String resultCode;
        public String resultMessage;
        public String soapCallResult;
    }

    public class OrderH{
        public String ZTIMS;
        public String IFDATE;
        public String EBELN;
        public String EBELN_R;
        public String RESWK;
        public String SND_YN;
        public String SHIP_TYP;
        public String XDATS;
        public String XTIMS;
        public String XMSGS;
    }

    public class OrderD{
        public String ZTIMS;
        public String EBELN;
        public String EBELP;
        public String EBELN_R;
        public String EBELP_R;
        public String LIFNR;
        public String LOEKZ;
        public String WERKS;
        public String LGORT;
        public String MATNR;
        public String MAKTX;
        public String MENGE;
        public String MEINS;
        public String RAUBE;
        public String EINDT;
        public String RETPO;
        public String BUDAT;
        public String XMSGS;
        public String ORDERDKEY;
    }

    public Output callOut() {
        List<Order_H__C> inputHeader = new List<ORDER_H__C>(); 
        List<Order_D__C> inputDetail = new List<ORDER_D__C>(); 
        List<Order_H__C> updateHList = new List<ORDER_H__C>(); 
        List<Order_D__C> updateDList = new List<ORDER_D__C>(); 
        Map<String,Object> inputMap = new Map<String,Object>();

        Result objResult = new Result();
        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = '확정 데이터 전송 성공';
        String result = '';
        String inputString = '';

        try {
            inputHeader = [
                SELECT IFDATE__c, EBELN__c, EBELN_R__c, RESWK__c, CHECK__c, SHIP_TYP__c, CONFIRM__c, SND_YN__c, XDATS__c, XTIMS__c
                FROM Order_H__C
                WHERE CHECK__c = 'Y' AND EBELN_R__c = ''
                ];
            inputDetail = [
                SELECT EBELN__c, EBELP__c, LOEKZ__c, WERKS__c, LIFNR__c, LGORT__c, MATNR__c, MAKTX__c, MENGE__c, MEINS__c, RAUBE__c, EINDT__c, RETPO__c, BUDAT__c, ORDER_H__c, ORDERDKEY__c
                FROM Order_D__C
                WHERE ORDER_H__r.CHECK__c = 'Y' AND ORDER_H__r.EBELN_R__c = ''
            ];

            inputMap.put('header', inputHeader);
            inputMap.put('detail', inputDetail);
            inputMap.put('IF_ID', 'CK0002');

            inputString = JSON.serialize(inputMap);
            inputData.requestMsg = inputString;

            System.debug('========================requestMsg :::'+inputData.requestMsg);

            callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort soap = new callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort();
            result = soap.callSapCkProcedure(inputData);
            System.debug('result======================= :::'+result);

            if(result == '' || result == null) {
                strStatus = 'ERROR';
                strCode = '0003';
                strMessage = '확정 데이터 전송 실패';
            }else {
                Input input = (Input)JSON.deserialize(result, Input.class);

                if (input.header == null || input.header.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0001';
                    strMessage = '확정 데이터 전송 실패';
                }else {
                    Map<String, Order_H__c> mapUpOrder = new Map<String, Order_H__c>();
                    Map<String, Order_D__c> mapUpDOrder = new Map<String, Order_D__c>();
    
                    if (input.header <> null && input.header.size() > 0) {
                        for (Order_H__c obj : inputHeader) {
                            mapUpOrder.put(obj.EBELN__C, obj);
                        }
                        if (!inputHeader.isEmpty()) {
                            for (OrderH obj : input.header) {
                                Order_H__c orderHObj = new Order_H__c();
                                orderHObj = mapUpOrder.get(obj.EBELN);
                                if (obj.XMSGS == '') {
                                    orderHObj.CONFIRM__c = 'Y';
                                    // orderHObj.EBELN_R__C = obj.EBELN_R;
                                }
                                orderHObj.EBELN_R__C = obj.EBELN_R;
                                orderHObj.xmsgs__c = obj.XMSGS;
                                updateHList.add(orderHObj);
                            }
                            System.debug(('====================mapUpOrder:::' + mapUpOrder));
                            System.debug(('====================updateHList:::' + updateHList));
                            update updateHList;
                        }
                        for (Order_D__c obj : inputDetail) {
                            mapUpDOrder.put(obj.EBELN__C, obj);
                        }
                        if(!inputDetail.isEmpty()){
                            for (OrderD obj : input.detail) {
                                Order_D__c orderDObj = new Order_D__c();
                                orderDObj = mapUpDOrder.get(obj.EBELN);
                                // if(obj.XMSGS == ''){
                                //     orderDObj.EBELN_R__C = obj.EBELN_R;
                                //     orderDObj.EBELP_R__c = obj.EBELP_R;
                                // }
                                orderDObj.EBELN_R__C = obj.EBELN_R;
                                orderDObj.EBELP_R__c = obj.EBELP_R;
                                orderDObj.xmsgs__c = obj.XMSGS;
                            }
                            System.debug(('====================mapUpDOrder:::' + mapUpDOrder));
                            System.debug(('====================updateDList:::' + updateDList));
                            update updateDList;
                        }
                    }
                }    
            }
        }catch (Exception e) {
            strCode = '-1';
            strStatus = 'ERROR';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage(); 
            System.debug(strMessage);
        }finally{

            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            objResult.soapCallResult = result;

            objOutput.result = objResult;

            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = 'strMessage:::' + strMessage + ':::soapCallResult:::' + result;
            LogWrapper.responseTime = Datetime.now();
            LogWrapper.requestBody = inputString;
            LogWrapper.responseBody = result;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);
            
            IFUtil objIF = new IFUtil('IF_SFDC_SAP_SAND_ORDER');
            objIF.setLog(LogWrapper);
        }
        return objOutput;
    }
}