force-app/main/default/objects/RELEASE_D__c/RELEASE_D__c.object-meta.xml
<CustomObject>
    <label>출고내역상세</label>
    <nameField>
        <label>상품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_D__c/fields/CHARG__c.field-meta.xml
<CustomField>
    <fullName>CHARG__c</fullName>
    <label>배치번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <label>이체오더번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/EBELP__c.field-meta.xml
<CustomField>
    <fullName>EBELP__c</fullName>
    <label>이체오더품목</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>전송일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재 내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>자재 번호</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>구매 오더 단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>구매 오더 수량</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/PBUDAT__c.field-meta.xml
<CustomField>
    <fullName>PBUDAT__c</fullName>
    <label>생산일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/PSMNG__c.field-meta.xml
<CustomField>
    <fullName>PSMNG__c</fullName>
    <label>생산수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/R_PSMNG__c.field-meta.xml
<CustomField>
    <fullName>R_PSMNG__c</fullName>
    <label>출고제한수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RAUBE__c.field-meta.xml
<CustomField>
    <fullName>RAUBE__c</fullName>
    <label>저장조건</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RAUBE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RELEASE_H__c.field-meta.xml
<CustomField>
    <fullName>RELEASE_H__c</fullName>
    <label>출고내역</label>
    <referenceTo>RELEASE_H__c</referenceTo>
    <relationshipLabel>출고내역상세</relationshipLabel>
    <relationshipName>RELEASE_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RELEASEDKEY__c.field-meta.xml
<CustomField>
    <fullName>RELEASEDKEY__c</fullName>
    <externalId>true</externalId>
    <label>ckwms키</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RETPO__c.field-meta.xml
<CustomField>
    <fullName>RETPO__c</fullName>
    <label>반품 품목</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/xstat__c.field-meta.xml
<CustomField>
    <fullName>xstat__c</fullName>
    <label>xstat</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/RELEASE_H__c.object-meta.xml
<CustomObject>
    <label>출고내역</label>
    <nameField>
        <displayFormat>RH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_H__c/fields/CHECK__c.field-meta.xml
<CustomField>
    <fullName>CHECK__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>출고확인</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/CONFIRM__c.field-meta.xml
<CustomField>
    <fullName>CONFIRM__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>확정</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <externalId>true</externalId>
    <label>이체오더번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>수신일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/SND_YN__c.field-meta.xml
<CustomField>
    <fullName>SND_YN__c</fullName>
    <label>전송성공여부 S/E</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/XDATS__c.field-meta.xml
<CustomField>
    <fullName>XDATS__c</fullName>
    <label>수신날짜 (YYYYMMDD)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/xstat__c.field-meta.xml
<CustomField>
    <fullName>xstat__c</fullName>
    <label>xstat</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/XTIMS__c.field-meta.xml
<CustomField>
    <fullName>XTIMS__c</fullName>
    <label>수신시간 (HHMMSS)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LGORT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>상온 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>냉장 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>냉동 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>원자재 불량 창고</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>제품 장기재고 창고</label>
    </customValue>
    <customValue>
        <fullName>3100</fullName>
        <label>상온 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3200</fullName>
        <label>냉장 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3300</fullName>
        <label>냉동 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3900</fullName>
        <label>제품 불량창고</label>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
        <label>정상품창고</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>불량품창고</label>
    </customValue>
    <customValue>
        <fullName>L091</fullName>
        <label>센트럴키친중부세척센터근태점</label>
    </customValue>
    <masterLabel>저장위치</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RAUBE.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>실온</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>냉장</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>냉동</label>
    </customValue>
    <masterLabel>저장조건</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IF_SFDC_SAP_SAND_RELEASE.cls
/**
 * @description       : 
 * @author            : 안태진
 * @group             : 
 * @last modified on  : 06-24-2022
 * @last modified by  : 안태진(tj.ahn@daeunextier.com)
**/
public class IF_SFDC_SAP_SAND_RELEASE {
    public IF_SFDC_SAP_SAND_RELEASE() {}

    public class Input {
        public List<ReleaseH> header;
        public List<ReleaseD> detail;
    }

    public class Output {
        public Result result;
    }

    public class Result {
        public String resultCode;
        public String resultMessage;
        public String soapCallResult;
    }

    public class ReleaseH{
        public String ZTIMS;
        public String IFDATE;
        public String EBELN;
        public String BSART;
        public String RESWK;
        public String EKORG;
        public String EKGRP;
        public String SND_YN;
        public String XDATS;
        public String XTIMS;
        public String XMSGS;
        public String xstat;
    }

    public class ReleaseD{
        public String ZTIMS;
        public String EBELN;
        public String EBELP;
        public String WERKS;
        public String LGORT;
        public String MATNR;
        public String MAKTX;
        public String CHARG;
        public String PBUDAT;
        public String MENGE;
        public String MEINS;
        public String RAUBE;
        public String EINDT;
        public String RETPO;
        public String BUDAT;
        public String SND_YN;
        public String PSMNG;
        public String R_PSMNG;
        public String RELEASEDKEY;
    }

    public Output callOut() {
        callCjCkSoapVer_2.sapCkInParameter inputData = new callCjCkSoapVer_2.sapCkInParameter();
        List<RELEASE_H__c> inputHeader = new List<RELEASE_H__c>(); 
        List<RELEASE_D__c> inputDetail = new List<RELEASE_D__c>();
        List<RELEASE_H__c> targetHList = new List<RELEASE_H__c>(); 
        List<RELEASE_H__c> updateHList = new List<RELEASE_H__c>(); 
        Map<String,Object> inputMap = new Map<String,Object>();

        Result objResult = new Result();
        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = '확정 데이터 전송 성공';
        String result = '';
        String inputString = '';
        
        try {
            inputHeader = [
                SELECT IFDATE__c,
                EBELN__c,
                SND_YN__c,
                XDATS__c,
                XTIMS__c,
                xmsgs__c
                FROM RELEASE_H__c
                WHERE CHECK__c = 'Y' AND CONFIRM__c = 'N'
            ];
            inputDetail = [
                SELECT EBELN__c,
                EBELP__c,
                WERKS__c,
                LGORT__c,
                MATNR__c,
                MAKTX__c,
                CHARG__c,
                PBUDAT__c,
                MENGE__c,
                MEINS__c,
                RAUBE__c,
                EINDT__c,
                RETPO__c,
                PSMNG__c,
                R_PSMNG__c,
                RELEASEDKEY__c,
                xmsgs__c
                FROM RELEASE_D__c
                WHERE RELEASE_H__r.CHECK__c = 'Y' AND RELEASE_H__r.CONFIRM__c = 'N'
            ];

            inputMap.put('header', inputHeader);
            inputMap.put('detail', inputDetail);
            inputMap.put('IF_ID', 'CK0004');

            inputString = JSON.serialize(inputMap);
            inputData.requestMsg = inputString;

            System.debug('========================requestMsg :::'+inputData.requestMsg);

            callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort soap = new callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort();
            result = soap.callSapCkProcedure(inputData);
            System.debug('result======================= :::'+result);

            if(result == '' || result == null) {
                strStatus = 'ERROR';
                strCode = '0003';
                strMessage = '확정 데이터 전송 실패';
            }else {
                Input input = (Input)JSON.deserialize(result, Input.class);

                if (input.header == null || input.header.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0001';
                    strMessage = '확정 데이터 전송 실패';
                }else if (input.detail == null || input.detail.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0002';
                    strMessage = '확정 데이터 전송 실패';
                }
                else {
                    Map<String, RELEASE_H__c> mapUpOrder = new Map<String, RELEASE_H__c>();
    
                    if (input.header <> null && input.header.size() > 0) {
                        targetHList = [
                            SELECT Id, IFDATE__c,  EBELN__c, SND_YN__c, XDATS__c, XTIMS__c, xmsgs__c
                            FROM RELEASE_H__c
                            WHERE CHECK__c = 'Y' AND CONFIRM__c = 'N'
                        ];
                        System.debug('==================targetList:::'+targetHList);

                        for (RELEASE_H__c obj : targetHList) {
                            mapUpOrder.put(obj.EBELN__C, obj);
                        }
                        System.debug(('====================mapUpOrder:::' + mapUpOrder));
                        if (!targetHList.isEmpty()) {
                            for (ReleaseH obj : input.header) {
                                RELEASE_H__c releaseHObj = new RELEASE_H__c();
                                releaseHObj = mapUpOrder.get(obj.EBELN);
                                releaseHObj.Confirm__c = 'Y';
                                // releaseHObj.xmsgs__c = obj.XMSGS;
                                // releaseHObj.xstat__c = obj.xstat;
                                updateHList.add(releaseHObj);
                            }
                            System.debug('====================updateHList:::' + updateHList);
                            update updateHList;
                        }else {
                            strCode = '0004';
                            strMessage = '확정 데이터 전송 실패';
                            strStatus = 'ERROR';
                        }
                    }
                }
            }
        } catch (Exception e) {
            strCode = '-1';
            strStatus = 'ERROR';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage();
            System.debug(strMessage);
        }finally{

            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            objResult.soapCallResult = result;

            objOutput.result = objResult;

            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = 'strMessage:::' + strMessage + ':::soapCallResult:::' + result;
            LogWrapper.responseTime = Datetime.now();
            LogWrapper.requestBody = inputString;
            LogWrapper.responseBody = result;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);
            
            IFUtil objIF = new IFUtil('IF_SFDC_SAP_SAND_RELEASE');
            objIF.setLog(LogWrapper);
        }
        return objOutput;
    }
    // public Output callOut(Boolean isRetry) {
    //     callCjCkSoapVer_2.sapCkInParameter inputData = new callCjCkSoapVer_2.sapCkInParameter();
    //     List<RELEASE_H__c> inputHeader = new List<RELEASE_H__c>(); 
    //     List<RELEASE_D__c> inputDetail = new List<RELEASE_D__c>();
    //     List<RELEASE_H__c> targetHList = new List<RELEASE_H__c>(); 
    //     List<RELEASE_H__c> updateHList = new List<RELEASE_H__c>(); 
    //     Map<String,Object> inputMap = new Map<String,Object>();

    //     Result objResult = new Result();
    //     Output objOutput = new Output();
    //     LogWrapper LogWrapper = new LogWrapper();
    //     LogWrapper.requestTime = Datetime.now();

    //     String strStatus = 'SUCCESS';
    //     String strCode = '0000';
    //     String strMessage = 'Soap Call Success';
    //     String result = '';
    //     String inputString = '';
        
    //     try {
    //         if(!isRetry){
    //             inputHeader = [
    //                 SELECT IFDATE__c,
    //                 EBELN__c,
    //                 SND_YN__c,
    //                 XDATS__c,
    //                 XTIMS__c,
    //                 xmsgs__c
    //                 FROM RELEASE_H__c
    //                 WHERE CHECK__c = 'Y' AND CONFIRM__c = 'N'
    //             ];
    //             inputDetail = [
    //                 SELECT EBELN__c,
    //                 EBELP__c,
    //                 WERKS__c,
    //                 LGORT__c,
    //                 MATNR__c,
    //                 MAKTX__c,
    //                 CHARG__c,
    //                 PBUDAT__c,
    //                 MENGE__c,
    //                 MEINS__c,
    //                 RAUBE__c,
    //                 EINDT__c,
    //                 RETPO__c,
    //                 PSMNG__c,
    //                 R_PSMNG__c,
    //                 RELEASEDKEY__c,
    //                 xmsgs__c
    //                 FROM RELEASE_D__c
    //                 WHERE RELEASE_H__r.CHECK__c = 'Y' AND RELEASE_H__r.CONFIRM__c = 'N'
    //             ];
    //         }else {
    //             inputHeader = [
    //                 SELECT IFDATE__c,
    //                 EBELN__c,
    //                 SND_YN__c,
    //                 XDATS__c,
    //                 XTIMS__c,
    //                 xmsgs__c
    //                 FROM RELEASE_H__c
    //                 WHERE (CHECK__c = 'Y' AND CONFIRM__c = 'N') /*OR EBELN_R__c = ''*/
    //             ];
    //             inputDetail = [
    //                 SELECT EBELN__c,
    //                 EBELP__c,
    //                 WERKS__c,
    //                 LGORT__c,
    //                 MATNR__c,
    //                 MAKTX__c,
    //                 CHARG__c,
    //                 PBUDAT__c,
    //                 MENGE__c,
    //                 MEINS__c,
    //                 RAUBE__c,
    //                 EINDT__c,
    //                 RETPO__c,
    //                 PSMNG__c,
    //                 R_PSMNG__c,
    //                 RELEASEDKEY__c,
    //                 xmsgs__c
    //                 FROM RELEASE_D__c
    //                 WHERE (RELEASE_H__r.CHECK__c = 'Y' AND RELEASE_H__r.CONFIRM__c = 'N') /*OR EBELN_R__c = ''*/
    //             ];  
    //         }

    //         inputMap.put('header', inputHeader);
    //         inputMap.put('detail', inputDetail);
    //         inputMap.put('IF_ID', 'CK0004');

    //         inputString = JSON.serialize(inputMap);
    //         inputData.requestMsg = inputString;

    //         System.debug('========================requestMsg :::'+inputData.requestMsg);

    //         callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort soap = new callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort();
    //         result = soap.callSapCkProcedure(inputData);
    //         System.debug('result======================= :::'+result);

    //         if(result == '' || result == null) {
    //             strStatus = 'ERROR';
    //             strCode = '-1';
    //             strMessage = 'response body value does not exist';
    //         }else {
    //             Input input = (Input)JSON.deserialize(result, Input.class);

    //             if (input.header == null || input.header.size() < 1) {
    //                 strStatus = 'ERROR';
    //                 strCode = '0001';
    //                 strMessage = 'header list is null';
    //             }else if (input.detail == null || input.detail.size() < 1) {
    //                 strStatus = 'ERROR';
    //                 strCode = '0002';
    //                 strMessage = 'detail list is null';
    //             }else {
    //                 Map<String, RELEASE_H__c> mapUpOrder = new Map<String, RELEASE_H__c>();
    
    //                 if (input.header <> null && input.header.size() > 0) {
    //                     targetHList = [
    //                         SELECT Id, IFDATE__c,  EBELN__c, SND_YN__c, XDATS__c, XTIMS__c, xmsgs__c
    //                         FROM RELEASE_H__c
    //                         WHERE CHECK__c = 'Y' AND CONFIRM__c = 'N'
    //                     ];
    //                     System.debug('==================targetList:::'+targetHList);

    //                     for (RELEASE_H__c obj : targetHList) {
    //                         mapUpOrder.put(obj.EBELN__C, obj);
    //                     }
    //                     System.debug(('====================mapUpOrder:::' + mapUpOrder));
    //                     if (!targetHList.isEmpty()) {
    //                         for (ReleaseH obj : input.header) {
    //                             RELEASE_H__c releaseHObj = new RELEASE_H__c();
    //                             releaseHObj = mapUpOrder.get(obj.EBELN);
    //                             releaseHObj.xmsgs__c = obj.XMSGS;
    //                             releaseHObj.xstat__c = obj.xstat;
    //                             updateHList.add(releaseHObj);
    //                         }
    
    //                         update updateHList;
    //                     }else {
    //                         strCode = '0003';
    //                         strMessage = 'The target to update does not exist';
    //                         strStatus = 'ERROR';
    //                     }
    //                 }
    //             }
    //         }
    //     } catch (Exception e) {
    //         strCode = '-1';
    //         strStatus = 'ERROR';
    //         System.debug('soapCallFaild...:::soapCallResult:::'+result+':::strMessage:::'+strMessage);
    //     }finally{

    //         objResult.resultCode = strCode;
    //         objResult.resultMessage = strMessage;
    //         objResult.soapCallResult = result;

    //         objOutput.result = objResult;

    //         LogWrapper.status = strStatus;
    //         LogWrapper.resultCode = strCode;
    //         LogWrapper.resultMessage = 'strMessage:::' + strMessage + ':::soapCallResult:::' + result;
    //         LogWrapper.responseTime = Datetime.now();
    //         LogWrapper.requestBody = inputString;
    //         LogWrapper.responseBody = result;
    //         System.debug(LogWrapper);
    //         IFUtil objIF = new IFUtil('IF_SFDC_SAP_SAND_RELEASE');
    //         objIF.setLog(LogWrapper);
    //     }
    //     return objOutput;
    // }
}