force-app/main/default/objects/RELEASE_D__c/RELEASE_D__c.object-meta.xml
<CustomObject>
    <label>출고내역상세</label>
    <nameField>
        <label>상품명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_D__c/fields/CHARG__c.field-meta.xml
<CustomField>
    <fullName>CHARG__c</fullName>
    <label>배치번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <label>이체오더번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/EBELP__c.field-meta.xml
<CustomField>
    <fullName>EBELP__c</fullName>
    <label>이체오더품목</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>전송일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재 내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>자재 번호</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>구매 오더 단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>구매 오더 수량</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/PBUDAT__c.field-meta.xml
<CustomField>
    <fullName>PBUDAT__c</fullName>
    <label>생산일자</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/PSMNG__c.field-meta.xml
<CustomField>
    <fullName>PSMNG__c</fullName>
    <label>생산수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/R_PSMNG__c.field-meta.xml
<CustomField>
    <fullName>R_PSMNG__c</fullName>
    <label>출고제한수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RAUBE__c.field-meta.xml
<CustomField>
    <fullName>RAUBE__c</fullName>
    <label>저장조건</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RAUBE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RELEASE_H__c.field-meta.xml
<CustomField>
    <fullName>RELEASE_H__c</fullName>
    <label>출고내역</label>
    <referenceTo>RELEASE_H__c</referenceTo>
    <relationshipLabel>출고내역상세</relationshipLabel>
    <relationshipName>RELEASE_D</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RELEASEDKEY__c.field-meta.xml
<CustomField>
    <fullName>RELEASEDKEY__c</fullName>
    <externalId>true</externalId>
    <label>ckwms키</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_D__c/fields/RETPO__c.field-meta.xml
<CustomField>
    <fullName>RETPO__c</fullName>
    <label>반품 품목</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/RELEASE_H__c.object-meta.xml
<CustomObject>
    <label>출고내역</label>
    <nameField>
        <displayFormat>RH-{00000000}</displayFormat>
        <label>SFDC Key</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RELEASE_H__c/fields/EBELN__c.field-meta.xml
<CustomField>
    <fullName>EBELN__c</fullName>
    <externalId>true</externalId>
    <label>이체오더번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/IFDATE__c.field-meta.xml
<CustomField>
    <fullName>IFDATE__c</fullName>
    <label>수신일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/SND_YN__c.field-meta.xml
<CustomField>
    <fullName>SND_YN__c</fullName>
    <label>전송성공여부 S/E</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/XDATS__c.field-meta.xml
<CustomField>
    <fullName>XDATS__c</fullName>
    <label>수신날짜 (YYYYMMDD)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RELEASE_H__c/fields/XTIMS__c.field-meta.xml
<CustomField>
    <fullName>XTIMS__c</fullName>
    <label>수신시간 (HHMMSS)</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LGORT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>상온 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>냉장 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>냉동 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>원자재 불량 창고</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>제품 장기재고 창고</label>
    </customValue>
    <customValue>
        <fullName>3100</fullName>
        <label>상온 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3200</fullName>
        <label>냉장 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3300</fullName>
        <label>냉동 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3900</fullName>
        <label>제품 불량창고</label>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
        <label>정상품창고</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>불량품창고</label>
    </customValue>
    <customValue>
        <fullName>L091</fullName>
        <label>센트럴키친중부세척센터근태점</label>
    </customValue>
    <masterLabel>저장위치</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RAUBE.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>실온</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>냉장</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>냉동</label>
    </customValue>
    <masterLabel>저장조건</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IF_SFDC_SAP_REC_RELEASE.cls
/**
 * @description       : 
 * @author            : 안태진(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 06-22-2022
 * @last modified by  : 안태진(tj.ahn@daeunextier.com)
**/
public class IF_SFDC_SAP_REC_RELEASE {
    
    public IF_SFDC_SAP_REC_RELEASE() {}

    callCjCkSoapVer_2.sapCkInParameter inputData = new callCjCkSoapVer_2.sapCkInParameter();

    public class Input {
        public List<ReleaseH> header;
        public List<ReleaseD> detail;
    }

    public class Output {
        public Result result;
    }

    public class Result {
        public String resultCode;
        public String resultMessage;
        public String soapCallResult;
    }

    public class ReleaseH{
        public String IFDATE;
        public String EBELN;
        public String BSART;
        public String RESWK;
        public String EKORG;
        public String EKGRP;
        public String SND_YN;
        public String XDATS;
        public String XTIMS;
    }

    public class ReleaseD{
        public String ZTIMS;
        public String EBELN;
        public String EBELP;
        public String WERKS;
        public String LGORT;
        public String MATNR;
        public String MAKTX;
        public String CHARG;
        public String PBUDAT;
        public String MENGE;
        public String MEINS;
        public String RAUBE;
        public String EINDT;
        public String RETPO;
        public String BUDAT;
        public String SND_YN;
        public String PSMNG;
        public String R_PSMNG;
        public String RELEASEDKEY;
    }

    // public Output callOut() {
    public Output callOut(String sysdate) {
        Set<String> releaseEbelnDelSet = new Set<String>();
        Map<String, Id> id_ebelnMap = new Map<String, Id>();
        List<Release_H__c> releaseHList = new List<Release_H__c>(); 
        List<Release_D__c> releaseDList = new List<Release_D__c>(); 

        Result objResult = new Result();
        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = '데이터가 성공적으로 수신 되었습니다.';
        String result = '';

        try {
            inputData.requestMsg = '{"sysdate" : "'+sysdate+'", "IF_ID" : "CK0003"}';
            system.debug('====================== requestMsg :::'+inputData.requestMsg);
            callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort soap = new callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort();
            result = soap.callSapCkProcedure(inputData);
            System.debug('=======================result:::'+result);

            if(result == '' || result == null) {
                strStatus = 'ERROR';
                strCode = '0003';
                strMessage = '수신받을 데이터가 없습니다.';
            }else {
                Input input = (Input)JSON.deserialize(result, Input.class);

                if (input.header == null || input.header.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0001';
                    strMessage = '수신받을 데이터가 없습니다.';
                }else if (input.detail == null || input.detail.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0002';
                    strMessage = '수신받을 데이터가 없습니다.';
                }else {
                    Map<String, String> mapSND_YN = CommonUtil.getMapPickListLabel('Release_H__c', 'Snd_Yn__c');
                    Set<String> releaseNoSet = new Set<String>();
                    List<RELEASE_H__c> delReleaseList = new List<RELEASE_H__c>();
                    List<RELEASE_H__c> updReleaseList = new List<RELEASE_H__c>();

                    for (ReleaseH obj : input.header) {
                        releaseNoSet.add(obj.EBELN);
                    }

                    delReleaseList = [
                        SELECT Id,IFDATE__c,EBELN__c,SND_YN__c,XDATS__c,XTIMS__c
                        FROM Release_H__c
                        WHERE Ebeln__c in: releaseNoSet 
                    ];

                    for (Release_H__c obj : delReleaseList) {
                        releaseEbelnDelSet.add(obj.Ebeln__c);
                    }

                    if (input.header <> null && input.header.size() > 0) {
                        for (ReleaseH obj : input.header) {
                            Release_H__c releaseObj = new Release_H__c();
                            if (releaseEbelnDelSet.contains(obj.EBELN)) {
                                continue;
                            }else {
                                releaseObj.IFDATE__c = Date.valueOf(obj.IFDATE);
                                releaseObj.EBELN__c = obj.EBELN;
                                releaseObj.Snd_Yn__c = mapSND_YN.get(obj.SND_YN);
                                releaseObj.Xdats__c = obj.XDATS;
                                releaseObj.Xtims__c = obj.XTIMS;
                                releaseHList.add(releaseObj);
                            }
                        }
                        System.debug('============= releaseHList :::' + releaseHList);
                    }

                    // if (input.header <> null && input.header.size() > 0) {
                    //     for (Integer i = 0; i < input.header.size(); i++) {
                    //         Release_H__c obj = new Release_H__c();
                    //         obj.IFDATE__c = Date.valueOf(input.header[i].IFDATE);
                    //         obj.EBELN__c = input.header[i].EBELN;
                    //         obj.Snd_Yn__c = mapSND_YN.get(input.header[i].SND_YN);
                    //         obj.Xdats__c = input.header[i].XDATS;
                    //         obj.Xtims__c = input.header[i].XTIMS;
                    //         releaseNoSet.add(input.header[i].EBELN);
                    //         releaseHList.add(obj);
                    //     }
                
                    insert releaseHList;

                    for (Release_H__c obj : releaseHList) {
                        id_ebelnMap.put(obj.Ebeln__c, obj.id);
                    }

                    if (input.detail <> null && input.detail.size() > 0) {
                        // Map<String, String> mapWERKS = CommonUtil.getMapPickListLabel('Release_D__c', 'WERKS__c');
                        for (Integer i = 0; i < input.detail.size(); i++) {
                            if (releaseEbelnDelSet.contains(input.detail[i].EBELN)) {
                                continue;
                            }else {
                            Release_D__c obj = new Release_D__c();
                            obj.Name = input.detail[i].MAKTX;
                            obj.EBELN__c = input.detail[i].EBELN;
                            obj.EBELP__c = input.detail[i].EBELP;
                            obj.WERKS__c = input.detail[i].WERKS;
                            obj.LGORT__c = input.detail[i].LGORT;
                            obj.MATNR__c = input.detail[i].MATNR;
                            obj.MAKTX__c = input.detail[i].MAKTX;
                            obj.CHARG__c = input.detail[i].CHARG;
                            obj.PBUDAT__c = Date.valueOf(input.detail[i].PBUDAT);
                            obj.MENGE__c = Decimal.valueOf(input.detail[i].MENGE);
                            obj.MEINS__c = input.detail[i].MEINS;
                            obj.RAUBE__c = input.detail[i].RAUBE;
                            obj.EINDT__c = Date.valueOf(input.detail[i].EINDT);
                            obj.RETPO__c = input.detail[i].RETPO;
                            obj.PSMNG__c = Decimal.valueOf(input.detail[i].PSMNG);
                            obj.R_PSMNG__c = Decimal.valueOf(input.detail[i].R_PSMNG);
                            // obj.BUDAT__c = Date.valueOf(input.detail[i].BUDAT);
                            obj.Release_H__c = id_ebelnMap.get(input.detail[i].EBELN);
                            obj.RELEASEDKEY__c = input.detail[i].RELEASEDKEY;
                            releaseDList.add(obj);
                            }
                        }
                        
                        System.debug('============= dtail list :::' + releaseDList);
                        insert releaseDList;
                    }    
                }    
            }
        } catch (Exception e) {
            strStatus = 'ERROR';
            strCode = '-1';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage(); 
            System.debug(strMessage);
        } finally {
            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            objResult.soapCallResult = result;

            objOutput.result = objResult;

            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = 'message:::' + strMessage + ':::result:::' + result;
            LogWrapper.responseTime = Datetime.now();
            LogWrapper.requestBody = inputdata.requestMsg;
            LogWrapper.responseBody = result;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);
        
            IFUtil objIF = new IFUtil('IF_SFDC_SAP_REC_RELEASE');
            objIF.setLog(LogWrapper);
        }

        return objOutput;
    }

}