force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>시산</label>
    <nameField>
        <label>Balance Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BalanceDetail__c/BalanceDetail__c.object-meta.xml
<CustomObject>
    <label>시산상세</label>
    <nameField>
        <label>Type</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BalanceDetail__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Balance</label>
    <referenceTo>Balance__c</referenceTo>
    <relationshipLabel>BalanceDetails</relationshipLabel>
    <relationshipName>BalanceDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BidNoticeSource__c.field-meta.xml
<CustomField>
    <fullName>BidNoticeSource__c</fullName>
    <label>Bid Notice Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BidQualifyRegistCloseDateTime__c.field-meta.xml
<CustomField>
    <fullName>BidQualifyRegistCloseDateTime__c</fullName>
    <description>나라장터 입찰 참가 자격 등록 마감 일시(mapping)</description>
    <label>Bid Qualify Regist Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BalanceExcelUploadController_test.cls
/**
 * Created by 천유정 on 2023-01-30.
 */

@IsTest
private class BalanceExcelUploadController_test {
    @TestSetup
    static void BalanceExcelUploadController_testSetUp() {
        Account objAccount = TestObjectCreator.objExAccount;
        insert objAccount;

        PricebookEntry objPriceBookEntry = TestObjectCreator.objPricebookEntry;
        insert objPriceBookEntry;

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objAccount.Id;
        objOpportunity.Name = '영업활동';
        objOpportunity.CloseDate = date.valueOf('2022-01-01');
        objOpportunity.StageName = 'Proposal';
        objOpportunity.BidNoticeSource__c = 'NotNull';
        objOpportunity.LeadSource = 'NaraMarket';
        objOpportunity.BidQualifyRegistCloseDateTime__c = date.valueOf('2022-01-01');
        insert objOpportunity;

    }

    @IsTest
    static void BalanceExcelUploadController_test() {
        test.startTest();

        Opportunity objOpportunity = [SELECT Id FROM Opportunity LIMIT 1];

        Balance__c objBalance = TestObjectCreator.objSuggestBalance;
        objBalance.Opportunity__c = objOpportunity.Id;
        insert objBalance;

        List<BalanceDetail__c> listBalanceDetail = new List<BalanceDetail__c>();
        BalanceDetail__c objBalanceDetail = new BalanceDetail__c();
        objBalanceDetail.Balance__c = objBalance.Id;
        listBalanceDetail.add(objBalanceDetail);

        List<BalanceDetail__c> listBalanceDetail2 = new List<BalanceDetail__c>();
        BalanceDetail__c objBalanceDetail2 = new BalanceDetail__c();
        objBalanceDetail2.Balance__c = objBalance.Id;
        listBalanceDetail2.add(objBalanceDetail2);

        BalanceExcelUploadController balClass = new BalanceExcelUploadController();
        System.debug(balClass.recordId);
        System.debug(balClass.selectedTab);
        System.debug(balClass.balanceType);

        PageReference pageRef = Page.BalanceExcelUploadView;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', objOpportunity.Id);
        ApexPages.currentPage().getParameters().put('balanceType', '제안시산');
        ApexPages.currentPage().getParameters().put('viewType', 'PL');

        BalanceExcelUploadController controller = new BalanceExcelUploadController();
        System.debug(controller.objBalance);
        System.debug(controller.listBalanceDetail_SUM);
        System.debug(controller.listBalanceDetail_IRR);
        System.debug(controller.listBalanceDetail_PL);


        BalanceExcelUploadController.doGetPrefix();
        BalanceExcelUploadController.doInit(objOpportunity.Id, '제안시산');
        BalanceExcelUploadController.doInit(objOpportunity.Id, '오픈시산');

        BalanceExcelUploadController.doOpenUpload(objOpportunity.Id, '제안시산');
        BalanceExcelUploadController.doOpenUpload(objOpportunity.Id, '오픈시산');

        BalanceExcelUploadController.doSave(objOpportunity.Id, '제안시산', objBalance, listBalanceDetail, listBalanceDetail, listBalanceDetail);
        System.debug(balClass.objProposalBalance);

        Balance__c objBalance2 = TestObjectCreator.objOpenBalance;
        objBalance2.Opportunity__c = objOpportunity.Id;
        insert objBalance2;

        BalanceExcelUploadController.doSave(objOpportunity.Id, '오픈시산', objBalance2, listBalanceDetail2, listBalanceDetail2, listBalanceDetail2);
        System.debug(balClass.objOpenBalance); 

        test.stopTest();
    }

}