force-app/main/default/objects/OilTypeChange__c/OilTypeChange__c.object-meta.xml
<CustomObject>
    <label>유류유형 변경</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OilTypeChange__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>ApprovalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>작성중</fullName>
                <default>true</default>
                <label>작성중</label>
            </value>
            <value>
                <fullName>승인요청</fullName>
            </value>
            <value>
                <fullName>반려</fullName>
            </value>
            <value>
                <fullName>승인</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OilTypeChange__c/fields/oil_type_cd__c.field-meta.xml
<CustomField>
    <fullName>oil_type_cd__c</fullName>
    <label>oil type cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>휘발유</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>경유</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>LPG</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>전기차</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>수소차</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocument_tr_test.cls
/************************************************************************************
 * File Name   		    : ContentDocument_tr_test.cls
 * Author	  		    : sy.lee
 * Date				    : 2023.04.18
 * Target	  		    : ContentDocument_tr.cls
 * Description 		    : ContentDocument_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.04.18      sy.lee          Create
 *************************************************************************************/

 @IsTest
 public with sharing class ContentDocument_tr_test {
     @isTest 
     static void itShould() {
        Test.startTest();
        Id ownerIdInfo = UserInfo.getUserId();  

        OilTypeChange__c obj1 = new OilTypeChange__c();
        obj1.oil_type_cd__c = '1';
        obj1.OwnerId = ownerIdInfo;
        obj1.ApprovalStatus__c = '작성중';        
        insert obj1;
 
        ContentVersion objContentVersion = new Contentversion();
        objContentVersion.Title = 'test';
        objContentVersion.PathOnClient = 'test.txt';
        objContentVersion.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert objContentVersion;

        objContentVersion = [
            SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =:objContentVersion.Id
        ];
        Id objConDocId = objContentVersion.ContentDocumentId;

        ContentDocumentLink conDcLink = new ContentDocumentLink();
        conDcLink.LinkedEntityId = obj1.Id;
        conDcLink.ContentDocumentId = objConDocId;

        insert conDcLink;
        obj1.OwnerId = ownerIdInfo;
        obj1.ApprovalStatus__c = '승인요청';

        update obj1;

        ContentDocument delTarget = [SELECT Id FROM ContentDocument WHERE Id =:objConDocId];

        delete delTarget;
         
        Test.stopTest();
     }
 }