force-app/main/default/objects/CJFW_NotificationTarget__c/CJFW_NotificationTarget__c.object-meta.xml
<CustomObject>
    <description>알림 추가 수신자 Group, Role, User</description>
    <label>Notification Target</label>
    <nameField>
        <displayFormat>TG{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_NotificationTarget__c/fields/GroupId__c.field-meta.xml
<CustomField>
    <fullName>GroupId__c</fullName>
    <description>협업그룹Id (CollaborationGroupId)</description>
    <label>GroupId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_NotificationTarget__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>CJFW_Notification__c</referenceTo>
    <relationshipLabel>Notification Target</relationshipLabel>
    <relationshipName>Notification_Target</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_NotificationTarget__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>사용자</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notification_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 관리</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NM{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>보낼 알림 이력을 재구성하기 위한 Class 명</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>보낼 알림 이력을 재구성할 Class 를 사용하기 위한 값 true: ClassName__c 필수, false: 기본 공통로직 사용</description>
    <label>IsDynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>알림 관리 레코드의 고유명</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <description>데이터 가져올 sObject API 명</description>
    <label>sObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/TargetFields__c.field-meta.xml
<CustomField>
    <fullName>TargetFields__c</fullName>
    <description>데이터 가져올 sObject 의 필드 값</description>
    <inlineHelpText>여러개 일 경우, 로 구분</inlineHelpText>
    <label>TargetFields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <description>SFDC 이메일 알림</description>
    <label>Email</label>
</RecordType>

force-app/main/default/objects/NotificationTarget__c/NotificationTarget__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 추가 수신자 Group, Role, User</description>
    <label>Notification Target</label>
    <nameField>
        <displayFormat>TG{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTarget__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <description>협업그룹명 (CollaborationGroup명)</description>
    <label>GroupName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Target</relationshipLabel>
    <relationshipName>Notification_Target</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/fields/RoleId__c.field-meta.xml
<CustomField>
    <fullName>RoleId__c</fullName>
    <description>역할Id</description>
    <label>RoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/fields/RoleName__c.field-meta.xml
<CustomField>
    <fullName>RoleName__c</fullName>
    <description>역할명</description>
    <label>Role Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>협업그룹</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/NotificationTarget__c/recordTypes/User.recordType-meta.xml
<RecordType>
    <fullName>User</fullName>
    <active>true</active>
    <description>사용자</description>
    <label>User</label>
</RecordType>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - App 알림, Email 알림.. 등 Template 관리</description>
    <label>Notification Template</label>
    <nameField>
        <displayFormat>NT{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/EmailDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>EmailDeveloperName__c</fullName>
    <description>Classic Email Template Developer Name</description>
    <label>Email Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>언어</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ko</fullName>
                <default>true</default>
                <label>ko</label>
            </value>
            <value>
                <fullName>en_US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>App 본문</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Template</relationshipLabel>
    <relationshipName>Notification_Template</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>App 제목</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NotificationManager.cls
/**
* 알림 전송 관리 Object
*
*@group  Notification
*@author 진현욱
*@since 2023-07-24  최초 작성
*/
public with sharing class NotificationManager {
    
    private static NotificationManager instance;

    @testVisible private Map<String, Notification__c> notiMap;
    @testVisible protected Set<String> targetIdSet;
    @testVisible protected List<sObject> targetObjectList;

    /* Data 형식
        {
            'Id': [
                User : {
                    Id:''
                    Email:''
                }
            ]
            ,'Email':[User]
        }
    */
    @testVisible protected Map<String,List<User>> recipientListMap;

    private NotificationManager() {
        notiMap = new Map<String, Notification__c>();

        for(Notification__c noti : [
            select 
                ClassName__c
                , IsDynamic__c
                , Key__c
                , Description__c
                , CustomNotificationTypeId__c
                , PageReference__c
                , sObject__c
                , TargetFields__c
                , IsSendToSender__c
                , RecordType.DeveloperName
                ,(   select 
                        Title__c
                        , Message__c
                        , Language__c
                        , EmailDeveloperName__c
                        , RecordType.DeveloperName 
                    from Notification_Template__r
                )
                ,(   select 
                        GroupId__c
                        , GroupName__c
                        , RoleId__c
                        , RoleName__c
                        , User__c
                        , RecordType.DeveloperName 
                    from Notification_Target__r
                )
            from Notification__c
            where IsActive__c = true
        ]) {
            notiMap.put(noti.Key__c, noti);
        }
    }



    public NotificationManager setTargetIdSet(Set<String> targetIdSet) {
        instance.targetIdSet = targetIdSet;
        return instance;
    }

    public NotificationManager setTargetObjectList(List<sObject> targetObjectList) {
        instance.targetObjectList = targetObjectList;
        return instance;
    }

    public NotificationManager setRecipientListMap(Map<String,List<User>> recipientListMap) {
        instance.recipientListMap = recipientListMap;
        return instance;
    }

    public static NotificationManager getInstance() {
        if(instance == null) instance = new NotificationManager();
        return instance;
    }

    public void execute(String key) {
        Notification__c noti = notiMap.get(key);

        if(noti == null) return;

        String className = 'NotiHandler';
        if(noti.IsDynamic__c) {
            className = noti.ClassName__c;
        }
        NotiHandler notiHandler = (NotiHandler)Type.forName(className).newInstance();
        notiHandler.setNotiData(noti);
        notiHandler.setUserListMap(recipientListMap);
        
         if(instance.targetIdSet != null) notiHandler.execute(instance.targetIdSet, null);
         else if(instance.targetObjectList != null) notiHandler.execute(null, instance.targetObjectList);

        instance.resetData();

    }

    private void resetData() {
        instance.setTargetIdSet(null);
        instance.setTargetObjectList(null);
        instance.setRecipientListMap(null);
    }
}