force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 관리</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NM{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>보낼 알림 이력을 재구성하기 위한 Class 명</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>보낼 알림 이력을 재구성할 Class 를 사용하기 위한 값 true: ClassName__c 필수, false: 기본 공통로직 사용</description>
    <label>IsDynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/recordTypes/App.recordType-meta.xml
<RecordType>
    <fullName>App</fullName>
    <active>true</active>
    <description>SFDC 종 알림</description>
    <label>App</label>
</RecordType>

force-app/main/default/classes/NotiTriggerHandler.cls
/**
* NotiTriggerHandler
*
*@group  Notificatoin
*@author 진현욱
*@since 2023-08-14  최초작성
*/
public with sharing class NotiTriggerHandler extends TriggerHandler{
    
    @testVisible private List<Notification__c> newList; 
    @testVisible private List<Notification__c> oldList; 
    @testVisible private Map<Id, Notification__c> oldMap; 
    @testVisible private Map<Id, Notification__c> newMap;
    @testVisible private static Map<String, Schema.RecordTypeInfo> recordTypeMap;
    @testVisible private static Map<String,CustomNotificationType> customNotiTypeMap;
    @testVisible private static COMM_Util.SchemaInfo schemaInfo; 

    
    public NotiTriggerHandler() {
        newList = (List<Notification__c>) Trigger.new;
        oldList = (List<Notification__c>) Trigger.old;
        newMap  = (Map<Id,Notification__c>) Trigger.newMap;
        oldMap  = (Map<Id,Notification__c>) Trigger.oldMap;

        if(schemaInfo == null) schemaInfo = new COMM_Util.SchemaInfo('Notification__c');

        if(recordTypeMap == null)recordTypeMap = schemaInfo.getRecordTypeMapByDeveloperNames();

        if(customNotiTypeMap == null) customNotiTypeMap = new Map<String,CustomNotificationType>();
        if(customNotiTypeMap.isEmpty()) {

            for(CustomNotificationType customNoti :[
                select
                    Id
                    ,DeveloperName    
                from CustomNotificationType 
            ]) {
                customNotiTypeMap.put(customNoti.DeveloperName, customNoti);
            }
        }

    }

    public override void beforeInsert() {        
        validationCheck(newList);
    }

    public override void beforeUpdate() {
        validationCheck(newList);
    }

    private void validationCheck(List<Notification__c> notiList) {
      

        Id appRecordTypeId = recordTypeMap.get('App').getRecordTypeId();

        for(Notification__c noti : notiList) {
            if(noti.RecordTypeId == appRecordTypeId) {
                
                //App Notification 일떄 CustomNotificationTypeId 생성 체크 
                if(!customNotiTypeMap.containsKey(noti.CustomNotificationTypeId__c)) noti.addError('CustomNotificationTypeId__c', 'Custom Notification Type 을 먼저 생성후 등록해 주세요.');
            }

            //개발자가 동적으로 개인화시에 ClassName 필수값 체크
            if(noti.IsDynamic__c && String.isBlank(noti.ClassName__c)) noti.addError('ClassName__c', '알림 생성 로직 커스텀시에 ClassName 은 필수값 입니다.');
        }

    }
}