force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 관리</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NM{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>보낼 알림 이력을 재구성하기 위한 Class 명</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsDynamic__c.field-meta.xml
<CustomField>
    <fullName>IsDynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>보낼 알림 이력을 재구성할 Class 를 사용하기 위한 값 true: ClassName__c 필수, false: 기본 공통로직 사용</description>
    <label>IsDynamic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsNotiTest__c.field-meta.xml
<CustomField>
    <fullName>IsNotiTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>알림 테스트용으로 수행 여부 (false: 발송 후 이력생성, true: 이력생성)</description>
    <label>IsNotiTest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsSaveAsActivity__c.field-meta.xml
<CustomField>
    <fullName>IsSaveAsActivity__c</fullName>
    <defaultValue>true</defaultValue>
    <description>이메일 활동 저장 여부</description>
    <label>IsSaveAsActivity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsSystemEmail__c.field-meta.xml
<CustomField>
    <fullName>IsSystemEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Classic Email Template 에서 Verify Merge Field 를 이용하여 System 개인화 여부</description>
    <inlineHelpText>IsSystem 이 True 일 경우 IsSaveAsActivity 의 값에 상관없이 활동 저장</inlineHelpText>
    <label>IsSystemEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/IsUseOWE__c.field-meta.xml
<CustomField>
    <fullName>IsUseOWE__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Email 송신시 발신자 Org 대표 주소로 표시여부</description>
    <label>IsUseOWE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>알림 관리 레코드의 고유명</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <description>데이터 가져올 sObject API 명</description>
    <label>sObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/TargetFields__c.field-meta.xml
<CustomField>
    <fullName>TargetFields__c</fullName>
    <description>데이터 가져올 sObject 의 필드 값</description>
    <inlineHelpText>여러개 일 경우, 로 구분</inlineHelpText>
    <label>TargetFields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/recordTypes/App.recordType-meta.xml
<RecordType>
    <fullName>App</fullName>
    <active>true</active>
    <description>SFDC 종 알림</description>
    <label>App</label>
</RecordType>

force-app/main/default/objects/Notification__c/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <description>SFDC 이메일 알림</description>
    <label>Email</label>
</RecordType>

force-app/main/default/objects/NotificationTarget__c/NotificationTarget__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 추가 수신자 Group, Role, User</description>
    <label>Notification Target</label>
    <nameField>
        <displayFormat>TG{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTarget__c/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <description>협업그룹명 (CollaborationGroup명)</description>
    <label>GroupName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Target</relationshipLabel>
    <relationshipName>Notification_Target</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/fields/RoleId__c.field-meta.xml
<CustomField>
    <fullName>RoleId__c</fullName>
    <description>역할Id</description>
    <label>RoleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/fields/RoleName__c.field-meta.xml
<CustomField>
    <fullName>RoleName__c</fullName>
    <description>역할명</description>
    <label>Role Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - App 알림, Email 알림.. 등 Template 관리</description>
    <label>Notification Template</label>
    <nameField>
        <displayFormat>NT{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/EmailDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>EmailDeveloperName__c</fullName>
    <description>Classic Email Template Developer Name</description>
    <label>Email Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>언어</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ko</fullName>
                <default>true</default>
                <label>ko</label>
            </value>
            <value>
                <fullName>en_US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>App 본문</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Template</relationshipLabel>
    <relationshipName>Notification_Template</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>App 제목</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/recordTypes/App.recordType-meta.xml
<RecordType>
    <fullName>App</fullName>
    <active>true</active>
    <description>SFDC 종 템플릿</description>
    <label>App</label>
</RecordType>

force-app/main/default/classes/NotiHandler_TEST.cls
@isTest
public with sharing class NotiHandler_TEST {
    @testSetup
    static void makeData() {
        NotificationManager_TEST.makeData();
        
    }

    @isTest
    static void testCase() {
        //RecordType: App
        List<Notification__c> notiList = [
            select 
                ClassName__c
                , IsDynamic__c
                , Key__c
                , Description__c
                , CustomNotificationTypeId__c
                , PageReference__c
                , sObject__c
                , TargetFields__c
                , IsSendToSender__c
                , RecordType.DeveloperName
                , IsNotiTest__c
                , IsSystemEmail__c
                , IsUseOWE__c
                , IsSaveAsActivity__c
                ,(   select 
                        Title__c
                        , Message__c
                        , Language__c
                        , EmailDeveloperName__c
                        , RecordType.DeveloperName 
                    from Notification_Template__r
                )
                ,(   select 
                        GroupId__c
                        , GroupName__c
                        , RoleId__c
                        , RoleName__c
                        , User__c
                        , RecordType.DeveloperName 
                    from Notification_Target__r
                )
            from Notification__c
            where 
                IsActive__c = true
                and Key__c = 'Sample_Noti_App'
        ];
        
        NotiHandler notiHandler = new NotiHandler();
        notiHandler.setNotiData(notiList[0]);

        //getMappingClass_TEST
        System.assert('Set<AppTemplate>'.equals(notiHandler.getMappingClass('Set', notiList[0].RecordType.DeveloperName)));
        System.assert('List<AppTemplate>'.equals(notiHandler.getMappingClass('List', notiList[0].RecordType.DeveloperName)));


        //getTemplate_TEST
        notiHandler.getTemplate();

        //getRicipientIdSet_TEST
        notiHandler.getRicipientIdSet();

        //setCategorySendDataListMap_TEST 알림 전송시에 필수적인 값: notiHandler.categorySendDataListMap
        Map<String, Map<String,NotiTemplate>> categoryTemplateMapMap = notiHandler.categoryTemplateMapMap;
        notiHandler.setCategorySendDataListMap(notiHandler.categorySendDataListMap ,'App', categoryTemplateMapMap.get('App').get('ko'));

        //notiHandler_TEST
        notiHandler.setExcludeRecipient();

        List<Account> targetAccountList = [select Id, Name, Owner.Name from Account];
        Set<String> targetIds = new Set<String>();

        Map<String,List<NotiTarget>> recipientMap = new Map<String,List<NotiTarget>>();
        NotiTarget recipientId = new NotiTarget('id');
        recipientId.setToAddresses(new Set<String>{UserInfo.getUserId()});

        for(Account ac : targetAccountList) {
            targetIds.add(ac.Id);
            recipientMap.put(ac.Id, new List<NotiTarget>{recipientId});
        }

        Id targetId = targetAccountList[0].Id;
        String targetName = targetAccountList[0].Name;

        String message = 'Name : '+targetName+' , Id '+String.valueOf(targetId);
        //초기화
        notiHandler.setNotiData(notiList[0]);
        //수신자 set
        NotificationManager.getInstance().setRecipientListMap(recipientMap);

        //execute_TEST App
        notiHandler.execute(targetIds, null, null);
        for(String category : notiHandler.categorySendDataListMap.keySet()) {
            for(NotiTemplate sendTemplate : notiHandler.categorySendDataListMap.get(category)) {
                if(targetId == sendTemplate.getTargetId()){
                    System.assert(message.equals(sendTemplate.getBody()));
                }
            }
        }

        notiList = [
            select 
                ClassName__c
                , IsDynamic__c
                , Key__c
                , Description__c
                , CustomNotificationTypeId__c
                , PageReference__c
                , sObject__c
                , TargetFields__c
                , IsSendToSender__c
                , RecordType.DeveloperName
                , IsNotiTest__c
                , IsSystemEmail__c
                , IsUseOWE__c
                , IsSaveAsActivity__c
                ,(   select 
                        Title__c
                        , Message__c
                        , Language__c
                        , EmailDeveloperName__c
                        , RecordType.DeveloperName 
                    from Notification_Template__r
                )
                ,(   select 
                        GroupId__c
                        , GroupName__c
                        , RoleId__c
                        , RoleName__c
                        , User__c
                        , RecordType.DeveloperName 
                    from Notification_Target__r
                )
            from Notification__c
            where 
                IsActive__c = true
                and Key__c = 'Sample_Noti_Email'
        ];

        //초기화
        notiHandler.setNotiData(notiList[0]);

        //수신자 set
        NotificationManager.getInstance().setRecipientListMap(recipientMap);

        //execute_TEST App
        notiHandler.execute(targetIds, null, null);

        recipientMap = new Map<String,List<NotiTarget>>();
        NotiTarget recipientEmail = new NotiTarget('email');
        recipientEmail.setToAddresses(new Set<String>{'test@test.com'});
        recipientEmail.setCcAddresses(new Set<String>{'test2@test.com'});
        recipientEmail.setBccAddresses(new Set<String>{'test3@test.com'});

        NotiTarget recipientEmail2 = new NotiTarget('email');
        recipientEmail2.setToAddresses(new Set<String>{'test4@test.com','test5@test.com'});
        recipientEmail2.setCcAddresses(new Set<String>{'test6@test.com','test7@test.com'});
        recipientEmail2.setBccAddresses(new Set<String>{'test8@test.com','test9@test.com'});

        for(Account ac : targetAccountList) {
            recipientMap.put(ac.Id, new List<NotiTarget>{recipientEmail});
        }

        targetId = targetAccountList[1].Id;
        recipientMap.get(targetId).add(recipientEmail2);

         //초기화
         notiHandler.setNotiData(notiList[0]);

        //수신자 set
        NotificationManager.getInstance().setRecipientListMap(recipientMap);

        //execute_TEST Email 단건, 다건
        notiHandler.execute(targetIds, null, null);
        for(String category : notiHandler.categorySendDataListMap.keySet()) {
            for(NotiTemplate sendTemplate : notiHandler.categorySendDataListMap.get(category)) {
                if(targetId == sendTemplate.getTargetId()){
                    if(sendTemplate.getToAddresses().size() > 1) {
                        System.assert(sendTemplate.getToAddresses().contains('test5@test.com'));
                    }
                    else {
                        System.debug(sendTemplate.getToAddresses());
                        if(new List<String>(sendTemplate.getToAddresses())[0].contains('@'))
                        System.assert(sendTemplate.getToAddresses().contains('test@test.com'));
                    }
                }
            }
        }



    }


}