force-app/main/default/objects/SalesMonthOfMASummary__c/SalesMonthOfMASummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(MA별)</label>
    <nameField>
        <label>SalesMonthOfMASummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/TotalSalesAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesAmount__c</fullName>
    <label>TotalSalesAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/TotalSalesProfit__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesProfit__c</fullName>
    <label>TotalSalesProfit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SalesBusinessPlan_ba_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-10-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class SalesBusinessPlan_ba_test {
    @TestSetup
    static void testSetup(){

        User objUser = new User();
        objUser.Id = UserInfo.getUserId();
        objUser.EmployeeNumber = 'test1234';
        update objUser;

        SalesMonthOfMASummary__c objSales = new SalesMonthOfMASummary__c();

        //objSales.CRG_MA_ID__c = objUser.EmployeeNumber;
        objSales.SalesDate__c = Date.today().addDays(-1);
        objSales.TotalNetAmount__c = 1000;
        objSales.TotalSalesAmount__c = 1100;
        objSales.TotalSalesProfit__c = 100;

        insert objSales;
    }

    @isTest
    static void itShould() {
        Test.startTest();

        //Date dtTarget = Date.newInstance(2023, 1, 1);
        SalesBusinessPlan_ba ba = new SalesBusinessPlan_ba(UserInfo.getUserId(), Date.today().year(), Date.today().month());
        Database.executeBatch(ba);

        Test.stopTest();
    }
}