force-app/main/default/objects/Quote/fields/EffectiveStartDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveStartDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/QuoteFile__c.object-meta.xml
<CustomObject>
    <label>견적 파일</label>
    <nameField>
        <displayFormat>QF-{0000000000}</displayFormat>
        <label>견적파일번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteFile__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>할인</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/fields/DownloadURL__c.field-meta.xml
<CustomField>
    <fullName>DownloadURL__c</fullName>
    <label>DownloadUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/fields/FileName__c.field-meta.xml
<CustomField>
    <fullName>FileName__c</fullName>
    <label>파일명(Txt)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/fields/FileType__c.field-meta.xml
<CustomField>
    <fullName>FileType__c</fullName>
    <label>파일유형</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/fields/FileVersion__c.field-meta.xml
<CustomField>
    <fullName>FileVersion__c</fullName>
    <label>FileVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/fields/GrandTotal__c.field-meta.xml
<CustomField>
    <fullName>GrandTotal__c</fullName>
    <label>총계</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteFile__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>견적</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>견적 파일</relationshipLabel>
    <relationshipName>QuoteFiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BasePurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePurchasePrice__c</fullName>
    <label>Base Purchase Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CountryOfOriginName__c.field-meta.xml
<CustomField>
    <fullName>CountryOfOriginName__c</fullName>
    <label>원산지</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LogisticsCenter__c.field-meta.xml
<CustomField>
    <fullName>LogisticsCenter__c</fullName>
    <label>Logistics Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1000</fullName>
                <label>KX물류센터</label>
            </value>
            <value>
                <fullName>2040</fullName>
                <label>제주FS센터</label>
            </value>
            <value>
                <fullName>2041</fullName>
                <label>제주FC</label>
            </value>
            <value>
                <fullName>2042</fullName>
                <label>제주급식</label>
            </value>
            <value>
                <fullName>2043</fullName>
                <label>제주급식센터(키즈)</label>
            </value>
            <value>
                <fullName>2120</fullName>
                <label>실수요직송센터</label>
            </value>
            <value>
                <fullName>2140</fullName>
                <label>이천)푸드빌센터</label>
            </value>
            <value>
                <fullName>2150</fullName>
                <label>농수가공비축센터</label>
            </value>
            <value>
                <fullName>2170</fullName>
                <label>외부비축창고</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FO 유통</label>
            </value>
            <value>
                <fullName>2230</fullName>
                <label>장성물류센터</label>
            </value>
            <value>
                <fullName>2231</fullName>
                <label>장성물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2240</fullName>
                <label>이천)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2250</fullName>
                <label>양산직수입센터</label>
            </value>
            <value>
                <fullName>2260</fullName>
                <label>양산물류센터</label>
            </value>
            <value>
                <fullName>2261</fullName>
                <label>양산물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2330</fullName>
                <label>장성)아라마크센터</label>
            </value>
            <value>
                <fullName>2340</fullName>
                <label>양산)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2350</fullName>
                <label>대구)아라마크센터</label>
            </value>
            <value>
                <fullName>2360</fullName>
                <label>양산)아라마크센터</label>
            </value>
            <value>
                <fullName>2370</fullName>
                <label>수원2)아라마크센터</label>
            </value>
            <value>
                <fullName>2400</fullName>
                <label>FO중부센터(물류대행)</label>
            </value>
            <value>
                <fullName>2410</fullName>
                <label>FO강남센터(물류대행)</label>
            </value>
            <value>
                <fullName>2420</fullName>
                <label>FO동서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2430</fullName>
                <label>광주외식센터</label>
            </value>
            <value>
                <fullName>2440</fullName>
                <label>FO남서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2450</fullName>
                <label>FO대구센터(물류대행)</label>
            </value>
            <value>
                <fullName>2460</fullName>
                <label>FO부산센터(물류대행)</label>
            </value>
            <value>
                <fullName>2470</fullName>
                <label>FO광주센터(물류대행)</label>
            </value>
            <value>
                <fullName>2480</fullName>
                <label>FO울산센터(물류대행)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HalfOfMonth_PL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/OldBasePurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>OldBasePurchasePrice__c</fullName>
    <label>전년 기준매입가</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductCategoryLName__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryLName__c</fullName>
    <label>ProductCategoryLName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductCategoryMName__c.field-meta.xml
<CustomField>
    <fullName>ProductCategoryMName__c</fullName>
    <label>ProductCategoryMName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProfitMargin__c.field-meta.xml
<CustomField>
    <fullName>ProfitMargin__c</fullName>
    <label>Profit Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/StorageConditionName__c.field-meta.xml
<CustomField>
    <fullName>StorageConditionName__c</fullName>
    <label>저장 조건</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TaxTypeName__c.field-meta.xml
<CustomField>
    <fullName>TaxTypeName__c</fullName>
    <label>면세여부</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPriceWithVAT__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceWithVAT__c</fullName>
    <label>Unit Price With VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/HalfOfMonth_PL.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EarlyJan</fullName>
        <label>Early Jan</label>
    </customValue>
    <customValue>
        <fullName>LateJan</fullName>
        <label>Late Jan</label>
    </customValue>
    <customValue>
        <fullName>EarlyFeb</fullName>
        <label>Early Feb</label>
    </customValue>
    <customValue>
        <fullName>LateFeb</fullName>
        <label>Late Feb</label>
    </customValue>
    <customValue>
        <fullName>EarlyMar</fullName>
        <label>Early Mar</label>
    </customValue>
    <customValue>
        <fullName>LateMar</fullName>
        <label>Late Mar</label>
    </customValue>
    <customValue>
        <fullName>EarlyApr</fullName>
        <label>Early Apr</label>
    </customValue>
    <customValue>
        <fullName>LateApr</fullName>
        <label>Late Apr</label>
    </customValue>
    <customValue>
        <fullName>EarlyMay</fullName>
        <label>Early May</label>
    </customValue>
    <customValue>
        <fullName>LateMay</fullName>
        <label>Late May</label>
    </customValue>
    <customValue>
        <fullName>EarlyJun</fullName>
        <label>Early Jun</label>
    </customValue>
    <customValue>
        <fullName>LateJun</fullName>
        <label>Late Jun</label>
    </customValue>
    <customValue>
        <fullName>EarlyJul</fullName>
        <label>Early Jul</label>
    </customValue>
    <customValue>
        <fullName>LateJul</fullName>
        <label>Late Jul</label>
    </customValue>
    <customValue>
        <fullName>EarlyAug</fullName>
        <label>Early Aug</label>
    </customValue>
    <customValue>
        <fullName>LateAug</fullName>
        <label>Late Aug</label>
    </customValue>
    <customValue>
        <fullName>EarlySep</fullName>
        <label>Early Sep</label>
    </customValue>
    <customValue>
        <fullName>LateSep</fullName>
        <label>Late Sep</label>
    </customValue>
    <customValue>
        <fullName>EarlyOct</fullName>
        <label>Early Oct</label>
    </customValue>
    <customValue>
        <fullName>LateOct</fullName>
        <label>Late Oct</label>
    </customValue>
    <customValue>
        <fullName>EarlyNov</fullName>
        <label>Early Nov</label>
    </customValue>
    <customValue>
        <fullName>LateNov</fullName>
        <label>Late Nov</label>
    </customValue>
    <customValue>
        <fullName>EarlyDec</fullName>
        <label>Early Dec</label>
    </customValue>
    <customValue>
        <fullName>LateDec</fullName>
        <label>Late Dec</label>
    </customValue>
    <masterLabel>Half Of Month</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CJFW_QuoteFileCreateNewController.cls
/**
* Custom Object QuoteLineItem 용 견적서 파일 생성
*
*@group  
*@author 진현욱
*@since 2023-10-17  내용 작성
*/
public without sharing class CJFW_QuoteFileCreateNewController {
        
    /**
     * 견적서 Record Id
     */
    public Id recordId {
        get {
            if(recordId == null) {
                recordId = ApexPages.currentPage().getParameters().get('Id');
                system.debug('[recordId] :: ' + recordId);
            }
            return recordId;
        }
        set;
    }

    /**
     * 견적서 Record
     */
    public Quote objQuote {
        get {
            if(objQuote == null) {
                objQuote = [SELECT  Id, Name, OwnerId, EffectiveStartDate__c, ExpirationDate
                                    FROM    Quote
                                    WHERE   Id = :recordId];
                system.debug('[objQuote] :: ' + objQuote);
            }
            return objQuote;
        }
        set;
    }

    /**
     * 견적서 소유자 정보
     */
    public User objOwner {
        get {
            if(objOwner == null) {
                objOwner = [SELECT  Id, Name, MobilePhone, CurrencyIsoCode
                                    FROM    User
                                    WHERE   Id = :objQuote.OwnerId];
                system.debug('[objOwner] :: ' + objOwner);
            }
            return objOwner;
        }
        set;
    }

    /**
     * 미리보기 시 선택가능한 필드 리스트
    */
    public Map<String, String> mapField {
        get {
            if(mapField == null) {
                List<Map<String, Object>> listFieldMap = CommonUtil.getFieldSet('CJFW_QuoteLineItem__c','QuoteLineItemFileCreate');
                system.debug(' listFieldMap :: ' + listFieldMap);
                Map<String, String> mapTemp= new Map<String, String> ();
                for ( Map<String, Object> objMap : listFieldMap ) {
                    String apiName = String.valueOf(objMap.get('apiName'));
                    String label = String.valueOf(objMap.get('label'));
                    system.debug(' String.valueOf(objMap.get(apiName)) :: ' + String.valueOf(objMap.get('apiName')));
                    system.debug(' String.valueOf(objMap.get(label)) :: ' + String.valueOf(objMap.get('label')));
                    mapTemp.put(apiName , label);
                }
                mapField = mapTemp;
                System.debug(
                    JSON.serializePretty(mapField)
                );
            }
            return mapField;
        }
        set;
    }
    
    /**
     * 미리보기 시 필수 필드 리스트
    */
    public List<String> listSelectedField {
        get {
            if(listSelectedField == null) {
                String strlistSelectedField = ApexPages.currentPage().getParameters().get('listSelectedField');
                system.debug('strlistSelectedField :: ' + strlistSelectedField );
                listSelectedField = strlistSelectedField.split(',');
                system.debug('listSelectedField :: ' + listSelectedField );
            }
            return listSelectedField;
        }
        set;
    }
    
    /**
     * 엑셀 생성 시 Row Span 용 
    */
    public String ExcelColummLength {
        get {
            if(ExcelColummLength == null) {
                ExcelColummLength = String.valueOf(listSelectedField.size()+2);
            }
            return ExcelColummLength;
        }
        set;
    }


    /**
     * 견적서 아이템 리스트
    */
    public List<List<CJFW_QuoteLineItem__c>> listQuoteLineItem {
        get {
            if(listQuoteLineItem == null) {
                listQuoteLineItem = new List<List<CJFW_QuoteLineItem__c>>();
                List<CJFW_QuoteLineItem__c> listTempQuoteLineItem = new List<CJFW_QuoteLineItem__c>();

                recordId = ApexPages.currentPage().getParameters().get('Id');

                listTempQuoteLineItem = [SELECT   Id, QuoteId__c, ProductName__c, QuantityUnitOfMeasure__c, ProfitMargin__c,
                                                  CountryOfOriginName__c, TaxTypeName__c, ProductCode__c, Product2Id__c, UnitPriceWithVAT__c, VAT__c,
                                                  UnitPrice__c, ToLabel(LogisticsCenter__c), ToLabel(Month__c), BasePurchasePrice__c, OldBasePurchasePrice__c, StorageConditionName__c,
                                                  ProductWeight__c, BoxQuantity__c, UnitConversion__c, Barcode__c, 
                                                  ProductCategoryLName__c, ProductCategoryMName__c
                                                  ,BiddingProductName__c ,BiddingProductWeight__c, BiddingSpec__c, BiddingUnit__c
                                         FROM     CJFW_QuoteLineItem__c
                                         WHERE    QuoteId__c = :recordId
                                         ORDER BY SortOrder__c ASC
                                         LIMIT    10000
                                        ];

                system.debug('listTempQuoteLineItem ::::::' + listTempQuoteLineItem );
                system.debug('recordId ::::::' + recordId );
                
                integer count = 0;
                integer listcount = 0;
                integer totallistsize = listTempQuoteLineItem.size();

                if ( !listTempQuoteLineItem.isEmpty()){
                    listQuoteLineItem.add(listTempQuoteLineItem);
                    if (totallistsize == 10000){

                        List<CJFW_QuoteLineItem__c> listTempQuoteLineItem2 = new List<CJFW_QuoteLineItem__c>();
                        listTempQuoteLineItem2 = [SELECT   Id, QuoteId__c, ProductName__c, QuantityUnitOfMeasure__c, ProfitMargin__c,
                                                           CountryOfOriginName__c, TaxTypeName__c, ProductCode__c, Product2Id__c, UnitPriceWithVAT__c, VAT__c,
                                                           UnitPrice__c, ToLabel(LogisticsCenter__c), ToLabel(Month__c), BasePurchasePrice__c, OldBasePurchasePrice__c, StorageConditionName__c,
                                                           ProductWeight__c, BoxQuantity__c, UnitConversion__c, Barcode__c, 
                                                           ProductCategoryLName__c, ProductCategoryMName__c
                                                           ,BiddingProductName__c ,BiddingProductWeight__c, BiddingSpec__c, BiddingUnit__c
                                                  FROM     CJFW_QuoteLineItem__c
                                                  WHERE    QuoteId__c = :recordId
                                                  AND      SortOrder__c > 10000
                                                  ORDER BY SortOrder__c ASC
                                                  LIMIT    10000
                                                 ];
                                                 
                        if ( !listTempQuoteLineItem2.isEmpty()){
                            listQuoteLineItem.add(listTempQuoteLineItem2);
                        }

                    }
                    
                }
            }
            system.debug('listQuoteLineItem.size ::::::' + listQuoteLineItem.size() );
            system.debug('[listQuoteLineItem] :: ' + listQuoteLineItem);
            return listQuoteLineItem;
        }
        set;
    }

    /**
     * Prefix 및 필드셋 정보 조회
     *      
     * @return Map<String, Object>
     *         - prefix : 현 Org의 Base Url
     *         - listField : 파일 생성시 선택 가능한 필드 목록
     *         - listRequiredField : 파일 생성시 보여질 필수 필드 목록
    **/
    @AuraEnabled
    public static Map<String, Object> getInitData() {
        
        // Excel Download 시 보여질 필드 선택
        List<Map<String, Object>> listFieldMap = CommonUtil.getFieldSet('CJFW_QuoteLineItem__c','QuoteLineItemFileCreate');
        List<Map<String, String>> listField = new List<Map<String, String>>();
        List<String> listRequiredField = new List<String>();

        for ( Map<String, Object> objMap : listFieldMap ) {
            listField.add(new Map<String, String>{
                    'label' => String.valueOf(objMap.get('label')),
                    'value' => String.valueOf(objMap.get('apiName')),
                    'type' => String.valueOf(objMap.get('type'))
            });
            if ( objMap.get('required') == true )
                listRequiredField.add(String.valueOf(objMap.get('apiName')));
        }

        String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
        System.debug('baseUrl =' + baseUrl);
        

        Map<String, Object> mapInitData = new Map<String, Object>{
            'prefix' => baseUrl,
            'listField' => listField,   
            'listRequiredField' => listRequiredField
        };
        return mapInitData;
    }


    /**
     * Prefix 및 필드셋 정보 조회
     * 
     * @param  recordId : 견적서 Record Id
     * @param  saveType : 파일 타입 (PDF/Excel)
     * @param  listSelectedSave : 파일 내 조회될 필드 리스트
     * 
    **/
    @AuraEnabled
    public static void doCreateFile(Id recordId, String saveType, String listSelectedSave) {
        System.debug('listSelectedSave ========> '  + listSelectedSave); 
        
        // Standard Quote PDF 에서 Discount, GrandTotal을 제공함에 따라 Custom에서도 동일 기능 구현 
        Quote objQuote = [SELECT Id, Name, Discount, GrandTotal
                                   FROM Quote
                                   WHERE id =: recordId
                                  ];


        // File Version Check
        List<QuoteFile__c> listQuoteFile = [SELECT   Id, FileVersion__c
                                            FROM     QuoteFile__c
                                            WHERE    Quote__c = :recordId
                                            ORDER BY FileVersion__c DESC
                                            LIMIT    1
                                           ];
                                                
        String strfileVersion ;              
        Decimal decfileVersion ;
        if ( listQuoteFile.isEmpty() ){
            decfileVersion = 1;
        } else {
            decfileVersion = listQuoteFile[0].FileVersion__c+1;
        }
        strfileVersion = String.valueOf(decfileVersion);

        // Type에 따라 Blob화 분기
        Blob body ;
        try {
            if ( saveType == 'PDF'){
                PageReference pdf = new pagereference('/apex/CJFW_QuotePDFCreateNew');
                pdf.getParameters().put('Id', recordId ); 
                pdf.getParameters().put('listSelectedField', listSelectedSave );
                System.debug('pdf link ========> '  + pdf.getUrl());
                body = pdf.getContentAsPDF();
            }
            else if ( saveType == 'Excel'){
                PageReference excel = new pagereference('/apex/CJFW_QuoteExcelCreateNew');
                excel.getParameters().put('Id', recordId ); 
                excel.getParameters().put('listSelectedField', listSelectedSave );
                System.debug('excel link ========> '  + excel.getUrl());
                body = excel.getContent();
            }
        } catch (VisualforceException e) {
            body = Blob.valueOf('Error');
        }

        
        // 확장자 따라 Blob화 분기
        String fileType = 'None';
        if ( saveType == 'PDF')
            fileType = 'pdf';
        else if ( saveType == 'Excel')
            fileType = 'xls';

        String fileName = objQuote.Name+'_V'+strfileVersion+'.'+fileType;


        ContentVersion objContentVersion = new ContentVersion(
                Title = fileName,
                PathOnClient = fileName,
                VersionData = body,
                FirstPublishLocationId = recordId
        );
        insert objContentVersion;

        ContentDistribution objContentDistribution = new ContentDistribution(
            ContentVersionId = objContentVersion.Id,
            Name = fileName,
            PreferencesAllowViewInBrowser = true,
            PreferencesLinkLatestVersion = true,
            PreferencesNotifyOnVisit = false,
            PreferencesPasswordRequired = false,
            PreferencesAllowOriginalDownload = true
        );

        insert objContentDistribution;

        ContentDistribution objContentDistribution2 = [SELECT Id, ContentVersionId, ContentDocumentId, ContentDownloadUrl
                                   FROM ContentDistribution
                                   WHERE id =: objContentDistribution.Id
                                  ];
        
        ContentDocument objContentDocument = [SELECT Id, FileType
                                   FROM ContentDocument
                                   WHERE id =: objContentDistribution2.ContentDocumentId
                                  ];

        QuoteFile__c objQuoteFile = new QuoteFile__c(
            FileName__c = fileName,
            DownloadUrl__c =  objContentDistribution2.ContentDownloadUrl,
            ContentDocumentId__c =  objContentDistribution2.ContentDocumentId,
            FileType__c =  saveType,
            FileVersion__c = decfileVersion,
            Discount__c = objQuote.Discount,
            GrandTotal__c = objQuote.GrandTotal,
            Quote__c = recordId
        );

        insert objQuoteFile;
        system.debug(objQuoteFile);
    }

}