force-app/main/default/objects/ActivityReport__c/ActivityReport__c.object-meta.xml
<CustomObject>
    <label>활동 보고</label>
    <nameField>
        <label>Activity Report Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityReport__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/DecisionProcess__c.object-meta.xml
<CustomObject>
    <label>품의 이력</label>
    <nameField>
        <label>품의명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DecisionProcess__c/fields/approvedCount__c.field-meta.xml
<CustomField>
    <fullName>approvedCount__c</fullName>
    <label>approvedCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/APPV_NO__c.field-meta.xml
<CustomField>
    <fullName>APPV_NO__c</fullName>
    <label>APPVNO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocId__c.field-meta.xml
<CustomField>
    <fullName>DocId__c</fullName>
    <label>DocId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocStatus__c.field-meta.xml
<CustomField>
    <fullName>DocStatus__c</fullName>
    <label>DocStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocURL__c.field-meta.xml
<CustomField>
    <fullName>DocURL__c</fullName>
    <label>품의서 URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/fm_ApprovalStatusInfo__c.field-meta.xml
<CustomField>
    <fullName>fm_ApprovalStatusInfo__c</fullName>
    <formula>CASE(
   DocStatus__c, 
   &quot;임시저장&quot;, DocStatus__c, 
   &quot;진행&quot;, DocStatus__c &amp;&quot;[&quot;&amp;   TEXT(approvedCount__c ) &amp;&quot;/&quot;&amp; TEXT(totalLineCount__c )&amp;&quot;]&quot;,
   &quot;완료&quot;, DocStatus__c &amp;&quot;[&quot;&amp;   TEXT(approvedCount__c ) &amp;&quot;/&quot;&amp; TEXT(totalLineCount__c )&amp;&quot;]&quot;,
   DocStatus__c
)</formula>
    <label>결재상태</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/fm_RecentApprovalInfo__c.field-meta.xml
<CustomField>
    <fullName>fm_RecentApprovalInfo__c</fullName>
    <formula>IF(  
   NOT(ISBLANK(approvedUserName__c)),
   approvedUserName__c &amp;&quot;(&quot;&amp; approvedUserType__c&amp;&quot;) &quot;&amp; approvedDate__c,
   &quot;&quot;
)</formula>
    <label>최근 결재 이력</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/RegUserHeadOfficeCode__c.field-meta.xml
<CustomField>
    <fullName>RegUserHeadOfficeCode__c</fullName>
    <label>RegUserHeadOfficeCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/RegUserName__c.field-meta.xml
<CustomField>
    <fullName>RegUserName__c</fullName>
    <label>RegUserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/RegUserNumber__c.field-meta.xml
<CustomField>
    <fullName>RegUserNumber__c</fullName>
    <label>RegUserNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/RegUserSUCode__c.field-meta.xml
<CustomField>
    <fullName>RegUserSUCode__c</fullName>
    <label>RegUserSUCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/RegUserTeamCode__c.field-meta.xml
<CustomField>
    <fullName>RegUserTeamCode__c</fullName>
    <label>RegUserTeamCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/TotalHeadcount__c.field-meta.xml
<CustomField>
    <fullName>TotalHeadcount__c</fullName>
    <label>TotalHeadcount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/totalLineCount__c.field-meta.xml
<CustomField>
    <fullName>totalLineCount__c</fullName>
    <label>totalLineCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>377</fullName>
                <label>FS본부)기타</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>378</fullName>
                <label>FS개발)병원·레저개발팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>153</fullName>
                <label>아이누리)아이누리1팀</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>아이누리)아이누리동부팀</label>
            </value>
            <value>
                <fullName>314</fullName>
                <label>아이누리)아이누리2팀</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>363</fullName>
                <label>아이누리)아이누리서부팀</label>
            </value>
            <value>
                <fullName>365</fullName>
                <label>아이누리)아이누리3팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>348</fullName>
                <label>외식중부)외식2팀</label>
            </value>
            <value>
                <fullName>366</fullName>
                <label>외식중부)외식1팀</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Writing</fullName>
        <default>true</default>
        <label>Writing</label>
    </customValue>
    <customValue>
        <fullName>Request</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
        <isActive>false</isActive>
        <label>In Progress</label>
    </customValue>
    <description>승인 상태</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OilApprovalSendHistory.cls
/************************************************************************************
 * File Name   		: OilApprovalSendHistory.cls
 * Author	  		: Kim.Minje
 * Date				: 2023.01.10
 * Tester	  		: OilApprovalSendHistory_test.cls
 * Description 		: 주유비 전표처리 전송 이력 관리 Controller
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.01.10      Minje.Kim       Create
*************************************************************************************/

public with sharing class OilApprovalSendHistory {
    
    /**
     * 주유비 정산 전송이력 탭 Init (데이터 조회를 위한 정보 셋팅)
     * 
     * @params 없음
     * @return DataWrapper 
     *         - objUser : 유저 정보
     *         - listSelectStatus : 제출상태 리스트
     *         - listSelectHeadOffice : 사업부 리스트
     *         - mapSelectSU : SU 리스트
     *         - listYear : 년도 리스트
     *         - listMonth : 월 리스트
     *         - targetYear : 초기 년도 설정값
     *         - targetMonth : 초기 월 설정값
     *
    **/
    @AuraEnabled
    public static DataWrapper doInit() {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        DataWrapper objWrapper = new DataWrapper();

        try {
            User objUser = [
                SELECT  Id, EmployeeNumber, HeadOffice__c, SU__c, Team__c
                FROM    User
                WHERE   Id =: UserInfo.getUserId()
            ];
            objWrapper.objUser = objUser;

            objWrapper.listSelectStatus = CommonUtil.getPickListValues('ActivityReport__c', 'ApprovalStatus__c', false);
            objWrapper.listSelectHeadOffice = CommonUtil.getPickListValues('User', 'HeadOffice__c', false);
            objWrapper.mapSelectSU = CommonUtil.getDependentPicklistValues(User.SU__c); 

            // Dafault 선택 년도 및 월 계산
            Date targetDate = Date.today().day() > 10 ? Date.today() : Date.today().addMonths(-1);  
            String targetYear = String.valueOf(targetDate.year());
            
            // Dafault 선택 년도 및 선택목록에 표시될 년도 셋팅
            List<Map<String,String>> listYear = new List<Map<String,String>>();
            Integer seqYear = Date.today().year() - 4;
            System.debug( 'targetYear :: ' + targetYear);
            System.debug( 'seqYear :: ' + seqYear);
            while ( seqYear <=  Date.today().year()) {
                listYear.add(new Map<String, String>{
                    'label' => String.valueOf(seqYear) + '년',
                    'value' => String.valueOf(seqYear),
                    'selected' => targetDate.year() == seqYear ? 'true' : 'false'
                });
                seqYear++;
            }
            objWrapper.listYear = listYear;
            objWrapper.targetYear = targetYear;
            
            // 선택목록 표시될 월 셋팅 (Default 선택 월은 전체)
            List<Map<String,String>> listMonth = new List<Map<String,String>>();
            Integer seqMonth = 1; 
            
            listMonth.add(new Map<String, String>{
                'label' => '전체',
                'value' => 'none',
                'selected' => 'true'
            });

            while ( seqMonth < 13 ) {
                listMonth.add(new Map<String, String>{
                    'label' => String.valueOf(seqMonth) + '월',
                    'value' => String.valueOf(seqMonth),
                    'selected' => 'false'
                });
                seqMonth++;
            }
            objWrapper.listMonth = listMonth;
            objWrapper.targetMonth = 'none';

        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    
    /**
     * 주유비 정산 전송이력 데이터 조회
     * 
     * @params Map<String, String> mapParam
     *         - selectedYear : 선택된 년도 정보
     *         - selectedMonth : 선택된 월 정보
     *         - selectedStatus : 선택된 제출상태 코드
     *         - selectedHeadOffice : 선택된 사업부 코드
     *         - selectedSU : 선택된 SU 코드
     * @return DataWrapper objWrapper
     *         - listTargetId : 품의이력 SFDC ID 리스트
     *         - strStatus : 조회 성공/실패 여부
     *         - strMessage : 조회 실패시 에러메세지
     *
    **/
    @AuraEnabled
    public static SearchWrapper doGetTargetData(Map<String, String> mapParam) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        SearchWrapper objWrapper = new SearchWrapper();
    
        String strTargetYear = String.valueOf(mapParam.get('selectedYear'));
        String strTargetMonth = String.valueOf(mapParam.get('selectedMonth'));

        try {
            System.debug('selectedHeadOffice :: ' + String.valueOf(mapParam.get('selectedHeadOffice')));
            System.debug('selectedSU :: ' + String.valueOf(mapParam.get('selectedSU')));

            // 선택된 파라미터를 바탕으로 대상 데이터 쿼리
            String strQuery = '';
            strQuery += '    SELECT  Id, RegUserName__c, RegUserNumber__c, Year__c, Month__c, DocURL__c,  ';
            strQuery += '            RegUserTeamCode__c, RegUserSUCode__c, totalAmount__c, totalHeadcount__c,  ';
            strQuery += '            fm_ApprovalStatusInfo__c, fm_RecentApprovalInfo__c ';
            strQuery += '    FROM    DecisionProcess__c   ';
            strQuery += '    WHERE   year__c = \''+ strTargetYear+'\'';
            
            if(strTargetMonth <> null && strTargetMonth <> 'none') {
                strQuery += '    AND     month__c = \''+ strTargetMonth+'\'';
            }

            if(mapParam.get('selectedHeadOffice') <> null && mapParam.get('selectedHeadOffice') <> 'none') {
                strQuery += '    AND     RegUserHeadOfficeCode__c = \''+mapParam.get('selectedHeadOffice')+'\'';
            }

            if(mapParam.get('selectedSU') <> null && mapParam.get('selectedSU') <> 'none') {
                strQuery += '    AND     RegUserSUCode__c = \''+mapParam.get('selectedSU')+'\'';
            }

            System.debug('strQuery :: ' + strQuery);

            Map<Id, DecisionProcess__c> mapDecisionProcess = new Map<Id, DecisionProcess__c>( (List<DecisionProcess__c>) Database.query(strQuery));
            objWrapper.listTargetId = mapDecisionProcess.keyset();

        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    
    /**
     * 주유비 정산 탭 전송이력 전자결재 번호 변환 (재무시스템 문서번호 -> 전자결재 문서번호 변환 I/F 후 저장 )
     * 
     * @params String targetId : 전자결재 문서 조회 대상 ID
     * @return DataWrapper objWrapper
     *         - strStatus : 성공/실패 여부
     *         - strMessage : 실패시 에러메세지
     *
    **/
    @AuraEnabled
    public static SearchWrapper doUpdateDocId(String targetId) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        SearchWrapper objWrapper = new SearchWrapper();

        try {
            // 품의이력 대상 조회
            List<DecisionProcess__c> listDecisionProcess = [
                SELECT  Id, APPV_NO__c
                FROM    DecisionProcess__c
                WHERE   Id =: targetId
                AND     APPV_NO__c != ''
                AND     DocId__c =''
            ];

            // I/F 진행
            if( !listDecisionProcess.isEmpty()){
                DecisionProcess__c objDecisionProcess = listDecisionProcess[0];
                // 파라미터 설정
                Map<String,String> objInput = new Map<String,String>();
                objInput.put('opcode', 'EC003');    
                objInput.put('COM_CD', 'FW00');    
                objInput.put('APPV_NO', objDecisionProcess.APPV_NO__c);    

                // I/F 실행
                IFUtil ifutilWrapper = new IFUtil('IF_SFDC_EACCT_INFO_VRC');
                
                String strJsonRequestBody = JSON.serialize(objInput);
                HttpResponse response = ifutilWrapper.webCallout(strJsonRequestBody, true);

                system.debug(' doUpdateDocId response.getStatusCode() ::: ' + response.getStatusCode() );

                // I/F 성공 시 
                if ( response.getStatusCode() == 200  ){
                    system.debug(' doUpdateDocId response.getBody() ::: ' + response.getBody() );
                    Map<String, Object> resultMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());  
                    // 반환 시 에러코드 발생한 경우 에러메세지 
                    if ( resultMap.get('ERR_CD') == 'E') {
                        strStatus = 'ERROR';
                        strMessage = '[I/F Error] ::: ['+resultMap.get('err_cd')+'] '+resultMap.get('err_msg_ctt');
                        system.debug( 'ERROR ::: ['+resultMap.get('err_cd')+'] '+resultMap.get('err_msg_ctt'));
                    }
                    // 반환 시 정상적인 경우 해당 품의이력에 전자결재 문서번호 저장 
                    else {
                        DecisionProcess__c objTarget = new DecisionProcess__c();
                        objTarget.Id = objDecisionProcess.Id;
                        objTarget.DocId__c =  String.valueOf(resultMap.get('DOC_ID'));
                        update objTarget;
                    }
                }
                // I/F 실패 시 에러메세지
                else {
                    strStatus = 'ERROR';
                    strMessage = '[I/F Error] ::: [' + response.getStatusCode() + '] 서버접속 실패';
                    system.debug( 'ERROR ::: [' + response.getStatusCode() + '] 서버접속 실패');
                }
            }
        // 기타 실패 시 에러메세지
        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    
    /**
     * 주유비 정산 탭 전송이력 전자결재 문서 상태 업데이트 
     * 
     * @params String targetId : 전자결재 문서 조회 대상 ID
     * @return DataWrapper objWrapper
     *         - strStatus : 성공/실패 여부
     *         - strMessage : 실패시 에러메세지
     *
    **/
    @AuraEnabled
    public static SearchWrapper doUpdateDocState(String targetId) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        SearchWrapper objWrapper = new SearchWrapper();

        // 품의이력 대상 조회
        List<DecisionProcess__c> listDecisionProcess = [
            SELECT  Id, Name, DocId__c, DocStatus__c, totalLineCount__c, approvedCount__c, 
                    approvedUserName__c, approvedUserType__c, approvedDate__c, approvedUserCode__c
            FROM    DecisionProcess__c
            WHERE   Id =: targetId
        ];

        // I/F 진행
        List<DecisionProcess__c> listTarget = new List<DecisionProcess__c>();
        if( !listDecisionProcess.isEmpty()){
            // 파라미터 설정
            DecisionProcess__c objDecisionProcess = listDecisionProcess[0];
            Map<String,String> objInput = new Map<String,String>();
            objInput.put('doc_id', objDecisionProcess.DocId__c);    

            // I/F 실행
            IFUtil ifutilWrapper = new IFUtil('IF_SFDC_IFRESH_INFO_APPROVAL');
            String strJsonRequestBody = JSON.serialize(objInput);
            HttpResponse response = ifutilWrapper.webCallout(strJsonRequestBody, true);

            // I/F 성공 시 
            if ( response.getStatusCode() == 200  ){

                system.debug(' response.getStatusCode() ::: ' + response.getStatusCode() );
                system.debug(' response.getBody() ::: ' + response.getBody() );
                Map<String, Object> resultMap = new Map<String, Object>();
                
                // 반환 데이터가 SFDC 형태로 변환, 정상적이지 않은 경우 에러 메세지
                try{
                    resultMap = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());  
                } catch (Exception e) {
                    objWrapper.strStatus = 'ERROR';
                    objWrapper.strMessage = '[I/F Error] ::: 전자결재 서버접속 실패';
                    system.debug( '[I/F Error] :::  전자결재 서버접속 실패');
                    return objWrapper;
                }
                // 반환 시 에러코드 발생한 경우 에러메세지 
                if ( resultMap.get('err_cd') == '실패') {
                    // 프로세스 종료 
                    strStatus = 'ERROR';
                    strMessage = '[I/F Error] ::: ['+resultMap.get('err_cd')+'] '+resultMap.get('err_msg_ctt');
                    system.debug( '[I/F Error] ::: ['+resultMap.get('err_cd')+'] '+resultMap.get('err_msg_ctt'));
                }
                // 반환 시 정상적인 경우 변경된 상태값으로 저장
                else {
                    system.debug( 'check doc_state ::: ' + resultMap.get('doc_state'));
                    system.debug( 'check url ::: ' + resultMap.get('url'));
                    system.debug( 'check approval_line ::: ' + resultMap.get('approval_line'));
                    List<Object> listLine = (List<Object>) resultMap.get('approval_line');

                    String DocStatus = String.valueOf(resultMap.get('doc_state'));
                    if (DocStatus == '' ) DocStatus = '임시저장';
                    Integer approvedCount = 0;
                    Integer totalLineCount = listLine != null ? listLine.size() : 0;
                    String approvedUserName = '';
                    String approvedUserType = '';
                    String approvedDate = '';
                    String approvedUserCode = '';         
                    
                    for (Integer i = totalLineCount-1 ; i >= 0 ; i--){
                        system.debug( 'i ::: ' + i);
                        system.debug( 'listLine['+i+'] ::: ' + listLine[i]);
                        Map<String, Object> mapObjLine = (Map<String, Object>) listLine[i]; 
                        String status = String.valueOf(mapObjLine.get('status'));
                        if ( status == '결재처리함'){
                            approvedCount    = Integer.valueOf(String.valueOf(mapObjLine.get('no')));
                            approvedUserName = String.valueOf(mapObjLine.get('user_name')); 
                            approvedUserType = String.valueOf(mapObjLine.get('approval_type'));
                            approvedDate     = String.valueOf(mapObjLine.get('approval_date')); 
                            approvedUserCode = String.valueOf(mapObjLine.get('user_id'));
                            break;
                        }             
                    }

                    // 값이 바뀌어 있는 경우에만 update 하도록 처리
                    if ( 
                        objDecisionProcess.DocStatus__c != DocStatus || 
                        objDecisionProcess.approvedCount__c != approvedCount || 
                        objDecisionProcess.approvedUserName__c != approvedUserName || 
                        objDecisionProcess.approvedUserType__c != approvedUserType || 
                        objDecisionProcess.approvedDate__c != approvedDate || 
                        objDecisionProcess.approvedUserCode__c != approvedUserCode ||
                        objDecisionProcess.totalLineCount__c != totalLineCount
                    )
                    {
                        DecisionProcess__c objTarget = new DecisionProcess__c();
                        objTarget.Id = objDecisionProcess.Id;
                        objTarget.DocStatus__c = DocStatus;
                        objTarget.approvedCount__c = approvedCount;
                        objTarget.approvedUserName__c = approvedUserName;
                        objTarget.approvedUserType__c = approvedUserType;
                        objTarget.approvedDate__c = approvedDate;
                        objTarget.approvedUserCode__c = approvedUserCode;
                        objTarget.totalLineCount__c = totalLineCount;
                        listTarget.add(objTarget);
                    }
                }

                if ( !listTarget.isEmpty() ) {
                    System.debug(' ::: listTargetDecisionProcess  ::: ');
                    System.debug( listTarget);
                    System.debug(' :::::::::::::::::::::::::::::::::: ');
                    update listTarget;
                }
            }
            // I/F 실패 시 에러메세지
            else {
                strStatus = 'ERROR';
                strMessage = '[I/F Error] ::: [' + response.getStatusCode() + '] 서버접속 실패';
                system.debug( '[I/F Error] ::: [' + response.getStatusCode() + '] 서버접속 실패');
            }
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    
    /**
     * 주유비 정산 탭 전송이력 데이터 조회
     * 
     * @params String listTargetId : 품의이력 조회 대상 ID 리스트
     * @return DataWrapper objWrapper
     *         - listSearchLineWrapper : 조회 결과 리스트
     *         - strStatus : 성공/실패 여부
     *         - strMessage : 실패시 에러메세지
     *
    **/
    @AuraEnabled
    public static SearchWrapper getDataTable(List<String> listTargetId) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        SearchWrapper objWrapper = new SearchWrapper();
        List<SearchLineWrapper> listSearchLineWrapper = new List<SearchLineWrapper>();

        Map<String, String> mapSUToLabel = CommonUtil.getMapPickListValuetoLabel('User', 'SU__c');
        Map<String, String> mapTeamToLabel = CommonUtil.getMapPickListValuetoLabel('User', 'Team__c');

        try {
            // 대상 리스트 조회
            List<DecisionProcess__c> listDecisionProcess = [
                SELECT  Id, RegUserName__c, RegUserNumber__c, Year__c, Month__c, DocURL__c, 
                        RegUserTeamCode__c, RegUserSUCode__c, totalAmount__c, totalHeadcount__c,
                        fm_ApprovalStatusInfo__c, fm_RecentApprovalInfo__c
                FROM    DecisionProcess__c
                WHERE   Id =: listTargetId
            ];

            // 화면 출력을 위해 Wrapper 형태로 변환
            for ( DecisionProcess__c objDecisionProcess : listDecisionProcess ){      
                SearchLineWrapper objSearchWrapper = new SearchLineWrapper();
                objSearchWrapper.RegUser = objDecisionProcess.RegUserName__c +' ('+objDecisionProcess.RegUserNumber__c+')';
                objSearchWrapper.YearAndMonth = objDecisionProcess.Year__c + '년 ' + objDecisionProcess.Month__c +'월';
                objSearchWrapper.TeamLabel = mapTeamToLabel.get(objDecisionProcess.RegUserTeamCode__c);
                objSearchWrapper.SULabel = mapSUToLabel.get(objDecisionProcess.RegUserSUCode__c); 
                objSearchWrapper.totalAmount = String.valueOf(objDecisionProcess.totalAmount__c);
                objSearchWrapper.totalHeadcount = String.valueOf(objDecisionProcess.totalHeadcount__c)+'명' ;
                objSearchWrapper.ApprovalStatusInfo = objDecisionProcess.fm_ApprovalStatusInfo__c;
                objSearchWrapper.RecentApprovalInfo = objDecisionProcess.fm_RecentApprovalInfo__c;
                objSearchWrapper.DocURL = objDecisionProcess.DocURL__c;
                listSearchLineWrapper.add(objSearchWrapper);
            }
        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.listSearchLineWrapper = listSearchLineWrapper;
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    
    public class DataWrapper {
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}
        @AuraEnabled
        public List<SearchWrapper> listSearchWrapper {get;set;}
        @AuraEnabled
        public Map<String,Set<String>> mapActivityReportId {get;set;}
        @AuraEnabled
        public User objUser {get;set;}
        @AuraEnabled
        public String strHeadOffice {get;set;}
        @AuraEnabled
        public String strSU {get;set;}
        @AuraEnabled
        public String strTeam {get;set;}
        // SearchData
        @AuraEnabled
        public String targetYear {get;set;}
        @AuraEnabled
        public String targetMonth {get;set;}
        @AuraEnabled
        public List<Map<String,String>> listYear {get;set;}
        @AuraEnabled
        public List<Map<String,String>> listMonth {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listSelectStatus {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listSelectHeadOffice {get;set;}
        @AuraEnabled
        public Map<String, List<Map<String, String>>> mapSelectSU {get;set;}        

    }

    public class SearchWrapper {
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}
        @AuraEnabled
        public List<SearchLineWrapper> listSearchLineWrapper {get;set;}
        @AuraEnabled
        public Set<Id> listTargetId {get;set;}
    }

    public class SearchLineWrapper {
        @AuraEnabled
        public String SULabel {get;set;}
        @AuraEnabled
        public String TeamLabel {get;set;}
        @AuraEnabled
        public String RegUser {get;set;}
        @AuraEnabled
        public String YearAndMonth {get;set;}
        @AuraEnabled
        public String totalAmount {get;set;}
        @AuraEnabled
        public String totalHeadcount {get;set;}
        @AuraEnabled
        public String ApprovalStatusInfo {get;set;}
        @AuraEnabled
        public String RecentApprovalInfo {get;set;}
        @AuraEnabled
        public String DocUrl {get;set;}
    }
}