force-app/main/default/objects/ActivityReport__c/ActivityReport__c.object-meta.xml
<CustomObject>
    <label>활동 보고</label>
    <nameField>
        <label>Activity Report Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityReport__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Writing</fullName>
        <default>true</default>
        <label>Writing</label>
    </customValue>
    <customValue>
        <fullName>Request</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
        <isActive>false</isActive>
        <label>In Progress</label>
    </customValue>
    <description>승인 상태</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ActivityReport_tr_test.cls
/************************************************************************************
 * File Name   		    : ActivityReport_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2022.11.21
 * Target	  		    : ActivityReport_tr.cls`
 * Description 		    : ActivityReport_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2022.11.21      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class ActivityReport_tr_test {
    @isTest 
    static void itShould() {
        Test.startTest();
        Account objExAccount = TestObjectCreator.objExAccount;
        insert objExAccount;

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objExAccount.Id;
        objOpportunity.Name = '영업활동';
        objOpportunity.CloseDate = date.valueOf('2022-01-01');
        objOpportunity.StageName = 'Proposal';
        insert objOpportunity;


        Event objEvent = new Event();
        objEvent.ActivityDate = Date.today();
        objEvent.Subject = 'Test';
        objEvent.Opportunity__c = objOpportunity.Id;
        objEvent.StartDateTime = Datetime.now();
        objEvent.EndDateTime = Datetime.now().addHours(1);
        objEvent.WorkType__c = '외근';
        insert objEvent;

        ActivityReport__c objActivityReport = [
            SELECT Id, ApprovalStatus__c  FROM ActivityReport__c LIMIT 1
        ];

        objActivityReport.ApprovalStatus__c = 'Request';

        update objActivityReport;

        Test.stopTest();
    }
}