force-app/main/default/objects/ActivityReport__c/ActivityReport__c.object-meta.xml
<CustomObject>
    <label>활동 보고</label>
    <nameField>
        <label>Activity Report Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityReport__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActivityReport__c/fields/OilTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>OilTotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OilTotalAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/FieldBriefing__c.object-meta.xml
<CustomObject>
    <label>현장설명회</label>
    <nameField>
        <label>공고명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieldBriefing__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/isMig__c.field-meta.xml
<CustomField>
    <fullName>isMig__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isMig</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/LinkedRecordId__c.field-meta.xml
<CustomField>
    <fullName>LinkedRecordId__c</fullName>
    <label>LinkedRecordId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Field_Briefing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/SalesStage__c.field-meta.xml
<CustomField>
    <fullName>SalesStage__c</fullName>
    <description>영업단계</description>
    <label>Sales Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>현장실사 및 시설파악</fullName>
            </value>
            <value>
                <fullName>고객 및 키맨 인터뷰</fullName>
            </value>
            <value>
                <fullName>운영 기초 정보 파악</fullName>
            </value>
            <value>
                <fullName>해당없음</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/WorkType__c.field-meta.xml
<CustomField>
    <fullName>WorkType__c</fullName>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내근</fullName>
            </value>
            <value>
                <fullName>외근</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Writing</fullName>
        <default>true</default>
        <label>Writing</label>
    </customValue>
    <customValue>
        <fullName>Request</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
        <isActive>false</isActive>
        <label>In Progress</label>
    </customValue>
    <description>승인 상태</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Event_tr_test.cls
/************************************************************************************
 * File Name   		    : Event_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2022.11.21
 * Target	  		    : Event_tr.cls
 * Description 		    : Event_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2022.11.21      Minje.kim       Create
 *************************************************************************************/

 @IsTest
 public with sharing class Event_tr_test {
 
     @isTest 
     static void itShould() {
         Test.startTest();
         Account objExAccount = TestObjectCreator.objExAccount;
         insert objExAccount;
         Opportunity objOpportunity = new Opportunity();
         objOpportunity.AccountId = objExAccount.Id;
         objOpportunity.Name = '영업활동';
         objOpportunity.CloseDate = date.valueOf('2022-01-01');
         objOpportunity.StageName = 'Proposal';
         insert objOpportunity;
 
         FieldBriefing__c objFieldBriefing = new FieldBriefing__c();
         objFieldBriefing.Opportunity__c = objOpportunity.Id;
         objFieldBriefing.name = 'test';
         objFieldBriefing.SalesStage__c = '현장실사 및 시설파악';
         objFieldBriefing.WorkType__c = '외근';
         objFieldBriefing.StartDateTime__c = datetime.valueOf('2022-01-01 15:00:00.000Z');
         objFieldBriefing.EndDateTime__c = datetime.valueOf('2022-01-02 15:00:00.000Z');
         insert objFieldBriefing;
 
         Event objEvent1 = new Event();
         objEvent1.StartDateTime = Datetime.valueOf('2022-01-01 09:00:00');
         objEvent1.DurationInMinutes = 2;
         objEvent1.VehicleRefuelingCosts__c = 2000;
         objEvent1.Opportunity__c = objOpportunity.Id;
         objEvent1.isMig__c = false;
         insert objEvent1;
 
         Event objEvent2 = new Event();
         objEvent2.StartDateTime = Datetime.valueOf('2022-01-01 09:00:00');
         objEvent2.WhatId = objExAccount.Id;
         objEvent2.DurationInMinutes = 2;
         objEvent2.VehicleRefuelingCosts__c = 2000;
         insert objEvent2;
 
         Event objEvent4 = new Event();
         objEvent4.StartDateTime = Datetime.valueOf('2022-01-01 09:00:00');
         objEvent4.WhatId = objOpportunity.Id;
         objEvent4.DurationInMinutes = 2;
         objEvent4.VehicleRefuelingCosts__c = 2000;
         insert objEvent4;
 
         //linkedRecordId 있음
         Event objEvent5 = new Event();
         objEvent5.StartDateTime = Datetime.valueOf('2022-01-01 09:00:00');
         objEvent5.WhatId = objOpportunity.Id;
         objEvent5.DurationInMinutes = 2;
         objEvent5.VehicleRefuelingCosts__c = 2000;
         objEvent5.LinkedRecordId__c = objFieldBriefing.Id;
         insert objEvent5;
         delete objEvent5;       
 
         Event objEvent = new Event();
         objEvent.Id = objEvent1.Id;
         objEvent.VehicleRefuelingCosts__c = 3000;
         objEvent.WhatId = objOpportunity.Id;
         update objEvent;
 
         // objEvent = new Event();
         // objEvent.Id = objEvent2.Id;
         // objEvent.WhatId = objOpportunity.Id;
         // delete objEvent;
 
 
         Test.stopTest();
     }
     
     @isTest 
     static void itShould2() {
         Test.startTest();
 
         Account objExAccount = TestObjectCreator.objExAccount;
         insert objExAccount;
         Opportunity objOpportunity = new Opportunity();
         objOpportunity.AccountId = objExAccount.Id;
         objOpportunity.Name = '영업활동';
         objOpportunity.CloseDate = date.valueOf('2022-01-01');
         objOpportunity.StageName = 'Proposal';
         insert objOpportunity;
         
         ActivityReport__c objActivityReport = new ActivityReport__c();
         objActivityReport.OilTotalAmount__c = 1000;
         objActivityReport.ApprovalStatus__c = 'Writing';
         insert objActivityReport;
 
         Event objEvent6 = new Event();
         objEvent6.StartDateTime = Datetime.valueOf('2022-01-01 09:00:00');
         objEvent6.EndDateTime = Datetime.valueOf('2022-01-01 18:00:00');
         objEvent6.WhatId = objOpportunity.Id;
         objEvent6.DurationInMinutes = 540;
         objEvent6.VehicleRefuelingCosts__c = 2000;
         objEvent6.WorkType__c ='외근';
         objEvent6.isMig__c = false;
         insert objEvent6;
 
         objEvent6.StartDateTime = Datetime.valueOf('2022-01-02 09:00:00');
         objEvent6.EndDateTime = Datetime.valueOf('2022-01-02 18:00:00');
         objEvent6.DurationInMinutes = 540;
         objEvent6.WhatId = objOpportunity.Id;
         objEvent6.WorkType__c ='내근';
         update objEvent6;
 
         objEvent6.ActivityReport__c = objActivityReport.Id;
         objEvent6.WorkType__c ='외근';
         update objEvent6;
 
         // objEvent6.StartDateTime = Datetime.valueOf('2021-12-31 09:00:00');
         // objEvent6.EndDateTime = Datetime.valueOf('2021-12-31 10:00:00');
         // objEvent6.DurationInMinutes = 60;
         // update objEvent6;
         
         // objActivityReport.ApprovalStatus__c = 'Approved';
         // update objActivityReport;
 
         // objEvent6.StartDateTime = Datetime.valueOf('2021-12-30 09:00:00');
         // objEvent6.EndDateTime = Datetime.valueOf('2021-12-30 10:00:00');
         // objEvent6.DurationInMinutes = 60;
         // update objEvent6;
 
         // delete objEvent6;
 
         Test.stopTest();
     }
 
     @isTest 
     static void itShould3() {
         Test.startTest();
         Account objExAccount = TestObjectCreator.objExAccount;
         insert objExAccount;
         Opportunity objOpportunity = new Opportunity();
         objOpportunity.AccountId = objExAccount.Id;
         objOpportunity.Name = '영업활동ofLSY';
         objOpportunity.CloseDate = date.valueOf('2023-03-01');
         objOpportunity.StageName = 'Proposal';
         insert objOpportunity;
 
         Event objEvt1 = new Event();
         objEvt1.StartDateTime = Datetime.valueOf('2023-04-06 09:00:00');
         objEvt1.EndDateTime = Datetime.valueOf('2023-04-06 18:00:00');
         objEvt1.WhatId = objOpportunity.Id;
         objEvt1.DurationInMinutes = 540;
         objEvt1.VehicleRefuelingCosts__c = 2000;
         objEvt1.WorkType__c ='외근';
         objEvt1.isMig__c = false;
         insert objEvt1;
 
         ActivityReport__c actRept1 = new ActivityReport__c();
         actRept1.Id = objEvt1.ActivityReport__r.Id;
 
         delete objEvt1;
 
         Event objEvt2 = new Event();
         objEvt2.StartDateTime = Datetime.valueOf('2023-04-06 09:00:00');
         objEvt2.EndDateTime = Datetime.valueOf('2023-04-06 18:00:00');
         objEvt2.WhatId = objOpportunity.Id;
         objEvt2.DurationInMinutes = 540;
         objEvt2.VehicleRefuelingCosts__c = 2000;
         objEvt2.WorkType__c ='내근';
         objEvt2.isMig__c = false;
         insert objEvt2;
 
         ActivityReport__c actRept2 = new ActivityReport__c();
         actRept2.Id = objEvt2.ActivityReport__r.Id;
 
         objEvt2.StartDateTime = Datetime.valueOf('2023-04-07 09:00:00');
         objEvt2.EndDateTime = Datetime.valueOf('2023-04-07 18:00:00');
         update objEvt2;
         Test.stopTest();
     }
 
     @isTest 
     static void itShould4() {
         Test.startTest();
         Account objExAccount = TestObjectCreator.objExAccount;
         insert objExAccount;
         Opportunity objOpportunity = new Opportunity();
         objOpportunity.AccountId = objExAccount.Id;
         objOpportunity.Name = '영업활동';
         objOpportunity.CloseDate = date.valueOf('2022-01-01');
         objOpportunity.StageName = 'Proposal';
         insert objOpportunity;
 
         Event objEvent6 = new Event();
         objEvent6.StartDateTime = Datetime.valueOf('2022-01-01 09:00:00');
         objEvent6.EndDateTime = Datetime.valueOf('2022-01-01 18:00:00');
         objEvent6.WhatId = objOpportunity.Id;
         objEvent6.DurationInMinutes = 540;
         objEvent6.VehicleRefuelingCosts__c = 2000;
         objEvent6.WorkType__c ='외근';
         objEvent6.isMig__c = false;
         insert objEvent6;
 
         objEvent6.StartDateTime = Datetime.valueOf('2022-01-02 09:00:00');
         objEvent6.EndDateTime = Datetime.valueOf('2022-01-02 18:00:00');
         objEvent6.DurationInMinutes = 540;
         objEvent6.WhatId = objOpportunity.Id;
         objEvent6.WorkType__c ='내근';
         update objEvent6;
         Test.stopTest();
     }
 }