force-app/main/default/objects/ActivityReport__c/ActivityReport__c.object-meta.xml
<CustomObject>
    <label>활동 보고</label>
    <nameField>
        <label>Activity Report Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityReport__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/BusinessPlan__c.object-meta.xml
<CustomObject>
    <label>경영계획</label>
    <nameField>
        <label>BusinessPlan 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessPlan__c/fields/EmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>EmployeeNumber</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <description>User.UserName_사원번호_년도_월</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>월</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6월</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7월</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9월</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10월</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11월</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12월</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NEW</fullName>
                <label>신규</label>
            </value>
            <value>
                <fullName>EXT</fullName>
                <label>기존</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>377</fullName>
                <label>FS본부)기타</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>378</fullName>
                <label>FS개발)병원·레저개발팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>153</fullName>
                <label>아이누리)아이누리1팀</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>아이누리)아이누리동부팀</label>
            </value>
            <value>
                <fullName>314</fullName>
                <label>아이누리)아이누리2팀</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>363</fullName>
                <label>아이누리)아이누리서부팀</label>
            </value>
            <value>
                <fullName>365</fullName>
                <label>아이누리)아이누리3팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>348</fullName>
                <label>외식중부)외식2팀</label>
            </value>
            <value>
                <fullName>366</fullName>
                <label>외식중부)외식1팀</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Writing</fullName>
        <default>true</default>
        <label>Writing</label>
    </customValue>
    <customValue>
        <fullName>Request</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
        <isActive>false</isActive>
        <label>In Progress</label>
    </customValue>
    <description>승인 상태</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BusinessPlanExcelUpload.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-09-2023
 * @last modified by  : admin
**/
public without sharing class BusinessPlanExcelUpload {
    /**
     * 경영계획 엑셀업로드 Init
     *      
     * @return Map<String, object>
     *          - objUser : 사용자정보
     *          - listSelectHeadOffice : SU Picklist value 정보
     *          - mapSelectSU : 본부 SU 종속성 정보
     *          - mapSelectTeam : SU 팀 종속성 정보
    **/
    @AuraEnabled
    public static Map<String, object>  doInit() {

        User objUser = [
            SELECT  Id, Name, EmployeeNumber, HeadOffice__c, SU__c, Team__c
            FROM    User
            WHERE   Id =: UserInfo.getUserId()
        ];

        // objWrapper.listSelectStatus = CommonUtil.getPickListValues('ActivityReport__c', 'ApprovalStatus__c', false);
        // objWrapper.listSelectHeadOffice = CommonUtil.getPickListValues('User', 'HeadOffice__c', false);
        // objWrapper.mapSelectSU = CommonUtil.getDependentPicklistValues(User.SU__c); 
        // objWrapper.mapSelectTeam = CommonUtil.getDependentPicklistValues(User.Team__c); 

        Map<String, object> mapResult = new Map<String, object>{
            'objUser' => objUser,
            'listSelectHeadOffice' => CommonUtil.getPickListValues('User', 'HeadOffice__c', false),
            'mapSelectSU' => CommonUtil.getDependentPicklistValues(User.SU__c),
            'mapSelectTeam' => CommonUtil.getDependentPicklistValues(User.Team__c)            
        };
        return mapResult;
    }

    /**
     * 경영계획 엑셀파일 Validation
     *
     * @param recordId : Record Id
     * @param strItemDetail : 엑셀데이터
     * @param fileName : 
     * @param fileContents : 
     * @return DataWrapper
     *          - strStatus : 상태
     *          - strMessage : 메시지
     *          - listErrorWrapper : 오류리스트
     *          - listSuccessWrapper : 성공리스트
     *          - totalSize : 전체건수
     *          - successSize : 성공건수
     *          - errorSize : 오류건수
     *
    **/
    @AuraEnabled
    public static DataWrapper doCheckFile(String recordId, String strItemDetail, String fileName, String fileContents) {
        DataWrapper objDataWrapper = new DataWrapper();

        List<FileWrapper> listSuccessWrapper = new List<FileWrapper>();
        List<FileWrapper> listErrorWrapper = new List<FileWrapper>();

        Integer totalSize = 0;
        Integer successSize = 0;
        Integer errorSize = 0;

        try {

            System.debug('================> strItemDetail : '+strItemDetail);

            List<BusinessPlan__c> listItem = (List<BusinessPlan__c>) JSON.deserialize(strItemDetail, List<BusinessPlan__c>.class);

            totalSize = listItem.size();

            Set<String> setEmployeeNumber = new Set<String>();

            for(BusinessPlan__c obj : listItem) {
                if(obj.EmployeeNumber__c <> null) {
                    setEmployeeNumber.add(obj.EmployeeNumber__c);
                }
            }

            Map<String, User> mapUser = new Map<String, User>();

            for(User objUser : [
                SELECT  Id, Name, EmployeeNumber
                FROM    User
                WHERE   EmployeeNumber In:setEmployeeNumber
            ]) {
                mapUser.put(objUser.EmployeeNumber, objUser);
            }

            Integer intSEQ = 1;

            for(BusinessPlan__c objItem : listItem) {
                String strStatus = 'SUCCESS';
                String strMessage;

                FileWrapper objFileWrapper = new FileWrapper();

                System.debug('=========> objItem.EmployeeNumber__c : '+objItem.EmployeeNumber__c);

                objFileWrapper.intSEQ = ++intSEQ;

                if(objItem.EmployeeNumber__c <> null) {
                    objFileWrapper.inputEmployeeNumber = objItem.EmployeeNumber__c;

                    if(mapUser == null || (mapUser <> null && mapUser.get(objItem.EmployeeNumber__c) == null)) {
                        strStatus = 'ERROR';
                        strMessage = '잘못된 사원번호입니다.';
                        errorSize++;
                    }else {
                        successSize++;

                        System.debug('================> objItem : '+JSON.serialize(objItem));
                        objFileWrapper.objItem = objItem;
                    }
                }else {
                    strStatus = 'ERROR';
                    strMessage = '사원번호가 존재하지 않습니다.';
                    errorSize++;
                }

                objFileWrapper.strStatus = strStatus;
                objFileWrapper.strMessage = strMessage;

                System.debug('=============> objFileWrapper.strStatus : '+objFileWrapper.strStatus);
                System.debug('=============> objFileWrapper.strMessage : '+objFileWrapper.strMessage);

                if(objFileWrapper.strStatus == 'SUCCESS') {
                    listSuccessWrapper.add(objFileWrapper);                    
                }else {
                    listErrorWrapper.add(objFileWrapper);                    
                }
            }
        }catch(Exception e) {
            System.debug('======================> Error Line'+e.getLineNumber());
            System.debug('======================> Error Message'+e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }

        System.debug('=============> listSuccessWrapper : '+listSuccessWrapper);
        System.debug('=============> listErrorWrapper : '+listErrorWrapper);

        objDataWrapper.listErrorWrapper = listErrorWrapper;
        objDataWrapper.listSuccessWrapper = listSuccessWrapper;
        objDataWrapper.totalSize = totalSize;
        objDataWrapper.successSize = successSize;
        objDataWrapper.errorSize = errorSize;

        return objDataWrapper;
    }

    /**
     * 경영계획 엑셀업로드 Init
     *
     * @param recordId : Record Id
     * @param strAddItem : 엑셀데이터
     * @param mapCount : 
     * @return
     *
    **/
    @AuraEnabled
    public static void doAddItem(String recordId, String strAddItem, Map<String, Integer> mapCount) {
        try {

            List<FileWrapper> listItem = (List<FileWrapper>) JSON.deserialize(strAddItem, List<FileWrapper>.class);

            List<BusinessPlan__c> listAddItem = new List<BusinessPlan__c>();

            for(FileWrapper obj : listItem) {
                BusinessPlan__c objTarget = obj.objItem;

                objTarget.Year__c = objTarget.Year__c.setScale(0);                
                objTarget.ExtId__c = objTarget.EmployeeNumber__c+'_'+objTarget.Year__c+'_'+objTarget.Month__c;

                if(objTarget.Type__c == '신규') {
                    objTarget.Type__c = 'New';
                }else if(objTarget.Type__c == '기존') {
                    objTarget.Type__c = 'EXT';
                }else {
                    objTarget.Type__c = 'New';
                }
                listAddItem.add(objTarget);
            }

            if(listAddItem <> null && listAddItem.size() > 0) {
                upsert listAddItem ExtId__c;
            }
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * 경영계획 엑셀업로드 샘플 다운로드
     *
     * @param selectedHeadOffice : SU정보
     * @param selectedSU : 사업부정보
     * @return List<DownloadWrapper> : 경영계획 Row 정보
     *
    **/
    @AuraEnabled
    public static List<DownloadWrapper> doGetExportTarget(String selectedHeadOffice, String selectedSU ) {
        try {

            
            Map<String, String> mapHeadOfficeToLabel = CommonUtil.getMapPickListValuetoLabel('User', 'HeadOffice__c');
            Map<String, String> mapSUToLabel = CommonUtil.getMapPickListValuetoLabel('User', 'SU__c');
            Map<String, String> mapTeamToLabel = CommonUtil.getMapPickListValuetoLabel('User', 'Team__c');

            String strQuery = '';
            strQuery += '    SELECT  Id, Name, EmployeeNumber, HeadOffice__c, SU__c, Team__c';
            strQuery += '    FROM    User';
            strQuery += '    WHERE   isActive = true ';
            if(selectedHeadOffice <> null && selectedHeadOffice <> 'none') {
                strQuery += '    AND     HeadOffice__c = \''+selectedHeadOffice+'\'';
            }

            if(selectedSU <> null && selectedSU <> 'none') {
                strQuery += '    AND     SU__c = \''+ selectedSU+'\'';
            }
            strQuery += '    ORDER BY   HeadOffice__c, SU__c, Team__c, EmployeeNumber ';

            System.debug('strQuery :: ' + strQuery);
            System.debug('selectedSU :: ' + selectedSU);

            List<DownloadWrapper> listDownloadWrapper = new List<DownloadWrapper>();

            Set<String> setMonth = new Set<String>{'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'};

            for(User objUser : Database.query(strQuery)) {
                for ( String strMonth : setMonth){
                    DownloadWrapper objDownload = new DownloadWrapper();
                    objDownload.HeadOfficeName = mapHeadOfficeToLabel.get(objUser.HeadOffice__c);
                    objDownload.HeadOfficeCode = objUser.HeadOffice__c;
                    objDownload.SUName = mapSUToLabel.get(objUser.SU__c);
                    objDownload.SUCode = objUser.SU__c;
                    objDownload.TeamName = mapTeamToLabel.get(objUser.Team__c);
                    objDownload.TeamCode = objUser.Team__c;
                    objDownload.UserNumber = objUser.EmployeeNumber;
                    objDownload.UserName = objUser.Name;
                    objDownload.Year = String.valueOf(Date.today().year());
                    objDownload.Month = strMonth;
                    objDownload.Dummy1 = '신규';
                    objDownload.Dummy2 = '';
                    objDownload.Dummy3 = '';
                    objDownload.Dummy4 = '';
                    objDownload.Dummy5 = '';
                    objDownload.Dummy6 = '';
                    listDownloadWrapper.add(objDownload);
                }
            }
            return listDownloadWrapper;

        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class DataWrapper {
        @AuraEnabled
        public Integer totalSize;
        @AuraEnabled
        public Integer successSize;
        @AuraEnabled
        public Integer errorSize;        
        @AuraEnabled
        public List<FileWrapper> listSuccessWrapper;
        @AuraEnabled
        public List<FileWrapper> listErrorWrapper;
    }

    public class FileWrapper {
        @AuraEnabled
        public Integer intSEQ;
        @AuraEnabled
        public String strStatus;
        @AuraEnabled
        public String strMessage;
        @AuraEnabled
        public String inputEmployeeNumber;
        @AuraEnabled
        public BusinessPlan__c objItem;
    }

    public class DownloadWrapper {
        @AuraEnabled
        public String HeadOfficeName;
        @AuraEnabled
        public String HeadOfficeCode;
        @AuraEnabled
        public String SUName;
        @AuraEnabled
        public String SUCode;
        @AuraEnabled
        public String TeamName;
        @AuraEnabled
        public String TeamCode;
        @AuraEnabled
        public String UserNumber;
        @AuraEnabled
        public String UserName;
        @AuraEnabled
        public String Year;
        @AuraEnabled
        public String Month;
        @AuraEnabled
        public String Dummy1;
        @AuraEnabled
        public String Dummy2;
        @AuraEnabled
        public String Dummy3;
        @AuraEnabled
        public String Dummy4;
        @AuraEnabled
        public String Dummy5;
        @AuraEnabled
        public String Dummy6;
    }
}