force-app/main/default/objects/ActivityReport__c/ActivityReport__c.object-meta.xml
<CustomObject>
    <label>활동 보고</label>
    <nameField>
        <label>Activity Report Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityReport__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActivityReport__c/fields/EventStartDate__c.field-meta.xml
<CustomField>
    <fullName>EventStartDate__c</fullName>
    <label>EventStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ActivityReport__c/fields/IsSendECCAT__c.field-meta.xml
<CustomField>
    <fullName>IsSendECCAT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSendECCAT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ActivityReport__c/fields/OilTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>OilTotalAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OilTotalAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ActivityReport__c/fields/OilTotalDistance__c.field-meta.xml
<CustomField>
    <fullName>OilTotalDistance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>OilTotalDistance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ActivityReport__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ActivityReport</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/CJTitle__c.field-meta.xml
<CustomField>
    <fullName>CJTitle__c</fullName>
    <defaultValue>&quot;MA&quot;</defaultValue>
    <label>직책</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GM</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>사업부장</label>
            </value>
            <value>
                <fullName>TM</fullName>
                <label>팀장</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>지원</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <default>true</default>
                <label>MA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>377</fullName>
                <label>FS본부)기타</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>378</fullName>
                <label>FS개발)병원·레저개발팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>153</fullName>
                <label>아이누리)아이누리1팀</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>아이누리)아이누리동부팀</label>
            </value>
            <value>
                <fullName>314</fullName>
                <label>아이누리)아이누리2팀</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>363</fullName>
                <label>아이누리)아이누리서부팀</label>
            </value>
            <value>
                <fullName>365</fullName>
                <label>아이누리)아이누리3팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>348</fullName>
                <label>외식중부)외식2팀</label>
            </value>
            <value>
                <fullName>366</fullName>
                <label>외식중부)외식1팀</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
            <value>
                <fullName>385</fullName>
                <label>유통중부)리테일파트</label>
            </value>
            <value>
                <fullName>381</fullName>
                <label>유통중부)식자재마트파트</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Writing</fullName>
        <default>true</default>
        <label>Writing</label>
    </customValue>
    <customValue>
        <fullName>Request</fullName>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
        <isActive>false</isActive>
        <label>In Progress</label>
    </customValue>
    <description>승인 상태</description>
    <masterLabel>Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OilApporvalRequest.cls
/*
* ==================================================================================
*   File Name   : OilApporvalRequest.cls
*   Author      : Minje.Kim
*   Date        : 2022.11.06
*   Tester      : OilApporvalRequest_Test.cls
*   Description : 주유비 정산 승인 관리 Controller
*   Modification Log
* ==================================================================================
*   Ver     Date          Author          Modification
* ==================================================================================
*   1.0     2022.11.06    Minje.Kim    Create
* ==================================================================================
*/
public with sharing class OilApporvalRequest {
    
    /**
     * 주유비 정산 승인 탭 Init (검색 조건 셋팅)
     * 
     * @params 없음
     * @return DataWrapper 
     *         - objUser : 유저 정보
     *         - listSelectStatus : 제출 상태
     *         - listSelectHeadOffice : 사업부 리스트
     *         - mapSelectSU : SU 리스트
     *         - mapSelectTeam : 팀 리스트
     *         - listYear : 년도 리스트
     *         - listMonth : 월 리스트
     *         - targetYear : 초기 년도 설정값
     *         - targetMonth : 초기 월 설정값
     *
    **/
    @AuraEnabled
    public static DataWrapper doInit() {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        DataWrapper objWrapper = new DataWrapper();

        try {

            User objUser = [
                SELECT  Id, EmployeeNumber, HeadOffice__c, SU__c, Team__c, CJTitle__c
                FROM    User
                WHERE   Id =: UserInfo.getUserId()
            ];
            objWrapper.objUser = objUser;

            objWrapper.listSelectStatus = CommonUtil.getPickListValues('ActivityReport__c', 'ApprovalStatus__c', false);
            objWrapper.listSelectHeadOffice = CommonUtil.getPickListValues('User', 'HeadOffice__c', false);
            objWrapper.mapSelectSU = CommonUtil.getDependentPicklistValues(User.SU__c); 
            objWrapper.mapSelectTeam = CommonUtil.getDependentPicklistValues(User.Team__c); 

            // Dafault 선택 년도 및 월 계산
            Date targetDate = Date.today();   

            String targetYear = String.valueOf(targetDate.year());
            String targetMonth = String.valueOf(targetDate.month());

            // Dafault 선택 년도 및 선택목록에 표시될 년도 셋팅
            List<Map<String,String>> listYear = new List<Map<String,String>>();
            Integer seqYear = Date.today().year() - 4;
            System.debug( 'targetYear :: ' + targetYear);
            System.debug( 'seqYear :: ' + seqYear);
            while ( seqYear <=  Date.today().year()) {
                listYear.add(new Map<String, String>{
                    'label' => String.valueOf(seqYear) + '년',
                    'value' => String.valueOf(seqYear),
                    'selected' => targetDate.year() == seqYear ? 'true' : 'false'
                });
                seqYear++;
            }
            objWrapper.listYear = listYear;
            objWrapper.targetYear = String.valueOf(targetDate.year());

            // Dafault 선택 월 및 선택목록에 표시될 월 셋팅
            List<Map<String,String>> listMonth = new List<Map<String,String>>();
            Integer seqMonth = 1; 
            while ( seqMonth < 13 ) {
                listMonth.add(new Map<String, String>{
                    'label' => String.valueOf(seqMonth) + '월',
                    'value' => String.valueOf(seqMonth),
                    'selected' => targetDate.month() == seqMonth ? 'true' : 'false'
                });
                seqMonth++;
            }
            objWrapper.listMonth = listMonth;
            objWrapper.targetMonth = String.valueOf(targetDate.month()).leftPad(2,'0') ;
            

        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    /**
     * 주유비 정산 승인 탭 데이터 조회
     * 
     * @params Map<String, String> mapParam
     *         - userType : 유저 정보
     *         - selectedYear : 선택된 년도 정보
     *         - selectedMonth : 선택된 월 정보
     *         - strSearchMA : MA명 검색창에 입력된 단어
     *         - selectedStatus : 선택된 제출상태 코드
     *         - selectedHeadOffice : 선택된 사업부 코드
     *         - selectedSU : 선택된 SU 코드
     *         - selectedTeam : 선택된 팀 코드
     * @return DataWrapper objWrapper
     *         - listSearchWrapper : 조회된 활동보고 데이터 리스트
     *         - strStatus : 조회 성공/실패 여부
     *         - strMessage : 조회 실패시 에러메세지
     *
    **/
    @AuraEnabled
    public static DataWrapper getDataTable(Map<String, String> mapParam) {
        String strStatus = 'SUCCESS';
        String strMessage = ''; 
        String userType = String.valueOf(mapParam.get('userType'));

        Integer targetYear = Integer.valueOf(mapParam.get('selectedYear'));
        Integer targetMonth = Integer.valueOf(mapParam.get('selectedMonth'));

        Integer targetDaysInMonth = date.daysInMonth(targetYear, targetMonth);
        
        String targetDateStart = String.valueOf(Date.newInstance(targetYear, targetMonth, 1));
        String targetDateEnd = String.valueOf(Date.newInstance(targetYear, targetMonth, targetDaysInMonth));

        String strSearchMA = '';
        if ( mapParam.get('strSearchMA') != null){
            strSearchMA = mapParam.get('strSearchMA');
        }
        
       
        DataWrapper objWrapper = new DataWrapper();

        List<SearchWrapper> listSearchWrapper = new List<SearchWrapper>();

        try {
            String strQuery = 'SELECT Id, OwnerId,';

            strQuery += '    User__r.Name, User__r.EmployeeNumber, User__r.HeadOffice__c, User__r.SU__c, User__r.Team__c, User__r.CJTitle__c,';
            strQuery += '    EventStartDate__c, OilTotalAmount__c, OilTotalDistance__c,';
            strQuery += '    ApprovalStatus__c, IsSendECCAT__c,';            
            strQuery += '    toLabel(User__r.HeadOffice__c) HeadOfficeName,';
            strQuery += '    toLabel(User__r.SU__c) SUName,';
            strQuery += '    toLabel(User__r.Team__c) TeamName,';
            strQuery += '    toLabel(ApprovalStatus__c) ApprovalStatusName';

            strQuery += '    FROM    ActivityReport__c';
            
            strQuery += '    WHERE   ApprovalStatus__c = \''+mapParam.get('selectedStatus')+'\'';
            strQuery += '    AND     EventStartDate__c >= '+ targetDateStart;
            strQuery += '    AND     EventStartDate__c <= '+ targetDateEnd;
            strQuery += '    AND     OilTotalDistance__c != 0';
            strQuery += '    AND     OilTotalDistance__c != null';
            
            if(mapParam.get('selectedHeadOffice') <> null && mapParam.get('selectedHeadOffice') <> 'none') {
                strQuery += '    AND     User__r.HeadOffice__c = \''+mapParam.get('selectedHeadOffice')+'\'';
            }

            if(mapParam.get('selectedSU') <> null && mapParam.get('selectedSU') <> 'none') {
                strQuery += '    AND     User__r.SU__c = \''+mapParam.get('selectedSU')+'\'';
            }

            if(mapParam.get('selectedTeam') <> null && mapParam.get('selectedTeam') <> 'none') {
                // 유통리테일 381, 385 통합관리
                if ( mapParam.get('selectedTeam') == '381' || mapParam.get('selectedTeam') == '385'){
                    strQuery += '    AND     User__r.Team__c IN (\'381\',\'385\') ';
                } else {
                    strQuery += '    AND     User__r.Team__c = \''+mapParam.get('selectedTeam')+'\'';
                }
            }

            if (userType == 'TM'){
                strQuery += '    AND     User__r.CJTitle__c = \'MA\'';
            }
            else if(userType == 'BM'){
                strQuery += '    AND     User__r.CJTitle__c = \'TM\'';
            }

            if ( strSearchMA != ''){
                strQuery += '    AND     (User__r.Name like \'%' + strSearchMA + '%\'  OR  User__r.EmployeeNumber like \'%' + strSearchMA + '%\')';
            }

            System.debug('strQuery :: ' + strQuery);
            System.debug('selectedSU :: ' + String.valueOf(mapParam.get('selectedSU')));
            System.debug('targetDateStart :: ' + targetDateStart);
            System.debug('targetDateEnd :: ' + targetDateEnd);

            Set<String> setUserId = new Set<String>();

            for(ActivityReport__c objAR : Database.query(strQuery)) {
                SearchWrapper objSearch = new SearchWrapper(objAR);
                listSearchWrapper.add(objSearch);
            }
        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.listSearchWrapper = listSearchWrapper;
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        System.debug( 'objWrapper :: '  +  objWrapper); 
        
        return objWrapper;
    }

    
    /**
     * 주유비 정산 승인 탭 데이터 저장 (승인, 반려)
     * 
     * @params String strListTarget : 체크된 활동보고 데이터 리스트
     * @params String ApprovalStatus : 저장 유형 (승인, 반려)
     * @return DataWrapper 
     *         - 저장 성공/실패 여부 (strStatus) 
     *         - 저장 실패시 에러메세지 (strMessage)
     *
    **/
    @AuraEnabled
    public static DataWrapper doSave(String strListTarget, String ApprovalStatus) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        DataWrapper objWrapper = new DataWrapper();

        try {
            List<SearchWrapper> listTarget = (List<SearchWrapper>)JSON.deserialize(strListTarget, List<SearchWrapper>.class);
            List<ActivityReport__c> listUpdate = new List<ActivityReport__c>();

            for(SearchWrapper obj : listTarget) {
                ActivityReport__c objTarget = new ActivityReport__c();

                objTarget.Id = obj.objActivityReport.Id;                
                objTarget.ApprovalStatus__c = ApprovalStatus;

                listUpdate.add(objTarget);
            }

            if(listUpdate <> null && listUpdate.size() > 0) {
                update listUpdate;
            }

        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    public class DataWrapper {
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}
        @AuraEnabled
        public List<SearchWrapper> listSearchWrapper {get;set;}
        @AuraEnabled
        public User objUser {get;set;}
        @AuraEnabled
        public String strHeadOffice {get;set;}
        @AuraEnabled
        public String strSU {get;set;}
        @AuraEnabled
        public String strTeam {get;set;}
        @AuraEnabled
        public String targetYear {get;set;}
        @AuraEnabled
        public String targetMonth {get;set;}
        @AuraEnabled
        public List<Map<String,String>> listYear {get;set;}
        @AuraEnabled
        public List<Map<String,String>> listMonth {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listSelectStatus {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listSelectHeadOffice {get;set;}
        @AuraEnabled
        public Map<String, List<Map<String, String>>> mapSelectSU {get;set;}        
        @AuraEnabled
        public Map<String, List<Map<String, String>>> mapSelectTeam {get;set;}

    }

    public class SearchWrapper{
        @AuraEnabled
        public String recordLink {get;set;}
        @AuraEnabled
        public String viewDetail {get;set;}
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String eventDate {get;set;}
        @AuraEnabled
        public String strHeadOffice {get;set;}
        @AuraEnabled
        public String strSU {get;set;}
        @AuraEnabled
        public String strTeam {get;set;}
        @AuraEnabled
        public String strUserInfo {get;set;}
        @AuraEnabled
        public String totalAmount {get;set;}
        @AuraEnabled
        public String totalDistance {get;set;}

        @AuraEnabled
        public ActivityReport__c objActivityReport {get;set;}

        public SearchWrapper() {
        }

        public SearchWrapper(ActivityReport__c objActivityReport) {

            this.objActivityReport = objActivityReport;

            // 2022-11-06 toLabel 필드때문에 Update가 안되어 Id, ApprovalStatus__c 만 세팅
            ActivityReport__c objNewAR = new ActivityReport__c();
            objNewAR.Id = objActivityReport.Id;
            objNewAR.ApprovalStatus__c = objActivityReport.ApprovalStatus__c;
            this.objActivityReport = objNewAR;

            this.strStatus = String.valueOf(objActivityReport.get('ApprovalStatusName'));
            this.eventDate = String.valueOf(objActivityReport.EventStartDate__c);

            if(objActivityReport.User__r <> null) {
                User objTargetUser = (User)objActivityReport.User__r;

                if(objTargetUser.get('HeadOfficeName') <> null) {
                    this.strHeadOffice = String.valueOf(objTargetUser.get('HeadOfficeName'));
                }
    
                if(objTargetUser.get('SUName') <> null) {
                    this.strSU = String.valueOf(objTargetUser.get('SUName'));
                }
    
                if(objTargetUser.get('TeamName') <> null) {
                    this.strTeam = String.valueOf(objTargetUser.get('TeamName'));
                }
            }

            String strUserName = objActivityReport.User__r.Name;
            String strUserEmployeeNumber = objActivityReport.User__r.EmployeeNumber;
            

            if(strUserEmployeeNumber <> null && strUserEmployeeNumber.length() > 0) {
                this.strUserInfo = strUserName+'('+strUserEmployeeNumber+')';
            }else {
                this.strUserInfo = strUserName;
            }

            this.totalAmount = String.valueOf(objActivityReport.OilTotalAmount__c);
            this.recordLink = '/'+String.valueOf(objActivityReport.Id);
            this.viewDetail = '상세보기';
            this.totalDistance = String.valueOf(objActivityReport.OilTotalDistance__c);
        }
    }
}