force-app/main/default/objects/CJFW_SurveyQuestion__c/CJFW_SurveyQuestion__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 질문</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ{YY}{MM}{DD}{000000}</displayFormat>
        <label>AutoNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/DateType__c.field-meta.xml
<CustomField>
    <fullName>DateType__c</fullName>
    <description>날짜유형 (From/ To) 설정</description>
    <label>Date Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From/To</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/MultipleChoice__c.field-meta.xml
<CustomField>
    <fullName>MultipleChoice__c</fullName>
    <description>객관식 유형</description>
    <label>Multiple Choice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>singular</fullName>
                <label>단수</label>
            </value>
            <value>
                <fullName>plural</fullName>
                <label>복수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>질문명</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>번호(순서)</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>질문유형</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>openended</fullName>
                <label>주관식</label>
            </value>
            <value>
                <fullName>multiple</fullName>
                <label>객관식</label>
            </value>
            <value>
                <fullName>date</fullName>
                <label>날짜</label>
            </value>
            <value>
                <fullName>time</fullName>
                <label>시간</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CJFW_SurveyQustion_tr.cls
/**
 * @description       : 
 * @author            : sunkyung.choi@dkbmc.com
 * @group             : 
 * @last modified on  : 10-30-2023
 * @last modified by  : sunkyung.choi@dkbmc.com
**/
public with sharing class CJFW_SurveyQustion_tr extends TriggerHandler {
    public CJFW_SurveyQustion_tr() {
        system.debug('SurveyQustion Trigger Handler START');
        listNew = (List<CJFW_SurveyQuestion__c>) Trigger.new;
        listOld = (List<CJFW_SurveyQuestion__c>) Trigger.old;
        mapNew = (Map<Id, CJFW_SurveyQuestion__c>) Trigger.newMap;
        mapOld = (Map<Id, CJFW_SurveyQuestion__c>) Trigger.oldMap;
        // recordIdEx =  ApexPages.CurrentPage().getparameters().get('id');
    }
    private List<CJFW_SurveyQuestion__c> listNew { get;set;}
    private List<CJFW_SurveyQuestion__c> listOld{ get;set;}
    // private Id recordIdEx { get; set; }
    private Map<Id, CJFW_SurveyQuestion__c> mapNew { get;set;}
    private Map<Id, CJFW_SurveyQuestion__c> mapOld { get;set;}

    
    public override void beforeInsert() {
       insertCheck();
    }
    public override void beforeUpdate() {
        doUpdateCheck(); // 수정 불가처리 
    }
    public override void beforeDelete() {
        // doDeleteCheck(); // 삭제 불가 처리
    }
    public override void afterInsert() {
        // doInsertCheck(); // 추가 불가 처리 
    }

    private void insertCheck() {
        System.debug('insertCheck start');
        List<CJFW_SurveyQuestion__c> newSurQues = listNew;
        System.debug('newSurQues?????????'+newSurQues);
        
        Set<Id> surveyQueId = new Set<Id>();
        Map<Id, CJFW_SurveyQuestion__c> surveyQueMap = new Map<Id, CJFW_SurveyQuestion__c>();
        for (CJFW_SurveyQuestion__c newSurQue : newSurQues) {
            // surveyQueId.add(newSurQue.Id); 
            // System.debug('surveyQueId >>>>> '+ surveyQueId);
            if (newSurQue.ActiveCheck__c) {
                newSurQue.addError('설문지가 활성화 되어 질문을 추가할 수 없습니다.');
            }

        }

    }
    private void doUpdateCheck() {
        System.debug('doUpdateCheck start');
        List<CJFW_SurveyQuestion__c> oldSurQues = listOld;
        System.debug('oldSurQues?????????'+oldSurQues);
        Set<Id> surveyQueId = new Set<Id>();
        // Map<Id, CJFW_SurveyQuestion__c> surveyQueMap = new Map<Id, CJFW_SurveyQuestion__c>();
        
        for (CJFW_SurveyQuestion__c oldSurQue : oldSurQues) {
            surveyQueId.add(oldSurQue.Id);
            System.debug('surveyQueId?????????'+surveyQueId);
        }

        List<CJFW_SurveyQuestion__c> activeCheckList = [ SELECT Id,  
        Name,  
        Name__c, 
        Survey__c, 
        Type__c, 
        MultipleChoice__c, 
        Order__c, 
        DateType__c, 
        TextType__c, 
        ActiveCheck__c  FROM CJFW_SurveyQuestion__c WHERE Id IN: surveyQueId];
        System.debug('activeCheckList?????????'+activeCheckList);

        for (CJFW_SurveyQuestion__c activeCheck : activeCheckList) {
            System.debug('????? start');
            if (activeCheck.ActiveCheck__c) {
                System.debug('!!!!! end');
                activeCheck.addError('설문지가 활성화 되어 질문을 수정할 수 없습니다.');
            }
        }

        // }
    }


}