force-app/main/default/objects/MDMRegRequestCustomer__c/MDMRegRequestCustomer__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 및 수정 요청</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_CUSTTYPE__c.field-meta.xml
<CustomField>
    <fullName>PV_CUSTTYPE__c</fullName>
    <label>PV_CUSTTYPE</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C01</fullName>
                <label>본점</label>
            </value>
            <value>
                <fullName>C02</fullName>
                <label>판매처</label>
            </value>
            <value>
                <fullName>C03</fullName>
                <label>관리처-배송</label>
            </value>
            <value>
                <fullName>C04</fullName>
                <label>관리처-분할</label>
            </value>
            <value>
                <fullName>C05</fullName>
                <label>점포</label>
            </value>
            <value>
                <fullName>C06</fullName>
                <label>사이트</label>
            </value>
            <value>
                <fullName>C07</fullName>
                <label>단체급식고객</label>
            </value>
            <value>
                <fullName>C08</fullName>
                <label>회계고객</label>
            </value>
            <value>
                <fullName>C09</fullName>
                <label>물류센터</label>
            </value>
            <value>
                <fullName>C10</fullName>
                <label>해외고객</label>
            </value>
            <value>
                <fullName>C11</fullName>
                <label>관리처-2차</label>
            </value>
            <value>
                <fullName>C12</fullName>
                <label>금융고객</label>
            </value>
            <value>
                <fullName>C13</fullName>
                <label>자가소비부서</label>
            </value>
            <value>
                <fullName>C14</fullName>
                <label>경영계획부서</label>
            </value>
            <value>
                <fullName>C15</fullName>
                <label>온라인유형</label>
            </value>
            <value>
                <fullName>C16</fullName>
                <label>해외고객-분할</label>
            </value>
            <value>
                <fullName>C17</fullName>
                <label>해외고객-배송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_NAME1__c.field-meta.xml
<CustomField>
    <fullName>PV_NAME1__c</fullName>
    <label>PV_NAME1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_PERNR__c.field-meta.xml
<CustomField>
    <fullName>PV_PERNR__c</fullName>
    <label>PV_PERNR</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CJFW_MDMBulkCustomerSearchController.cls
/**
 * @description       : 
 * @author            : hyeeun.song@dkbmc.com
 * @group             : 
 * @last modified on  : 10-27-2023
 * @last modified by  : hyeeun.song@dkbmc.com
**/
public with sharing class CJFW_MDMBulkCustomerSearchController {
    
    @AuraEnabled(cacheable=true)
    public static DataWrapper getCustomerInfo(String searchWord, String recordId, Integer pageNumber, Integer pageSize) {

        system.debug('### CJFW_MDMBulkAccountSearchController ###');
        system.debug('>>> getAccountInfo()');
        system.debug('>>> searchWord ' + searchWord);
        system.debug('>>> recordId ' + recordId);

        String strStatus = 'SUCCESS';
        String strMessage = '';

        DataWrapper objWrapper = new DataWrapper();
        
        try {

            List<MDMRegRequestCustomer__c> searchResult = new List<MDMRegRequestCustomer__c>(); // 분할해서 담은
            List<MDMRegRequestCustomer__c> listSearchResult = new List<MDMRegRequestCustomer__c>(); // 모두 담은

            String strQuery = 'SELECT Id, PV_NAME1__c, PV_CUSTTYPE__c, PV_PERNR__c FROM MDMRegRequestCustomer__c ';
            strQuery += ' WHERE   	MDMRegRequestBulkCustomer__c = \'' + recordId + '\'';
            if(searchWord <> null) {
                strQuery += ' AND     (PV_NAME1__c LIKE \'%' + searchWord + '%\')';
            }

            System.debug('============> strQuery : ' + strQuery);
            
            listSearchResult = Database.query(strQuery);

            Integer listSearchResultSize = listSearchResult.size();

            Integer startIndex = (pageNumber - 1) * pageSize;
            Integer endIndex = Math.min(startIndex + pageSize, listSearchResultSize);

            if(endIndex > startIndex){
                for (Integer i = startIndex; i < endIndex; i++) {
                    searchResult.add(listSearchResult[i]);
                }
            }

            objWrapper.searchResult = searchResult;

            System.debug('결과 => ' + searchResult);

            objWrapper.listSearchResult = listSearchResult;
            objWrapper.totalCnt = listSearchResultSize;
            
        } catch(Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    public class DataWrapper {

		@AuraEnabled
        public String strStatus {get;set;}

        @AuraEnabled
        public String strMessage {get;set;}

        @AuraEnabled
        public List<MDMRegRequestCustomer__c> searchResult {get;set;}

        @AuraEnabled
        public List<MDMRegRequestCustomer__c> listSearchResult {get;set;}

        @AuraEnabled
        public Integer totalCnt {get;set;}

        @AuraEnabled
        public String code {get;set;}

        @AuraEnabled
        public String inputId {get;set;}

        @AuraEnabled
        public String inputTextLabel {get;set;}

	}

}