force-app/main/default/objects/MDMRegRequestCustomer__c/MDMRegRequestCustomer__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 및 수정 요청</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/workflow__c/workflow__c.object-meta.xml
<CustomObject>
    <label>워크플로우</label>
    <nameField>
        <label>워크플로우 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/workflow__c/fields/LargeCode__c.field-meta.xml
<CustomField>
    <fullName>LargeCode__c</fullName>
    <label>대분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>본점</fullName>
            </value>
            <value>
                <fullName>판매처</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/workflow__c/fields/level__c.field-meta.xml
<CustomField>
    <fullName>level__c</fullName>
    <label>레벨</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/workflow__c/fields/MidCategory__c.field-meta.xml
<CustomField>
    <fullName>MidCategory__c</fullName>
    <label>중분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>고객(본점) 생성 프로세스</fullName>
            </value>
            <value>
                <fullName>고객(판매처) 생성 프로세스</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MDMRegRequestMain_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-29-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class MDMRegRequestMain_test {
    @TestSetup
    static void makeData() {
    }
    @IsTest
    static void itShould() {
        Test.startTest();

        Account objAccount = TestObjectCreator.objHealthAccount;
        objAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ExistingCustomer').getRecordTypeId();
        insert objAccount;

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objAccount.Id;
        objOpportunity.Name = '영업활동';
        objOpportunity.CloseDate = date.valueOf('2022-01-01');
        objOpportunity.StageName = 'Proposal';
        insert objOpportunity;

        MDMRegRequestMain.doInit(objOpportunity.Id);

        MDMRegRequestCustomer__c objCustomer = new MDMRegRequestCustomer__c();
        insert objCustomer;

        MDMRegRequestMain.doInit(objCustomer.Id);

        List<workflow__c> listWorkFlow = new List<workflow__c>();

        for(Integer i=1 ; i<3 ;i++) {
            workflow__c objWorkflow = new workflow__c();
            objWorkflow.Name = 'Test';
            objWorkflow.Level__c = String.valueOf(i);        
            objWorkflow.MidCategory__c = '고객(본점) 생성 프로세스';
            objWorkflow.LargeCode__c = '본점';
            listWorkFlow.add(objWorkflow);
        }

        insert listWorkFlow;

        MDMRegRequestMain.getCategoryLevel1();
        MDMRegRequestMain.getCategoryLevel2('본점');
        MDMRegRequestMain.getCategoryLevel3('test', listWorkFlow);



        Test.stopTest();
    }
}