force-app/main/default/objects/CJFW_SurveyOption__c/CJFW_SurveyOption__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 객관식 문항</description>
    <label>Survey Option</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>순서</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <description>설문지 문항</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Option</relationshipLabel>
    <relationshipName>Survey_Option</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/CJFW_SurveyQuestion__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 질문</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ{YY}{MM}{DD}{000000}</displayFormat>
        <label>AutoNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>번호(순서)</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResponse__c/CJFW_SurveyResponse__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 응답</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyResponse__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>고객</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Response</relationshipLabel>
    <relationshipName>Survey_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResponse__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>잠재고객</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Survey Response</relationshipLabel>
    <relationshipName>Survey_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResponse__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>영업기회</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Consulting</relationshipLabel>
    <relationshipName>Survey_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResponse__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Response</relationshipLabel>
    <relationshipName>Survey_Response</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/CJFW_SurveyResult__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 결과지</description>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/DateResult__c.field-meta.xml
<CustomField>
    <fullName>DateResult__c</fullName>
    <description>설문지 질문 Date 유형 (From/To) 값</description>
    <label>Date Result</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/FM_Question__c.field-meta.xml
<CustomField>
    <fullName>FM_Question__c</fullName>
    <description>질문명</description>
    <formula>SurveyQuestion__r.Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Question</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/OpenEnded__c.field-meta.xml
<CustomField>
    <fullName>OpenEnded__c</fullName>
    <description>주관식 답변</description>
    <label>Open Ended</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/SurveyOption__c.field-meta.xml
<CustomField>
    <fullName>SurveyOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>질문 선택지</description>
    <label>Survey Option</label>
    <referenceTo>CJFW_SurveyOption__c</referenceTo>
    <relationshipLabel>Survey Result</relationshipLabel>
    <relationshipName>Survey_Result</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지 질문</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Result</relationshipLabel>
    <relationshipName>Survey_Result</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/SurveyResponse__c.field-meta.xml
<CustomField>
    <fullName>SurveyResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>설문지 응답</description>
    <label>Survey Response</label>
    <referenceTo>CJFW_SurveyResponse__c</referenceTo>
    <relationshipLabel>Survey Result</relationshipLabel>
    <relationshipName>Survey_Result</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/TimeResult__c.field-meta.xml
<CustomField>
    <fullName>TimeResult__c</fullName>
    <description>선택한 시간 값</description>
    <label>Time Result</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/CJFW_SurveyPreviewController.cls
/**
 * @description       : 
 * @author            : sunkyung.choi@dkbmc.com
 * @group             : 
 * @last modified on  : 09-25-2023
 * @last modified by  : sunkyung.choi@dkbmc.com
**/
public with sharing class CJFW_SurveyPreviewController {
    public CJFW_SurveyPreviewController() {

    }

    // 설문 결과를 나타내는 클래스 정의
    public class SurveyQuestionResponse {
        @AuraEnabled
        public String question { get; set; }
        @AuraEnabled
        public String answer { get; set; }

        public SurveyQuestionResponse(String question, String answer) {
            this.question = question;
            this.answer = answer;
        }
    }

    @AuraEnabled
    public static List<SurveyQuestionResponse> getSurveyReulte(String recordId) {
        Set<String> responseId = new Set<String>();

        List<CJFW_SurveyResponse__c> responseList = [
            SELECT Id, OwnerId, Name, Survey__c, Lead__c, Account__c, Opportunity__c
            FROM CJFW_SurveyResponse__c
            WHERE Id = :recordId
        ];

        for (CJFW_SurveyResponse__c res : responseList) {
            responseId.add(res.Id);
        }

        List<CJFW_SurveyResult__c> resultList = [
            SELECT Id, OwnerId, Owner.Name, SurveyResponse__c, SurveyQuestion__c, SurveyOption__c,
                OpenEnded__c, DateResult__c, TimeResult__c, FM_Question__c, SurveyOption__r.Name,
                SurveyQuestion__r.Order__c
            FROM CJFW_SurveyResult__c
            WHERE SurveyResponse__c = :responseId
            ORDER BY SurveyQuestion__r.Order__c ASC
        ];

        List<SurveyQuestionResponse> totalList = new List<SurveyQuestionResponse>();
        Map<String, List<String>> questionToOptionsMap = new Map<String, List<String>>();
        Map<String, List<String>> questionToAnswerMap = new Map<String, List<String>>();

        for (CJFW_SurveyResult__c ru : resultList) {
            String question = ru.FM_Question__c;
            List<String> answers = new List<String>(); // 여러 개의 답변을 저장할 리스트를 생성
        
            if (ru.OpenEnded__c != null) {
                answers.add(ru.OpenEnded__c); // OpenEnded__c의 값을 리스트에 추가
            }
            else if (ru.SurveyOption__r.Name != null) {
                // 이미 처리한 질문인지 확인하고, 처리하지 않은 질문만 처리
                if (questionToAnswerMap.containsKey(question)) {
                    answers = questionToAnswerMap.get(question); // 이미 있는 리스트를 가져오기
                }
                answers.add(ru.SurveyOption__r.Name); // SurveyOption__r.Name의 값을 리스트에 추가
            }
            
            else if (ru.DateResult__c != null) {
                answers.add(String.valueOf(ru.DateResult__c)); // DateResult__c의 값을 리스트에 추가
            }
            else {
                answers.add(DateTime.newInstance(2000, 1, 1, ru.TimeResult__c.hour(), ru.TimeResult__c.minute(), ru.TimeResult__c.second()).format('a hh:mm'));
            }
        
            // 질문과 답변 리스트를 맵에 저장
            questionToAnswerMap.put(question, answers);
        }

        // 각 질문과 답변을 SurveyQuestionResponse 객체로 변환하여 totalList에 추가
        for (String question : questionToAnswerMap.keySet()) {
            List<String> answers = questionToAnswerMap.get(question);
            String answerString = String.join(answers, ', '); // 여러 개의 답변을 쉼표로 구분한 문자열로 변환
            SurveyQuestionResponse response = new SurveyQuestionResponse(question, answerString);
            totalList.add(response);
        }

        System.debug('22222' + totalList);
        return totalList;
    }
}