force-app/main/default/objects/MDMCustomerOrderType__c/MDMCustomerOrderType__c.object-meta.xml
<CustomObject>
    <label>MDMCustomerOrderType</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>MDMCustomerOrderType 이름</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMCustomerOrderType__c/fields/CLOSEGB__c.field-meta.xml
<CustomField>
    <fullName>CLOSEGB__c</fullName>
    <label>CLOSEGB</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMCustomerOrderType__c/fields/CUHR1__c.field-meta.xml
<CustomField>
    <fullName>CUHR1__c</fullName>
    <label>CUHR1</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMCustomerOrderType__c/fields/LOGISCENTER__c.field-meta.xml
<CustomField>
    <fullName>LOGISCENTER__c</fullName>
    <label>LOGISCENTER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestContact__c/MDMRegRequestContact__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 요청 담당자 정보</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomerContact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMRegRequestContact__c/fields/MDMRegRequestCustomer__c.field-meta.xml
<CustomField>
    <fullName>MDMRegRequestCustomer__c</fullName>
    <label>MDMRegRequestCustomer</label>
    <referenceTo>MDMRegRequestCustomer__c</referenceTo>
    <relationshipLabel>MDMRegRequestContact</relationshipLabel>
    <relationshipName>MDMRegRequestContact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/MDMRegRequestCustomer__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 및 수정 요청</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_ODCLOSEGB__c.field-meta.xml
<CustomField>
    <fullName>PV_ODCLOSEGB__c</fullName>
    <label>PV_ODCLOSEGB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>유통KX</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>급식</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>제주 FS</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>제주급식</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>아라마크</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>FS</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>키즈</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>제주키즈</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>급식직거래(군납)</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>외식일반/실수요</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>광역 외식일반/실수요</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>제주외식</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>푸드빌컨세션</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>푸드빌컨세션2</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>FO물류대행</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>광역 외식TC</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>푸드빌 구매통합</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>외부창고/FO</label>
            </value>
            <value>
                <fullName>ZZ</fullName>
                <label>SCM수급용</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CjfwMDMSalesCreateModalController.cls
/**
 * @description       : 
 * @author            : yeonji.lim@dkbmc.com
 * @group             : 
 * @last modified on  : 09-22-2023
 * @last modified by  : yeonji.lim@dkbmc.com
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   09-21-2023   yeonji.lim@dkbmc.com      Initial Version
**/
public with sharing class CjfwMDMSalesCreateModalController {
    
    public class DataWrapper {
        @AuraEnabled
        public String strStatus {get;set;}      // 성공, 실패
        @AuraEnabled
        public String strMessage {get;set;}     // 에러메세지
        @AuraEnabled
        public String strObjectType {get;set;}
        @AuraEnabled
        public String MDMRecordTypeId {get;set;}

        @AuraEnabled
        public List<Map<String, String>> listCustomerOrderType {get;set;}   //고객 주문마감 유형코드 pickList value

        @AuraEnabled
        public User objUser {get;set;}
        @AuraEnabled
        public Opportunity objOpportunity {get;set;}
        @AuraEnabled
        public MDMRegRequestCustomer__c objMDMRegReqCustomer {get;set;}     // MDM 고객 등록 및 수정 요청Obj
        @AuraEnabled
        public List<MDMRegRequestContact__c> listMDMReqContact {get;set;}   // MDM 고객 등록 요청 담당자 정보Obj
    }

    /* 
    * 고객 주문마감 유형코드 → PV_ODCLOSEGB__c Picklist Value 가져오기
    */
    @AuraEnabled
    public static List<Map<String,String>> getPvOdclosegbPicklist(){
        try {
            
            List<Map<String,String>> picklistValue = CommonUtil.getPickListValues('MDMRegRequestCustomer__c', 'PV_ODCLOSEGB__c', false);
            System.debug('picklistValue' + picklistValue);
            
            return picklistValue;

        } catch (Exception e) {
            System.debug('message => ' + e.getMessage());
            System.debug('trace => ' + e.getStackTraceString());
            
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * 출고센터, 고객분류 변경시 고객 주문마감 유형코드 SelectList 변경
     * 
     * @params strType : LOGIC(출고센터), CUHR(고객분류)
     * @return DataWrapper
     *
    **/
    @AuraEnabled
    public static DataWrapper doCheckOrderType(String strType, String PV_LOGISCENTER, String PV_CUHR1) {
        try {
            DataWrapper objWrapper = new DataWrapper();
            String strStatus = 'SUCCESS';
            String strMessage = '';
            String PV_ODCLOSEGB = '';

            System.debug('==============> strType : '+strType);
            System.debug('==============> PV_LOGISCENTER : '+PV_LOGISCENTER);

            // 고객분류 코드 앞에 숫자4자리만 가져오기
            System.debug('==============> before PV_CUHR1 : '+PV_CUHR1);
            if(PV_CUHR1 <> null && PV_CUHR1.contains('-')) {
                PV_CUHR1 = PV_CUHR1.split('-')[0];
            }
            System.debug('==============> after PV_CUHR1 : '+PV_CUHR1);


            // MDMCustomerOrderType__c obj에서 선택된 Fw출고센터&고객분류에 맞는 고객주문마감 유형코드 리스트 가져오기
            Set<String> setCloseGB = new Set<String>();

            String strQuery = 'SELECT Id, CUHR1__c, LOGISCENTER__c, CLOSEGB__c';
            strQuery += ' FROM  MDMCustomerOrderType__c';
            
            if(strType == 'LOGIC') {
                strQuery += ' WHERE LOGISCENTER__c LIKE \'%'+PV_LOGISCENTER+'%\'';
            }else {                
                strQuery += ' WHERE CUHR1__c =\''+PV_CUHR1+'\'';
            }
            
            strQuery += '   ORDER BY CLOSEGB__c ASC';


            System.debug('Database.query(strQuery)' + Database.query(strQuery));

            // 고객주문마감 유형코드 리스트에서 중복된 코드들 제외
            for(MDMCustomerOrderType__c obj : Database.query(strQuery)) {
                System.debug('=========> obj.CUHR1__c : '+obj.CUHR1__c);
                System.debug('=========> obj.PV_CUHR1 : '+PV_CUHR1);

                if(strType == 'LOGIC') {
                    if(obj.CUHR1__c == 'All') {
                        setCloseGB.add(obj.CLOSEGB__c);
                    }else if(obj.CUHR1__c == PV_CUHR1) {
                        setCloseGB.add(obj.CLOSEGB__c);
                    }
                }else {
                    if(obj.CUHR1__c == 'All') {
                        setCloseGB.add(obj.CLOSEGB__c);
                    }else if(obj.LOGISCENTER__c.contains(PV_LOGISCENTER)) {
                        setCloseGB.add(obj.CLOSEGB__c);
                    }
                }
            }
            
            System.debug('===========> setCloseGB : '+setCloseGB);

            // 고객주문마감 유형코드 pickList 가져오기
            List<Map<String, String>> listOrderType = CommonUtil.getPickListValues('MDMRegRequestCustomer__c', 'PV_ODCLOSEGB__c', false);
            
            List<Map<String, String>> listCustomerOrderType = new List<Map<String, String>>();
            // listCustomerOrderType.add(new Map<String, String>{
            //     'label' => '--없음--',
            //     'value' => 'none'
            // });

            // setCloseGB에 값이 있다면 pickList중 코드가 일치한 pickList value 값 가져오기
            if(!setCloseGB.isEmpty()) {
                for(Map<String, String> mapTarget : listOrderType) {
                    if(setCloseGB.contains(mapTarget.get('value'))) {
                        listCustomerOrderType.add(mapTarget);
                    }
                }
            }else {
                listCustomerOrderType = listOrderType;
            }

            objWrapper.listCustomerOrderType = listCustomerOrderType;
            System.debug('listOrderType =>' + listCustomerOrderType);

            objWrapper.strStatus = strStatus;

            return objWrapper;

        } catch (Exception e) {
            System.debug('message => ' + e.getMessage());
            System.debug('trace => ' + e.getStackTraceString());
            
            throw new AuraHandledException(e.getMessage());
        }
    }

}