force-app/main/default/objects/CJFW_ModuleSetting__c/CJFW_ModuleSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>공통 모듈 Setting
1.전체 Trigger Handler On/Off 설정 (사용자, 프로필, Org)</description>
    <label>[CJFW] Module Setting</label>
</CustomObject>

force-app/main/default/objects/CJFW_ModuleSetting__c/fields/IsNotiTest__c.field-meta.xml
<CustomField>
    <fullName>IsNotiTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>알림 모듈 테스트용 활성화 여부(true: 히스토리 데이터 적재, false: 실제알림 발송 및 히스토리 적재)</description>
    <label>IsNotiTest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 관리</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NM{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/IsNotiTest__c.field-meta.xml
<CustomField>
    <fullName>IsNotiTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>알림 테스트용으로 수행 여부 (false: 발송 후 이력생성, true: 이력생성)</description>
    <label>IsNotiTest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>알림 관리 레코드의 고유명</description>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/fields/sObject__c.field-meta.xml
<CustomField>
    <fullName>sObject__c</fullName>
    <description>데이터 가져올 sObject API 명</description>
    <label>sObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/TargetFields__c.field-meta.xml
<CustomField>
    <fullName>TargetFields__c</fullName>
    <description>데이터 가져올 sObject 의 필드 값</description>
    <inlineHelpText>여러개 일 경우, 로 구분</inlineHelpText>
    <label>TargetFields</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/recordTypes/App.recordType-meta.xml
<RecordType>
    <fullName>App</fullName>
    <active>true</active>
    <description>SFDC 종 알림</description>
    <label>App</label>
</RecordType>

force-app/main/default/objects/Notification__c/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <description>SFDC 이메일 알림</description>
    <label>Email</label>
</RecordType>

force-app/main/default/objects/NotificationTarget__c/NotificationTarget__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - 알림 추가 수신자 Group, Role, User</description>
    <label>Notification Target</label>
    <nameField>
        <displayFormat>TG{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTarget__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Target</relationshipLabel>
    <relationshipName>Notification_Target</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NotificationTarget__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <description>협업그룹</description>
    <label>Group</label>
</RecordType>

force-app/main/default/objects/NotificationTarget__c/recordTypes/Role.recordType-meta.xml
<RecordType>
    <fullName>Role</fullName>
    <active>true</active>
    <description>역할</description>
    <label>Role</label>
</RecordType>

force-app/main/default/objects/NotificationTarget__c/recordTypes/User.recordType-meta.xml
<RecordType>
    <fullName>User</fullName>
    <active>true</active>
    <description>사용자</description>
    <label>User</label>
</RecordType>

force-app/main/default/objects/NotificationTemplate__c/NotificationTemplate__c.object-meta.xml
<CustomObject>
    <description>[P2] 공통 - App 알림, Email 알림.. 등 Template 관리</description>
    <label>Notification Template</label>
    <nameField>
        <displayFormat>NT{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NotificationTemplate__c/fields/EmailDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>EmailDeveloperName__c</fullName>
    <description>Classic Email Template Developer Name</description>
    <label>Email Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>App 본문</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <description>알림 관리</description>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Template</relationshipLabel>
    <relationshipName>Notification_Template</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>App 제목</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NotificationTemplate__c/recordTypes/App.recordType-meta.xml
<RecordType>
    <fullName>App</fullName>
    <active>true</active>
    <description>SFDC 종 템플릿</description>
    <label>App</label>
</RecordType>

force-app/main/default/classes/NotificationManager_TEST.cls
@isTest
public with sharing class NotificationManager_TEST {
    
    @testSetup
    static void makeData() {
        insert new IFMaster__c(Name = 'NotiAlert');

        List<CustomNotificationType> customNotiTypeList = [
            select
                Id, DeveloperName
            from CustomNotificationType 
        ];

        List<Notification__c> notiList = new List<Notification__c>();

        COMM_Util.SchemaInfo schemaInfo = new COMM_Util.SchemaInfo('Notification__c');
        Map<String, Schema.RecordTypeInfo> recordTypeMap = schemaInfo.getRecordTypeMapByDeveloperNames(); 
        Id appRecordTypeId = recordTypeMap.get('App').getRecordTypeId();
        Id eamilRecordTypeId = recordTypeMap.get('Email').getRecordTypeId();

        List<Account> testAccountList = new List<Account>();
        Account testAccount = new Account(Name='App Noti Test');
        testAccountList.add(testAccount);
        insert testAccountList;
        
        Notification__c appNoti = new Notification__c();
        appNoti.RecordTypeId = appRecordTypeId;
        appNoti.Key__c = 'Sample_Noti_App';
        appNoti.IsSendToSender__c = true;
        appNoti.IsActive__c = true;
        appNoti.sObject__c  = 'Account';
        appNoti.TargetFields__c = 'Id,Name,Owner.Name';
        appNoti.CustomNotificationTypeId__c = customNotiTypeList[0].DeveloperName;
        notiList.add(appNoti);

        Notification__c emailNoti = new Notification__c();
        emailNoti.RecordTypeId = eamilRecordTypeId;
        emailNoti.Key__c = 'Sample_Noti_Email';
        emailNoti.IsSendToSender__c = true;
        emailNoti.IsActive__c = true;
        emailNoti.sObject__c  = 'Account';
        emailNoti.TargetFields__c = 'Id,Name,Owner.Name';
        notiList.add(emailNoti);

        insert notiList;

        //NotiTarget 추가
        schemaInfo.setSchema('NotificationTarget__c');
        Map<String, Schema.RecordTypeInfo> recordTypeNotiTargetMap = schemaInfo.getRecordTypeMapByDeveloperNames(); 
        Id userRecordTypeId = recordTypeNotiTargetMap.get('User').getRecordTypeId();
        Id groupRecordTypeId = recordTypeNotiTargetMap.get('Group').getRecordTypeId();
        Id roleRecordTypeId = recordTypeNotiTargetMap.get('Role').getRecordTypeId();

        List<NotificationTarget__c> notiTargetList = new List<NotificationTarget__c>();
        NotificationTarget__c userTypeTarget = new NotificationTarget__c();
        userTypeTarget.User__c = UserInfo.getUserId();
        userTypeTarget.RecordTypeId = userRecordTypeId;
        userTypeTarget.Notification__c = emailNoti.Id;
        notiTargetList.add(userTypeTarget);

        insert notiTargetList;

        //Template 부터 추가 
        schemaInfo.setSchema('NotificationTemplate__c');
        Map<String, Schema.RecordTypeInfo> recordTypeTemplateMap = schemaInfo.getRecordTypeMapByDeveloperNames(); 
        Id appTemplateRecordTypeId = recordTypeTemplateMap.get('App').getRecordTypeId();
        Id eamilTemplateRecordTypeId = recordTypeTemplateMap.get('Email').getRecordTypeId();

        List<NotificationTemplate__c> templateList = new List<NotificationTemplate__c>();

        NotificationTemplate__c appTemplate = new NotificationTemplate__c();
        appTemplate.RecordTypeId = appTemplateRecordTypeId;
        appTemplate.Title__c = 'Test Title';
        appTemplate.Message__c = 'Name : {1} , Id {0}';
        appTemplate.Notification__c = appNoti.Id;
        templateList.add(appTemplate);

        NotificationTemplate__c emailTemplate = new NotificationTemplate__c();
        emailTemplate.RecordTypeId = eamilTemplateRecordTypeId;
        emailTemplate.EmailDeveloperName__c = 'ExtraServiceRejectedEmailTemplate';
        emailTemplate.Notification__c = emailNoti.Id;
        templateList.add(emailTemplate);


        insert templateList;
        
    }

    @isTest
    static void appAlertExecute_test() {

        String userId = UserInfo.getUserId();

        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 RecordId 기준
        */
        List<Account> targetAccountList = [select Id, Name, Owner.Name from Account];
        String targetId = targetAccountList[0].Id;
        NotiTarget recipientId = new NotiTarget('id');
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetIdSet(new Set<String>{targetId})
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_App');


        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 sObject List 기준
         */ 
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetSObjectList(targetAccountList)
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_App');
                           

        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 Object 기준
        */
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetObject(targetAccountList)
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_App');
        
    }

    @isTest
    static void emailAlertExecute_test() {

        String userId = UserInfo.getUserId();

        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 RecordId 기준
        */
        List<Account> targetAccountList = [select Id, Name, Owner.Name from Account];
        String targetId = targetAccountList[0].Id;
        NotiTarget recipientId = new NotiTarget('id');
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetIdSet(new Set<String>{targetId})
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_Email');


        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 sObject List 기준
         */ 
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetSObjectList(targetAccountList)
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_Email');
                           

        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 Object 기준
        */
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetObject(targetAccountList)
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_Email');

        
        /*
            1. 수신자 Email 기준 
            2. 알림 개인화시 RecordId 기준
        */
        NotiTarget recipientEmail = new NotiTarget('email');
        recipientEmail.setToAddresses(new Set<String>{'test@test.com'});
        NotificationManager.getInstance()
                            .setTargetIdSet(new Set<String>{targetId})
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientEmail}
                            })
                            .execute('Sample_Noti_Email');

                            
         /*
            1. 수신자 Email 기준 
            2. 알림 개인화시 sObject List 기준
         */ 
        
        recipientEmail.setToAddresses(new Set<String>{'test@test.com'});
        NotificationManager.getInstance()
                            .setTargetSObjectList(targetAccountList)
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientEmail}
                            })
                            .execute('Sample_Noti_Email');
                           

        /*
            1. 수신자 Email 기준 
            2. 알림 개인화시 Object 기준
        */
        recipientEmail.setToAddresses(new Set<String>{'test@test.com'});
        NotificationManager.getInstance()
                            .setTargetObject(targetAccountList)
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientEmail}
                            })
                            .execute('Sample_Noti_Email');
        
    }

    @isTest
    static void sendTest() {
        CJFW_ModuleSetting__c module = CJFW_ModuleSetting__c.getInstance();
        module.IsNotiTest__c = true;
        insert module;

        List<Notification__c> notiList = [ select Id from Notification__c ];
        for(Notification__c noti : notiList) {
            noti.IsNotiTest__c = true;
        }
        update notiList;

        String userId = UserInfo.getUserId();
        /*
            1. 수신자 Id 기준 
            2. 알림 개인화시 RecordId 기준
        */
        List<Account> targetAccountList = [select Id, Name, Owner.Name from Account];
        String targetId = targetAccountList[0].Id;
        NotiTarget recipientId = new NotiTarget('id');
        recipientId.setToAddresses(new Set<String>{userId});
        NotificationManager.getInstance()
                            .setTargetIdSet(new Set<String>{targetId})
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientId}
                            })
                            .execute('Sample_Noti_App');


        /*
            1. 수신자 Email 기준 
            2. 알림 개인화시 RecordId 기준
        */
        NotiTarget recipientEmail = new NotiTarget('email');
        recipientEmail.setToAddresses(new Set<String>{'test@test.com'});
        NotificationManager.getInstance()
                            .setTargetIdSet(new Set<String>{targetId})
                            .setRecipientListMap(new Map<String,List<NotiTarget>>{
                                targetId => new List<NotiTarget>{recipientEmail}
                            })
                            .execute('Sample_Noti_Email');
    }
}