force-app/main/default/objects/CJFW_CollateralEnrollment__c/CJFW_CollateralEnrollment__c.object-meta.xml
<CustomObject>
    <description>[P2] 매출채권 - 담보 입보</description>
    <label>담보 입보</label>
    <nameField>
        <displayFormat>CE{YY}{MM}{DD}{000000}</displayFormat>
        <label>Auto No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/ActualCollateralAmount__c.field-meta.xml
<CustomField>
    <fullName>ActualCollateralAmount__c</fullName>
    <description>실 담보금액</description>
    <label>실 담보금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/AppraisalDate__c.field-meta.xml
<CustomField>
    <fullName>AppraisalDate__c</fullName>
    <description>담보감정일</description>
    <label>담보감정일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/ApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>ApprovalDate__c</fullName>
    <label>승인일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CashCollateralReceipt__c.field-meta.xml
<CustomField>
    <fullName>CashCollateralReceipt__c</fullName>
    <description>현금담보 전표번호</description>
    <label>현금담보 전표번호</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>종류</description>
    <label>종류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>예적금통장</fullName>
            </value>
            <value>
                <fullName>양도성예금증서</fullName>
            </value>
            <value>
                <fullName>기업어음</fullName>
            </value>
            <value>
                <fullName>나대지(잡종지)</fullName>
            </value>
            <value>
                <fullName>임야,전답,과수원</fullName>
            </value>
            <value>
                <fullName>아파트,단독주택</fullName>
            </value>
            <value>
                <fullName>연립주택</fullName>
            </value>
            <value>
                <fullName>다세대주택</fullName>
            </value>
            <value>
                <fullName>오피스텔</fullName>
            </value>
            <value>
                <fullName>공장</fullName>
            </value>
            <value>
                <fullName>상가점포</fullName>
            </value>
            <value>
                <fullName>업무용빌딩</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
            <value>
                <fullName>보증보험</fullName>
            </value>
            <value>
                <fullName>신용보증기금</fullName>
            </value>
            <value>
                <fullName>은행지급보증</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CertificateNo__c.field-meta.xml
<CustomField>
    <fullName>CertificateNo__c</fullName>
    <description>증서번호</description>
    <label>증서번호</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CloseStatus__c.field-meta.xml
<CustomField>
    <fullName>CloseStatus__c</fullName>
    <label>해지여부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CollateralAddress__c.field-meta.xml
<CustomField>
    <fullName>CollateralAddress__c</fullName>
    <description>담보물 주소</description>
    <label>담보물 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CollateralAddressDetail__c.field-meta.xml
<CustomField>
    <fullName>CollateralAddressDetail__c</fullName>
    <description>담보물 상세주소</description>
    <label>담보물 상세주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CollateralNo__c.field-meta.xml
<CustomField>
    <fullName>CollateralNo__c</fullName>
    <description>담보번호 &gt; Auto Number 로 변경할 수도 있음</description>
    <label>담보번호</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CollateralType__c.field-meta.xml
<CustomField>
    <fullName>CollateralType__c</fullName>
    <description>담보구분</description>
    <label>담보구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>계약이행</fullName>
            </value>
            <value>
                <fullName>외상물품대금</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CollateralValue__c.field-meta.xml
<CustomField>
    <fullName>CollateralValue__c</fullName>
    <description>담보감정가액</description>
    <label>담보감정가액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/CommencementDate__c.field-meta.xml
<CustomField>
    <fullName>CommencementDate__c</fullName>
    <description>개시일</description>
    <label>개시일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>고객</description>
    <label>고객</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Existing Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>담보 입보</relationshipLabel>
    <relationshipName>Collateral_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/Debtor__c.field-meta.xml
<CustomField>
    <fullName>Debtor__c</fullName>
    <description>채무자</description>
    <label>채무자</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/DebtorRelationship__c.field-meta.xml
<CustomField>
    <fullName>DebtorRelationship__c</fullName>
    <description>채무자와의 관계</description>
    <label>채무자와의 관계</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <description>입금금액</description>
    <label>입금금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/DepositDate__c.field-meta.xml
<CustomField>
    <fullName>DepositDate__c</fullName>
    <description>입금일</description>
    <label>입금일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>지급 (만기)일</description>
    <label>지급 (만기)일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/ExpirationStatus__c.field-meta.xml
<CustomField>
    <fullName>ExpirationStatus__c</fullName>
    <label>만기여부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/FM_CollateralValue__c.field-meta.xml
<CustomField>
    <fullName>FM_CollateralValue__c</fullName>
    <description>담보설정 및 감정 탭의 담보감정가액</description>
    <formula>CollateralValue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>감정가액</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/FM_Customer__c.field-meta.xml
<CustomField>
    <fullName>FM_Customer__c</fullName>
    <description>(고객코드)고객명</description>
    <formula>&apos;(&apos;+ Customer__r.CustomerID__c  +&apos;)&apos; + Customer__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>고객</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/GuaranteeAmount__c.field-meta.xml
<CustomField>
    <fullName>GuaranteeAmount__c</fullName>
    <description>보증(발행)금액</description>
    <label>보증(발행)금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <description>발행 (보증)일</description>
    <label>발행 (보증)일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/Issuer__c.field-meta.xml
<CustomField>
    <fullName>Issuer__c</fullName>
    <description>발행처</description>
    <label>발행처</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/MortgageAmount__c.field-meta.xml
<CustomField>
    <fullName>MortgageAmount__c</fullName>
    <description>근저당 설정 금액</description>
    <label>근저당 설정 금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/MortgageDate__c.field-meta.xml
<CustomField>
    <fullName>MortgageDate__c</fullName>
    <description>근저당 설정일</description>
    <label>근저당 설정일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/ProcessStatus__c.field-meta.xml
<CustomField>
    <fullName>ProcessStatus__c</fullName>
    <label>처리구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>승인</fullName>
            </value>
            <value>
                <fullName>미상신</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <description>제공자</description>
    <label>제공자</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/PurchaseAmount__c.field-meta.xml
<CustomField>
    <fullName>PurchaseAmount__c</fullName>
    <description>구입금액</description>
    <label>구입금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_CollateralEnrollment__c/fields/TotalCollateralAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalCollateralAmount__c</fullName>
    <description>총 담보금액</description>
    <label>총 담보금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_DepartmentAllocation__c/CJFW_DepartmentAllocation__c.object-meta.xml
<CustomObject>
    <description>[P2] 부서별 배부</description>
    <label>부서별 배부</label>
    <nameField>
        <displayFormat>DA{YY}{MM}{DD}{000000}</displayFormat>
        <label>Auto No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_DepartmentAllocation__c/fields/ActualCollateralAmount__c.field-meta.xml
<CustomField>
    <fullName>ActualCollateralAmount__c</fullName>
    <description>실 담보금액</description>
    <label>실 담보금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_DepartmentAllocation__c/fields/CollateralEnrollment__c.field-meta.xml
<CustomField>
    <fullName>CollateralEnrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>담보 입보</label>
    <referenceTo>CJFW_CollateralEnrollment__c</referenceTo>
    <relationshipLabel>부서별 배부</relationshipLabel>
    <relationshipName>Collateral_Enrollment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_DepartmentAllocation__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>고객명</description>
    <label>고객</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>부서별 배부</relationshipLabel>
    <relationshipName>Department_Allocation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_DepartmentAllocation__c/fields/ExpirationStatus__c.field-meta.xml
<CustomField>
    <fullName>ExpirationStatus__c</fullName>
    <description>담보 만기여부 체크</description>
    <label>만기여부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassService__c/ClassService__c.object-meta.xml
<CustomObject>
    <description>교육시스템신청레코드저장 오브젝트
해당레코드의 적합성판단후 부가서비스내역으로 삽입</description>
    <label>교육서비스신청</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassService__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>교육서비스신청</relationshipLabel>
    <relationshipName>Customer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CJFW_AccountDamBoSearchController.cls
/**
 * @description       : CjfwAccountDamBoSearch comp에서 호출되는 controller
 * @author            : doyeon.kim@dkbmc.com
 * @since 2023-08-07  내용 작성
 * @group             : 
 * @last modified on  : 08-11-2023
 * @last modified by  : doyeon.kim@dkbmc.com
**/
public with sharing class CJFW_AccountDamBoSearchController {
    //담보 조회 메서드
    @AuraEnabled(cacheable=true)
    public static List<CJFW_CollateralEnrollment__c> getAccDamBoInfo(String searchKey , String Dambovalue , String searchCertiCode){

        System.debug('Check searchKey : ' +searchKey);//Customer__c
        System.debug('Check Dambovalue : ' +Dambovalue);//CollateralType__c
        System.debug('Check searchCertiCode : ' +searchCertiCode);//CertificateNo__c

        List<CJFW_CollateralEnrollment__c> resultList = new List<CJFW_CollateralEnrollment__c>();
        List<CJFW_CollateralEnrollment__c> certiResultList = new List<CJFW_CollateralEnrollment__c>();
        
        //담보쿼리문
        String strQuery = 'SELECT Id, Name, Customer__c, FM_Customer__c, CollateralType__c, CollateralNo__c, ';//거래처코드, 담보구분, 담보번호
                                        //담보종류
                strQuery +=         ' RecordTypeId, RecordType.Name, Category__c,';
                                        //증서번호, 발행처, 채무자, 제공자, 보증(발행)금액, 발행일, 개시일, 지급(만기)일
                strQuery +=         ' CertificateNo__c, Issuer__c, Debtor__c, Provider__c, GuaranteeAmount__c, IssueDate__c, CommencementDate__c, DueDate__c,';
                                        //주소, 세부주소, 채무자와의 관계, 담보감정가액, 담보감정일, 근저당 설정 금액, 근저당 설정일
                strQuery +=         ' CollateralAddress__c, CollateralAddressDetail__c, DebtorRelationship__c, CollateralValue__c, AppraisalDate__c, MortgageAmount__c, MortgageDate__c,';
                                        //구입금액, 입금금액, 현금담보전표번호, 감정가액, 입금일
                strQuery +=         ' PurchaseAmount__c, Deposit__c, CashCollateralReceipt__c, FM_CollateralValue__c, DepositDate__c,';
                                        //총담보, 실담보, 처리구분, 승인일, 만기여부, 해지여부, 비고
                strQuery +=         ' TotalCollateralAmount__c, ActualCollateralAmount__c, ProcessStatus__c, ApprovalDate__c, ExpirationStatus__c, CloseStatus__c, Description__c';
                strQuery += ' FROM       CJFW_CollateralEnrollment__c';

        
        if(searchKey == null){
            System.debug('searchKey Null');
        }else if( searchKey == null && Dambovalue == null){
            System.debug('All Null');
        }else{
            System.debug('All Data');
            
            if (searchKey != null) {//거래처 + 담보구분 쿼리문
                System.debug('strQuery CHECK >>>>>' + strQuery);
                strQuery +=         '   WHERE       Customer__r.CustomerId__c = :searchKey';
                strQuery +=         '   AND       CollateralType__c = :Dambovalue';
                System.debug('strQuery CHECK >>>>>' + strQuery);

                resultList = Database.query(strQuery);
                System.debug('collResultList CHECK >>>>>' + resultList);

            }else if(searchCertiCode != null){//증서번호 쿼리문
                // strQuery +=         '   WHERE       CollateralNo__c = :searchCertiCode';
                strQuery +=         '   WHERE       CertificateNo__c = :searchCertiCode';
                System.debug('strQuery CHECK >>>>>' + strQuery);

                resultList = Database.query(strQuery);
                System.debug('certiResultList CHECK >>>>>' + resultList);

            }

        }
        
        if (!resultList.isEmpty()) {
            system.debug('return => ' + resultList.size() );
        }
        
        return resultList;
    }

    //증서 조회 메서드
    @AuraEnabled(cacheable=true)
    public static List<CJFW_CollateralEnrollment__c> getAccCertiInfo(String searchCertiCode){

        System.debug('Check searchCertiCode : ' +searchCertiCode);//CertificateNo__c

        List<CJFW_CollateralEnrollment__c> certiResultList = new List<CJFW_CollateralEnrollment__c>();
        
        //보증보험 쿼리문
        String strQuery = 'SELECT Id, Name, Customer__c, FM_Customer__c, CollateralType__c, CollateralNo__c, ';//거래처코드, 담보구분, 담보번호
                                        //담보종류, 종류
                strQuery +=         ' RecordTypeId, RecordType.Name, Category__c,';
                                        //증서번호, 발행처, 채무자, 보증(발행)금액, 발행일, 개시일, 지급(만기)일
                strQuery +=         ' CertificateNo__c, Issuer__c, Debtor__c, GuaranteeAmount__c, IssueDate__c, CommencementDate__c, DueDate__c,';
                                        //총담보, 실담보, 처리구분, 승인일, 만기여부, 해지여부, 비고
                strQuery +=         ' TotalCollateralAmount__c, ActualCollateralAmount__c, ProcessStatus__c, ApprovalDate__c, ExpirationStatus__c, CloseStatus__c, Description__c';
                strQuery += ' FROM       CJFW_CollateralEnrollment__c';

        
        if(searchCertiCode == null){
            System.debug('searchCertiCode Null Check (((' + searchCertiCode);
        }else if(searchCertiCode != null){//증서번호 쿼리문
            System.debug('strQuery CHECK >>>>>' + strQuery);

            strQuery +=         '   WHERE       CertificateNo__c = :searchCertiCode';
            System.debug('strQuery += WHERE CertificateNo__c = :  ' + searchCertiCode);

            certiResultList = Database.query(strQuery);
            System.debug('certiResultList CHECK >>>>>' + certiResultList);

        }
        
        if (!certiResultList.isEmpty()) {
            system.debug('return => ' + certiResultList.size() );
        }
        
        return certiResultList;
    }

    //부서별 배부 데이터 조회 메서드
    @AuraEnabled(cacheable=true)
    public static List<CJFW_DepartmentAllocation__c> getDepartInfo(String searchKey){
        
        System.debug('Check searchKey : ' +searchKey);//Customer__c
        List<CJFW_DepartmentAllocation__c> departList = new List<CJFW_DepartmentAllocation__c>();

        try {
            
            if (searchKey != null) {

                //부서별 배부 쿼리문
                String departQuery ='SELECT Id, Name, Customer__c, Customer__r.Name, DeptCode__c, DeptName__c, CollateralEnrollment__c, CollateralEnrollment__r.Name, FM_CustomerId__c,';
                        departQuery += ' FM_TotalCollateralAmount__c, ActualCollateralAmount__c, CloseStatus__c, ExpirationStatus__c, Description__c';
                        departQuery += ' FROM CJFW_DepartmentAllocation__c';
                        departQuery += ' WHERE FM_CustomerId__c =: searchKey';
        
                departList = Database.query(departQuery);
                System.debug('check departList : '+ departList);
                    
                if (!departList.isEmpty()) {
                    System.debug('departList >>>> ' + departList.size());
                }
            }
            
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        
        return departList;

    }
}