force-app/main/default/objects/IF_RELAY_INFO__c/IF_RELAY_INFO__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IF_RELAY_INFO</label>
</CustomObject>

force-app/main/default/objects/IF_RELAY_INFO__c/fields/Interface_auth_key__c.field-meta.xml
<CustomField>
    <fullName>Interface_auth_key__c</fullName>
    <label>Interface_auth_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_RELAY_INFO__c/fields/Interface_id__c.field-meta.xml
<CustomField>
    <fullName>Interface_id__c</fullName>
    <label>Interface_id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/WebserviceType__c.field-meta.xml
<CustomField>
    <fullName>WebserviceType__c</fullName>
    <label>WebserviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/oil_type_cd__c.field-meta.xml
<CustomField>
    <fullName>oil_type_cd__c</fullName>
    <label>oil type cd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>휘발유</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>경유</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>LPG</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>전기차</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>수소차</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalcNoPriceFuelActivity_test.cls
/**
 * Created by kw on 2023-02-02.
 */

@IsTest
private class CalcNoPriceFuelActivity_test {
    @TestSetup
    static void CalcNoPriceFuelActivity_testSetUp() {
        try{
            Set<String> setIFId = new Set<String>{'IF_SFDC_EACCT_INQ_OIL_AMOUNT'};

            List<IFMaster__c> listIF = new List<IFMaster__c>();

            for(String str : setIFId) {
                IFMaster__c obj = new IFMaster__c();
                obj.Name = str;
                obj.ContentType__c = 'application/json';
                obj.Endpoint__c = 'https://test.salesforce.com';
                obj.Method__c = 'POST';
                obj.Type__c = 'Inbound';
                obj.WebServiceType__c = 'REST';

                listIF.add(obj);
            }

            insert listIF;

            IF_RELAY_INFO__c objRelayInfo = new IF_RELAY_INFO__c();
            objRelayInfo.Interface_id__c = 'test';
            objRelayInfo.Interface_auth_key__c = 'test';

            insert objRelayInfo;

            User objUser = new User();
            objUser.Id = UserInfo.getUserId();
            objUser.EmployeeNumber = 'test1234';
            objUser.oil_type_cd__c = '1';
            update objUser;

            Event objEvent = new Event();
            objEvent.Distancekm__c = 5.29;
            objEvent.VehicleRefuelingCosts__c = 0;
            objEvent.DurationInMinutes = 1;
            objEvent.WorkType__c = '외근';
            objEvent.oil_type_cd__c = '1';
            objEvent.ActivityDateTime = Datetime.now();
            insert objEvent;
            system.debug('objEvent :: ' + objEvent);

        } catch (Exception e) {
            System.debug('CalcNoPriceFuelActivity_test line : ' + e.getLineNumber());
            System.debug('CalcNoPriceFuelActivity_test message : ' + e.getMessage());
            System.debug('CalcNoPriceFuelActivity_test cause : ' + e.getCause());
        }
    }

    @IsTest
    static void CalcNoPriceFuelActivity_test() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        CalcNoPriceFuelActivity_sc sc = new CalcNoPriceFuelActivity_sc();
        System.schedule('CalcNoPriceFuelActivity_sc','0 0 2 1/1 * ? *', sc);

        Test.stopTest();
    }

    // SUCCESS
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = newResponse(200);

            return response;
        }
    }

    private static HTTPResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(statusCode);
        response.setBody('{"ERR_CD":"S","ERR_MSG_CTT":"","DS_MASTER":{"data":[{"OIL_UNITP":262,"BASE_MON":"202301","COM_CD":"FW00","OIL_TYPE_CD":"1","DPRC_UNITP":101}],"SVC_ERR_MSG_TEXT":"","ErrorCode":0}}');
        return response;
    }
}