force-app/main/default/objects/IF_RELAY_INFO__c/IF_RELAY_INFO__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IF_RELAY_INFO</label>
</CustomObject>

force-app/main/default/objects/IF_RELAY_INFO__c/fields/Interface_auth_key__c.field-meta.xml
<CustomField>
    <fullName>Interface_auth_key__c</fullName>
    <label>Interface_auth_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_RELAY_INFO__c/fields/Interface_id__c.field-meta.xml
<CustomField>
    <fullName>Interface_id__c</fullName>
    <label>Interface_id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/ifKeyId__c.field-meta.xml
<CustomField>
    <fullName>ifKeyId__c</fullName>
    <label>ifKeyId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/InterfaceId__c.field-meta.xml
<CustomField>
    <fullName>InterfaceId__c</fullName>
    <label>InterfaceId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFN_TestDataFactory.cls
public class IFN_TestDataFactory {
    
    
    public static void createIfPrograms()
    {
        
        StaticResource resource = [SELECT Id, Name, Body FROM StaticResource WHERE Name = 'IFMaster_JSON'];
        List<IFMaster__c> newList = (List<IFMaster__c>) JSON.deserialize(resource.Body.toString(), List<IFMaster__c>.class);
        Insert newList;

        IFMaster__c ifmst = new IFMaster__c(Name='Dummy',
            InterfaceId__c = 'Dummy',
            Endpoint__c = '',
            Method__c = 'POST',
            ContentType__c = 'application/json',
            ifKeyId__c = 'test1',
            CallORBatch__c='Call'
        );
        insert ifmst;
        

        IF_RELAY_INFO__c objRelayInfo = new IF_RELAY_INFO__c();
        objRelayInfo.Interface_id__c = 'test';
        objRelayInfo.Interface_auth_key__c = 'test';
        insert objRelayInfo;

        StaticResource resource2 = [SELECT Id, Name, Body FROM StaticResource WHERE Name = 'IFERRORMST_JSON'];
        List<IF_ERROR_CODE_MST__c> newList2 = (List<IF_ERROR_CODE_MST__c>) JSON.deserialize(resource2.Body.toString(), List<IF_ERROR_CODE_MST__c>.class);
        Insert newList2;


                
    }
}