force-app/main/default/objects/UserBankInfo__c/UserBankInfo__c.object-meta.xml
<CustomObject>
    <label>지급은행정보</label>
    <nameField>
        <label>UserBankInfo Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserBankInfo__c/fields/IsOilExpenseAccount__c.field-meta.xml
<CustomField>
    <fullName>IsOilExpenseAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>주유비정산계좌여부</description>
    <inlineHelpText>주유비정산계좌여부</inlineHelpText>
    <label>IsOilExpenseAccount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/PV_ACUSE__c.field-meta.xml
<CustomField>
    <fullName>PV_ACUSE__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용여부</description>
    <label>PV_ACUSE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/PV_BANKL__c.field-meta.xml
<CustomField>
    <fullName>PV_BANKL__c</fullName>
    <label>PV_BANKL</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>한국은행(001)</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>산업은행(002)</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>기업은행(003)</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>국민은행(004)</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>외환은행(005)</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>국민은행(006)</label>
            </value>
            <value>
                <fullName>007</fullName>
                <label>수협은행(007)</label>
            </value>
            <value>
                <fullName>008</fullName>
                <label>수출입은행(008)</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>농협은행(011)</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>농협은행(010)</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>지역농축협은행(012)</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>지역농축협은행(013)</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>지역농축협은행(014)</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>지역농축협은행(015)</label>
            </value>
            <value>
                <fullName>016</fullName>
                <label>농협은행(016)</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>지역농축협은행(017)</label>
            </value>
            <value>
                <fullName>018</fullName>
                <label>지역농축협은행(018)</label>
            </value>
            <value>
                <fullName>019</fullName>
                <label>국민은행(019)</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>우리은행(020)</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>신한은행(021)</label>
            </value>
            <value>
                <fullName>023</fullName>
                <label>SC은행(023)</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>하나은행(025)</label>
            </value>
            <value>
                <fullName>026</fullName>
                <label>신한은행(026)</label>
            </value>
            <value>
                <fullName>027</fullName>
                <label>한국씨티은행(027)</label>
            </value>
            <value>
                <fullName>028</fullName>
                <label>신한은행(028)</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>국민은행(029)</label>
            </value>
            <value>
                <fullName>031</fullName>
                <label>대구은행(031)</label>
            </value>
            <value>
                <fullName>032</fullName>
                <label>부산은행(032)</label>
            </value>
            <value>
                <fullName>033</fullName>
                <label>하나은행(033)</label>
            </value>
            <value>
                <fullName>034</fullName>
                <label>광주은행(034)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/PV_BKONT__c.field-meta.xml
<CustomField>
    <fullName>PV_BKONT__c</fullName>
    <description>은행관리키</description>
    <label>PV_BKONT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>물대및미지급 결제계좌</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>전도금주류구매계좌</label>
            </value>
            <value>
                <fullName>91</fullName>
                <label>경비계좌</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <label>BC카드 결제계좌(사원)</label>
            </value>
            <value>
                <fullName>HD</fullName>
                <label>현대카드 결제계좌(사원)</label>
            </value>
            <value>
                <fullName>SS</fullName>
                <label>삼성카드 결제계좌(사원)</label>
            </value>
            <value>
                <fullName>X1</fullName>
                <label>구매카드 결제계좌</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/PV_BVTYP__c.field-meta.xml
<CustomField>
    <fullName>PV_BVTYP__c</fullName>
    <description>은행유형</description>
    <label>PV_BVTYP</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/PV_KOINH__c.field-meta.xml
<CustomField>
    <fullName>PV_KOINH__c</fullName>
    <description>예금주명</description>
    <label>PV_KOINH</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/PV_ZTERM_B1__c.field-meta.xml
<CustomField>
    <fullName>PV_ZTERM_B1__c</fullName>
    <label>PV_ZTERM_B1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>K400</fullName>
                <default>true</default>
                <label>출납일 지정 지급</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <label>Seq</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserBankInfo__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserBankInfo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserBankInfo_tr_test.cls
/************************************************************************************
 * File Name   		    : UserBankInfo_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2023.02.10
 * Target	  		    : UserBankInfo_tr.cls
 * Description 		    : UserBankInfo_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.02.10      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class UserBankInfo_tr_test {
    @isTest 
    static void itShould() {

        Test.startTest();
        UserBankInfo__c objUserBankInfo = new UserBankInfo__c();
        objUserBankInfo.Name = '씨앗은행';
        objUserBankInfo.User__c = UserInfo.getUserId();
        objUserBankInfo.PV_ZTERM_B1__c = 'K400';
        objUserBankInfo.PV_BANKL__c = '004';
        objUserBankInfo.PV_KOINH__c = '테스트';
        objUserBankInfo.PV_BKONT__c = 'HD';
        objUserBankInfo.PV_BVTYP__c = '1001';
        objUserBankInfo.PV_ACUSE__c = true;
        objUserBankInfo.Seq__c = 1;
        objUserBankInfo.IsOilExpenseAccount__c = false;
        insert objUserBankInfo;
        
        UserBankInfo__c objUserBankInfo2 = new UserBankInfo__c();
        objUserBankInfo2.Name = '풀잎은행';
        objUserBankInfo2.User__c = UserInfo.getUserId();
        objUserBankInfo2.PV_ZTERM_B1__c = 'K400';
        objUserBankInfo2.PV_BANKL__c = '004';
        objUserBankInfo2.PV_KOINH__c = '테스트';
        objUserBankInfo2.PV_BKONT__c = 'HD';
        objUserBankInfo2.PV_BVTYP__c = '1001';
        objUserBankInfo2.PV_ACUSE__c = true;
        objUserBankInfo2.Seq__c = 2;
        objUserBankInfo2.IsOilExpenseAccount__c = true;
        insert objUserBankInfo2;

        String strUserBankInfoId = objUserBankInfo.Id;
        objUserBankInfo = new UserBankInfo__c();
        objUserBankInfo.Id = strUserBankInfoId;
        objUserBankInfo.IsOilExpenseAccount__c = true;
        update objUserBankInfo;
        Test.stopTest();
    }
}