force-app/main/default/objects/BusinessPlan__c/BusinessPlan__c.object-meta.xml
<CustomObject>
    <label>경영계획</label>
    <nameField>
        <label>BusinessPlan 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessPlan__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <description>User.UserName_사원번호_년도_월</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>월</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6월</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7월</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9월</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10월</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11월</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12월</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/SLBZ_ORG_NM__c.field-meta.xml
<CustomField>
    <fullName>SLBZ_ORG_NM__c</fullName>
    <label>SLBZ_ORG_NM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IsExtraServiceInstructor__c.field-meta.xml
<CustomField>
    <fullName>IsExtraServiceInstructor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>부가서비스 강사&amp;셰프</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>377</fullName>
                <label>FS본부)기타</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>378</fullName>
                <label>FS개발)병원·레저개발팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>153</fullName>
                <label>아이누리)아이누리1팀</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>아이누리)아이누리동부팀</label>
            </value>
            <value>
                <fullName>314</fullName>
                <label>아이누리)아이누리2팀</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>363</fullName>
                <label>아이누리)아이누리서부팀</label>
            </value>
            <value>
                <fullName>365</fullName>
                <label>아이누리)아이누리3팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>348</fullName>
                <label>외식중부)외식2팀</label>
            </value>
            <value>
                <fullName>366</fullName>
                <label>외식중부)외식1팀</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BusinessPlanAutoCreate_ba.cls
/**
 * @description       : 사용자별 경영계획 생성 Batch Class
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : admin
**/
/*
BusinessPlanAutoCreate_ba b = new BusinessPlanAutoCreate_ba(2022, null);
Database.executeBatch(b, 1000);
*/
global class BusinessPlanAutoCreate_ba implements Database.Batchable<SObject>, Database.Stateful {
    global Integer targetYear;
    global String strUserId;
    global Set<String> setMonth;

    global BusinessPlanAutoCreate_ba(Integer targetYear, String strUserId) {
        if(targetYear == null) {
            targetYear = Date.today().year();
        }

        this.strUserId = strUserId;

        this.targetYear = targetYear;
        this.setMonth = new Set<String>{'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'};
    }

    /***********************************************************************************************************
    *  Bacth   : start
    *  내용    : 사용자 정보 조회
    ************************************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = '';
        strQuery += 'SELECT Id, Name, Username, EmployeeNumber,';                
        strQuery += '   HeadOffice__c, SU__c, Team__c';
        strQuery += '   FROM    User';
        strQuery += '   WHERE   EmployeeNumber != NULL';
        strQuery += '   AND     IsExtraServiceInstructor__c = false';
        strQuery += '   AND     IsActive = true';

        if(!Test.isRunningTest()) {
            strQuery += '   AND     Profile.Name LIKE \'%CJFW_%\'';
        }

        if(this.strUserId <> null) {
            strQuery += '   AND     Id =\''+this.strUserId+'\'';
        }
        
        if(Test.isRunningTest()) {
            strQuery += '   LIMIT 1';
        }

        return  Database.getQueryLocator(strQuery);
    }
    /***********************************************************************************************************
    *  Bacth   : execute
    *  내용    : 사용자별 경영계획 자동생성
    ************************************************************************************************************/
    global void execute(Database.BatchableContext bc, List<User> scope) {

        List<BusinessPlan__c> listBP = new List<BusinessPlan__c>();

        Map<String, String> mapSlbzOrgNm = CommonUtil.getMapPickListValuetoLabel('User', 'HeadOffice__c');
        Map<String, String> mapDivNm = CommonUtil.getMapPickListValuetoLabel('User', 'SU__c');
        Map<String, String> mapBrcNm = CommonUtil.getMapPickListValuetoLabel('User', 'Team__c');


        for(User obj : scope) {
            System.debug('=====================> HeadOffice__c : '+obj.HeadOffice__c);
            System.debug('=====================> SU__c : '+obj.SU__c);
            System.debug('=====================> Team__c : '+obj.Team__c);

            for(String strMonth : this.setMonth) {
                BusinessPlan__c objBP = new BusinessPlan__c();
                objBP.Name = obj.Name+'('+obj.EmployeeNumber+')_'+this.targetYear+(strMonth.length() == 1 ? '0'+strMonth : strMonth);

                objBP.OwnerId = obj.Id;
                objBP.Year__c = this.targetYear;
                objBP.Month__c = strMonth;
                objBP.SLBZ_ORG_ID__c = String.valueOf(obj.HeadOffice__c);
                objBP.SLBZ_ORG_NM__c = mapSlbzOrgNm.get(obj.HeadOffice__c);
                objBP.DIV_ID__c = String.valueOf(obj.SU__c);
                objBP.DIV_NM__c = mapDivNm.get(obj.SU__c);
                objBP.BRC_ID__c = String.valueOf(obj.Team__c);
                objBP.BRC_NM__c = mapBrcNm.get(obj.Team__c);

                objBP.ExtId__c = obj.EmployeeNumber+'_'+objBP.Year__c+'_'+objBP.Month__c;

                System.debug('==============> objBP.ExtId__c : '+objBP.ExtId__c);

                System.debug('==============> objBP : '+JSON.serialize(objBP));

                listBP.add(objBP);
            }
        }

        if(listBP <> null && listBP.size() > 0) {
            upsert listBP ExtId__c;
        }
    }

    /***********************************************************************************************************
    *  Bacth   : finish
    *  내용    : 내용 없음
    ************************************************************************************************************/
    global void finish(Database.BatchableContext BC) {
    }
}