force-app/main/default/objects/BusinessPlan__c/BusinessPlan__c.object-meta.xml
<CustomObject>
    <label>경영계획</label>
    <nameField>
        <label>BusinessPlan 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessPlan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>월</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6월</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7월</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9월</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10월</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11월</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12월</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BusinessPlan_tr_test.cls
/************************************************************************************
 * File Name   		    : BusinessPlan_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2023.02.06
 * Target	  		    : BusinessPlan_tr.cls
 * Description 		    : BusinessPlan_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.02.06      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class BusinessPlan_tr_test {
    @isTest 
    static void itShould() {
        Test.startTest();
        
        BusinessPlan__c objBusinessPlan = new BusinessPlan__c();
        objBusinessPlan.Name = '경영계획 1';
        objBusinessPlan.Year__c = 2021;
        objBusinessPlan.Month__c = '1';
        insert objBusinessPlan;

        String strBusinessPlanId = objBusinessPlan.Id;
        objBusinessPlan = new BusinessPlan__c();
        objBusinessPlan.Id = strBusinessPlanId;
        objBusinessPlan.Name = '경영계획 2';
        update objBusinessPlan;
        Test.stopTest();
    }
}