force-app/main/default/objects/BusinessPlan__c/BusinessPlan__c.object-meta.xml
<CustomObject>
    <label>경영계획</label>
    <nameField>
        <label>BusinessPlan 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessPlan__c/fields/fm_SU__c.field-meta.xml
<CustomField>
    <fullName>fm_SU__c</fullName>
    <formula>Text(Owner:User.SU__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>fm_SU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>월</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6월</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7월</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9월</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10월</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11월</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12월</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NetAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/SalesAmount__c.field-meta.xml
<CustomField>
    <fullName>SalesAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SalesAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/SalesProfit__c.field-meta.xml
<CustomField>
    <fullName>SalesProfit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SalesProfit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FSOpportunitySalesSummary_ba.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-03-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
/*
Date startDate = Date.newInstance(2022, 11, 1);
Date endDate = Date.newInstance(2022, 11, 30);
Integer batchSize = 20;

FSOpportunitySalesSummary_ba ba = new FSOpportunitySalesSummary_ba(startDate, endDate, null, true, batchSize);
Database.executeBatch(ba, batchSize);
*/

global class FSOpportunitySalesSummary_ba implements Database.Batchable<SObject>, Database.Stateful {    
    global String targetUserId;
    global Date targetDate;

    global FSOpportunitySalesSummary_ba(Date targetDate, String targetUserId) {
        this.targetDate = targetDate;
        this.targetUserId = targetUserId;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = '';
        strQuery += 'SELECT Id, Owner.Name, Owner.Profile.Name, Year__c, Month__c, ';
        strQuery += '   NetAmount__c, SalesAmount__c, SalesProfit__c';
        strQuery += '   FROM    BusinessPlan__c';        
        // 2022-02-03 FS개발사업부 코드값(3100)으로 조회
        // 추후 코드값이 변경된다면 수정 필수!
        strQuery += '   WHERE   fm_SU__c =\'3100\'';

        if(this.targetUserId <> null && this.targetUserId <> '') {
            strQuery += '   AND     OwnerId =:targetUserId';
        }

        if(Test.isRunningTest()) {
            strQuery += '   ORDER BY Owner.Name, Year__c, Month__c asc';
        }
        
        return  Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext bc, List<BusinessPlan__c> scope) {
        // BatchSize 무조건 1개로 진행해야함
        
    }

    global void finish(Database.BatchableContext BC) {
    }
}