force-app/main/default/objects/BusinessPlan__c/BusinessPlan__c.object-meta.xml
<CustomObject>
    <label>경영계획</label>
    <nameField>
        <label>BusinessPlan 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessPlan__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>월</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6월</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7월</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9월</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10월</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11월</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12월</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NetAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/SalesAmount__c.field-meta.xml
<CustomField>
    <fullName>SalesAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SalesAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/SalesProfit__c.field-meta.xml
<CustomField>
    <fullName>SalesProfit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SalesProfit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/SLBZ_ORG_NM__c.field-meta.xml
<CustomField>
    <fullName>SLBZ_ORG_NM__c</fullName>
    <label>SLBZ_ORG_NM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BusinessPlan__c/fields/YearMonth__c.field-meta.xml
<CustomField>
    <fullName>YearMonth__c</fullName>
    <externalId>true</externalId>
    <label>YearMonth</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesMonthOfMASummary__c/SalesMonthOfMASummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(MA별)</label>
    <nameField>
        <label>SalesMonthOfMASummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/BRC_ID__c.field-meta.xml
<CustomField>
    <fullName>BRC_ID__c</fullName>
    <label>BRC_ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/TotalSalesAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesAmount__c</fullName>
    <label>TotalSalesAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesMonthOfMASummary__c/fields/TotalSalesProfit__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesProfit__c</fullName>
    <label>TotalSalesProfit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IsExtraServiceInstructor__c.field-meta.xml
<CustomField>
    <fullName>IsExtraServiceInstructor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>부가서비스 강사&amp;셰프</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>377</fullName>
                <label>FS본부)기타</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>378</fullName>
                <label>FS개발)병원·레저개발팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>153</fullName>
                <label>아이누리)아이누리1팀</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>아이누리)아이누리동부팀</label>
            </value>
            <value>
                <fullName>314</fullName>
                <label>아이누리)아이누리2팀</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>363</fullName>
                <label>아이누리)아이누리서부팀</label>
            </value>
            <value>
                <fullName>365</fullName>
                <label>아이누리)아이누리3팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>348</fullName>
                <label>외식중부)외식2팀</label>
            </value>
            <value>
                <fullName>366</fullName>
                <label>외식중부)외식1팀</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesBusinessPlan_ba.cls
/**
 * @description       : 경영계획 매출정보 업데이트 Batch Class
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : admin
**/
/*
SalesBusinessPlan_ba b = new SalesBusinessPlan_ba(null, 2023, 2);
Database.executeBatch(b, 1000);
*/
global class SalesBusinessPlan_ba implements Database.Batchable<SObject>, Database.Stateful {        
    global String targetUserId;
    global Integer targetYear;
    global Integer targetMonth;

    global SalesBusinessPlan_ba(String targetUserId, Integer targetYear, Integer targetMonth) {
        if(targetUserId == null) {
            targetUserId = 'ALL';
        }
        
        if(Test.isRunningTest()) {
            targetUserId = UserInfo.getUserId();
        }

        this.targetUserId = targetUserId;

        if(targetYear == null) {
            targetYear = Date.today().year();
        }

        this.targetYear = targetYear;

        if(targetMonth == null) {
            targetMonth = Date.today().month();
        }

        this.targetMonth = targetMonth;
    }

    /***********************************************************************************************************
    *  Bacth   : start
    *  내용    : 사용자정보 정보 조회
    ************************************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = '';
        strQuery += 'SELECT Id, Name, UserName, EmployeeNumber,';                
        strQuery += '   HeadOffice__c, SU__c, Team__c';
        strQuery += '   FROM    User';        
        strQuery += '   WHERE   EmployeeNumber != NULL';
        strQuery += '   AND     IsExtraServiceInstructor__c = false';


        if(!Test.isRunningTest()) {
            strQuery += '   AND     Profile.Name LIKE \'%CJFW_%\'';
        }

        if(this.targetUserId <> null && this.targetUserId <> '' && this.targetUserId != 'ALL') {
            strQuery += '   AND     Id=:targetUserId';
        }
        
        return  Database.getQueryLocator(strQuery);
    }
    /***********************************************************************************************************
    *  Bacth   : execute
    *  내용    : 경영계획 매출정보 업데이트
    ************************************************************************************************************/
    global void execute(Database.BatchableContext bc, List<User> scope) {

        Set<String> setUserId = new Set<String>();
        Set<String> setUserEmployeeNumber = new Set<String>();

        Map<String, User> mapUser = new Map<String, User>();

        for(User obj : scope) {
            setUserId.add(obj.Id);
            setUserEmployeeNumber.add(obj.EmployeeNumber);
            mapUser.put(obj.Id, obj);
        }

        System.debug('===================> setUserEmployeeNumber : '+JSON.serialize(setUserEmployeeNumber));

        String strQuery = '';

        Date dtStart = Date.newInstance(this.targetYear, this.targetMonth, 1);
        Date dtEnd = Date.newInstance(this.targetYear, this.targetMonth, Date.today().day());

        strQuery += 'SELECT  OwnerId,';        
        strQuery += '   SUM(TotalNetAmount__c) TotalNetAmount, SUM(TotalSalesAmount__c) TotalSalesAmount, SUM(TotalSalesProfit__c) TotalSalesProfit';
        strQuery += '   FROM    SalesMonthOfMASummary__c';
        strQuery += '   WHERE   OwnerId IN:setUserId';
        strQuery += '   AND   SalesDate__c >=: dtStart';
        strQuery += '   AND   SalesDate__c <: dtEnd';

        strQuery += '   GROUP BY OwnerId';

        System.debug('=============> strQuery : '+strQuery);

        List<AggregateResult> listSalesMonthSummmary = Database.query(strQuery);

        List<BusinessPlan__c> listBP = new List<BusinessPlan__c>();

        if(listSalesMonthSummmary <> null && listSalesMonthSummmary.size() > 0) {            
            Map<String, String> mapSlbzOrgNm = CommonUtil.getMapPickListValuetoLabel('User', 'HeadOffice__c');
            Map<String, String> mapDivNm = CommonUtil.getMapPickListValuetoLabel('User', 'SU__c');
            Map<String, String> mapBrcNm = CommonUtil.getMapPickListValuetoLabel('User', 'Team__c');

            for(AggregateResult obj : listSalesMonthSummmary) {
                BusinessPlan__c objBP = new BusinessPlan__c();

                String strTargetOwnerId = String.valueOf(obj.get('OwnerId'));
                String strUserName = '';
                String strUserFullName = 'CJFWAdmin';
                String strTargetEmployeeNumber = '';

                if(mapUser <> null && mapUser.get(strTargetOwnerId) <> null) {
                    User objTargetUser = mapUser.get(strTargetOwnerId);

                    strUserName = objTargetUser.UserName;
                    strUserFullName = objTargetUser.Name;
                    strTargetEmployeeNumber = objTargetUser.EmployeeNumber;
                    objBP.OwnerId = objTargetUser.Id;

                    objBP.SLBZ_ORG_ID__c = String.valueOf(objTargetUser.HeadOffice__c);
                    objBP.SLBZ_ORG_NM__c = mapSlbzOrgNm.get(objBP.SLBZ_ORG_ID__c);
                    objBP.DIV_ID__c = String.valueOf(objTargetUser.SU__c);
                    objBP.DIV_NM__c = mapDivNm.get(objBP.DIV_ID__c);
                    objBP.BRC_ID__c = String.valueOf(objTargetUser.Team__c);
                    objBP.BRC_NM__c = mapBrcNm.get(objBP.BRC_ID__c);
                }

                objBP.Year__c = this.targetYear;
                objBP.Month__c = String.valueOf(this.targetMonth);
                objBP.YearMonth__c = objBP.Year__c+(objBP.Month__c.length() == 1 ? '0'+objBP.Month__c : objBP.Month__c);
                
                // 순매출
                objBP.NetAmount__c = (Decimal)obj.get('TotalNetAmount');

                /*
                if(objBP.NetAmount__c == null) {
                    objBP.NetAmount__c = 0;
                }
                */

                // 총매출
                objBP.SalesAmount__c = (Decimal)obj.get('TotalSalesAmount');

                /*
                if(objBP.SalesAmount__c == null) {
                    objBP.SalesAmount__c = 0;
                }
                */
                
                // 매출이익
                objBP.SalesProfit__c = (Decimal)obj.get('TotalSalesProfit');

                /*
                if(objBP.SalesProfit__c == null) {
                    objBP.SalesProfit__c = 0;
                }
                */

                objBP.Name = strUserFullName+'('+strTargetEmployeeNumber+')_'+objBP.YearMonth__c;
                objBP.ExtId__c = strTargetEmployeeNumber+'_'+objBP.Year__c+'_'+objBP.Month__c;

                listBP.add(objBP);
            }

            if(listBP <> null && listBP.size() > 0) {
                upsert listBP ExtId__c;
            }
        }
    }

    /***********************************************************************************************************
    *  Bacth   : finish
    *  내용    : 없음
    ************************************************************************************************************/
    global void finish(Database.BatchableContext BC) {
    }
}