force-app/main/default/objects/CJFW_CommSearchData__c/CJFW_CommSearchData__c.object-meta.xml
<CustomObject>
    <description>[P2]공통필터 , 공통리스트 에 가져올 데이터를 담아주는 object</description>
    <label>CJFW_CommSearchData</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>CommSearchData</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <description>Object의 api name 값</description>
    <label>ApiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>설명란</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>편집가능여부 ( true-편집불가 / false-편집가능)</description>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/FieldType__c.field-meta.xml
<CustomField>
    <fullName>FieldType__c</fullName>
    <label>FieldType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>picklist</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>search</fullName>
            </value>
            <value>
                <fullName>customComboBox</fullName>
            </value>
            <value>
                <fullName>customAccountModal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/HeaderLine__c.field-meta.xml
<CustomField>
    <fullName>HeaderLine__c</fullName>
    <description>header Filter 에서 노출되는 Line을 지정할 수 있다. 
1이면 첫번째라인에 노출 , 
2이면 두번째라인에 노출 , 
3이면 세번째라인에 노출
4이면 세번째라인에 노출</description>
    <label>HeaderLine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/HeadFilterOrder__c.field-meta.xml
<CustomField>
    <fullName>HeadFilterOrder__c</fullName>
    <label>HeadFilterOrder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>7</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>8</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>true - 활성 , false -비활성</description>
    <label>활성여부</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/IsMobile__c.field-meta.xml
<CustomField>
    <fullName>IsMobile__c</fullName>
    <defaultValue>false</defaultValue>
    <description>모바일 노출여부 (true-노출 / false-노출안함)</description>
    <label>IsMobile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>노출하고자하는 라벨</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/ListOrder__c.field-meta.xml
<CustomField>
    <fullName>ListOrder__c</fullName>
    <description>공통리스트에 뿌려줄 필드 순서 지정</description>
    <label>ListOrder</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/MenuName__c.field-meta.xml
<CustomField>
    <fullName>MenuName__c</fullName>
    <description>사용하는 매뉴의 이름
해당값에 의해 데이터 가져와짐</description>
    <label>메뉴명</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>매출원장</fullName>
            </value>
            <value>
                <fullName>기타매출관리</fullName>
            </value>
            <value>
                <fullName>매출채권현황리포트</fullName>
            </value>
            <value>
                <fullName>체인판매수수료정산현황조회</fullName>
            </value>
            <value>
                <fullName>일자별매출채권리포트</fullName>
            </value>
            <value>
                <fullName>All</fullName>
                <isActive>false</isActive>
                <label>All</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object 명</description>
    <label>Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/OptionLabel__c.field-meta.xml
<CustomField>
    <fullName>OptionLabel__c</fullName>
    <description>selectbox 에서 노출될 옵션 라벨정보</description>
    <label>OptionLabel</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/OptionValue__c.field-meta.xml
<CustomField>
    <fullName>OptionValue__c</fullName>
    <description>selectbox 에서 노출될 옵션 라벨정보</description>
    <label>OptionValue</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>(필수여부 True - 필수 / False -  필수아님)</description>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CJFW_CommSearchData__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>헤더에 쓰일정보인지 , List에 쓰일정보인지 구분하는 값</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>List</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CommSearchDataController.cls
/**
 * @description       : 매출/채권 메뉴탭 마다 다른 , header 정보 list 정보에 뿌려질 데이터를 모아놓은 object 를 조회하는 용도
 * @author            : eunyoung.choi@dkbmc.com
 * @group             : 
 * @last modified on  : 08-16-2023
 * @last modified by  : eunyoung.choi@dkbmc.com
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   08-07-2023   eunyoung.choi@dkbmc.com   Initial Version
 * 1.1   08-08-2023   eunyoung.choi@dkbmc.com   다이나믹 쿼리 추가..
**/
public with sharing class CommSearchDataController {

    /**
    *@param  menuSearch : 어떤메뉴바를 선택했는지 구분값 
    *@return  CJFW_CommSearchData__c 리스트 반환 
     @description : Header에 어떤 컬럼을 노출할지 확인을 위해 해당 오브젝트에서 조회
     CommSearchDataController.getCommSearchData   
     @author : eunyoung
    */
   @AuraEnabled(cacheable=true)
   public static List<CJFW_CommSearchData__c> getCommSearchData(String menuSearch){
       system.debug('CommSearchDataController #getCommSearchData => ' );
       
       List<CJFW_CommSearchData__c> searList = new List<CJFW_CommSearchData__c>();
           System.debug('All Data');
           searList = [SELECT 
             Id
           , Object__c
           , OptionLabel__c
           , OptionValue__c
           , Type__c
           , Label__c
           , ApiName__c
           , Required__c
           , Disabled__c
           , FieldType__c
           , IsMobile__c
           , Description__c 
           , HeaderLine__c
           , HeadFilterOrder__c
           , ListOrder__c
           , IsActive__c
           FROM CJFW_CommSearchData__c  
           WHERE MenuName__c =: menuSearch AND IsActive__c = true
           // WHERE Object__c =: menuSearch OR MenuName__c ='All'
           ORDER BY HeadFilterOrder__c ASC ];   
           
           system.debug('return => ' + searList.size() );
           system.debug('return => ' + searList );

       return searList;
   }


    /**
    *@param  filterDataList : [ api name / objName / searchkey ] List
     @paramExample :  ({apiName=GD_NM__c, objName=SalesLedgerInformation__c, searchKey=3}) 
    *@return  String : WHERE 절 반환 
     @description : Header에 입력받은 값으로 WHERE절 생성 
     CommSearchDataController.getWhereQuery 
     @author : eunyoung
    */
   @AuraEnabled
   public static String getWhereQuery(List<Map<String, String>> filterDataList ){
       system.debug('CommSearchDataController #getWhereQuery=> ' + filterDataList);
       Boolean addWhereClause = true;
       String whereQuery='';
    
        for(Map<String,String> filterData : filterDataList){
            String apiName = filterData.get('apiName');
            String searchKey = filterData.get('searchKey');
            //WHERE 절
            if(addWhereClause){
                whereQuery +=' WHERE ';
                whereQuery +=  apiName + ' LIKE \'%' + searchKey + '%\'';
                addWhereClause = false;
            }else {
                whereQuery += ' AND ' + apiName + ' LIKE \'%' + searchKey + '%\'';
            }
        }
        system.debug(' Final whereQuery -> ' + whereQuery );
       return whereQuery;
   }

    /**
    *@param  finalQuery : select from where 조합한 전체쿼리 
    *@return  조회된 데이터 반환
     @description : cjfwCommListView.js 에서 전체 쿼리조합 후 , 조회
     CommSearchDataController.getDataList 
     @author : eunyoung
    */
   @AuraEnabled
   public static List<Object> getDataList(String finalQuery){
       system.debug('CommSearchDataController #getDataList=> ');

       List<SObject> dataList = new List<SObject>();
       try{
           system.debug('data=>' + finalQuery);
           dataList = Database.query(finalquery); 
           system.debug('data=>' + dataList);
           system.debug('data size =>' + dataList.size());
       }catch(Exception e) {
           System.debug(' getDataList Error -> ' + e.getMessage());
       }
       return dataList;
   }

}