force-app/main/default/objects/Account/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <description>MDM 고객계정그룹</description>
    <label>AccountGroup</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Z100</fullName>
                <label>CJ FW금융 고객</label>
            </value>
            <value>
                <fullName>Z200</fullName>
                <label>CJ FW일반 고객</label>
            </value>
            <value>
                <fullName>Z300</fullName>
                <label>일반고객(판매처)</label>
            </value>
            <value>
                <fullName>Z400</fullName>
                <label>관리처</label>
            </value>
            <value>
                <fullName>Z900</fullName>
                <label>CJ FW일회성 고객</label>
            </value>
            <value>
                <fullName>Z910</fullName>
                <label>경영계획부서고객</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AccountStatus__c.field-meta.xml
<CustomField>
    <fullName>AccountStatus__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessConditions__c.field-meta.xml
<CustomField>
    <fullName>BusinessConditions__c</fullName>
    <label>Business Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CompanyRegisterNumber__c.field-meta.xml
<CustomField>
    <fullName>CompanyRegisterNumber__c</fullName>
    <description>기업의 사업자 등록번호</description>
    <label>Company Register Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerIDASIS__c.field-meta.xml
<CustomField>
    <fullName>CustomerIDASIS__c</fullName>
    <description>MDM 구코드(As-Is)</description>
    <label>CustomerIDASIS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerRoute__c.field-meta.xml
<CustomField>
    <fullName>CustomerRoute__c</fullName>
    <label>CustomerRoute</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3101-001</fullName>
                <label>외식대리점_상온_상온</label>
            </value>
            <value>
                <fullName>3102-001</fullName>
                <label>외식대리점_저온_저온</label>
            </value>
            <value>
                <fullName>3103-001</fullName>
                <label>외식대리점_해피스푼_해피스푼</label>
            </value>
            <value>
                <fullName>3104-001</fullName>
                <label>외식유통점_식당점_한분식</label>
            </value>
            <value>
                <fullName>3105-001</fullName>
                <label>외식유통점_식당점_중식</label>
            </value>
            <value>
                <fullName>3106-001</fullName>
                <label>외식유통점_식당점_양식</label>
            </value>
            <value>
                <fullName>3107-001</fullName>
                <label>외식유통점_식당점_일식</label>
            </value>
            <value>
                <fullName>3108-001</fullName>
                <label>외식유통점_식자재마트_기업형</label>
            </value>
            <value>
                <fullName>3109-001</fullName>
                <label>외식유통점_식자재마트_개별형</label>
            </value>
            <value>
                <fullName>3110-001</fullName>
                <label>외식직거래_FC_FC)레스토랑</label>
            </value>
            <value>
                <fullName>3111-001</fullName>
                <label>외식직거래_FC_FC)카페</label>
            </value>
            <value>
                <fullName>3112-001</fullName>
                <label>외식직거래_FC_FC)주점</label>
            </value>
            <value>
                <fullName>3113-001</fullName>
                <label>외식직거래_RS_RS)한식</label>
            </value>
            <value>
                <fullName>3114-001</fullName>
                <label>외식직거래_RS_RS)아시안</label>
            </value>
            <value>
                <fullName>3115-001</fullName>
                <label>외식직거래_RS_RS)외식기타Ⅰ</label>
            </value>
            <value>
                <fullName>3116-001</fullName>
                <label>외식직거래_RS_RS)양식</label>
            </value>
            <value>
                <fullName>3117-001</fullName>
                <label>외식직거래_RS_RS)웨딩부페&amp;호텔</label>
            </value>
            <value>
                <fullName>3118-001</fullName>
                <label>외식직거래_RS_RS)외식기타Ⅱ</label>
            </value>
            <value>
                <fullName>3119-001</fullName>
                <label>FO_도매_대도매</label>
            </value>
            <value>
                <fullName>3120-001</fullName>
                <label>FO_도매_중도매</label>
            </value>
            <value>
                <fullName>3121-001</fullName>
                <label>FO_도매_중도매/협력점</label>
            </value>
            <value>
                <fullName>3122-001</fullName>
                <label>FO_소사장_차량사업자</label>
            </value>
            <value>
                <fullName>3123-001</fullName>
                <label>FO_직영_식당</label>
            </value>
            <value>
                <fullName>3124-001</fullName>
                <label>FO_직영_웨딩뷔페</label>
            </value>
            <value>
                <fullName>3125-001</fullName>
                <label>FO_직영_체인</label>
            </value>
            <value>
                <fullName>3126-001</fullName>
                <label>FO_소매_현매</label>
            </value>
            <value>
                <fullName>3127-001</fullName>
                <label>FO_기타_실수요</label>
            </value>
            <value>
                <fullName>3128-001</fullName>
                <label>FO_기타_기타</label>
            </value>
            <value>
                <fullName>3129-001</fullName>
                <label>FO_기타_직원</label>
            </value>
            <value>
                <fullName>3130-001</fullName>
                <label>FO_법인_법인</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/DisHisRegType__c.field-meta.xml
<CustomField>
    <fullName>DisHisRegType__c</fullName>
    <label>DisHisRegType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>수입</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>유통업자</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>소매업자</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>최종소비자</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>수출</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>손실량</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/fm_SalesGroup__c.field-meta.xml
<CustomField>
    <fullName>fm_SalesGroup__c</fullName>
    <formula>Owner.UserRole.Name</formula>
    <label>Sales Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FWReleaseCenter__c.field-meta.xml
<CustomField>
    <fullName>FWReleaseCenter__c</fullName>
    <label>FWReleaseCenter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1000</fullName>
                <label>KX물류센터</label>
            </value>
            <value>
                <fullName>2040</fullName>
                <label>제주FS센터</label>
            </value>
            <value>
                <fullName>2041</fullName>
                <label>제주FC</label>
            </value>
            <value>
                <fullName>2042</fullName>
                <label>제주급식</label>
            </value>
            <value>
                <fullName>2043</fullName>
                <label>제주급식센터(키즈)</label>
            </value>
            <value>
                <fullName>2120</fullName>
                <label>실수요직송센터</label>
            </value>
            <value>
                <fullName>2140</fullName>
                <label>이천)푸드빌센터</label>
            </value>
            <value>
                <fullName>2150</fullName>
                <label>농수가공비축센터</label>
            </value>
            <value>
                <fullName>2170</fullName>
                <label>외부비축창고</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FO</label>
            </value>
            <value>
                <fullName>2230</fullName>
                <label>장성물류센터</label>
            </value>
            <value>
                <fullName>2231</fullName>
                <label>장성물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2240</fullName>
                <label>이천)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2250</fullName>
                <label>양산직수입센터</label>
            </value>
            <value>
                <fullName>2260</fullName>
                <label>양산물류센터</label>
            </value>
            <value>
                <fullName>2261</fullName>
                <label>양산물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2330</fullName>
                <label>장성)아라마크센터</label>
            </value>
            <value>
                <fullName>2340</fullName>
                <label>양산)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2350</fullName>
                <label>대구)아라마크센터</label>
            </value>
            <value>
                <fullName>2360</fullName>
                <label>양산)아라마크센터</label>
            </value>
            <value>
                <fullName>2370</fullName>
                <label>수원2)아라마크센터</label>
            </value>
            <value>
                <fullName>2400</fullName>
                <label>FO중부센터(물류대행)</label>
            </value>
            <value>
                <fullName>2410</fullName>
                <label>FO강남센터(물류대행)</label>
            </value>
            <value>
                <fullName>2420</fullName>
                <label>FO동서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2430</fullName>
                <label>광주외식센터</label>
            </value>
            <value>
                <fullName>2440</fullName>
                <label>FO남서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2450</fullName>
                <label>FO대구센터(물류대행)</label>
            </value>
            <value>
                <fullName>2460</fullName>
                <label>FO부산센터(물류대행)</label>
            </value>
            <value>
                <fullName>2470</fullName>
                <label>FO광주센터(물류대행)</label>
            </value>
            <value>
                <fullName>2480</fullName>
                <label>FO울산센터(물류대행)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>LegalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>개인</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>영리법인</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>비영리법인</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/NameAlias__c.field-meta.xml
<CustomField>
    <fullName>NameAlias__c</fullName>
    <description>MDM 고객양칭명(변경)</description>
    <label>NameAlias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NameKor__c.field-meta.xml
<CustomField>
    <fullName>NameKor__c</fullName>
    <label>NameKor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PVVF_PERNR__c.field-meta.xml
<CustomField>
    <fullName>PVVF_PERNR__c</fullName>
    <label>PVVF_PERNR</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PVVF_VKGRP__c.field-meta.xml
<CustomField>
    <fullName>PVVF_VKGRP__c</fullName>
    <label>PVVF_VKGRP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/RepresentativeBirthDate__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeBirthDate__c</fullName>
    <label>Representative BirthDate</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>가망처</fullName>
    </customValue>
    <customValue>
        <fullName>무매출처</fullName>
    </customValue>
    <customValue>
        <fullName>중단처</fullName>
    </customValue>
    <description>전략사업부에서 사용하는 상태 필드의 선택목록</description>
    <masterLabel>고객상태_전략사업부</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CJFW_MDMReferenceCreateController.cls
/**
 * @description       : 
 * @author            : joohyeon.jang@dkbmc.com
 * @group             : 
 * @last modified on  : 08-24-2023
 * @last modified by  : joohyeon.jang@dkbmc.com
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   08-24-2023   joohyeon.jang@dkbmc.com   Initial Version
**/
public with sharing class CJFW_MDMReferenceCreateController {
    /**
     * @description 참조생성 모달 로딩 시, Default 데이터 (Account데이터 10개)
     * 
     * @return      `String`
     */ 
    @AuraEnabled
    public static List<DataWrapper> doInit(){
        system.debug('doInit!!!');
        List<DataWrapper> result = new List<DataWrapper>();

        List<Account> accList = doSelect(null, null, null);

        if(!AccList.isEmpty()) {
            for(Account acc : accList){
                result.add(new DataWrapper(acc));
            }
        }
        return result;
    }
     /**
     * @description 참조생성 모달 > 검색어 입력 후 검색 > 검색어로 Like 
     * 
     * @return      `String`
     */ 
    @AuraEnabled
    public static List<DataWrapper> doSearch(String customerId, String customerName, String managerMA){
        List<DataWrapper> result = new List<DataWrapper>();
        List<Account>    accList = doSelect(customerId, customerName, managerMA);

        if(!AccList.isEmpty()){
            for(Account acc : accList){
                result.add(new DataWrapper(acc));
            }
        }
        return result;
    }

    // 기본조회
    public static List<Account> doSelect(String customerId, String customerName, String managerMA ){
        String S_SELECT = '';
        S_SELECT  ='  SELECT ' 
                  +'  id '
                  +' ,CustomerID__c ' 
                  +' ,Name ' 
                  +' ,CompanyRegisterNumber__c ' 
                  +' ,fm_SalesGroup__c ' 
                  +' ,CustomerRoute__c ' 
                  +' ,Owner.Name ' 
                  +' ,AccountStatus__c ' 
                  +' ,CustomerIDASIS__c ' 
                  +' ,CreatedDate ' 
                  +' ,FWReleaseCenter__c ' 
                  +' ,DisHisRegType__c ' 
                  +' FROM Account ';
            
        String S_WHERE  = ' WHERE CustomerID__c != null';
        system.debug('doSearch');

        if(String.isNotBlank(customerId) || String.isNotBlank(customerName) || String.isNotBlank(managerMA)){
            String pSearchLike = '';

            if(String.isNotBlank(customerId)) {
                pSearchLike = '%' + customerId + '%';
                S_WHERE += ' AND CustomerID__c Like : pSearchLike' ;
            }
            if(String.isNotBlank(customerName)) {
                system.debug('customerName 잘 들어옵니까 ' + customerName);
                pSearchLike = '%' + customerName + '%';
                S_WHERE += ' AND Name Like : pSearchLike' ;
            }
            if(String.isNotBlank(managerMA)) {
                pSearchLike = '%' + managerMA + '%';
                S_WHERE += ' AND Owner.Name Like : pSearchLike' ;
            }
        }

        //String S_ORDER  = ' ORDER BY NAME ASC '; //나중에 검색 조건이 생기면 그때 추가 할 예정임
        
        String S_LIMITS = ' LIMIT 10';
                                        // S_ORDER +
        system.debug(S_SELECT + S_WHERE +  S_LIMITS);
                                                // S_ORDER +
        return Database.query(S_SELECT + S_WHERE +  S_LIMITS);
    }

    /** 
     * @description 참조생성 모달 List Data
     */
    public class DataWrapper { 
        @AuraEnabled public String id{get;set;}                    // Account Object Id 
        @AuraEnabled public String customerID{get;set;}            // 고객ID 
        @AuraEnabled public String name{get;set;}                  // 고객명(영문명포함) 
        @AuraEnabled public String companyRegisterNumber{get;set;} // 사업자등록번호 
        @AuraEnabled public String fm_SalesGroup{get;set;}         // 영업그룹 
        @AuraEnabled public String customerRoute{get;set;}         // 고객분류 
        @AuraEnabled public String ownerName{get;set;}             // 담당MA 
        @AuraEnabled public String accountStatus{get;set;}         // 고객상태 
        @AuraEnabled public String customerIDASIS{get;set;}        // 구코드(AS-IS) 
        @AuraEnabled public Date   createdDate{get;set;}           // 등록일시 
        @AuraEnabled public String fWReleaseCenter{get;set;}       // FW출고센터 
        @AuraEnabled public String disHisRegType{get;set;}         // 유통이력신고대상유형 

        public DataWrapper(){}
        public DataWrapper(Account acc) {
            this.id                     = acc.Id;
            this.customerID             = acc.CustomerID__c;
            this.name                   = acc.Name;
            this.companyRegisterNumber  = acc.CompanyRegisterNumber__c;
            this.fm_SalesGroup          = acc.fm_SalesGroup__c;
            this.customerRoute          = acc.CustomerRoute__c;
            this.ownerName              = acc.Owner.Name;
            this.accountStatus          = acc.AccountStatus__c;
            this.customerIDASIS         = acc.CustomerIDASIS__c;
            this.createdDate            = Date.valueOf(acc.CreatedDate);
            this.fWReleaseCenter        = acc.FWReleaseCenter__c;
            this.disHisRegType          = acc.DisHisRegType__c;
        }
    }

    /** 
     * @description 참조생성 모달에서 선택한 Account Data Wrapper
     */
    public class AccountDataWrapper { 
        @AuraEnabled public String id{get;set;}                                   // 판매처 
        @AuraEnabled public String name{get;set;}                                 // 고객명(영문명포함)
        @AuraEnabled public String nameKor{get;set;}                              // 고객명(G)/자국명 
        @AuraEnabled public String nameAlias{get;set;}                            // 고객약칭명(변경)
        @AuraEnabled public String accountGroup{get;set;}                         // 고객계정그룹
        @AuraEnabled public String type{get;set;}                                 // 고객유형
        @AuraEnabled public String companyRegisterNumber{get;set;}                // 사업자등록번호
        @AuraEnabled public String legalStatus{get;set;}                          // 법적상태
        @AuraEnabled public String representativeName{get;set;}                   // 대표자이름 
        @AuraEnabled public String representativeBirthDate{get;set;}              // 대표자생년월일
        @AuraEnabled public String industry{get;set;}                             // 업태
        @AuraEnabled public String businessConditions{get;set;}                   // 업종
        @AuraEnabled public String phone{get;set;}                                // 업태 
        @AuraEnabled public Date   pVVF_VKGRP{get;set;}                           // 전화번호
        @AuraEnabled public Date   pVVF_PERNR{get;set;}                           // 영업그룹유효일자 
        @AuraEnabled public String taxInvoiceType{get;set;}                       // 담당MA유효일자
        @AuraEnabled public String taxationType{get;set;}                         // 세금계산서발행유형
        @AuraEnabled public String headOfficeCode{get;set;}                       // 과세유형
        @AuraEnabled public String countryKeyCode{get;set;}                       // 본점코드
        @AuraEnabled public String locationState{get;set;}                        // 국가
        @AuraEnabled public String postalCode{get;set;}                           // 지역 
        @AuraEnabled public String address{get;set;}                              // 우편번호
        @AuraEnabled public String address2{get;set;}                             // 도로명주소
        @AuraEnabled public String addressDetails2{get;set;}                      // 지번주소

        public AccountDataWrapper(){}
        public AccountDataWrapper(Account acc) {
            this.id                                   = acc.Id;
            this.name                                 = acc.Name;
            this.nameKor                              = acc.NameKor__c;
            this.nameAlias                            = acc.NameAlias__c;
            this.accountGroup                         = acc.AccountGroup__c;
            this.type                                 = acc.Type;
            this.companyRegisterNumber                = acc.CompanyRegisterNumber__c;
            this.legalStatus                          = acc.LegalStatus__c;
            //this.representativeName                   = acc.RepresentativeName__c;
            this.representativeBirthDate              = acc.RepresentativeBirthDate__c;
            this.industry                             = acc.Industry;
            this.businessConditions                   = acc.BusinessConditions__c;
            this.phone                                = acc.Phone;
            this.pVVF_VKGRP                           = Date.valueOf(acc.PVVF_VKGRP__c);
            this.pVVF_PERNR                           = Date.valueOf(acc.PVVF_PERNR__c);
            this.taxInvoiceType                       = acc.TaxInvoiceType__c;
            this.taxationType                         = acc.TaxationType__c;
            this.headOfficeCode                       = acc.HeadOfficeCode__c;
            this.countryKeyCode                       = acc.CountryKeyCode__c;
            this.locationState                        = acc.LocationState__c;
            //this.postalCode                           = acc.PostalCode__c;
            this.address                              = acc.Address__c;
            this.address2                             = acc.Address2__c;
            this.addressDetails2                      = acc.AddressDetails2__c;
        }
    }
}