force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BusinessPath__c.field-meta.xml
<CustomField>
    <fullName>BusinessPath__c</fullName>
    <label>Business Path</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessPath</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OurSales__c.field-meta.xml
<CustomField>
    <fullName>OurSales__c</fullName>
    <label>Our Sales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/PV_EXISTSUP__c.field-meta.xml
<CustomField>
    <fullName>PV_EXISTSUP__c</fullName>
    <label>PV_EXISTSUP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesMonthly__c.field-meta.xml
<CustomField>
    <fullName>SalesMonthly__c</fullName>
    <formula>CaptialSales__c +  EastSales__c +  WestSales__c +  JejuSales__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Monthly</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/SULabel__c.field-meta.xml
<CustomField>
    <fullName>SULabel__c</fullName>
    <label>SULabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessPath.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>골프장</fullName>
    </customValue>
    <customValue>
        <fullName>관공서</fullName>
    </customValue>
    <customValue>
        <fullName>대형병원</fullName>
    </customValue>
    <customValue>
        <fullName>리조트</fullName>
    </customValue>
    <customValue>
        <fullName>산업체</fullName>
    </customValue>
    <customValue>
        <fullName>소형병원</fullName>
    </customValue>
    <customValue>
        <fullName>스키장</fullName>
    </customValue>
    <customValue>
        <fullName>실버타운</fullName>
    </customValue>
    <customValue>
        <fullName>연수원</fullName>
    </customValue>
    <customValue>
        <fullName>오피스</fullName>
    </customValue>
    <customValue>
        <fullName>요양병원</fullName>
    </customValue>
    <customValue>
        <fullName>유치원</fullName>
    </customValue>
    <customValue>
        <fullName>장례식장</fullName>
    </customValue>
    <customValue>
        <fullName>중형병원</fullName>
    </customValue>
    <customValue>
        <fullName>컨세션</fullName>
    </customValue>
    <customValue>
        <fullName>학원</fullName>
    </customValue>
    <customValue>
        <fullName>휴게소</fullName>
    </customValue>
    <customValue>
        <fullName>초등학교</fullName>
    </customValue>
    <customValue>
        <fullName>중학교</fullName>
    </customValue>
    <customValue>
        <fullName>고등학교</fullName>
    </customValue>
    <customValue>
        <fullName>그외학교</fullName>
    </customValue>
    <customValue>
        <fullName>특수학교</fullName>
    </customValue>
    <customValue>
        <fullName>식품첨가물제조업</fullName>
    </customValue>
    <customValue>
        <fullName>식품판매업(기타)</fullName>
    </customValue>
    <customValue>
        <fullName>즉석판매제조가공업</fullName>
    </customValue>
    <customValue>
        <fullName>식품소분업</fullName>
    </customValue>
    <customValue>
        <fullName>식품제조가공업</fullName>
    </customValue>
    <customValue>
        <fullName>유통전문판매업</fullName>
    </customValue>
    <customValue>
        <fullName>집단급식소식품판매업</fullName>
    </customValue>
    <customValue>
        <fullName>캐터링</fullName>
    </customValue>
    <masterLabel>경로</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CJFW_CreateNewReportController.cls
/**
 * @description       : Oppty 품의서 작성화면 관련 Controller
 * @author            : yeonji.lim@dkbmc.com
 * @group             : 
 * @last modified on  : 09-13-2023
 * @last modified by  : yeonji.lim@dkbmc.com
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   09-13-2023   yeonji.lim@dkbmc.com      Initial Version
**/
public class CJFW_CreateNewReportController {
    
    /* 
     * lwc (cjfwCreateNewReport) 연결
     * Oppty에 연결된 Account 데이터 가져오기 
     */
    @AuraEnabled
    public static Opportunity getAccountData(String OpptyId){
        try {
            System.debug('OpptyId = ' + OpptyId);

            Opportunity accountData = [
                SELECT Id, Name, Account.Name, Account.RepresentativeName__c, Account.BusinessPath__c, Account.SalesMonthly__c, Account.OurSales__c, Account.Address__c, Account.PV_EXISTSUP__c
                FROM Opportunity
                WHERE Id =:OpptyId
            ];

            return accountData;

        } catch (Exception e) {
            System.debug('message => ' + e.getMessage());
            System.debug('trace => ' + e.getStackTraceString());

            throw new AuraHandledException(e.getMessage());
        }
    }

    /* 
     * User Obj에서 영업경로 가져오기 
     */
    @AuraEnabled
    public static User getSulLabel(String UserId){
        try {
            System.debug('UserId = ' + UserId);

            User sulLabelData = [
                select id , SULabel__c 
                from User 
                where Id ='0050w000004E8L1AAK'
            ];

            return sulLabelData;

        } catch (Exception e) {
            System.debug('message => ' + e.getMessage());
            System.debug('trace => ' + e.getStackTraceString());

            throw new AuraHandledException(e.getMessage());
        }
    }
}