force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/ClassService__c.object-meta.xml
<CustomObject>
    <description>교육시스템신청레코드저장 오브젝트
해당레코드의 적합성판단후 부가서비스내역으로 삽입</description>
    <label>교육서비스신청</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassService__c/fields/ApplicantsNumber__c.field-meta.xml
<CustomField>
    <fullName>ApplicantsNumber__c</fullName>
    <label>ApplicantsNumber</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>교육서비스신청</relationshipLabel>
    <relationshipName>Customer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/CustomerPhone__c.field-meta.xml
<CustomField>
    <fullName>CustomerPhone__c</fullName>
    <label>CustomerPhone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/GroupMealAge__c.field-meta.xml
<CustomField>
    <fullName>GroupMealAge__c</fullName>
    <label>GroupMealAge</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <label>Manager</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/MDMCode__c.field-meta.xml
<CustomField>
    <fullName>MDMCode__c</fullName>
    <label>MDMCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/ServiceContent__c.field-meta.xml
<CustomField>
    <fullName>ServiceContent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>부가서비스 컨텐츠</label>
    <referenceTo>ServiceContents__c</referenceTo>
    <relationshipName>ClassService</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H</fullName>
                <label>신청접수</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>신청완료</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>신청거부</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/TargetGroup__c.field-meta.xml
<CustomField>
    <fullName>TargetGroup__c</fullName>
    <label>TargetGroup</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>원장</fullName>
            </value>
            <value>
                <fullName>어린이</fullName>
            </value>
            <value>
                <fullName>교직원</fullName>
            </value>
            <value>
                <fullName>학부모</fullName>
            </value>
            <value>
                <fullName>학부모참여</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
            <value>
                <fullName>실버</fullName>
            </value>
            <value>
                <fullName>보육원성인</fullName>
            </value>
            <value>
                <fullName>보육원</fullName>
            </value>
            <value>
                <fullName>지적장애인</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExtraService__c/ExtraService__c.object-meta.xml
<CustomObject>
    <label>부가서비스 내역</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Extra Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtraService__c/fields/ApplicantsNumber__c.field-meta.xml
<CustomField>
    <fullName>ApplicantsNumber__c</fullName>
    <label>Applicants Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SH</fullName>
                <label>서비스/힐링</label>
            </value>
            <value>
                <fullName>NC</fullName>
                <label>위생컨설팅</label>
            </value>
            <value>
                <fullName>영양교육</fullName>
            </value>
            <value>
                <fullName>쿠킹클래스</fullName>
            </value>
            <value>
                <fullName>영양+쿠킹클래스</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>쿠킹/세미나</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>영양/건강/위생</label>
            </value>
            <value>
                <fullName>쉐프가 간다</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>가망처 대상으로 부가서비스 신청은 불가능합니다.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Existing Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>School Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>부가서비스 내역</relationshipLabel>
    <relationshipName>ExtraServiceCustomer1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/CustomerPhone__c.field-meta.xml
<CustomField>
    <fullName>CustomerPhone__c</fullName>
    <label>Customer Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/GroupMealAge__c.field-meta.xml
<CustomField>
    <fullName>GroupMealAge__c</fullName>
    <label>Age</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/ProgressTime__c.field-meta.xml
<CustomField>
    <fullName>ProgressTime__c</fullName>
    <label>Progress Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/ServiceContents__c.field-meta.xml
<CustomField>
    <fullName>ServiceContents__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contents</label>
    <referenceTo>ServiceContents__c</referenceTo>
    <relationshipName>ExtraServiceContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/ServiceStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDateTime__c</fullName>
    <label>Service Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T</fullName>
                <default>true</default>
                <label>임시저장</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>접수</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>승인</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>반려</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>완료</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>취소</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/TargetGroup__c.field-meta.xml
<CustomField>
    <fullName>TargetGroup__c</fullName>
    <label>Target Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>원장</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>어린이</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>교직원</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>학부모</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>학부모참여</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>기타</label>
            </value>
            <value>
                <fullName>실버</fullName>
            </value>
            <value>
                <fullName>보육원성인</fullName>
            </value>
            <value>
                <fullName>보육원</fullName>
            </value>
            <value>
                <fullName>지적장애인</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContents__c/ServiceContents__c.object-meta.xml
<CustomObject>
    <label>부가서비스 컨텐츠</label>
    <nameField>
        <label>Contents Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ServiceContents__c/fields/IsUsage__c.field-meta.xml
<CustomField>
    <fullName>IsUsage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Usage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceContents__c/fields/OpenDate__c.field-meta.xml
<CustomField>
    <fullName>OpenDate__c</fullName>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContents__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>전국</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>수도권</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>동부권</label>
            </value>
            <value>
                <fullName>W</fullName>
                <label>서부권</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFN_LIF1002_OD003_MD004_TEST.cls
@isTest
public class IFN_LIF1002_OD003_MD004_TEST {

    @TestSetup
    static void makeData(){
        IFN_TestDataFactory.createIfPrograms();


        ServiceContents__c svccont = new ServiceContents__c();
        svccont.IsUsage__c = true;
        svccont.Region__c = 'A';
        svccont.Category__c = 'SH';
        svccont.OpenDate__c = Date.today();
        svccont.Name = '1';
        svccont.IsUsage__c = true;
        insert svccont;

        Account objAccount = TestObjectCreator.objHealthAccount;
        insert objAccount;

        ClassService__c cls = new ClassService__c();
        cls.ServiceContent__c = svccont.id;
        cls.MDMCode__c = '1';
        cls.Status__c = 'H';
        cls.Manager__c = '1';
        cls.CustomerPhone__c = '02-000-0000';
        cls.TargetGroup__c = 'DIRECTOR';
        cls.ApplicantsNumber__c = '1';
        cls.GroupMealAge__c = '1';
        cls.Address__c = '1';
        cls.Description__c = '1';
        cls.Customer__c    =objAccount.id;
        insert cls;

        ExtraService__c exs = new ExtraService__c();
        exs.ServiceStartDateTime__c = Datetime.now();
        exs.ProgressTime__c =12;
        insert exs;
    }

    @isTest
    static void test01() {
        Test.startTest();
        ServiceContents__c svccont = [select id from ServiceContents__c  Limit 1];

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String strBody = '{ '
                         +'   "schttl": "", '
                         +'   "stDt": "2023-01-01", '
                         +'   "edDt": "2023-12-31", '
                         +'   "dataCnt": "3", '
                         +'   "pgNo": "1", '
                         +'   "mdmCd": "23123" '
                         +'}';

        req.requestBody = Blob.valueOf(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD003_MD004.doPost();
        
        Test.stopTest();
    }


    @isTest
    static void test02() {
        Test.startTest();
        ServiceContents__c svccont = [select id from ServiceContents__c  Limit 1];

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        String strBody = '{ '
                         +'   "schttl": "", '
                         +'   "stDt": "", '
                         +'   "edDt": "", '
                         +'   "dataCnt": "", '
                         +'   "pgNo": "1", '
                         +'   "mdmCd": "23123" '
                         +'}';

        req.requestBody = Blob.valueOf(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD003_MD004.doPost();
        
        Test.stopTest();
    }


}