force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressDetails__c.field-meta.xml
<CustomField>
    <fullName>AddressDetails__c</fullName>
    <label>Address Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/brf_mlcnt__c.field-meta.xml
<CustomField>
    <fullName>brf_mlcnt__c</fullName>
    <label>brf_mlcnt</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/custID__c.field-meta.xml
<CustomField>
    <fullName>custID__c</fullName>
    <externalId>true</externalId>
    <label>고객ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/din_mlcnt__c.field-meta.xml
<CustomField>
    <fullName>din_mlcnt__c</fullName>
    <label>din_mlcnt</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/dlv_agc_nm__c.field-meta.xml
<CustomField>
    <fullName>dlv_agc_nm__c</fullName>
    <label>dlv_agc_nm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dstfd_mtd_cd__c.field-meta.xml
<CustomField>
    <fullName>dstfd_mtd_cd__c</fullName>
    <label>dstfd_mtd_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
                <label>교실</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>교실+식당</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>식당</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ecof_fdr_us_rt__c.field-meta.xml
<CustomField>
    <fullName>ecof_fdr_us_rt__c</fullName>
    <label>ecof_fdr_us_rt</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/jrsdt_cido_eduofic_cd__c.field-meta.xml
<CustomField>
    <fullName>jrsdt_cido_eduofic_cd__c</fullName>
    <label>jrsdt_cido_eduofic_cd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100</fullName>
                <label>서울</label>
            </value>
            <value>
                <fullName>110</fullName>
                <label>경기</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>인천</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>강원도</label>
            </value>
            <value>
                <fullName>140</fullName>
                <label>대전</label>
            </value>
            <value>
                <fullName>150</fullName>
                <label>충남</label>
            </value>
            <value>
                <fullName>160</fullName>
                <label>충북</label>
            </value>
            <value>
                <fullName>170</fullName>
                <label>부산</label>
            </value>
            <value>
                <fullName>180</fullName>
                <label>대구</label>
            </value>
            <value>
                <fullName>190</fullName>
                <label>울산</label>
            </value>
            <value>
                <fullName>200</fullName>
                <label>경남</label>
            </value>
            <value>
                <fullName>210</fullName>
                <label>경북</label>
            </value>
            <value>
                <fullName>220</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>230</fullName>
                <label>전남</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>250</fullName>
                <label>제주</label>
            </value>
            <value>
                <fullName>세종</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jrsdt_gugun_eduofic_cd__c.field-meta.xml
<CustomField>
    <fullName>jrsdt_gugun_eduofic_cd__c</fullName>
    <label>jrsdt_gugun_eduofic_cd</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>jrsdt_cido_eduofic_cd__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1001</fullName>
                <label>강남(1001)</label>
            </value>
            <value>
                <fullName>1002</fullName>
                <label>강동</label>
            </value>
            <value>
                <fullName>1003</fullName>
                <label>강서</label>
            </value>
            <value>
                <fullName>1004</fullName>
                <label>남부(1004)</label>
            </value>
            <value>
                <fullName>1005</fullName>
                <label>동부(1005)</label>
            </value>
            <value>
                <fullName>1006</fullName>
                <label>동작</label>
            </value>
            <value>
                <fullName>1007</fullName>
                <label>북부(1007)</label>
            </value>
            <value>
                <fullName>1008</fullName>
                <label>서부(1008)</label>
            </value>
            <value>
                <fullName>1009</fullName>
                <label>성동</label>
            </value>
            <value>
                <fullName>1010</fullName>
                <label>성북</label>
            </value>
            <value>
                <fullName>1011</fullName>
                <label>중부</label>
            </value>
            <value>
                <fullName>1101</fullName>
                <label>가평</label>
            </value>
            <value>
                <fullName>1102</fullName>
                <label>고양</label>
            </value>
            <value>
                <fullName>1103</fullName>
                <label>광명</label>
            </value>
            <value>
                <fullName>1104</fullName>
                <label>광주하남</label>
            </value>
            <value>
                <fullName>1105</fullName>
                <label>군포의왕</label>
            </value>
            <value>
                <fullName>1106</fullName>
                <label>김포</label>
            </value>
            <value>
                <fullName>1107</fullName>
                <label>구리남양주</label>
            </value>
            <value>
                <fullName>1108</fullName>
                <label>동두천양주</label>
            </value>
            <value>
                <fullName>1109</fullName>
                <label>부천</label>
            </value>
            <value>
                <fullName>1110</fullName>
                <label>성남</label>
            </value>
            <value>
                <fullName>1111</fullName>
                <label>수원</label>
            </value>
            <value>
                <fullName>1112</fullName>
                <label>시흥</label>
            </value>
            <value>
                <fullName>1113</fullName>
                <label>안산</label>
            </value>
            <value>
                <fullName>1114</fullName>
                <label>안성</label>
            </value>
            <value>
                <fullName>1115</fullName>
                <label>안양과천</label>
            </value>
            <value>
                <fullName>1116</fullName>
                <label>양평</label>
            </value>
            <value>
                <fullName>1121</fullName>
                <label>이천</label>
            </value>
            <value>
                <fullName>1122</fullName>
                <label>파주</label>
            </value>
            <value>
                <fullName>1123</fullName>
                <label>평택</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/lnc_mlcnt__c.field-meta.xml
<CustomField>
    <fullName>lnc_mlcnt__c</fullName>
    <label>lnc_mlcnt</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/odd_txt__c.field-meta.xml
<CustomField>
    <fullName>odd_txt__c</fullName>
    <label>odd_txt</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/pmeal_cst__c.field-meta.xml
<CustomField>
    <fullName>pmeal_cst__c</fullName>
    <label>pmeal_cst</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sboil_us_brd_nm__c.field-meta.xml
<CustomField>
    <fullName>sboil_us_brd_nm__c</fullName>
    <label>sboil_us_brd_nm</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/schl_cust_div_cd__c.field-meta.xml
<CustomField>
    <fullName>schl_cust_div_cd__c</fullName>
    <label>schl_cust_div_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>초</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>중</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>고</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>대</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_bid_cycl_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_bid_cycl_cd__c</fullName>
    <label>sma_cust_bid_cycl_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1개월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2개월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3개월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4개월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5개월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6개월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>연간</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_bid_mtd_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_bid_mtd_cd__c</fullName>
    <label>sma_cust_bid_mtd_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>G2B</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>지명입찰</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>비교견적</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>수의</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>AT</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>단일업체</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_mng_frm_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_mng_frm_cd__c</fullName>
    <label>sma_cust_mng_frm_cd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>직영(대리점)</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>직영(직거래)</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>위탁</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_mng_grd_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_mng_grd_cd__c</fullName>
    <label>sma_cust_mng_grd_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
                <label>관리제외</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_SFDC_IFRESH_REG_ACCOUNT.cls
/**
 * @description       : I-FRESH SMA고객정보 전송 Class
 * @author            : admin
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : admin
**/
global without sharing class IF_SFDC_IFRESH_REG_ACCOUNT {
    @Future(Callout=true)
    public static void doSend(List<String> listTargetAccoutId, Set<Id> setUserId, Map<Id, String> mapCUD, Set<String> setTargetcustId) {
        System.debug('[IF_SFDC_IFRESH_REG_ACCOUNT] doSend !!!!!');
//        String strStatus = 'SUCCESS';
//        String strMessage = '성공';
//        DataWrapper objDataWrap = new DataWrapper();
        try {
            System.debug('setUserId :: ' + setUserId);
            Map<Id, User> mapUser = new Map<Id, User>([SELECT Id, EmployeeNumber FROM User WHERE Id IN :setUserId]);
            User objUser = [SELECT Id, EmployeeNumber FROM User WHERE Id = :UserInfo.getUserId()];
            String if_Id = 'IF_SFDC_IFRESH_REG_ACCOUNT';
            System.debug('if_Id =========>' + if_Id);
            List<Map<String, Object>> listJsonData = new List<Map<String, Object>>();
            Map<String, List<Map<String,Object>>> mapDataWrap = new Map<String, List<Map<String, Object>>>();
            IFUtil i = new IFUtil(if_Id);

            if (listTargetAccoutId != null) {
                List<Account> targetAccout = new List<Account>(
                [
                        SELECT custID__c, Name, sma_cust_bid_mtd_cd__c, sma_cust_bid_cycl_cd__c
                                , sma_cust_mng_frm_cd__c, dstfd_mtd_cd__c, brf_mlcnt__c, lnc_mlcnt__c, din_mlcnt__c
                                , schl_cust_div_cd__c, OwnerId, jrsdt_cido_eduofic_cd__c, jrsdt_gugun_eduofic_cd__c, dlv_agc_nm__c
                                , sma_cust_mng_grd_cd__c, sboil_us_brd_nm__c, ecof_fdr_us_rt__c, odd_txt__c, PostalCode__c, Address__c, AddressDetails__c
                                , pmeal_cst__c, Phone, CreatedById, CreatedDate, LastModifiedById, LastModifiedDate, LocationStateProvince__c, LocationState__c
                                ,tot_mlcnt__c
                        FROM Account
                        WHERE Id IN :listTargetAccoutId
                ]);
                System.debug('TargetAccount :: ' + targetAccout);


                for (Account obj : targetAccout) {
                    Map<String, Object> mapData = new Map<String, Object>();
                    if (mapCUD != null) {
                        String CUDCode = mapCUD.get(obj.Id);
                        System.debug('[IF_SFDC_IFRESH_REG_ACCOUNT] Upsert');
                        mapData.put('co_id', 'FW00');                //회사 ID : FW00으로 고정
                        mapData.put('sma_cust_bid_mtd_cd', obj.sma_cust_bid_mtd_cd__c <> null ? obj.sma_cust_bid_mtd_cd__c : ' ');       //SMA 고객 입찰 방법 코드
                        mapData.put('sma_cust_bid_cycl_cd', obj.sma_cust_bid_cycl_cd__c <> null ? obj.sma_cust_bid_cycl_cd__c : ' ');       //SMA 고객 입찰 주기 코드
                        mapData.put('sma_cust_mng_frm_cd', obj.sma_cust_mng_frm_cd__c <> null ? obj.sma_cust_mng_frm_cd__c : ' ');       //SMA 고객 운영 형태 코드
                        mapData.put('dstfd_mtd_cd', obj.dstfd_mtd_cd__c <> null ? obj.dstfd_mtd_cd__c : ' ');       //배식 방법 코드
                        mapData.put('tot_mlcnt', obj.tot_mlcnt__c <> null ? obj.tot_mlcnt__c : 0);       //총 식수
                        mapData.put('brf_mlcnt', obj.brf_mlcnt__c <> null ? obj.brf_mlcnt__c : 0);       //조식 식수
                        mapData.put('lnc_mlcnt', obj.lnc_mlcnt__c <> null ? obj.lnc_mlcnt__c : 0);       //중식 식수
                        mapData.put('din_mlcnt', obj.din_mlcnt__c <> null ? obj.din_mlcnt__c : 0);       //석식 식수
                        mapData.put('schl_cust_div_cd', obj.schl_cust_div_cd__c <> null ? obj.schl_cust_div_cd__c : ' ');       //학교 고객 구분 코드
                        mapData.put('sma_crg_sman_id', mapUser.get(obj.OwnerId).EmployeeNumber);       //SMA 담당 영업사원 ID
                        mapData.put('jrsdt_cido_eduofic_cd', obj.jrsdt_cido_eduofic_cd__c <> null ? obj.jrsdt_cido_eduofic_cd__c : ' ');       //관할 시도 교육청 코드
                        mapData.put('jrsdt_gugun_eduofic_cd', obj.jrsdt_gugun_eduofic_cd__c <> null ? obj.jrsdt_gugun_eduofic_cd__c : ' ');       //관할 구군 교육청 코드
                        mapData.put('dlv_agc_nm',obj.dlv_agc_nm__c);       //납품 대리점 명
                        mapData.put('sma_cust_mng_grd_cd', obj.sma_cust_mng_grd_cd__c <> null ? obj.sma_cust_mng_grd_cd__c : ' ');       //SMA 고객 관리 등급 코드
                        mapData.put('sboil_us_brd_nm', obj.sboil_us_brd_nm__c);       //대두유 사용 브랜드 명
                        mapData.put('ecof_fdr_us_rt', obj.ecof_fdr_us_rt__c <> null ? obj.ecof_fdr_us_rt__c : 0);       //친환경 식자재 사용 률
                        mapData.put('odd_txt', obj.odd_txt__c <> null ? obj.odd_txt__c : ' ');       //특이 내용
                        mapData.put('cust_zip', obj.PostalCode__c <> null ? obj.PostalCode__c : ' ');       //고객 우편번호
                        mapData.put('cust_addr', obj.Address__c <> null ? obj.Address__c : ' ');       //고객 주소
                        mapData.put('cust_dtl_addr', obj.AddressDetails__c <> null ? obj.AddressDetails__c : ' ');       //고객 상세 주소
                        mapData.put('pmeal_cst', obj.pmeal_cst__c <> null ? obj.pmeal_cst__c : 0);       //급식 비
                        mapData.put('cust_tel_no', obj.Phone <> null ? obj.Phone : ' ');       //고객 전화 번호
                        if ( CUDCode == 'C'){
                            mapData.put('regr_id', mapUser.get(obj.CreatedById).EmployeeNumber <> null ? mapUser.get(obj.CreatedById).EmployeeNumber : ' ');       //등록자 ID
                            mapData.put('reg_dt', obj.CreatedDate);       //등록 일시
                        }
                        mapData.put('updr_id', objUser.EmployeeNumber <> null ? objUser.EmployeeNumber : ' ');       //수정자 ID
                        mapData.put('upd_dt', obj.LastModifiedDate);       //수정 일시
                        mapData.put('cido_cd', obj.LocationStateProvince__c <> null ? obj.LocationStateProvince__c : ' ');       //시도 코드
                        mapData.put('gugun_cd', obj.LocationState__c <> null ? obj.LocationState__c : ' ');       //구군 코드
//                        mapData.put('gugun_cd', obj.oven_poss_yn__c);       //오븐 보유 여부
//                        mapData.put('gugun_cd', obj.crt_wrt_cycl_bd__c);       //식단 작성주기 내역
                        mapData.put('system_type_cd', 'IF1004');     //적용 구분 코드
                        mapData.put('opcode', 'CR017');     //적용 구분 코드
                        mapData.put('sma_cust_nm', obj.Name);        //SMA 고객 명
                        mapData.put('cust_id', obj.custID__c);       //고객 ID
                        mapData.put('APLY_DIV_CD', CUDCode);     //적용 구분 코드
                    }
                    listJsonData.add(mapData);
                }
            } else {
                for (String custId : setTargetcustId) {
                    Map<String, Object> mapData = new Map<String, Object>();
                    System.debug('[IF_SFDC_IFRESH_REG_ACCOUNT] Delete');
                    mapData.put('cust_id', custId);       //고객 ID
                    mapData.put('APLY_DIV_CD', 'D');
                    listJsonData.add(mapData);
                }
            }

            mapDataWrap.put('ds_list', listJsonData);
            String strReqJSON = JSON.serialize(mapDataWrap);
            System.debug('============================> strReqJSON : ' + strReqJSON);

            HttpResponse response = i.webCallout(strReqJSON, true);
            System.debug('response.getStatusCode() =======> ' + response.getStatusCode());

            String responseBody = response.getBody();
            System.debug('responseBody =======> ' + responseBody);

            Map<String, Object> mapResponse = (Map<String, Object>) JSON.deserializeUntyped(responseBody);
            System.debug('mapResponse =======> ' + mapResponse);
            String strCode = String.valueOf(mapResponse.get('err_cd'));
            if (strCode.equals('9999') && mapResponse.get('err_msg_ctt') != null) {
                if (mapResponse.get('err_msg_ctt') != '') {
                    String jsonErrMsgCtt = JSON.serialize(mapResponse.get('err_msg_ctt'));
                    List<Map<String,String>> mapErrMsgCtt = (List<Map<String,String>>) JSON.deserialize(jsonErrMsgCtt, List<Map<String,String>>.class);
                    System.debug(mapErrMsgCtt);
                    //Error msg 처리
                }
//                System.debug('err_msg_ctt :: ' + mapResponse.get('err_msg_ctt'));
            }
            System.debug('err_msg_ctt :: ' + mapResponse.get('err_msg_ctt'));
        } catch (Exception e) {
//            strStatus = 'ERROR';
//            strMessage = e.getMessage() + ' Line : ' + e.getLineNumber();
            System.debug('strMessage ===> ' + e.getMessage() + ' Line : ' + e.getLineNumber());
        }

//        objDataWrap.strStatus = strStatus;
//        objDataWrap.strMessage = strMessage;
//        return objDataWrap;
    }

    public class DataWrapper {
        public String strStatus { get; set; }
        public String strMessage { get; set; }
    }
}