force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AddressDetails__c.field-meta.xml
<CustomField>
    <fullName>AddressDetails__c</fullName>
    <label>Address Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/dstfd_mtd_cd__c.field-meta.xml
<CustomField>
    <fullName>dstfd_mtd_cd__c</fullName>
    <label>dstfd_mtd_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
                <label>교실</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>교실+식당</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>식당</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jrsdt_cido_eduofic_cd__c.field-meta.xml
<CustomField>
    <fullName>jrsdt_cido_eduofic_cd__c</fullName>
    <label>jrsdt_cido_eduofic_cd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100</fullName>
                <label>서울</label>
            </value>
            <value>
                <fullName>110</fullName>
                <label>경기</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>인천</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>강원도</label>
            </value>
            <value>
                <fullName>140</fullName>
                <label>대전</label>
            </value>
            <value>
                <fullName>150</fullName>
                <label>충남</label>
            </value>
            <value>
                <fullName>160</fullName>
                <label>충북</label>
            </value>
            <value>
                <fullName>170</fullName>
                <label>부산</label>
            </value>
            <value>
                <fullName>180</fullName>
                <label>대구</label>
            </value>
            <value>
                <fullName>190</fullName>
                <label>울산</label>
            </value>
            <value>
                <fullName>200</fullName>
                <label>경남</label>
            </value>
            <value>
                <fullName>210</fullName>
                <label>경북</label>
            </value>
            <value>
                <fullName>220</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>230</fullName>
                <label>전남</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>250</fullName>
                <label>제주</label>
            </value>
            <value>
                <fullName>세종</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LocationState__c.field-meta.xml
<CustomField>
    <fullName>LocationState__c</fullName>
    <label>LocationState</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LocationStateProvince__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>41220</fullName>
                <label>경기 평택시</label>
            </value>
            <value>
                <fullName>41250</fullName>
                <label>경기 동두천시</label>
            </value>
            <value>
                <fullName>41270</fullName>
                <label>경기 안산시</label>
            </value>
            <value>
                <fullName>41280</fullName>
                <label>경기 고양시</label>
            </value>
            <value>
                <fullName>41290</fullName>
                <label>경기 과천시</label>
            </value>
            <value>
                <fullName>41310</fullName>
                <label>경기 구리시</label>
            </value>
            <value>
                <fullName>41360</fullName>
                <label>경기 남양주시</label>
            </value>
            <value>
                <fullName>41370</fullName>
                <label>경기 오산시</label>
            </value>
            <value>
                <fullName>41390</fullName>
                <label>경기 시흥시</label>
            </value>
            <value>
                <fullName>41410</fullName>
                <label>경기 군포시</label>
            </value>
            <value>
                <fullName>41430</fullName>
                <label>경기 의왕시</label>
            </value>
            <value>
                <fullName>41450</fullName>
                <label>경기 하남시</label>
            </value>
            <value>
                <fullName>41460</fullName>
                <label>경기 용인시</label>
            </value>
            <value>
                <fullName>41480</fullName>
                <label>경기 파주시</label>
            </value>
            <value>
                <fullName>41500</fullName>
                <label>경기 이천시</label>
            </value>
            <value>
                <fullName>46810</fullName>
                <label>전남 강진군</label>
            </value>
            <value>
                <fullName>46820</fullName>
                <label>전남 해남군</label>
            </value>
            <value>
                <fullName>46830</fullName>
                <label>전남 영암군</label>
            </value>
            <value>
                <fullName>46840</fullName>
                <label>전남 무안군</label>
            </value>
            <value>
                <fullName>46860</fullName>
                <label>전남 함평군</label>
            </value>
            <value>
                <fullName>46870</fullName>
                <label>전남 영광군</label>
            </value>
            <value>
                <fullName>46880</fullName>
                <label>전남 장성군</label>
            </value>
            <value>
                <fullName>46890</fullName>
                <label>전남 완도군</label>
            </value>
            <value>
                <fullName>46900</fullName>
                <label>전남 진도군</label>
            </value>
            <value>
                <fullName>46910</fullName>
                <label>전남 신안군</label>
            </value>
            <value>
                <fullName>45110</fullName>
                <label>전북 전주시</label>
            </value>
            <value>
                <fullName>45130</fullName>
                <label>전북 군산시</label>
            </value>
            <value>
                <fullName>45140</fullName>
                <label>전북 익산시</label>
            </value>
            <value>
                <fullName>45180</fullName>
                <label>전북 정읍시</label>
            </value>
            <value>
                <fullName>45190</fullName>
                <label>전북 남원시</label>
            </value>
            <value>
                <fullName>11560</fullName>
                <label>서울 영등포구</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LocationStateProvince__c.field-meta.xml
<CustomField>
    <fullName>LocationStateProvince__c</fullName>
    <label>LocationState/Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
                <label>서울</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>인천</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>경기</label>
            </value>
            <value>
                <fullName>42</fullName>
                <label>강원</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>부산</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>대구</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>울산</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>경북</label>
            </value>
            <value>
                <fullName>48</fullName>
                <label>경남</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>대전</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>충남</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>세종</label>
            </value>
            <value>
                <fullName>43</fullName>
                <label>충북</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>전남</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>제주</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/schl_cust_div_cd__c.field-meta.xml
<CustomField>
    <fullName>schl_cust_div_cd__c</fullName>
    <label>schl_cust_div_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
                <label>초</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>중</label>
            </value>
            <value>
                <fullName>H</fullName>
                <label>고</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>대</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_bid_cycl_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_bid_cycl_cd__c</fullName>
    <label>sma_cust_bid_cycl_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1개월</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2개월</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3개월</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4개월</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5개월</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6개월</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>연간</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_bid_mtd_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_bid_mtd_cd__c</fullName>
    <label>sma_cust_bid_mtd_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>G2B</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>지명입찰</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>비교견적</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>수의</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>AT</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>단일업체</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_mng_frm_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_mng_frm_cd__c</fullName>
    <label>sma_cust_mng_frm_cd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>직영(대리점)</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>직영(직거래)</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>위탁</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>기타</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SchoolAgency.recordType-meta.xml
<RecordType>
    <fullName>SchoolAgency</fullName>
    <active>true</active>
    <label>SchoolAgency</label>
</RecordType>

force-app/main/default/classes/IFN_Util_TEST.cls
/**
 * @Class : IFN_Util_TEST.cls
 * @group Framework : 
 * @Author :  조일근 
 * @Date : 2023.09.06
 * @Version : 1.0
 * @Description :
 * @Modified :
 * ----------------------------------------------
 *  NO | Date       | Modifier       | Description
 * ----------------------------------------------
 *  1. | 2023.09.06 | 조일근  | 최초작성
 * */
@isTest
public without sharing class IFN_Util_TEST {

    @TestSetup
    static void makeData(){
        Account objAcc = TestObjectCreator.objSchoolAccount;
        objAcc.Phone = '01012341234';
        objAcc.Address__c = 'Test Address';
        objAcc.AddressDetails__c = 'test';            
        objAcc.PostalCode__c = '12345';
        objAcc.sma_cust_bid_mtd_cd__c = 'A';
        objAcc.sma_cust_bid_cycl_cd__c = '1';
        objAcc.sma_cust_mng_frm_cd__c = '1';
        objAcc.dstfd_mtd_cd__c = '11';
        objAcc.LocationStateProvince__c = '11';
        objAcc.LocationState__c = '11560';
        objAcc.schl_cust_div_cd__c = 'E';
        objAcc.jrsdt_cido_eduofic_cd__c = '100';
        objAcc.jrsdt_gugun_eduofic_cd__c = '1007';
        objAcc.sma_cust_mng_grd_cd__c = 'C';
        objAcc.odd_txt__c = 'TEST';
        objAcc.sma_cust_mng_grd_cd__c = 'A';

        insert objAcc;
    }

    public static testMethod void testMethod1() {
        Test.startTest();

        Datetime dt = System.now();
        Double db1 = 100.1;
        Double db2 = 100.1;
        Double db3 = 100.1;

        IFN_Util.getRecordTypeId('Account', 'SchoolAgency');
        IFN_Util.getSObjectQuery('Account', 'AccountTracking');
        IFN_Util.replaceText('test1');
        IFN_Util.convertCIELabtoRGB255(db1, db2, db3);
        IFN_Util.trimDatetimeNum(dt);
        IFN_Util.trimString('test', 2);
        IFN_Util.trimString('test', 5);
        IFN_Util.convertMinus('0000-');
        IFN_Util.convertMinus('');
        IFN_Util.convertDate('20200202');
        IFN_Util.convertDateTime('20200202000000');
        IFN_Util.datetimeCheck('20200202000000');
        IFN_Util.dateSumTime('20200202', '000000');
        IFN_Util.getListDividedByByteSize('TEST', 1);
        IFN_Util.converDateTimeToStrFormat(Datetime.now());
        IFN_Util.converDateTimeToStrFormat(Datetime.now(),'yyyy-MM-dd');
        IFN_Util.converDateToStrFormat(Datetime.now());
        IFN_Util.converDateToStrFormat(Datetime.now(),'yyyy-MM-dd');        
        IFN_Util.converStringToNumber('0010907597');
        IFN_Util.converStringToNumber(null);
        IFN_Util.searchText('All',new Set<String>{'123'});
        IFN_Util.minusCheck(null);
        IFN_Util.minusCheck('032131-');
        IFN_Util.convertDateAddTime(Date.today(), Time.newInstance(0, 0, 0, 0));
        IFN_Util.convertDateTimeGMT('','');
        IFN_Util.convertDateTimeGMT('20211011','');
        IFN_Util.convertDateTimeGMT('20211011','12');
        IFN_Util.convertDateTimeGMT('20211011','1200');
        IFN_Util.convertDateTimeGMT('20211011','120000');
        IFN_Util.convertTime('120000');
        IFN_Util.convertTime('120000',6);
        IFN_Util.NextBatchCheck('IF_LCHC_EmployeeConvertBatch');
        IFN_Util.NextScheduleCheck('IF_ERP_ProductHierarchySearchQueueable');
        


        Test.stopTest();
    }
}