force-app/main/default/objects/Account/fields/BusinessConditions__c.field-meta.xml
<CustomField>
    <fullName>BusinessConditions__c</fullName>
    <label>Business Conditions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>CustomerType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C01</fullName>
                <label>본점</label>
            </value>
            <value>
                <fullName>C02</fullName>
                <label>판매처</label>
            </value>
            <value>
                <fullName>C03</fullName>
                <label>관리처-배송</label>
            </value>
            <value>
                <fullName>C04</fullName>
                <label>관리처-분할</label>
            </value>
            <value>
                <fullName>C05</fullName>
                <label>점포</label>
            </value>
            <value>
                <fullName>C06</fullName>
                <label>사이트</label>
            </value>
            <value>
                <fullName>C07</fullName>
                <label>단체급식고객</label>
            </value>
            <value>
                <fullName>C08</fullName>
                <label>회계고객</label>
            </value>
            <value>
                <fullName>C09</fullName>
                <label>물류센터</label>
            </value>
            <value>
                <fullName>C10</fullName>
                <label>해외고객</label>
            </value>
            <value>
                <fullName>C11</fullName>
                <label>관리처-2차</label>
            </value>
            <value>
                <fullName>C12</fullName>
                <label>금융고객</label>
            </value>
            <value>
                <fullName>C13</fullName>
                <label>자가소비부서</label>
            </value>
            <value>
                <fullName>C14</fullName>
                <label>경영계획부서</label>
            </value>
            <value>
                <fullName>C16</fullName>
                <label>해외고객-분할</label>
            </value>
            <value>
                <fullName>C17</fullName>
                <label>해외고객-배송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LegalStatus__c.field-meta.xml
<CustomField>
    <fullName>LegalStatus__c</fullName>
    <label>LegalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>개인</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>영리법인</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>비영리법인</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RepresentativeBirthDate__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeBirthDate__c</fullName>
    <label>Representative BirthDate</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CJFW_MDMBulkUpdateHeadController_test.cls
/**
 * @description       : 
 * @author            : hyeeun.song@dkbmc.com
 * @group             : 
 * @last modified on  : 10-05-2023
 * @last modified by  : hyeeun.song@dkbmc.com
**/
@isTest
private class CJFW_MDMBulkUpdateHeadController_test {
    
    static List<CJFW_MDMBulkUpdateHeadController.MDMRequest> customerList = new List<CJFW_MDMBulkUpdateHeadController.MDMRequest>();
    
    @TestSetup
    static void setData() {
        
        List<Account> accList = new List<Account>();
        
        // 본점 C01, 판매처 C02, 관리처 C03, C04, C11
        for(Integer i = 0; i < 100; i++) {
            Account acc = new Account();
            acc.Name = '치킨집';
            // acc.CustomerType__c = 'C01';
            acc.CustomerId__c = '105' + String.valueOf(i);
            acc.LegalStatus__c = 'A';
            acc.RepresentativeName__c = '대표자';
            acc.RepresentativeBirthDate__c = '123456';
            acc.BusinessConditions__c = '주점';
            acc.RecordTypeId = '0120w000001dMzHAAU';
            accList.add(acc);
        }

        System.debug('accList => ' + accList);

        insert accList;

    }

    // 본점 Test
    @isTest
    static void updateTest1() {

        getList();

        System.debug('customerList => ' + customerList);

        Test.startTest();
        // Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());

        CJFW_MDMBulkUpdateHeadController.SaveResult result = CJFW_MDMBulkUpdateHeadController.doSave(customerList, '본점');

        System.debug('본점 result => ' + result);
        System.Assert(result.status == 'S', '본점 성공');

        Test.stopTest();

    }

    // 판매처 Test
    @isTest
    static void updateTest2() {

        getList();

        System.debug('customerList => ' + customerList);

        Test.startTest();

        CJFW_MDMBulkUpdateHeadController.SaveResult result = CJFW_MDMBulkUpdateHeadController.doSave(customerList, '판매처');

        System.debug('판매처 result => ' + result);
        System.Assert(result.status == 'S', '판매처 성공');

        Test.stopTest();

    }

    // 관리처 Test
    @isTest
    static void updateTest3() {

        getList();

        System.debug('customerList => ' + customerList);

        Test.startTest();

        CJFW_MDMBulkUpdateHeadController.SaveResult result = CJFW_MDMBulkUpdateHeadController.doSave(customerList, '관리처');

        System.debug('관리처 result => ' + result);
        System.Assert(result.status == 'S', '관리처 성공');

        Test.stopTest();

    }

    // 공통 부분
    @isTest
    static void getList() {

        for(Integer i = 0; i < 100; i++) {
            CJFW_MDMBulkUpdateHeadController.MDMRequest cus = new CJFW_MDMBulkUpdateHeadController.MDMRequest();
            cus.PV_NAME1 = '피자집';
            cus.PV_KUNNR = '105' + String.valueOf(i);
            cus.PV_GFORM = 'B';
            cus.PV_J_1KFREPRE = '대표인';
            cus.PV_STCD1 = '789101';
            cus.PV_J_1KFTBUS = '음식점';
            customerList.add(cus);
        }

    }

    // // Mock1 : SUCCESS
    // private class HttpCalloutSuccessMock implements HttpCalloutMock {
    //     public HTTPResponse respond(HTTPRequest request) {
    //         HttpResponse response = newResponse(200);

    //         return response;
    //     }
    // }

    // private static HTTPResponse newResponse(Integer statusCode) {
    //     HttpResponse response = new HttpResponse();
    //     response.setStatusCode(statusCode);
    //     response.setBody('{"ERR_CD":"S","ERR_MSG_CTT":"","DS_MASTER":{"data":[{"OIL_UNITP":274,"BASE_MON":"202211","COM_CD":"FW00","OIL_TYPE_CD":"1","DPRC_UNITP":101}],"SVC_ERR_MSG_TEXT":"","ErrorCode":0}}');

    //     return response;
    // }

}