force-app/main/default/objects/Account/fields/CompanyRegisterNumber__c.field-meta.xml
<CustomField>
    <fullName>CompanyRegisterNumber__c</fullName>
    <description>기업의 사업자 등록번호</description>
    <label>Company Register Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerStatus__c.field-meta.xml
<CustomField>
    <fullName>CustomerStatus__c</fullName>
    <label>CustomerStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>신규점(Open)</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>기존점(정상처)</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>기존점(무회입처)</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>기존점(무매출처)</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>기존점(출고정지)</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>중단점</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>기존점(무매출/무회입)</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>기존점(심사관리)</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>중단점(회입관리)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>CustomerType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C01</fullName>
                <label>본점</label>
            </value>
            <value>
                <fullName>C02</fullName>
                <label>판매처</label>
            </value>
            <value>
                <fullName>C03</fullName>
                <label>관리처-배송</label>
            </value>
            <value>
                <fullName>C04</fullName>
                <label>관리처-분할</label>
            </value>
            <value>
                <fullName>C05</fullName>
                <label>점포</label>
            </value>
            <value>
                <fullName>C06</fullName>
                <label>사이트</label>
            </value>
            <value>
                <fullName>C07</fullName>
                <label>단체급식고객</label>
            </value>
            <value>
                <fullName>C08</fullName>
                <label>회계고객</label>
            </value>
            <value>
                <fullName>C09</fullName>
                <label>물류센터</label>
            </value>
            <value>
                <fullName>C10</fullName>
                <label>해외고객</label>
            </value>
            <value>
                <fullName>C11</fullName>
                <label>관리처-2차</label>
            </value>
            <value>
                <fullName>C12</fullName>
                <label>금융고객</label>
            </value>
            <value>
                <fullName>C13</fullName>
                <label>자가소비부서</label>
            </value>
            <value>
                <fullName>C14</fullName>
                <label>경영계획부서</label>
            </value>
            <value>
                <fullName>C16</fullName>
                <label>해외고객-분할</label>
            </value>
            <value>
                <fullName>C17</fullName>
                <label>해외고객-배송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PIC__c.field-meta.xml
<CustomField>
    <fullName>PIC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>MDM 담당자</description>
    <label>PIC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PICCode__c.field-meta.xml
<CustomField>
    <fullName>PICCode__c</fullName>
    <description>MDM 담당자코드</description>
    <label>PICCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/searchKey__c.field-meta.xml
<CustomField>
    <fullName>searchKey__c</fullName>
    <description>고객사 검색을 위해 고객사ID + 고객사명 조합한 Key값을 생성</description>
    <formula>&quot;[&quot;+CustomerID__c+&quot;]&quot; + Name</formula>
    <label>searchKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountGetInfoController.cls
/**
* class 설명 : cjfwAccountSearchModal cmp 에서 호출되는  Controller 
*
*@group  프로젝트 내부에서 사용하는 업무 그룹 작성
*@author eunyoung.choi
*@since 2023-07-31  내용 작성
*/
public with sharing class AccountGetInfoController {

    /*
    searchKey - 고객사명 or 고객사코드 
    customerType - 고객사 유형 : 본점 or 판매처 or 관리처
    */
    @AuraEnabled(cacheable=true)
    public static Account getAccInfo(String searchKey , String customerType){
         system.debug('AccountGetInfoController #getAccInfo => ' );
         Account accList = [SELECT id ,CustomerID__c, Name , CompanyRegisterNumber__c, CustomerStatus__c, PIC__r.Name, PICCode__c 
         FROM Account 
         WHERE searchKey__c  LIKE :'%'+searchKey+'%' AND toLabel(CustomerType__c) =: customerType];
         
         system.debug('return => ' + accList);
        return accList;
    }
}