force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerStatus__c.field-meta.xml
<CustomField>
    <fullName>CustomerStatus__c</fullName>
    <label>CustomerStatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>신규점(Open)</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>기존점(정상처)</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>기존점(무회입처)</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>기존점(무매출처)</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>기존점(출고정지)</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>중단점</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>기존점(무매출/무회입)</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>기존점(심사관리)</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>중단점(회입관리)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>CustomerType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C01</fullName>
                <label>본점</label>
            </value>
            <value>
                <fullName>C02</fullName>
                <label>판매처</label>
            </value>
            <value>
                <fullName>C03</fullName>
                <label>관리처-배송</label>
            </value>
            <value>
                <fullName>C04</fullName>
                <label>관리처-분할</label>
            </value>
            <value>
                <fullName>C05</fullName>
                <label>점포</label>
            </value>
            <value>
                <fullName>C06</fullName>
                <label>사이트</label>
            </value>
            <value>
                <fullName>C07</fullName>
                <label>단체급식고객</label>
            </value>
            <value>
                <fullName>C08</fullName>
                <label>회계고객</label>
            </value>
            <value>
                <fullName>C09</fullName>
                <label>물류센터</label>
            </value>
            <value>
                <fullName>C10</fullName>
                <label>해외고객</label>
            </value>
            <value>
                <fullName>C11</fullName>
                <label>관리처-2차</label>
            </value>
            <value>
                <fullName>C12</fullName>
                <label>금융고객</label>
            </value>
            <value>
                <fullName>C13</fullName>
                <label>자가소비부서</label>
            </value>
            <value>
                <fullName>C14</fullName>
                <label>경영계획부서</label>
            </value>
            <value>
                <fullName>C16</fullName>
                <label>해외고객-분할</label>
            </value>
            <value>
                <fullName>C17</fullName>
                <label>해외고객-배송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/InitialDeliveryShare__c.field-meta.xml
<CustomField>
    <fullName>InitialDeliveryShare__c</fullName>
    <label>InitialDeliveryShare</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsAffiliatedcompanyYN__c.field-meta.xml
<CustomField>
    <fullName>IsAffiliatedcompanyYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAffiliatedcompanyYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsBusinessPlaceKey__c.field-meta.xml
<CustomField>
    <fullName>IsBusinessPlaceKey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBusinessPlaceKey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsFaceToFaceInspectionStatus__c.field-meta.xml
<CustomField>
    <fullName>IsFaceToFaceInspectionStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MDM 대면검수여부</description>
    <label>IsFaceToFaceInspectionStatus</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsHeadShopUseYN__c.field-meta.xml
<CustomField>
    <fullName>IsHeadShopUseYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsHeadShopUseYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsInitialDeliveryFTFInspection__c.field-meta.xml
<CustomField>
    <fullName>IsInitialDeliveryFTFInspection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInitialDeliveryFTFInspection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsPrintVirtualAccount__c.field-meta.xml
<CustomField>
    <fullName>IsPrintVirtualAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MDM 가상계좌 출력 제외</description>
    <label>IsPrintVirtualAccount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/KXOTD__c.field-meta.xml
<CustomField>
    <fullName>KXOTD__c</fullName>
    <label>KXOTD</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PV_BLCKYN__c.field-meta.xml
<CustomField>
    <fullName>PV_BLCKYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_BLCKYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesForm__c.field-meta.xml
<CustomField>
    <fullName>SalesForm__c</fullName>
    <label>SalesForm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>일반영업</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>계약영업</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>구매대행</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/MDMReferenceCode__c.object-meta.xml
<CustomObject>
    <label>MDM 참조코드</label>
    <nameField>
        <label>MDMReferenceCode Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMReferenceCode__c/fields/CODE__c.field-meta.xml
<CustomField>
    <fullName>CODE__c</fullName>
    <externalId>true</externalId>
    <label>CODE</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/GROUPID__c.field-meta.xml
<CustomField>
    <fullName>GROUPID__c</fullName>
    <externalId>true</externalId>
    <label>GROUPID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestContact__c/MDMRegRequestContact__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 요청 담당자 정보</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomerContact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMRegRequestContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>MDMRegRequestContact</relationshipLabel>
    <relationshipName>MDMRegRequestContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestContact__c/fields/MDMRegRequestCustomer__c.field-meta.xml
<CustomField>
    <fullName>MDMRegRequestCustomer__c</fullName>
    <label>MDMRegRequestCustomer</label>
    <referenceTo>MDMRegRequestCustomer__c</referenceTo>
    <relationshipLabel>MDMRegRequestContact</relationshipLabel>
    <relationshipName>MDMRegRequestContact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestContact__c/fields/PV_KNVKGB__c.field-meta.xml
<CustomField>
    <fullName>PV_KNVKGB__c</fullName>
    <label>PV_KNVKGB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A01</fullName>
                <label>회계 담당자</label>
            </value>
            <value>
                <fullName>A02</fullName>
                <label>검수 담당자</label>
            </value>
            <value>
                <fullName>A03</fullName>
                <label>구매 담당자</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/MDMRegRequestCustomer__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 및 수정 요청</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_BLCKYN__c.field-meta.xml
<CustomField>
    <fullName>PV_BLCKYN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용중지</description>
    <label>PV_BLCKYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_BUSAB__c.field-meta.xml
<CustomField>
    <fullName>PV_BUSAB__c</fullName>
    <label>PV_BUSAB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>일반영업</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>계약영업</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>구매대행</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_EXAMYN__c.field-meta.xml
<CustomField>
    <fullName>PV_EXAMYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_EXAMYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_FDINFO__c.field-meta.xml
<CustomField>
    <fullName>PV_FDINFO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_FDINFO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_HDOFFICEYN__c.field-meta.xml
<CustomField>
    <fullName>PV_HDOFFICEYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_HDOFFICEYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_ISFDFTF__c.field-meta.xml
<CustomField>
    <fullName>PV_ISFDFTF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_ISFDFTF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_KEYYN__c.field-meta.xml
<CustomField>
    <fullName>PV_KEYYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_KEYYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_KXOTD__c.field-meta.xml
<CustomField>
    <fullName>PV_KXOTD__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_KXOTD</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_NAME1__c.field-meta.xml
<CustomField>
    <fullName>PV_NAME1__c</fullName>
    <label>PV_NAME1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_SUBSIDIARYYN__c.field-meta.xml
<CustomField>
    <fullName>PV_SUBSIDIARYYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_SUBSIDIARYYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/PV_VACCPRTEXCYN__c.field-meta.xml
<CustomField>
    <fullName>PV_VACCPRTEXCYN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PV_VACCPRTEXCYN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>0821추가
어떤 타입(생성, 수정, 중단)의 요청을 MDM으로 보내는지 알기 위해 추가</description>
    <label>RequestType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>stop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CJFW_MDMBulkUpdateMAController.cls
/**
 * @description       : 
 * @author            : hyeeun.song@dkbmc.com
 * @group             : 
 * @last modified on  : 11-06-2023
 * @last modified by  : hyeeun.song@dkbmc.com
**/
public with sharing class CJFW_MDMBulkUpdateMAController {
    
    /**
    * Save 버튼을 클릭 했을 때 호출
    * 
    * @params mdmContacts : 화면 mdmContact 데이터
    * 
    */
    @AuraEnabled
    public static SaveResult doSave(List<MDMRegRequestContact__c> mdmContacts, String recordId) {

        system.debug('# CJFW_MDMBulkCreateMAController >>> doSave ');

        SaveResult saveResult = new SaveResult();
        system.debug('>>>doSave # mdmContacts ' + JSON.serialize(mdmContacts));
        system.debug('>>>doSave # recordId ' + recordId);

        List<MDMRegRequestContact__c> contactList = new List<MDMRegRequestContact__c>();

        // 각종 ID 필요한 MDMReferenceCode__c 조회해서 Id값 가지고 오기
        Set<String> codeSet = new Set<String>();
        for(MDMRegRequestContact__c con : mdmContacts){
            String upperCode = con.PV_KNVKGB__c;
            codeSet.add(upperCode.toUpperCase());
            System.debug('# upperCode => ' + upperCode);
            codeSet.remove(null);
        }

        System.debug('# codeSet => ' + codeSet);
        
        List<MDMReferenceCode__c> referenceCodeList = [SELECT Id, Name, Code__c FROM MDMReferenceCode__c WHERE code__c = :codeSet AND GROUPID__c = 'KNVKGB'];

        System.debug('# referenceCodeList => ' + referenceCodeList);

        // Key : code , value : Id
        Map<String, String> codeToIdMap = new Map<String, String>();
        for(MDMReferenceCode__c mdmCode :referenceCodeList){
            codeToIdMap.put(mdmCode.Code__c, mdmCode.Id);
        }

        System.debug('# codeToIdMap => ' + codeToIdMap);

        // 받아 온 CustomerId로 MDM 혹은 Account로부터 Id 가지고 오기
        Set<String> idSet = new Set<String>();
        for(MDMRegRequestContact__c con : mdmContacts){
            idSet.add(con.MDMRegRequestCustomer__c);
            idSet.remove(null);
        }

        // Key : code , value : Id
        Map<String, String> kunnrToIdMap = new Map<String, String>();

        // Key : code , value : Id
        Map<String, String> newMDMToIdMap = new Map<String, String>();

        if(recordId != null) {
            
            List<MDMRegRequestCustomer__c> customerList = [SELECT Id, PV_KUNNR__c FROM MDMRegRequestCustomer__c WHERE PV_KUNNR__c = :idSet AND MDMRegRequestBulkCustomer__c = :recordId];

            System.debug('# <MDM> customerList => ' + customerList);
    
            for(MDMRegRequestCustomer__c cus : customerList){
                kunnrToIdMap.put(cus.PV_KUNNR__c, cus.Id);
            }
    
            System.debug('# kunnrToIdMap => ' + kunnrToIdMap);

        } else {

            List<Account> customerList = [SELECT Id, Name, CustomerId__c, CustomerType__c, SalesForm__c, CustomerStatus__c, PV_BLCKYN__c, IsHeadShopUseYN__c, IsAffiliatedcompanyYN__c, IsPrintVirtualAccount__c, IsFaceToFaceInspectionStatus__c, IsInitialDeliveryFTFInspection__c, IsBusinessPlaceKey__c, InitialDeliveryShare__c, KXOTD__c FROM Account WHERE CustomerId__c = :idSet];

            System.debug('# <Acc> customerList => ' + customerList);

            // MDM 요청 insert할 객체들 담기
            List<MDMRegRequestCustomer__c> mdmList = new List<MDMRegRequestCustomer__c>();

            MDMRegRequestBulkCustomer__c mdmRequestbulk = new MDMRegRequestBulkCustomer__c();

            String bulkName = customerList[0].Name;
            mdmRequestbulk.RequestType__c = 'Edit';
            
            mdmRequestbulk.Name = bulkName + ' 외 ' + (customerList.size() -1) + '건';

            insert mdmRequestbulk;
            
            for(Account acc : customerList) {

                MDMRegRequestCustomer__c customer = new MDMRegRequestCustomer__c();

                String recordIdEx = null;
                List<String> managementList = new List<String>{'C03', 'C04', 'C11'};

                if(acc.CustomerType__c == 'C01') {
                    recordIdEx = Schema.SObjectType.MDMRegRequestCustomer__c.getRecordTypeInfosByDeveloperName().get('MDMParent').getRecordTypeId();
                } else if(acc.CustomerType__c == 'C02') {
                    recordIdEx = Schema.SObjectType.MDMRegRequestCustomer__c.getRecordTypeInfosByDeveloperName().get('MDMChild').getRecordTypeId();
                } else if(managementList.contains(acc.CustomerType__c)) {
                    recordIdEx = Schema.SObjectType.MDMRegRequestCustomer__c.getRecordTypeInfosByDeveloperName().get('MDMManagement').getRecordTypeId();
                }

                customer.MDMRegRequestBulkCustomer__c    =       mdmRequestbulk.id;
                customer.RecordTypeId                    =       String.isBlank(acc.CustomerType__c) ? null : recordIdEx;
                customer.PV_KUNNR__c                     =       acc.CustomerId__c;
                customer.PV_NAME1__c                     =       acc.Name;
                customer.PV_BLCKYN__c                    =       acc.PV_BLCKYN__c;
                customer.PV_HDOFFICEYN__c                =       acc.IsHeadShopUseYN__c;
                
                Boolean isKxOtd = false;
                if(acc.KXOTD__c == 'Y') {
                    isKxOtd = true;
                } else if(acc.KXOTD__c == 'N') {
                    isKxOtd = false;
                }

                Boolean isFdInfo = false;
                if(acc.InitialDeliveryShare__c == 'Y') {
                    isFdInfo = true;
                } else if(acc.InitialDeliveryShare__c == 'N') {
                    isFdInfo = false;
                }
                
                customer.PV_SUBSIDIARYYN__c              =       acc.IsAffiliatedcompanyYN__c;
                customer.PV_VACCPRTEXCYN__c              =       acc.IsPrintVirtualAccount__c;
                customer.PV_EXAMYN__c                    =       acc.IsFaceToFaceInspectionStatus__c;
                customer.PV_KEYYN__c                     =       acc.IsBusinessPlaceKey__c;
                customer.PV_KXOTD__c                     =       isKxOtd;
                customer.PV_FDINFO__c                    =       isFdInfo;
                customer.PV_ISFDFTF__c                   =       acc.IsInitialDeliveryFTFInspection__c;
                customer.PV_BUSAB__c                     =       acc.SalesForm__c;
                customer.PV_CESSION_KZ__c                =       acc.CustomerStatus__c;
                customer.RequestType__c                  =       'Edit';

                mdmList.add(customer);

            }

            System.debug('# <Acc> mdmList => ' + mdmList);

            insert mdmList;

            // 커스텀ID : ID
            for(MDMRegRequestCustomer__c mdm : mdmList) {
                newMDMToIdMap.put(mdm.PV_KUNNR__c, mdm.Id);
            }

            System.debug('# <Acc> newMDMToIdMap => ' + newMDMToIdMap);

            saveResult.bulkId = mdmRequestbulk.id;

        }

        try {
            
            if(mdmContacts != null){

                for (MDMRegRequestContact__c con : mdmContacts) {
                    MDMRegRequestContact__c mdmContact = new MDMRegRequestContact__c();

                    mdmContact.PV_NAME1_VK__c           =      String.isBlank(con.PV_NAME1_VK__c) ? null : con.PV_NAME1_VK__c;
                    mdmContact.PV_KNVKGB__c             =      String.isBlank(con.PV_KNVKGB__c) ? null : con.PV_KNVKGB__c.toUpperCase();
                    mdmContact.PV_KNVKGB_lu__c          =      codeToIdMap.get(con.PV_KNVKGB__c.toUpperCase());
                    mdmContact.PV_TELF1_VK__c           =      String.isBlank(con.PV_TELF1_VK__c) ? null : con.PV_TELF1_VK__c;
                    mdmContact.PV_ABTNR_VK__c           =      String.isBlank(con.PV_ABTNR_VK__c) ? null : con.PV_ABTNR_VK__c;
                    mdmContact.PV_PAFKT_VK__c           =      String.isBlank(con.PV_PAFKT_VK__c) ? null : con.PV_PAFKT_VK__c;
                    mdmContact.PV_TALKT_VK__c           =      String.isBlank(con.PV_TALKT_VK__c) ? null : con.PV_TALKT_VK__c;
                    mdmContact.PV_EMAIL_VK__c           =      String.isBlank(con.PV_EMAIL_VK__c) ? null : con.PV_EMAIL_VK__c;
                    mdmContact.Contact__c               =      String.isBlank(con.Contact__c) ? null : con.Contact__c;
                    if(recordId != null) {
                        mdmContact.MDMRegRequestCustomer__c     =      kunnrToIdMap.get(con.MDMRegRequestCustomer__c);
                        mdmContact.MDMRegRequestBulkCustomer__c =      recordId;
                    } else {
                        mdmContact.MDMRegRequestCustomer__c     =      newMDMToIdMap.get(con.MDMRegRequestCustomer__c);
                        mdmContact.MDMRegRequestBulkCustomer__c =      saveResult.bulkId;
                    }
                    
                    contactList.add(mdmContact);
                }

                System.debug('contactList => ' + contactList);

                insert contactList;

            }
            
        } catch (Exception e) {
            saveResult = new SaveResult('F', e.getMessage() + e.getLineNumber());
        }

        return saveResult;

    }

    public class SaveResult{

        @AuraEnabled public String status {get;set;}
        @AuraEnabled public String massage {get;set;}
        @AuraEnabled public String bulkId {get;set;}

        // 생성자의 역할은 기본적으로
        // 전역변수(인스턴스변수) 초기화 해주는 역할을함
        public SaveResult() {
            this.status = 'S';
            this.massage = '성공 하였습니다.';
        }
        
        public SaveResult(String status, String massage) {
            this.status  = status;
            this.massage = massage;
        }

        public SaveResult(String status, String massage, String bulkId) {
            this.status  = status;
            this.massage = massage;
            this.bulkId = bulkId;
        }

    }

}