force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>CustomerType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C01</fullName>
                <label>본점</label>
            </value>
            <value>
                <fullName>C02</fullName>
                <label>판매처</label>
            </value>
            <value>
                <fullName>C03</fullName>
                <label>관리처-배송</label>
            </value>
            <value>
                <fullName>C04</fullName>
                <label>관리처-분할</label>
            </value>
            <value>
                <fullName>C05</fullName>
                <label>점포</label>
            </value>
            <value>
                <fullName>C06</fullName>
                <label>사이트</label>
            </value>
            <value>
                <fullName>C07</fullName>
                <label>단체급식고객</label>
            </value>
            <value>
                <fullName>C08</fullName>
                <label>회계고객</label>
            </value>
            <value>
                <fullName>C09</fullName>
                <label>물류센터</label>
            </value>
            <value>
                <fullName>C10</fullName>
                <label>해외고객</label>
            </value>
            <value>
                <fullName>C11</fullName>
                <label>관리처-2차</label>
            </value>
            <value>
                <fullName>C12</fullName>
                <label>금융고객</label>
            </value>
            <value>
                <fullName>C13</fullName>
                <label>자가소비부서</label>
            </value>
            <value>
                <fullName>C14</fullName>
                <label>경영계획부서</label>
            </value>
            <value>
                <fullName>C16</fullName>
                <label>해외고객-분할</label>
            </value>
            <value>
                <fullName>C17</fullName>
                <label>해외고객-배송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PV_KNVKGB__c.field-meta.xml
<CustomField>
    <fullName>PV_KNVKGB__c</fullName>
    <label>PV_KNVKGB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A01</fullName>
                <label>회계 담당자</label>
            </value>
            <value>
                <fullName>A02</fullName>
                <label>검수 담당자</label>
            </value>
            <value>
                <fullName>A03</fullName>
                <label>구매 담당자</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/PV_KUNNR__c.field-meta.xml
<CustomField>
    <fullName>PV_KUNNR__c</fullName>
    <label>고객ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PV_PAFKT_VK__c.field-meta.xml
<CustomField>
    <fullName>PV_PAFKT_VK__c</fullName>
    <label>PV_PAFKT_VK</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PV_TALKT_VK__c.field-meta.xml
<CustomField>
    <fullName>PV_TALKT_VK__c</fullName>
    <label>담당자 통화가능시간</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/MDMRegRequestCustomer__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 및 수정 요청</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CJFW_MDMBulkSearchContactController.cls
/**
 * @description       : 
 * @author            : hyeeun.song@dkbmc.com
 * @group             : 
 * @last modified on  : 11-06-2023
 * @last modified by  : joohyeon.jang@dkbmc.com
**/
public with sharing class CJFW_MDMBulkSearchContactController {
    
    @AuraEnabled(cacheable=true)
    public static DataWrapper getContactInfo(List<Map<String, String>> searchKey, String recordId, Integer pageNumber, Integer pageSize, String typeValue){

        system.debug('### CJFW_MDMBulkSearchContactController ###');
        system.debug('>>> getContactInfo()');

        String strStatus = 'SUCCESS';
        String strMessage = '';

        System.debug('===============> searchKey : ' + searchKey);
        System.debug('===============> recordId : ' + recordId);
        System.debug('===============> typeValue : ' + typeValue);

        // Key와 Value 따로 담아 주기
        List<String> searchKeys = new List<String>();
        List<String> searchValues = new List<String>();
        Map<String, String> dateValues = new Map<String, String>();

        for(Map<String, String> data : searchKey) {

            String apiType = data.get('type');
            String fieldName = data.get('fieldName');
            String datePoint = data.get('datePoint');
            String searchWord = data.get('searchKey');

            System.debug('## get param > ' + 'fieldName: ' + fieldName + ', apiType: ' + apiType + ', datePoint: ' + datePoint + ', searchWord: ' + searchWord);

            if(searchWord != null) {
                searchWord = searchWord.trim();
            }

            if(searchWord != null && searchWord.length() > 0 && fieldName != 'CreatedDate') {
                searchKeys.add(fieldName);
                searchValues.add(searchWord);
            } else if(searchWord != null && searchWord.length() > 0 && fieldName == 'CreatedDate') {
                searchWord = searchWord + 'T00:00:00.000+0000'; // UTC
                dateValues.put(datePoint, searchWord);
            }

        }

        System.debug('===============> searchKeys : ' + searchKeys);
        System.debug('===============> searchValues : ' + searchValues);
        System.debug('===============> dateValues : ' + dateValues);
        
        List<String> ids = new List<String>();

        if(recordId != null) {
            List<MDMRegRequestCustomer__c> customerList = [SELECT Id, PV_KUNNR__c FROM MDMRegRequestCustomer__c WHERE MDMRegRequestBulkCustomer__c = :recordId];
            
            for(MDMRegRequestCustomer__c cus : customerList) {
                //ids.add('\'' + cus.PV_KUNNR__c + '\'');
                ids.add(cus.PV_KUNNR__c);
            }
            
            System.debug('===============> customerList : ' + customerList);
            System.debug('===============> ids : ' + ids);
        }
        

        DataWrapper objWrapper = new DataWrapper();

        try {

            List<Contact> searchResult = new List<Contact>();       // 분할해서 담은
            List<Contact> listSearchResult = new List<Contact>();   // 모두 담은

            String strQuery = 'SELECT Id, AccountId, Account.CustomerId__c, Account.Name, Name, ';
            strQuery += ' PV_KNVKGB__c, toLabel(PV_KNVKGB__c) PV_KNVKGB__LABEL, ';
            strQuery += ' Phone, Department, PV_PAFKT_VK__c, PV_TALKT_VK__c, Email ';
            strQuery += ' FROM Contact ';
            strQuery += ' WHERE Account.CustomerId__c != null ';
            if(recordId != null) {
                // strQuery += ' AND Account.CustomerId__c IN (' + String.join(ids, ',') + ') ';
                strQuery += ' AND Account.CustomerId__c IN :  ids ';
            }
            if(typeValue != null) {
                strQuery += ' AND Account.CustomerType__c = \'' + typeValue + '\' ';
            }
            for(Integer i = 0; i < searchKeys.size(); i++) {
                if(searchKeys[i] == 'AccountId') {
                    strQuery += ' AND ' + searchKeys[i] + ' = \'' + searchValues[i] + '\'';
                } else {
                    strQuery += ' AND ' + searchKeys[i] + ' LIKE \'%' + searchValues[i] + '%\' ';
                }
            }

            System.debug('============> strQuery : '+strQuery);

            listSearchResult = Database.query(strQuery);

            Integer listSearchResultSize = listSearchResult.size();

            Integer startIndex = (pageNumber - 1) * pageSize;
            Integer endIndex = Math.min(startIndex + pageSize, listSearchResultSize);

            if(endIndex > startIndex){
                for (Integer i = startIndex; i < endIndex; i++) {
                    searchResult.add(listSearchResult[i]);
                }
            }

            objWrapper.searchResult = searchResult;

            System.debug('결과 => ' + searchResult);

            objWrapper.listSearchResult = listSearchResult;
            objWrapper.totalCnt = listSearchResultSize;

        } catch(Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
        
    }

    public class DataWrapper {

		@AuraEnabled
        public String strStatus {get;set;}

        @AuraEnabled
        public String strMessage {get;set;}

        @AuraEnabled
        public List<Contact> searchResult {get;set;}

        @AuraEnabled
        public List<Contact> listSearchResult {get;set;}

        @AuraEnabled
        public Integer totalCnt {get;set;}

        @AuraEnabled
        public String code {get;set;}

        @AuraEnabled
        public String inputId {get;set;}

        @AuraEnabled
        public String inputTextLabel {get;set;}

	}

}