force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CustomerType__c.field-meta.xml
<CustomField>
    <fullName>CustomerType__c</fullName>
    <label>CustomerType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C01</fullName>
                <label>본점</label>
            </value>
            <value>
                <fullName>C02</fullName>
                <label>판매처</label>
            </value>
            <value>
                <fullName>C03</fullName>
                <label>관리처-배송</label>
            </value>
            <value>
                <fullName>C04</fullName>
                <label>관리처-분할</label>
            </value>
            <value>
                <fullName>C05</fullName>
                <label>점포</label>
            </value>
            <value>
                <fullName>C06</fullName>
                <label>사이트</label>
            </value>
            <value>
                <fullName>C07</fullName>
                <label>단체급식고객</label>
            </value>
            <value>
                <fullName>C08</fullName>
                <label>회계고객</label>
            </value>
            <value>
                <fullName>C09</fullName>
                <label>물류센터</label>
            </value>
            <value>
                <fullName>C10</fullName>
                <label>해외고객</label>
            </value>
            <value>
                <fullName>C11</fullName>
                <label>관리처-2차</label>
            </value>
            <value>
                <fullName>C12</fullName>
                <label>금융고객</label>
            </value>
            <value>
                <fullName>C13</fullName>
                <label>자가소비부서</label>
            </value>
            <value>
                <fullName>C14</fullName>
                <label>경영계획부서</label>
            </value>
            <value>
                <fullName>C16</fullName>
                <label>해외고객-분할</label>
            </value>
            <value>
                <fullName>C17</fullName>
                <label>해외고객-배송</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CJFW_MDMBulkAccountSearchController.cls
/**
 * @description       : 
 * @author            : hyeeun.song@dkbmc.com
 * @group             : 
 * @last modified on  : 09-22-2023
 * @last modified by  : hyeeun.song@dkbmc.com
**/
public with sharing class CJFW_MDMBulkAccountSearchController {

    @AuraEnabled(cacheable=true)
    public static DataWrapper getAccountInfo(String searchWord, String type, Integer pageNumber, Integer pageSize) {

        system.debug('### CJFW_MDMBulkAccountSearchController ###');
        system.debug('>>> getAccountInfo()');
        system.debug('>>> searchWord ' + searchWord);
        system.debug('>>> type ' + type);

        String searchCode = null;

        if(type == '판매처') {
            searchCode = 'C02';
        } else if(type == '관리처') {
            searchCode = 'C03\', \'C04\', \'C11';
        }

        searchCode = searchCode.replace(' ', '');

        String[] codeList = searchCode.split(',');

        String strStatus = 'SUCCESS';
        String strMessage = '';

        System.debug('===============> searchWord : '+searchWord);
        System.debug('===============> searchCode : '+searchCode);

        DataWrapper objWrapper = new DataWrapper();

        
        try {

            List<Account> searchResult = new List<Account>(); // 분할해서 담은
            List<Account> listSearchResult = new List<Account>(); // 모두 담은

            String strQuery = 'SELECT Id, CustomerID__c, Name, Owner.Name';
            strQuery += '   FROM    Account';
            strQuery += '   WHERE   CustomerType__c IN ( \'' + searchCode + '\' ) AND CustomerId__c != NULL ';
            if(searchWord <> null) {
                strQuery += '   AND     (Name LIKE \'%' + searchWord + '%\' OR Owner.Name LIKE \'%' + searchWord + '%\')';
            }

            System.debug('============> strQuery : '+strQuery);
            
            listSearchResult = Database.query(strQuery);

            Integer listSearchResultSize = listSearchResult.size();

            Integer startIndex = (pageNumber - 1) * pageSize;
            Integer endIndex = Math.min(startIndex + pageSize, listSearchResultSize);

            if(endIndex > startIndex){
                for (Integer i = startIndex; i < endIndex; i++) {
                    searchResult.add(listSearchResult[i]);
                }
            }

            objWrapper.searchResult = searchResult;

            System.debug('결과 => ' + searchResult);

            objWrapper.listSearchResult = listSearchResult;
            objWrapper.totalCnt = listSearchResultSize;
            
        } catch(Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    public class DataWrapper {

		@AuraEnabled
        public String strStatus {get;set;}

        @AuraEnabled
        public String strMessage {get;set;}

        @AuraEnabled
        public List<Account> searchResult {get;set;}

        @AuraEnabled
        public List<Account> listSearchResult {get;set;}

        @AuraEnabled
        public Integer totalCnt {get;set;}

        @AuraEnabled
        public String code {get;set;}

        @AuraEnabled
        public String inputId {get;set;}

        @AuraEnabled
        public String inputTextLabel {get;set;}

	}

}