force-app/main/default/objects/Account/fields/custID__c.field-meta.xml
<CustomField>
    <fullName>custID__c</fullName>
    <externalId>true</externalId>
    <label>고객ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SchoolDepartment.recordType-meta.xml
<RecordType>
    <fullName>SchoolDepartment</fullName>
    <active>true</active>
    <label>School Department</label>
</RecordType>

force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SCHL__c.field-meta.xml
<CustomField>
    <fullName>SCHL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SCHL</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>매출원장정보 (SCHL_CD)</relationshipLabel>
    <relationshipName>SalesLedgerInformation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SCHL_CD__c.field-meta.xml
<CustomField>
    <fullName>SCHL_CD__c</fullName>
    <externalId>true</externalId>
    <label>SCHL_CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MIG_SalesSchool_ba.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-05-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class MIG_SalesSchool_ba implements Database.Batchable<SObject>, Database.Stateful {
    global MIG_SalesSchool_ba() {
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = '';

        Date inqDate = Date.newInstance(2022, 1, 1);

        strQuery += 'SELECT  Id, SALES_YMD__c, SCHL_CD__c, SCHL__c';        
        strQuery += '   FROM    SalesLedgerInformation__c';
        strQuery += '   WHERE   SCHL_CD__c != null';
        strQuery += '   AND     SALES_YMD__c >=:inqDate';
        //strQuery += '   AND     SCHL__c = null';
        
        return  Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext bc, List<SalesLedgerInformation__c> scope) {

        Set<String> setSchlCd = new Set<String>();

        for(SalesLedgerInformation__c obj : scope) {
            if(obj.SCHL_CD__c <> null) {
                setSchlCd.add(obj.SCHL_CD__c);
            }
        }

        Map<String, String> mapSchool = new Map<String, String>();

        for(Account objAccount : [
            SELECT  Id, Name, custID__c
            FROM    Account
            WHERE   RecordType.DeveloperName = 'SchoolDepartment'
            AND     custID__c In:setSchlCd
        ]) {
            mapSchool.put(objAccount.custID__c, objAccount.Id);
        }

        List<SalesLedgerInformation__c> listUpdate = new List<SalesLedgerInformation__c>();

        for(SalesLedgerInformation__c obj : scope) {
            if(mapSchool <> null && mapSchool.get(obj.SCHL_CD__c) <> null) {
                obj.SCHL__c = mapSchool.get(obj.SCHL_CD__c);

                listUpdate.add(obj);
            }            
        }

        if(listUpdate <> null && listUpdate.size() > 0) {
            update listUpdate;
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}