force-app/main/default/objects/Account/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <description>MDM 고객ID</description>
    <externalId>true</externalId>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingAccountCode__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccountCode__c</fullName>
    <description>MDM 청구처코드</description>
    <label>Shipping Account Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingAccountName__c.field-meta.xml
<CustomField>
    <fullName>ShippingAccountName__c</fullName>
    <label>ShippingAccountName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesAccountSummary__c/SalesAccountSummary__c.object-meta.xml
<CustomObject>
    <label>매출합계(고객별)</label>
    <nameField>
        <label>SalesAccountSummary 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesAccountSummary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesSummary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesAccountSummary__c/fields/BRC_ID__c.field-meta.xml
<CustomField>
    <fullName>BRC_ID__c</fullName>
    <externalId>true</externalId>
    <label>BRC_ID</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesAccountSummary__c/fields/DIV_ID__c.field-meta.xml
<CustomField>
    <fullName>DIV_ID__c</fullName>
    <externalId>true</externalId>
    <label>DIV_ID</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesAccountSummary__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>&quot;날짜&quot;+&quot;_&quot;+&quot;고객번호&quot;</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesAccountSummary__c/fields/TotalSalesProfit__c.field-meta.xml
<CustomField>
    <fullName>TotalSalesProfit__c</fullName>
    <description>총 매출이익</description>
    <label>TotalSalesProfit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BRC_ID__c.field-meta.xml
<CustomField>
    <fullName>BRC_ID__c</fullName>
    <label>BRC_ID</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>235</fullName>
                <label>원료)축산시너지팀</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>322</fullName>
                <label>급식)급식솔루션동부1팀</label>
            </value>
            <value>
                <fullName>323</fullName>
                <label>급식)급식솔루션서부팀</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
            <value>
                <fullName>337</fullName>
                <label>급식)급식솔루션동부2팀</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>347</fullName>
                <label>유통중부)유통글로벌식재팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>320</fullName>
                <label>급식)급식솔루션1팀</label>
            </value>
            <value>
                <fullName>321</fullName>
                <label>급식)급식솔루션2팀</label>
            </value>
            <value>
                <fullName>325</fullName>
                <label>급식)급식솔루션지원</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>346</fullName>
                <label>튼튼스쿨)튼튼스쿨2팀</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/DIV_ID__c.field-meta.xml
<CustomField>
    <fullName>DIV_ID__c</fullName>
    <label>SU Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>전략사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/fm_SalesProfit__c.field-meta.xml
<CustomField>
    <fullName>fm_SalesProfit__c</fullName>
    <formula>( SALE_UNPRC__c -  ORDR_REAL_BUY_UNPRC__c  ) *  RLSTK_UNIT_RLSTK_QTY__c</formula>
    <label>Sales Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_AT__c</fullName>
    <label>net sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_SUM_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_SUM_AT__c</fullName>
    <label>gross sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLBZ_ORG_ID__c.field-meta.xml
<CustomField>
    <fullName>SLBZ_ORG_ID__c</fullName>
    <label>SLBZ_ORG_ID</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLST__c.field-meta.xml
<CustomField>
    <fullName>SLST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesLedgerAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesAccountSummary_ba.cls
/**
 * @description       : 매출원장 고객별 Summary Batch Class
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-15-2023
 * @last modified by  : admin
**/
/*
Date startDate = Date.newInstance(2022, 11, 1);
Date endDate = Date.newInstance(2022, 11, 30);
Integer batchSize = 50;

SalesAccountSummary_ba ba = new SalesAccountSummary_ba(startDate, endDate);
Database.executeBatch(ba, batchSize);
*/
global class SalesAccountSummary_ba implements Database.Batchable<SObject>, Database.Stateful {
    //global String targetAccount;
    global Date startDate;
    global Date endDate;

    global SalesAccountSummary_ba(Date startDate, Date endDate) {
        this.startDate = startDate;
        this.endDate = endDate;
    }
    /***********************************************************************************************************
    *  Bacth   : start
    *  내용    : Account(기존고객) 정보 조회
    ************************************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext bc) {

        Id recordIdEx = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ExistingCustomer').getRecordTypeId();


        String strQuery = '';
        strQuery += 'SELECT Id, OwnerId';        
        //strQuery += '   ShippingAccountName__c, ShippingAccountCode__c';
        strQuery += '   FROM    Account';
        strQuery += '   WHERE   RecordTypeId =:recordIdEx';

        /*
        if(this.targetAccount <> null && this.targetAccount <> '') {
            strQuery += '   AND     Id=:targetAccount';
        }
        */
        
        return  Database.getQueryLocator(strQuery);
    }
    /***********************************************************************************************************
    *  Bacth   : execute
    *  내용    : 매출원장정보 고객별 Summary upsert
    ************************************************************************************************************/
    global void execute(Database.BatchableContext bc, List<Account> scope) {

        Set<String> setAccountId = new Set<String>();

        for(Account obj : scope) {
            setAccountId.add(obj.Id);
        }

        Map<String, Account> mapAccount = new Map<String, Account>();

        mapAccount.putAll([
            SELECT  Id, Name, CustomerID__c, OwnerId
            FROM    Account
            WHERE Id IN:setAccountId
        ]);

        String strQuery = '';

        strQuery += 'SELECT  SLST__c AccountId,';
        strQuery += '   SLBZ_ORG_ID__c, DIV_ID__c, BRC_ID__c,';
        strQuery += '   SALES_YMD__c SalesDate,';
        strQuery += '   SUM(SALES_AT__c) TotalNetAmount, SUM(SALES_SUM_AT__c) TotalSalesAmount, SUM(fm_SalesProfit__c) TotalSalesProfit';
        strQuery += '   FROM    SalesLedgerInformation__c';
        strQuery += '   WHERE   SLST__c IN:setAccountId';
        
        Date targetStartDate = Date.newInstance(Date.today().year(), Date.today().month(), 1);

        if(this.startDate <> null) {
            targetStartDate = this.startDate;
        }

        Date targetEndDate = Date.today().addDays(-1);

        if(this.endDate <> null) {
            targetEndDate = this.endDate;
        }

        strQuery += '   AND   SALES_YMD__c >=:targetStartDate';
        strQuery += '   AND   SALES_YMD__c <=:targetEndDate';
        strQuery += '   GROUP BY SLST__c, SLBZ_ORG_ID__c, DIV_ID__c, BRC_ID__c, SALES_YMD__c';

        System.debug('=============> strQuery : '+strQuery);

        List<AggregateResult> listAccountSalesSummary = Database.query(strQuery);

        /*
        List<AggregateResult> listAccountSalesSummary = new List<AggregateResult> ([
            SELECT  SLST__c AccountId,
                    SLBZ_ORG_ID__c, DIV_ID__c, BRC_ID__c,
                    SALES_YMD__c SalesDate, SUM(fm_SalesProfit__c) TotalSalesProfit, SUM(SALES_AT__c) totalSalesAmount
            FROM    SalesLedgerInformation__c
            WHERE   SLST__c IN:setAccountId
            GROUP BY SLST__c, SLBZ_ORG_ID__c, DIV_ID__c, BRC_ID__c, SALES_YMD__c
        ]);
        */

        List<SalesAccountSummary__c> listSalesSummary = new List<SalesAccountSummary__c>();

        if(listAccountSalesSummary <> null && listAccountSalesSummary.size() > 0) {

            Map<String, String> mapSlbzOrgNm = CommonUtil.getMapPickListValuetoLabel('SalesLedgerInformation__c', 'SLBZ_ORG_ID__c');
            Map<String, String> mapDivNm = CommonUtil.getMapPickListValuetoLabel('SalesLedgerInformation__c', 'DIV_ID__c');
            Map<String, String> mapBrcNm = CommonUtil.getMapPickListValuetoLabel('SalesLedgerInformation__c', 'BRC_ID__c');

            for(AggregateResult obj : listAccountSalesSummary) {
                SalesAccountSummary__c objSummary = new SalesAccountSummary__c();

                objSummary.Account__c = String.valueOf(obj.get('AccountId'));

                Account objTargetAccount = mapAccount.get(objSummary.Account__c);
                objSummary.SalesDate__c = Date.valueOf(obj.get('SalesDate'));
                objSummary.OwnerId = objTargetAccount.OwnerId;

                String strDate = objSummary.SalesDate__c.year()+'-'+objSummary.SalesDate__c.month()+'-'+objSummary.SalesDate__c.day();

                objSummary.Name = objTargetAccount.Name+'('+objTargetAccount.CustomerID__c+')_'+strDate;
                // 본부 Id
                objSummary.SLBZ_ORG_ID__c = String.valueOf(obj.get('SLBZ_ORG_ID__c'));
                // 본부명
                objSummary.SLBZ_ORG_NM__c = mapSlbzOrgNm.get(objSummary.SLBZ_ORG_ID__c);
                // SU Id
                objSummary.DIV_ID__c = String.valueOf(obj.get('DIV_ID__c'));
                // SU명
                objSummary.DIV_NM__c = mapDivNm.get(objSummary.DIV_ID__c);
                // 팀Id
                objSummary.BRC_ID__c = String.valueOf(obj.get('BRC_ID__c'));
                // 팀명
                objSummary.BRC_NM__c = mapBrcNm.get(objSummary.BRC_ID__c);
                // 순매출
                objSummary.TotalNetAmount__c = (Decimal)obj.get('TotalNetAmount');
                // 총매출
                objSummary.TotalSalesAmount__c = (Decimal)obj.get('TotalSalesAmount');
                // 매출이익
                objSummary.TotalSalesProfit__c = (Decimal)obj.get('TotalSalesProfit');
                // 고객ID+'_'+청구일자+'_'+본부코드+'_'+'SU코드'+'팀코드'
                objSummary.ExtId__c = objSummary.Account__c+'_'+objSummary.SalesDate__c+'_'+objSummary.SLBZ_ORG_ID__c+'_'+objSummary.DIV_ID__c+'_'+objSummary.BRC_ID__c;

                listSalesSummary.add(objSummary);
            }

            if(listSalesSummary <> null && listSalesSummary.size() > 0) {
                upsert listSalesSummary ExtId__c;
            }
        }
    }

    /***********************************************************************************************************
    *  Bacth   : finish
    *  내용    : 없음
    ************************************************************************************************************/
    global void finish(Database.BatchableContext BC) {
    }
}