force-app/main/default/objects/Account/fields/INSTANCEID__c.field-meta.xml
<CustomField>
    <fullName>INSTANCEID__c</fullName>
    <label>INSTANCEID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/MDMReferenceCode__c.object-meta.xml
<CustomObject>
    <label>MDM 참조코드</label>
    <nameField>
        <label>MDMReferenceCode Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMReferenceCode__c/fields/ACTIVE__c.field-meta.xml
<CustomField>
    <fullName>ACTIVE__c</fullName>
    <label>ACTIVE</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/ATTR1__c.field-meta.xml
<CustomField>
    <fullName>ATTR1__c</fullName>
    <label>ATTR1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/ATTR2__c.field-meta.xml
<CustomField>
    <fullName>ATTR2__c</fullName>
    <label>ATTR2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/ATTR3__c.field-meta.xml
<CustomField>
    <fullName>ATTR3__c</fullName>
    <label>ATTR3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/CODE__c.field-meta.xml
<CustomField>
    <fullName>CODE__c</fullName>
    <externalId>true</externalId>
    <label>CODE</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/GROUPID__c.field-meta.xml
<CustomField>
    <fullName>GROUPID__c</fullName>
    <externalId>true</externalId>
    <label>GROUPID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/INSTANCEID__c.field-meta.xml
<CustomField>
    <fullName>INSTANCEID__c</fullName>
    <label>INSTANCEID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_EN__c.field-meta.xml
<CustomField>
    <fullName>NAME_EN__c</fullName>
    <label>NAME_EN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_KO__c.field-meta.xml
<CustomField>
    <fullName>NAME_KO__c</fullName>
    <label>NAME_KO</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_VI__c.field-meta.xml
<CustomField>
    <fullName>NAME_VI__c</fullName>
    <label>NAME_VI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_ZH__c.field-meta.xml
<CustomField>
    <fullName>NAME_ZH__c</fullName>
    <label>NAME_ZH</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <externalId>true</externalId>
    <label>Ext Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CJFW_MDMManagementSearchController.cls
/**
 * @description       : 
 * @author            : joohyeon.jang@dkbmc.com
 * @group             : 
 * @last modified on  : 08-31-2023
 * @last modified by  : joohyeon.jang@dkbmc.com
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   08-30-2023   joohyeon.jang@dkbmc.com   Initial Version
**/
public with sharing class CJFW_MDMManagementSearchController {
    @AuraEnabled(cacheable=true)
    public static DataWrapper getMDMReferenceCodeInfo(String searchWord , String strGroupId){

        system.debug('###CJFW_MDMManagementSearchController###');
        system.debug('>>> getMDMReferenceCodeInfo()');
        system.debug('>>> searchWord ' + searchWord);
        system.debug('>>> groupId ' + strGroupId);
        String strStatus = 'SUCCESS';
        String strMessage = '';

        System.debug('===============> searchWord : '+searchWord);

        DataWrapper objWrapper = new DataWrapper();

        try {
            List<MDMReferenceCode__c> listSearchResult = new List<MDMReferenceCode__c>();

            String strQuery = 'SELECT Id,';
            strQuery += '   Name, ExtId__c, INSTANCEID__c, GROUPID__c, CODE__c,';
            strQuery += '   NAME_KO__c, NAME_EN__c, NAME_ZH__c, NAME_VI__c,';
            strQuery += '   ATTR1__c, ATTR2__c, ATTR3__c, IsActive__c, ACTIVE__c, IsDefault__c';
            strQuery += '   FROM    MDMReferenceCode__c';
            strQuery += '   WHERE   GROUPID__c = \''+strGroupId+'\'';
            strQuery += '   AND     IsActive__c = TRUE';
            if(searchWord <> null) {
                strQuery += '   AND     (Name LIKE \'%'+searchWord+'%\' OR CODE__c LIKE \'%'+searchWord+'%\')';
            }
            // 2023-01-14 지역코드일 경우 5자리 코드만 조회하도록 추가 
            if(strGroupId == 'T005S') {
                strQuery += '   AND     CODE__c LIKE \'_____\'';
            }
            // 2023-02-02 영업그룹코드일 경우 유효일자 체크로직 추가
            if(strGroupId == 'SALESGROUPH') {
                String strToday = Datetime.now().format('yyyy-MM-dd');

                strQuery += '   AND     ATTR1__c <= \''+strToday+'\'';
                strQuery += '   AND     ATTR2__c >= \''+strToday+'\'';
            }

            strQuery += '   ORDER   BY GROUPID__c, CODE__c ASC';            

            System.debug('============> strQuery : '+strQuery);
            
            listSearchResult = Database.query(strQuery);
            Integer listSearchResultSize = listSearchResult.size();
            
            /*
            objWrapper.listSelectBrand = CommonUtil.getPickListValues('Account', 'ExceptBrand__c', true);
            objWrapper.listSelectCompany = CommonUtil.getPickListValues('Account', 'Company__c', true);
            objWrapper.listSelectPlatform = CommonUtil.getPickListValues('Product2', 'Platform__c', true);
            */

            objWrapper.listSearchResult = listSearchResult;
            objWrapper.totalCnt = listSearchResultSize;
            
        } catch(Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }
    public class DataWrapper {
		@AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}

        @AuraEnabled
        public List<MDMReferenceCode__c> listSearchResult {get;set;}

        @AuraEnabled
        public Integer totalCnt {get;set;}

        @AuraEnabled
        public String code {get;set;}

        @AuraEnabled
        public String inputId {get;set;}

        @AuraEnabled
        public String inputTextLabel {get;set;}

        /*
        @AuraEnabled
        public List<SearchResult> listSearchResult {get;set;}
        */
	}


}