force-app/main/default/objects/Account/fields/jrsdt_cido_eduofic_cd__c.field-meta.xml
<CustomField>
    <fullName>jrsdt_cido_eduofic_cd__c</fullName>
    <label>jrsdt_cido_eduofic_cd</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>100</fullName>
                <label>서울</label>
            </value>
            <value>
                <fullName>110</fullName>
                <label>경기</label>
            </value>
            <value>
                <fullName>120</fullName>
                <label>인천</label>
            </value>
            <value>
                <fullName>130</fullName>
                <label>강원도</label>
            </value>
            <value>
                <fullName>140</fullName>
                <label>대전</label>
            </value>
            <value>
                <fullName>150</fullName>
                <label>충남</label>
            </value>
            <value>
                <fullName>160</fullName>
                <label>충북</label>
            </value>
            <value>
                <fullName>170</fullName>
                <label>부산</label>
            </value>
            <value>
                <fullName>180</fullName>
                <label>대구</label>
            </value>
            <value>
                <fullName>190</fullName>
                <label>울산</label>
            </value>
            <value>
                <fullName>200</fullName>
                <label>경남</label>
            </value>
            <value>
                <fullName>210</fullName>
                <label>경북</label>
            </value>
            <value>
                <fullName>220</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>230</fullName>
                <label>전남</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>250</fullName>
                <label>제주</label>
            </value>
            <value>
                <fullName>세종</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/jrsdt_gugun_eduofic_cd__c.field-meta.xml
<CustomField>
    <fullName>jrsdt_gugun_eduofic_cd__c</fullName>
    <label>jrsdt_gugun_eduofic_cd</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>jrsdt_cido_eduofic_cd__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1001</fullName>
                <label>강남(1001)</label>
            </value>
            <value>
                <fullName>1002</fullName>
                <label>강동</label>
            </value>
            <value>
                <fullName>1003</fullName>
                <label>강서</label>
            </value>
            <value>
                <fullName>1004</fullName>
                <label>남부(1004)</label>
            </value>
            <value>
                <fullName>1005</fullName>
                <label>동부(1005)</label>
            </value>
            <value>
                <fullName>1006</fullName>
                <label>동작</label>
            </value>
            <value>
                <fullName>1007</fullName>
                <label>북부(1007)</label>
            </value>
            <value>
                <fullName>1008</fullName>
                <label>서부(1008)</label>
            </value>
            <value>
                <fullName>1009</fullName>
                <label>성동</label>
            </value>
            <value>
                <fullName>1010</fullName>
                <label>성북</label>
            </value>
            <value>
                <fullName>1011</fullName>
                <label>중부</label>
            </value>
            <value>
                <fullName>1101</fullName>
                <label>가평</label>
            </value>
            <value>
                <fullName>1102</fullName>
                <label>고양</label>
            </value>
            <value>
                <fullName>1103</fullName>
                <label>광명</label>
            </value>
            <value>
                <fullName>1104</fullName>
                <label>광주하남</label>
            </value>
            <value>
                <fullName>1105</fullName>
                <label>군포의왕</label>
            </value>
            <value>
                <fullName>1106</fullName>
                <label>김포</label>
            </value>
            <value>
                <fullName>1107</fullName>
                <label>구리남양주</label>
            </value>
            <value>
                <fullName>1108</fullName>
                <label>동두천양주</label>
            </value>
            <value>
                <fullName>1109</fullName>
                <label>부천</label>
            </value>
            <value>
                <fullName>1110</fullName>
                <label>성남</label>
            </value>
            <value>
                <fullName>1111</fullName>
                <label>수원</label>
            </value>
            <value>
                <fullName>1112</fullName>
                <label>시흥</label>
            </value>
            <value>
                <fullName>1113</fullName>
                <label>안산</label>
            </value>
            <value>
                <fullName>1114</fullName>
                <label>안성</label>
            </value>
            <value>
                <fullName>1115</fullName>
                <label>안양과천</label>
            </value>
            <value>
                <fullName>1116</fullName>
                <label>양평</label>
            </value>
            <value>
                <fullName>1121</fullName>
                <label>이천</label>
            </value>
            <value>
                <fullName>1122</fullName>
                <label>파주</label>
            </value>
            <value>
                <fullName>1123</fullName>
                <label>평택</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LocationState__c.field-meta.xml
<CustomField>
    <fullName>LocationState__c</fullName>
    <label>LocationState</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LocationStateProvince__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>41220</fullName>
                <label>경기 평택시</label>
            </value>
            <value>
                <fullName>41250</fullName>
                <label>경기 동두천시</label>
            </value>
            <value>
                <fullName>41270</fullName>
                <label>경기 안산시</label>
            </value>
            <value>
                <fullName>41280</fullName>
                <label>경기 고양시</label>
            </value>
            <value>
                <fullName>41290</fullName>
                <label>경기 과천시</label>
            </value>
            <value>
                <fullName>41310</fullName>
                <label>경기 구리시</label>
            </value>
            <value>
                <fullName>41360</fullName>
                <label>경기 남양주시</label>
            </value>
            <value>
                <fullName>41370</fullName>
                <label>경기 오산시</label>
            </value>
            <value>
                <fullName>41390</fullName>
                <label>경기 시흥시</label>
            </value>
            <value>
                <fullName>41410</fullName>
                <label>경기 군포시</label>
            </value>
            <value>
                <fullName>41430</fullName>
                <label>경기 의왕시</label>
            </value>
            <value>
                <fullName>41450</fullName>
                <label>경기 하남시</label>
            </value>
            <value>
                <fullName>41460</fullName>
                <label>경기 용인시</label>
            </value>
            <value>
                <fullName>41480</fullName>
                <label>경기 파주시</label>
            </value>
            <value>
                <fullName>41500</fullName>
                <label>경기 이천시</label>
            </value>
            <value>
                <fullName>46810</fullName>
                <label>전남 강진군</label>
            </value>
            <value>
                <fullName>46820</fullName>
                <label>전남 해남군</label>
            </value>
            <value>
                <fullName>46830</fullName>
                <label>전남 영암군</label>
            </value>
            <value>
                <fullName>46840</fullName>
                <label>전남 무안군</label>
            </value>
            <value>
                <fullName>46860</fullName>
                <label>전남 함평군</label>
            </value>
            <value>
                <fullName>46870</fullName>
                <label>전남 영광군</label>
            </value>
            <value>
                <fullName>46880</fullName>
                <label>전남 장성군</label>
            </value>
            <value>
                <fullName>46890</fullName>
                <label>전남 완도군</label>
            </value>
            <value>
                <fullName>46900</fullName>
                <label>전남 진도군</label>
            </value>
            <value>
                <fullName>46910</fullName>
                <label>전남 신안군</label>
            </value>
            <value>
                <fullName>45110</fullName>
                <label>전북 전주시</label>
            </value>
            <value>
                <fullName>45130</fullName>
                <label>전북 군산시</label>
            </value>
            <value>
                <fullName>45140</fullName>
                <label>전북 익산시</label>
            </value>
            <value>
                <fullName>45180</fullName>
                <label>전북 정읍시</label>
            </value>
            <value>
                <fullName>45190</fullName>
                <label>전북 남원시</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LocationStateProvince__c.field-meta.xml
<CustomField>
    <fullName>LocationStateProvince__c</fullName>
    <label>LocationState/Province</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>11</fullName>
                <label>서울</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>인천</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>경기</label>
            </value>
            <value>
                <fullName>42</fullName>
                <label>강원</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>부산</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>대구</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>울산</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>경북</label>
            </value>
            <value>
                <fullName>48</fullName>
                <label>경남</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>대전</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>충남</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>세종</label>
            </value>
            <value>
                <fullName>43</fullName>
                <label>충북</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>전남</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>제주</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/sma_cust_mng_grd_cd__c.field-meta.xml
<CustomField>
    <fullName>sma_cust_mng_grd_cd__c</fullName>
    <label>sma_cust_mng_grd_cd</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
                <label>관리제외</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SchoolDepartment.recordType-meta.xml
<RecordType>
    <fullName>SchoolDepartment</fullName>
    <active>true</active>
    <label>School Department</label>
</RecordType>

force-app/main/default/objects/AccountOwnerReportURL__c/AccountOwnerReportURL__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>담당자 변경 탭 보고서 URL</label>
</CustomObject>

force-app/main/default/objects/AccountOwnerReportURL__c/fields/ReportURL__c.field-meta.xml
<CustomField>
    <fullName>ReportURL__c</fullName>
    <label>보고서 URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountOwnerUpdateController.cls
/*
* ==================================================================================
*   File Name   : AccountOwnerUpdateController.cls
*   Author      : Minje.Kim
*   Date        : 2023.01.09
*   Tester      : AccountOwnerUpdateController_test.cls
*   Description : AccountOwnerUpdateController Controller
*   Modification Log
* ==================================================================================
*   Ver     Date          Author          Modification
* ==================================================================================
*   1.0     2022.12.28    kw            Create
*   1.1     2023.04.12    sy.lee        update
* ==================================================================================
*/

public without sharing class AccountOwnerUpdateController {
    /**
     * SMA 고객관리 담당자 일괄변경 Init
     *      
     * @return DataWrapper 
     *          - strStatus : 상태값
     *          - strMessage : 메시지
     *          - reportURL : 전체 리스트 보고서 URL
     *          - listLocationStateProvince : 지역(시/도)(LocationStateProvince__c) Picklist value list
     *          - listLocationState : 지역(LocationState__c) Picklist value list
     *          - mapLocation : 지역 종속성 Map
     * 
    **/
    @AuraEnabled
    public static DataWrapper doInit() {
        String strStatus = 'SUCCESS';
        String strMessage = '';
        DataWrapper objWrapper = new DataWrapper();

        try{
            objWrapper.listLocationStateProvince = CommonUtil.getPickListValues('Account', 'LocationStateProvince__c', false);
            objWrapper.listLocationState = CommonUtil.getPickListValues('Account', 'LocationState__c', false);
            objWrapper.listSmaCustMngGrdCd = CommonUtil.getPickListValues('Account', 'sma_cust_mng_grd_cd__c', false);
            objWrapper.mapLocation = CommonUtil.getDependentPicklistValues(Account.LocationState__c);
            objWrapper.mapLocation.put('none',objWrapper.listLocationState);

            AccountOwnerReportURL__c objReportURL = new AccountOwnerReportURL__c();
            String strReportURL = '';
            objReportURL = AccountOwnerReportURL__c.getValues(UserInfo.getUserId());

            if ( objReportURL == null){
                objReportURL = AccountOwnerReportURL__c.getValues(UserInfo.getProfileId());
            } else {
                strReportURL = objReportURL.ReportURL__c;
            }

            if ( objReportURL == null){
                objReportURL = AccountOwnerReportURL__c.getOrgDefaults();
            } else {
                strReportURL = objReportURL.ReportURL__c;
            }

            if ( objReportURL.Id == null){
                objReportURL = null;
            } else {
                strReportURL = objReportURL.ReportURL__c;
            }
            objWrapper.reportURL = strReportURL;

        }catch (Exception e){
            strStatus = 'ERROR';
            if (e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                strMessage = e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ',': []');
            }else{
                strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            }
        }
        System.debug( objWrapper.reportURL);
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;
        return objWrapper;
    }

    /**
     * SMA 고객정보 조회
     *      
     * @params mapParam : selectedLocationStateProvince 지역(시/도), selectedLocationState 지역(시/군/구), selectedUserId User Id
     * @return DataWrapper
     *          - strStatus : 상태값
     *          - strMessage : 메시지
     *          - listSearchWrapper : 조회결과 
    **/
    @AuraEnabled
    public static DataWrapper getDataTable(Map<String, String> mapParam) {
        String strStatus = 'SUCCESS';
        String strMessage = '';
        Boolean isLocationStateProvince = false;
        DataWrapper objWrapper = new DataWrapper();
        List<SearchWrapper> listSearchWrapper = new List<SearchWrapper>();
        Id recordIdSchool = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('SchoolDepartment').getRecordTypeId();

        try {
            if (mapParam != null) {
                String strQuery =   '   SELECT     Id, Name, OwnerId, Owner.Name, Owner.EmployeeNumber, sma_cust_mng_grd_cd__c, toLabel(jrsdt_cido_eduofic_cd__c), toLabel(jrsdt_gugun_eduofic_cd__c), Phone';
                strQuery +=         '   FROM       Account';
                strQuery +=         '   WHERE       RecordTypeId = :recordIdSchool';
                if (mapParam.get('selectedLocationStateProvince') != null && mapParam.get('selectedLocationStateProvince') != 'none') {
                    strQuery +=     '   AND      LocationStateProvince__c = \''+mapParam.get('selectedLocationStateProvince')+'\'';
                    isLocationStateProvince = true;
                }
                if (mapParam.get('selectedLocationState') != null && mapParam.get('selectedLocationState') != 'none') {
                    strQuery +=     '   AND     LocationState__c = \''+mapParam.get('selectedLocationState')+'\'';
                }
                if (mapParam.get('selectedUserId') != null && mapParam.get('selectedUserId') != '') {
                    strQuery +=     '   AND     OwnerId = \''+mapParam.get('selectedUserId')+'\'';
                }
                strQuery +=         '   ORDER BY       Name';
            for(Account objAccount : Database.query(strQuery)) {
                if (objAccount.jrsdt_cido_eduofic_cd__c == '세종') {
                    objAccount.jrsdt_cido_eduofic_cd__c = null;
                }
                SearchWrapper objSearch = new SearchWrapper(objAccount);
                listSearchWrapper.add(objSearch);
            }

            }else {
                strStatus = 'ERROR';
                strMessage = '지역 설정 ERROR';
            }
        }catch (Exception e) {
            strStatus = 'ERROR';
            if (e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                strMessage = e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ',': []');
            }else{
                strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            }
        }

        objWrapper.listSearchWrapper = listSearchWrapper;
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        System.debug( 'objWrapper :: '  +  objWrapper);

        return objWrapper;
    }

    /**
     * 사용자 정보 조회
     * 
     * @return DataWrapper
     *          - strStatus : 상태값
     *          - strMessage : 메시지
     *          - listSearchWrapper : 조회결과
    **/
    @AuraEnabled
    public static DataWrapper getUserDataTable() {
        String strStatus = 'SUCCESS';
        String strMessage = '';
        DataWrapper objWrapper = new DataWrapper();
        List<SearchWrapper> listSearchWrapper = new List<SearchWrapper>();

        try {
            //Param조건 추가
            String strQuery =   '   SELECT      id, Name, EmployeeNumber, toLabel(Team__c),toLabel(CJTitle__c), Phone, Email';
            strQuery +=         '   FROM        User';
            strQuery +=         '   WHERE       IsActive = TRUE';
            strQuery +=         '   AND         SU__c = \'4709\'';

            for(User objUser : Database.query(strQuery)) {
                SearchWrapper objSearch = new SearchWrapper(objUser);
                listSearchWrapper.add(objSearch);
            }

        }catch (Exception e){
            strStatus = 'ERROR';
            if (e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                strMessage = e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ',': []');
            }else{
                strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            }
        }
        objWrapper.listSearchWrapper = listSearchWrapper;
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        System.debug( 'objWrapper :: '  +  objWrapper);

        return objWrapper;
    }

    /**
     * SMA 고객 담당자 변경
     *      
     * @params strOwnerId : 변경할 User Id
     * @params strListTarget : 변경할 SMA 고객리스트
     * @return DataWrapper
     *          - strStatus : 상태값
     *          - strMessage : 메시지
    **/
    @AuraEnabled
    public static DataWrapper doChangeOwner(String strOwnerId, String strListTarget) {

        System.debug('strOwnerId :: ' + strOwnerId);
        System.debug('strListTarget :: ' + strListTarget);

        String strStatus = 'SUCCESS';
        String strMessage = '';
        DataWrapper objWrapper = new DataWrapper();

        if (strOwnerId == null || strListTarget == null || strOwnerId == '' || strListTarget == '') {
            objWrapper.strStatus = 'ERROR';
            objWrapper.strMessage = '변경될 ';
            return objWrapper;
        }


        try {
            List<SearchWrapper> listTarget = (List<SearchWrapper>)JSON.deserialize(strListTarget, List<SearchWrapper>.class);
            List<Account> listUpdate = new List<Account>();

            for(SearchWrapper obj : listTarget) {
                Account objTarget = new Account();

                objTarget.Id = obj.id;
                objTarget.OwnerId = strOwnerId;
                listUpdate.add(objTarget);
            }

            if(listUpdate <> null && listUpdate.size() > 0) {
                update listUpdate;
            }

        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            /*
            if (e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                strMessage = e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ',': []');
            }else{
                strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            }
            */
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    /**
     * SMA 고객 관리 등급 코드 변경
     *      
     * @params strSmaCustMngGrdCd : 변경할 SMA 고객 관리 등급 코드
     * @params strListTarget : 변경할 SMA 고객리스트
     * @return DataWrapper
     *          - strStatus : 상태값
     *          - strMessage : 메시지
    **/
    @AuraEnabled
    public static DataWrapper doChangeSmaCustMngGrdCd(String strSmaCustMngGrdCd, String strListTarget) {

        System.debug('strSmaCustMngGrdCd :: ' + strSmaCustMngGrdCd);
        System.debug('strListTarget :: ' + strListTarget);

        String strStatus = 'SUCCESS';
        String strMessage = '';
        DataWrapper objWrapper = new DataWrapper();

        if (strSmaCustMngGrdCd == null || strListTarget == null || strSmaCustMngGrdCd == 'none' || strSmaCustMngGrdCd == '' || strListTarget == '') {
            objWrapper.strStatus = 'ERROR';
            objWrapper.strMessage = '변경될 대상이 없습니다';
            return objWrapper;
        }


        try {
            List<SearchWrapper> listTarget = (List<SearchWrapper>)JSON.deserialize(strListTarget, List<SearchWrapper>.class);
            List<Account> listUpdate = new List<Account>();

            for(SearchWrapper obj : listTarget) {
                Account objTarget = new Account();

                objTarget.Id = obj.id;
                objTarget.sma_cust_mng_grd_cd__c = strSmaCustMngGrdCd;
                listUpdate.add(objTarget);
            }

            if(listUpdate <> null && listUpdate.size() > 0) {
                update listUpdate;
            }

        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            /*
            if (e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                strMessage = e.getMessage().substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ',': []');
            }else{
                strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
            }
            */
        }
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }


    public class DataWrapper {
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}
        @AuraEnabled
        public String reportUrl {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listLocationStateProvince {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listLocationState {get;set;}
        @AuraEnabled
        public List<Map<String, String>> listSmaCustMngGrdCd {get;set;}
        @AuraEnabled
        public Map<String,List<Map<String, String>>> mapLocation {get;set;}
        @AuraEnabled
        public List<SearchWrapper> listSearchWrapper {get;set;}
    }

    public class SearchWrapper {
        @AuraEnabled
        public String id {get;set;}
        @AuraEnabled
        public String ownerId {get;set;}
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public String ownerName {get;set;}
        @AuraEnabled
        public String ownerEmployeeNumber {get;set;}
        @AuraEnabled
        public String smaCustMngGrdCd {get;set;}
        @AuraEnabled
        public String educationOffice {get;set;}
        @AuraEnabled
        public String phone {get;set;}
        @AuraEnabled
        public String recordLink {get;set;}
        @AuraEnabled
        public String viewDetail {get;set;}
        @AuraEnabled
        public String userName {get;set;}
        @AuraEnabled
        public String employeeNumber {get;set;}
        @AuraEnabled
        public String team {get;set;}
        @AuraEnabled
        public String title {get;set;}
        @AuraEnabled
        public String email {get;set;}

        public SearchWrapper() {
        }

        public SearchWrapper(Account objAccount) {
            this.id = objAccount.Id;
            this.ownerId = objAccount.OwnerId;
            this.name = objAccount.Name;
            this.ownerName = objAccount.Owner.Name;
            this.ownerEmployeeNumber = objAccount.Owner.EmployeeNumber;
            this.smaCustMngGrdCd = objAccount.sma_cust_mng_grd_cd__c;
            this.educationOffice = '';
            this.educationOffice = objAccount.jrsdt_cido_eduofic_cd__c != null ? objAccount.jrsdt_cido_eduofic_cd__c + ' ' : '';
            this.educationOffice += objAccount.jrsdt_gugun_eduofic_cd__c != null ? objAccount.jrsdt_gugun_eduofic_cd__c : '';
            this.phone = objAccount.Phone;
            this.recordLink = '/'+String.valueOf(objAccount.Id);
            this.viewDetail = '상세보기';
        }
        public SearchWrapper(User objUser) {
            this.id = objUser.Id;
            this.userName = objUser.Name;
            this.employeeNumber = objUser.EmployeeNumber;
            this.team = objUser.Team__c;
            this.title = objUser.CJTitle__c;
            this.phone = objUser.Phone;
            this.email = objUser.Email;
            this.recordLink = '/'+String.valueOf(objUser.Id);
            this.viewDetail = '상세보기';
        }
    }
}