force-app/main/default/objects/ExtraService__c/ExtraService__c.object-meta.xml
<CustomObject>
    <label>부가서비스 내역</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Extra Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtraService__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>가망처 대상으로 부가서비스 신청은 불가능합니다.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Existing Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>School Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>부가서비스 내역</relationshipLabel>
    <relationshipName>ExtraServiceCustomer1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/ServiceContents__c.field-meta.xml
<CustomField>
    <fullName>ServiceContents__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contents</label>
    <referenceTo>ServiceContents__c</referenceTo>
    <relationshipName>ExtraServiceContents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T</fullName>
                <default>true</default>
                <label>임시저장</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>접수</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>승인</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>반려</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>완료</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>취소</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ExtraService__c.field-meta.xml
<CustomField>
    <fullName>ExtraService__c</fullName>
    <label>Extra Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContents__c/ServiceContents__c.object-meta.xml
<CustomObject>
    <label>부가서비스 컨텐츠</label>
    <nameField>
        <label>Contents Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ExtraService_tr_test.cls
/************************************************************************************
 * File Name   		    : ExtraService_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2022.11.21
 * Target	  		    : ExtraService_tr.cls
 * Description 		    : ExtraService_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2022.11.21      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class ExtraService_tr_test {
    @isTest 
    static void itShould() {

        Account objAccount = TestObjectCreator.objHealthAccount;
        objAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ExistingCustomer').getRecordTypeId();
        insert objAccount;

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objAccount.Id;
        objOpportunity.Name = '영업활동';
        objOpportunity.CloseDate = date.valueOf('2022-01-01');
        objOpportunity.StageName = 'Proposal';
        insert objOpportunity;

        Test.startTest();
        
        ServiceContents__c objServiceContents = new ServiceContents__c();
        objServiceContents.Name = '부가서비스 컨텐츠';
        insert objServiceContents;
        
        ExtraService__c objExtraService = new ExtraService__c();
        objExtraService.ServiceContents__c = objServiceContents.Id;
        objExtraService.Customer__c = objAccount.Id;
        insert objExtraService;

        String strExtraService = objExtraService.Id;
        objExtraService = new ExtraService__c();
        objExtraService.Id = strExtraService;
        objExtraService.ServiceContents__c = objServiceContents.Id;
        objExtraService.Customer__c = objAccount.Id;
        objExtraService.Status__c = 'A';
        update objExtraService;

        Test.stopTest();
    }
}