force-app/main/default/objects/ClassService__c/ClassService__c.object-meta.xml
<CustomObject>
    <description>교육시스템신청레코드저장 오브젝트
해당레코드의 적합성판단후 부가서비스내역으로 삽입</description>
    <label>교육서비스신청</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassService__c/fields/ApplicantsNumber__c.field-meta.xml
<CustomField>
    <fullName>ApplicantsNumber__c</fullName>
    <label>ApplicantsNumber</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>교육서비스신청</relationshipLabel>
    <relationshipName>Customer</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/CustomerAgeGroup__c.field-meta.xml
<CustomField>
    <fullName>CustomerAgeGroup__c</fullName>
    <label>CustomerAgeGroup</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3세이하</fullName>
            </value>
            <value>
                <fullName>4세</fullName>
            </value>
            <value>
                <fullName>5세</fullName>
            </value>
            <value>
                <fullName>6세</fullName>
            </value>
            <value>
                <fullName>7세</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/CustomerPhone__c.field-meta.xml
<CustomField>
    <fullName>CustomerPhone__c</fullName>
    <label>CustomerPhone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <label>Manager</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/MDMCode__c.field-meta.xml
<CustomField>
    <fullName>MDMCode__c</fullName>
    <label>MDMCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/ServiceContent__c.field-meta.xml
<CustomField>
    <fullName>ServiceContent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>부가서비스 컨텐츠</label>
    <referenceTo>ServiceContents__c</referenceTo>
    <relationshipName>ClassService</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H</fullName>
                <label>신청접수</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>신청완료</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>신청거부</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClassService__c/fields/TargetGroup__c.field-meta.xml
<CustomField>
    <fullName>TargetGroup__c</fullName>
    <label>TargetGroup</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>원장</fullName>
            </value>
            <value>
                <fullName>어린이</fullName>
            </value>
            <value>
                <fullName>교직원</fullName>
            </value>
            <value>
                <fullName>학부모</fullName>
            </value>
            <value>
                <fullName>학부모참여</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
            <value>
                <fullName>실버</fullName>
            </value>
            <value>
                <fullName>보육원성인</fullName>
            </value>
            <value>
                <fullName>보육원</fullName>
            </value>
            <value>
                <fullName>지적장애인</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExtraService__c/ExtraService__c.object-meta.xml
<CustomObject>
    <label>부가서비스 내역</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Extra Service Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ExtraService__c/fields/ApplicantsNumber__c.field-meta.xml
<CustomField>
    <fullName>ApplicantsNumber__c</fullName>
    <label>Applicants Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>가망처 대상으로 부가서비스 신청은 불가능합니다.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Existing Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>School Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>부가서비스 내역</relationshipLabel>
    <relationshipName>ExtraServiceCustomer1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/CustomerAgeGroup__c.field-meta.xml
<CustomField>
    <fullName>CustomerAgeGroup__c</fullName>
    <label>Customer age group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>TargetGroup__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
                <label>3세이하</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4세</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5세</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6세</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7세</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/CustomerPhone__c.field-meta.xml
<CustomField>
    <fullName>CustomerPhone__c</fullName>
    <label>Customer Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T</fullName>
                <default>true</default>
                <label>임시저장</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>접수</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>승인</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>반려</label>
            </value>
            <value>
                <fullName>F</fullName>
                <label>완료</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>취소</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ExtraService__c/fields/TargetGroup__c.field-meta.xml
<CustomField>
    <fullName>TargetGroup__c</fullName>
    <label>Target Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D</fullName>
                <label>원장</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>어린이</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>교직원</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>학부모</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>학부모참여</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>기타</label>
            </value>
            <value>
                <fullName>실버</fullName>
            </value>
            <value>
                <fullName>보육원성인</fullName>
            </value>
            <value>
                <fullName>보육원</fullName>
            </value>
            <value>
                <fullName>지적장애인</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/changeToExtraServiceBtn.cls
/**
 * @description       : 
 * @author            : 백영주
 * @group             : 
 * @last modified on  : 08-16-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class changeToExtraServiceBtn {
    public changeToExtraServiceBtn() {

    }
    @AuraEnabled
    public static DataWrapper doInit(String recordId) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        DataWrapper objWrapper = new DataWrapper();

        try {

        } catch(Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        return objWrapper;
    }

    @AuraEnabled
	public static DataWrapper doChangeRecord(String recordId) {
        String strStatus = 'SUCCESS';
        String strMessage = '';

        DataWrapper objWrapper = new DataWrapper();
        try{
            List<ClassService__c> updateList = new List<ClassService__c>();
            updateList = [
                SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, LastReferencedDate, ServiceContent__c, MDMCode__c, Status__c, Customer__c, Manager__c, CustomerPhone__c, TargetGroup__c, ApplicantsNumber__c, CustomerAgeGroup__c, Address__c, Description__c 
                FROM ClassService__c 
                WHERE Id =:recordId
            ];
            List<ExtraService__c> insertList = new List<ExtraService__c>();
            for(ClassService__c cs : updateList){
                cs.Status__c = 'C';
                ExtraService__c extra = new ExtraService__c();

            }   
            update updateList;

        }catch(Exception e){
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }
        return objWrapper;

    }
    public class DataWrapper {
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}
	}
}