force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/CRG_MA_ID__c.field-meta.xml
<CustomField>
    <fullName>CRG_MA_ID__c</fullName>
    <externalId>true</externalId>
    <label>MA</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/ORDR_REAL_BUY_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>ORDR_REAL_BUY_UNPRC__c</fullName>
    <label>Operating Price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/RLSTK_UNIT_RLSTK_QTY__c.field-meta.xml
<CustomField>
    <fullName>RLSTK_UNIT_RLSTK_QTY__c</fullName>
    <label>Billing quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALE_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>SALE_UNPRC__c</fullName>
    <label>Operating unit price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_AT__c</fullName>
    <label>net sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLST__c.field-meta.xml
<CustomField>
    <fullName>SLST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesLedgerAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesMonthOfMASummary_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-10-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class SalesMonthOfMASummary_test {
    @TestSetup
    static void testSetup(){
        Account objAccount = TestObjectCreator.objExAccount;

        insert objAccount;

        SalesLedgerInformation__c objSales = new SalesLedgerInformation__c();

        objSales.SLST__c = objAccount.Id;
        objSales.SALES_YMD__c = Date.today();
        objSales.CRG_MA_ID__c = 'test1234';
        objSales.SALE_UNPRC__c = 1000;
        objSales.ORDR_REAL_BUY_UNPRC__c = 500;
        objSales.RLSTK_UNIT_RLSTK_QTY__c = 1;
        objSales.SALES_AT__c = 500;

        insert objSales;

        User objUser = new User();
        objUser.Id = UserInfo.getUserId();
        objUser.EmployeeNumber = 'test1234';

        update objUser;
    }

    @isTest
    static void itShouldSC() {
        Test.startTest();
        String CRON_EXP1 = '0 0 3 * * ? *';  // 초 분 시 일 월 ? ?  관련하여 Cron expression 검색.    
        SalesMonthOfMASummary_sc sc = new SalesMonthOfMASummary_sc(5);
        System.schedule('test', CRON_EXP1, sc);
        Test.stopTest();
    }
    
    @isTest
    static void itShould() {
        Test.startTest();

        Date endDate = Date.newInstance(Date.today().year(), Date.today().month(), Date.today().addDays(1).day());

        SalesMonthOfMASummary_ba ba = new SalesMonthOfMASummary_ba(Date.today().addDays(-1), endDate, UserInfo.getUserId(), true, 5);
        Database.executeBatch(ba);

        Test.stopTest();
    }
}