force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_AT__c</fullName>
    <label>net sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLST__c.field-meta.xml
<CustomField>
    <fullName>SLST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesLedgerAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesDecreaseNotice_ba.cls
/**
 * @description       :
 * @author            : JeonKwanWoo(kwanwoo.jeon@daeunextier.com)
 * @group             :
 * @last modified on  : 01-02-2023
 * @last modified by  : JeonKwanWoo(kwanwoo.jeon@daeunextier.com)
**/
global with sharing class SalesDecreaseNotice_ba implements Database.Batchable<SObject>, Database.Stateful {
    global Date targetDate;

    global SalesDecreaseNotice_ba() {
        if (targetDate == null) {
            this.targetDate = Date.today();
        } else {
            this.targetDate = targetDate;
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = 'SELECT Id FROM User WHERE IsActive = TRUE';
        strQuery += Test.isRunningTest()?' and id = \'' : '';
        strQuery += Test.isRunningTest()? UserInfo.getUserId(): '';
        strQuery += Test.isRunningTest()?'\' LIMIT 10' : '';
        return Database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext bc, List<User> scope) {
        Set<Id> setUserId = new Set<Id>();
        for (User obj: scope){
            setUserId.add(obj.Id);
        }
        Map<Id, Decimal> mapAccIdToTwoWeekAgo = new Map<Id, Decimal>();
        Id recordIdEx = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ExistingCustomer').getRecordTypeId();
        Map<Id, Account> mapIdToAcc = new Map<Id, Account>([SELECT Name, OwnerId FROM Account WHERE RecordTypeId = :recordIdEx]);

        CustomNotificationType objCustomNotification = [
                SELECT Id, DeveloperName
                FROM CustomNotificationType
                WHERE DeveloperName = 'CustomNotification'
        ];

        String strQueryOneWeek = '';
        String strQueryTwoWeek = '';
        strQueryOneWeek += '    SELECT  SLST__c AccountId, SUM(SALES_AT__c) totalSalesAmount';
        strQueryOneWeek += '    FROM    SalesLedgerInformation__c';
        strQueryOneWeek += '    WHERE   SLST__r.OwnerId IN : setUserId';
        strQueryOneWeek += '    AND   SLST__c != null';
        strQueryTwoWeek += strQueryOneWeek;
        if (this.targetDate <> null) {
            Date oneWeekAgo = Date.newInstance(this.targetDate.year(), this.targetDate.month(), this.targetDate.day() - 7);
            Date twoWeekAgo = Date.newInstance(this.targetDate.year(), this.targetDate.month(), this.targetDate.day() - 14);
            Date endDate = Date.newInstance(this.targetDate.year(), this.targetDate.month(), this.targetDate.day());

            strQueryOneWeek += '   AND      SALES_YMD__c >=:oneWeekAgo';
            strQueryOneWeek += '   AND      SALES_YMD__c <:endDate';

            strQueryTwoWeek += '   AND      SALES_YMD__c >=:twoWeekAgo';
            strQueryTwoWeek += '   AND      SALES_YMD__c <:oneWeekAgo';
        }

        strQueryOneWeek += '    GROUP BY    SLST__c';
        strQueryTwoWeek += '    GROUP BY    SLST__c';

        for (AggregateResult ar : Database.query(strQueryTwoWeek)) {
            mapAccIdToTwoWeekAgo.put(String.valueOf(ar.get('AccountId')), Decimal.valueOf(String.valueOf(ar.get('totalSalesAmount'))));
        }

        for (AggregateResult ar : Database.query(strQueryOneWeek)) {
            String accId = String.valueOf(ar.get('AccountId'));
            Decimal totalSalesAmount = Decimal.valueOf(String.valueOf(ar.get('totalSalesAmount')));
            if (mapAccIdToTwoWeekAgo.get(accId) != null && totalSalesAmount < mapAccIdToTwoWeekAgo.get(accId) * 0.7) {
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
                notification.setTitle('고객 매출 감소 알림');
                notification.setBody(mapIdToAcc.get(accId).Name + ' 고객의 매출이 30% 감소되었습니다.');
                notification.setNotificationTypeId(objCustomNotification.Id);
                notification.setTargetId(accId);
                notification.send(new Set<String>{mapIdToAcc.get(accId).OwnerId});
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
    }


}