force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MIG_ORDER_DEL_ba_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-23-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class MIG_ORDER_DEL_ba_test {
    @testSetup
	static void setData() {
        SalesLedgerInformation__c obj = new SalesLedgerInformation__c();
                
        obj.SALES_YMD__c = Date.today();        

        insert obj;

	}
    @isTest 
    static void itShould() {
        MIG_ORDER_DEL_ba b = new MIG_ORDER_DEL_ba(null, Date.today().addDays(1));
        Database.executeBatch(b);
    }
}