force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_AT__c</fullName>
    <label>net sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLST__c.field-meta.xml
<CustomField>
    <fullName>SLST__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SalesLedgerAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SalesDecreaseNotice_test.cls
/**
 * Created by kw on 2023-01-06.
 */
@IsTest
public with sharing class SalesDecreaseNotice_test {
    @TestSetup
    static void makeData() {
        User objUser = new User();
        String username = 'test00';
        objUser.Username = username + '@test.com';
        objUser.LastName = 'LastTest';
        objUser.Email = 'testemail@test.com';
        objUser.Alias = 'test';
        objUser.TimeZoneSidKey = 'America/New_York';
        objUser.LocaleSidKey = 'en_US';
        objUser.EmailEncodingKey = 'ISO-8859-1';
        objUser.LanguageLocaleKey = 'en_US';
        objUser.ProfileId = [SELECT Id FROM Profile WHERE Name = '시스템 관리자' OR Name = 'System Administrator' LIMIT 1].Id;
        Account objAccount = TestObjectCreator.objExAccount;
        insert objAccount;
        Date today = Date.today();
        List<SalesLedgerInformation__c> listSLI = new List<SalesLedgerInformation__c>();
        SalesLedgerInformation__c objSLI = new SalesLedgerInformation__c();
        objSLI.SLST__c = objAccount.Id;
        objSLI.SALES_YMD__c = today - 1;
        objSLI.SALES_AT__c = 10;
        SalesLedgerInformation__c objSLI2 = objSLI.clone();
        objSLI2.SALES_YMD__c = today - 8;
        objSLI2.SALES_AT__c = 1000;
        listSLI.add(objSLI);
        listSLI.add(objSLI2);
        insert listSLI;



    }

    @IsTest
    static void SalesDecreaseNotice_test() {
        Test.startTest();
        SalesDecreaseNotice_sc sc = new SalesDecreaseNotice_sc();
        String sch = '0 0 * * * ?';
        String jobID = System.schedule('Merge Job', sch, sc);
        Test.stopTest();
    }
}