force-app/main/default/objects/SalesLedgerInformation__c/SalesLedgerInformation__c.object-meta.xml
<CustomObject>
    <description>매출원장정보</description>
    <label>매출원장정보</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BARCD_NO__c.field-meta.xml
<CustomField>
    <fullName>BARCD_NO__c</fullName>
    <label>Bar code number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BAS_TKSTK_QTY__c.field-meta.xml
<CustomField>
    <fullName>BAS_TKSTK_QTY__c</fullName>
    <label>Actual weight</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BCNR_ID__c.field-meta.xml
<CustomField>
    <fullName>BCNR_ID__c</fullName>
    <label>Partner code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BILI_DOC_NO__c.field-meta.xml
<CustomField>
    <fullName>BILI_DOC_NO__c</fullName>
    <externalId>true</externalId>
    <label>Billing document number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BOX_CTCNT_QTY__c.field-meta.xml
<CustomField>
    <fullName>BOX_CTCNT_QTY__c</fullName>
    <label>Commodity Box Acquisition Volume</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/BRC_ID__c.field-meta.xml
<CustomField>
    <fullName>BRC_ID__c</fullName>
    <label>BRC_ID</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>235</fullName>
                <label>원료)축산시너지팀</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>322</fullName>
                <label>급식)급식솔루션동부1팀</label>
            </value>
            <value>
                <fullName>323</fullName>
                <label>급식)급식솔루션서부팀</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
            <value>
                <fullName>337</fullName>
                <label>급식)급식솔루션동부2팀</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>347</fullName>
                <label>유통중부)유통글로벌식재팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>320</fullName>
                <label>급식)급식솔루션1팀</label>
            </value>
            <value>
                <fullName>321</fullName>
                <label>급식)급식솔루션2팀</label>
            </value>
            <value>
                <fullName>325</fullName>
                <label>급식)급식솔루션지원</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>346</fullName>
                <label>튼튼스쿨)튼튼스쿨2팀</label>
            </value>
            <value>
                <fullName>374</fullName>
                <label>헬씨누리)헬씨누리전문점팀</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/CRG_MA_ID__c.field-meta.xml
<CustomField>
    <fullName>CRG_MA_ID__c</fullName>
    <externalId>true</externalId>
    <label>MA</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/DSTR_HIS_MNG_YN_NM__c.field-meta.xml
<CustomField>
    <fullName>DSTR_HIS_MNG_YN_NM__c</fullName>
    <label>Distribution history number type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/DSTR_HIS_NO_RPT_OBJ_YN_NM__c.field-meta.xml
<CustomField>
    <fullName>DSTR_HIS_NO_RPT_OBJ_YN_NM__c</fullName>
    <label>Distribution history reporting agency</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/fm_OurHeadOffice__c.field-meta.xml
<CustomField>
    <fullName>fm_OurHeadOffice__c</fullName>
    <formula>if( Text(CRG_MA__r.HeadOffice__c) =  Text($User.HeadOffice__c) , &quot;Y&quot; , &quot;N&quot; )</formula>
    <label>OurHeadOffice</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/fm_OurSu__c.field-meta.xml
<CustomField>
    <fullName>fm_OurSu__c</fullName>
    <formula>If( Text(  CRG_MA__r.SU__c  ) =  Text($User.SU__c) , &quot;Y&quot; , &quot;N&quot; )</formula>
    <label>OurSu</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/fm_OurTeam__c.field-meta.xml
<CustomField>
    <fullName>fm_OurTeam__c</fullName>
    <formula>if( Text(CRG_MA__r.Team__c ) = Text($User.Team__c) , &quot;Y&quot; , &quot;N&quot; )</formula>
    <label>OurTeam</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/GD_NO__c.field-meta.xml
<CustomField>
    <fullName>GD_NO__c</fullName>
    <externalId>true</externalId>
    <label>Product code</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/MNGPLC_ID__c.field-meta.xml
<CustomField>
    <fullName>MNGPLC_ID__c</fullName>
    <label>Management Place code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/OPT_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>OPT_UNPRC__c</fullName>
    <label>an appropriate selling price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/ORDR_NO__c.field-meta.xml
<CustomField>
    <fullName>ORDR_NO__c</fullName>
    <externalId>true</externalId>
    <label>Order number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/ORDR_OPT_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>ORDR_OPT_UNPRC__c</fullName>
    <label>an appropriate order price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/ORDR_REAL_BUY_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>ORDR_REAL_BUY_UNPRC__c</fullName>
    <label>Operating Price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/REAL_BUY_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>REAL_BUY_UNPRC__c</fullName>
    <label>Original Price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/RLSTK_UNIT_RLSTK_QTY__c.field-meta.xml
<CustomField>
    <fullName>RLSTK_UNIT_RLSTK_QTY__c</fullName>
    <label>Billing quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/RLSTK_UNIT_RLSTK_QTY_KG__c.field-meta.xml
<CustomField>
    <fullName>RLSTK_UNIT_RLSTK_QTY_KG__c</fullName>
    <label>KG conversion quantity</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALE_UNPRC__c.field-meta.xml
<CustomField>
    <fullName>SALE_UNPRC__c</fullName>
    <label>Operating unit price</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_AT__c</fullName>
    <label>net sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_LNKG_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>SALES_LNKG_CL_CD__c</fullName>
    <externalId>true</externalId>
    <label>Type code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_LNKG_CL_NM__c.field-meta.xml
<CustomField>
    <fullName>SALES_LNKG_CL_NM__c</fullName>
    <label>type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_P_RT__c.field-meta.xml
<CustomField>
    <fullName>SALES_P_RT__c</fullName>
    <label>an addition/decrease ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_SUM_AT__c.field-meta.xml
<CustomField>
    <fullName>SALES_SUM_AT__c</fullName>
    <label>gross sales</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_TAT__c.field-meta.xml
<CustomField>
    <fullName>SALES_TAT__c</fullName>
    <label>Surtax</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SALES_YMD__c.field-meta.xml
<CustomField>
    <fullName>SALES_YMD__c</fullName>
    <label>Billing date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SAP_ERR_MSG__c.field-meta.xml
<CustomField>
    <fullName>SAP_ERR_MSG__c</fullName>
    <label>Remarks</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLBZ_ORG_ID__c.field-meta.xml
<CustomField>
    <fullName>SLBZ_ORG_ID__c</fullName>
    <label>SLBZ_ORG_ID</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/SLST_ID__c.field-meta.xml
<CustomField>
    <fullName>SLST_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer code</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesLedgerInformation__c/fields/TAXT_CL_CD_NM__c.field-meta.xml
<CustomField>
    <fullName>TAXT_CL_CD_NM__c</fullName>
    <label>tax</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesLedgerInformationDel_test.cls
/**
 * @description       : 
 * @author            : AhnTaeJin(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 11-27-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public with sharing class SalesLedgerInformationDel_test {

    @TestSetup
    static void makeData(){
        SalesLedgerInformation__c obj = new SalesLedgerInformation__c();
        obj.SALES_YMD__c=Date.valueOf('2022-08-04');
        obj.SALES_LNKG_CL_CD__c='ZP05';
        obj.SALES_LNKG_CL_NM__c='자가소비 판촉 오더';
        obj.ORDR_NO__c='2172550485';
        obj.BILI_DOC_NO__c='Z000000000';
        obj.SLST_ID__c='468100';
        obj.BRC_ID__c='374';
        obj.MNGPLC_ID__c='468100';
        obj.CRG_MA_ID__c='253655';
        // obj.fm_OurHeadOffice__c=true;
        // obj.fm_OurSu__c=true;
        // obj.fm_OurTeam__c=true;
        obj.SLBZ_ORG_ID__c='3001';
        obj.GD_NO__c='246734';
        obj.BARCD_NO__c='8801111186247';
        obj.BCNR_ID__c='1001399';
        obj.DSTR_HIS_NO_RPT_OBJ_YN_NM__c='해당없음';
        obj.DSTR_HIS_MNG_YN_NM__c='대상아님';
        obj.TAXT_CL_CD_NM__c='과세';
        obj.RLSTK_UNIT_RLSTK_QTY__c=3;
        obj.RLSTK_UNIT_RLSTK_QTY_KG__c=0.426;
        obj.BOX_CTCNT_QTY__c=20;
        obj.REAL_BUY_UNPRC__c=1991;
        obj.OPT_UNPRC__c=3587;
        obj.ORDR_REAL_BUY_UNPRC__c=1991;
        obj.ORDR_OPT_UNPRC__c=3587;
        obj.SALE_UNPRC__c=3766;
        obj.SALES_AT__c=0;
        obj.SALES_TAT__c=0;
        obj.SALES_SUM_AT__c=0;
        obj.SALES_P_RT__c=4.990242542514636;
        obj.SAP_ERR_MSG__c='';
        obj.BAS_TKSTK_QTY__c=3;
        obj.DIV_ID__c='4705';
        // obj.fm_MyData__c=false;
        obj.ISLIQ__c=false;
        obj.RLSTK_UNIT__c='EA';
        obj.BAS_UNIT__c='EA';
        obj.SPLY_CTR_ID__c='2600';
        obj.SHIPLC_ID__c='2600';
        obj.ExtId__c='2172550485_Z000000000_246734';
        obj.CUST_NM__c='헬씨누리)헬씨누리전문점팀';
        obj.MNGPLC_NM__c='헬씨누리)헬씨누리전문점팀';
        // obj.CRG_MA__c='';
        obj.CRG_MA_NM__c='신승윤';
        obj.BCNR_NM__c='(주)명현유통';
        obj.PB_GD_CL__c='40';
        obj.GD_NM__c='크라운제과 화이트하임(142g/EA)';
        // obj.GD__c='';
        // obj.fm_SalesProfit__c='5325';
        // obj.fm_SalesCost__c='5973';

        insert obj;
    }

    @isTest
    static void testSalesLedgerInformationDel_test() {
        Test.startTest();

        Date targetDate = Date.today();

        SalesLedgerInformationDel_sc sc = new SalesLedgerInformationDel_sc();
        sc.execute(null);
        Test.stopTest();
    }
}