force-app/main/default/objects/CJOilPrice__c/CJOilPrice__c.object-meta.xml
<CustomObject>
    <label>대두유 시황</label>
    <nameField>
        <label>PriceListName</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJOilPrice__c/fields/WholesalePrice__c.field-meta.xml
<CustomField>
    <fullName>WholesalePrice__c</fullName>
    <label>WholesalePrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CjOilPrice_tr_test.cls
/************************************************************************************
 * File Name   		    : CjOilPrice_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2023.02.06
 * Target	  		    : CjOilPrice_tr.cls
 * Description 		    : CjOilPrice_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.02.06      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class CjOilPrice_tr_test {
    @isTest 
    static void itShould() {

        Test.startTest();
        CJOilPrice__c objCJOilPrice = new CJOilPrice__c();
        objCJOilPrice.Name = '대두유 1';
        objCJOilPrice.WholesalePrice__c = 0;
        insert objCJOilPrice;

        String strServiceContentsId = objCJOilPrice.Id;
        objCJOilPrice.WholesalePrice__c = 1000;
        update objCJOilPrice;
        Test.stopTest();
    }
}