force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c.object-meta.xml
<CustomObject>
    <label>IF_IFRESH_SFDC_VOC_INFO_DETAIL</label>
    <nameField>
        <displayFormat>No-{00000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c/fields/IsNotVOC__c.field-meta.xml
<CustomField>
    <fullName>IsNotVOC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsNotVOC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IF_DUMMY_DEL_ba_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-31-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class IF_DUMMY_DEL_ba_test {
    @testSetup
	static void setData() {
        IF_IFRESH_SFDC_VOC_INFO_DETAIL__c obj = new IF_IFRESH_SFDC_VOC_INFO_DETAIL__c();
                
        obj.transactionId__c = 'test12345';
        obj.IsUpdate__c = true;
        obj.IsNotVOC__c = false;

        insert obj;

	}
    @isTest 
    static void itShould() {
        IF_DUMMY_DEL_ba b = new IF_DUMMY_DEL_ba('IF_IFRESH_SFDC_VOC_INFO_DETAIL__c', 'test12345');
        Database.executeBatch(b);
    }

    @isTest 
    static void itShould2() {
        IF_DUMMY_DEL_sc scd = new IF_DUMMY_DEL_sc('IF_IFRESH_SFDC_VOC_INFO_DETAIL__c');
        SchedulableContext sc = null;
        scd.execute(sc);
    }
}