force-app/main/default/objects/VOC__c/VOC__c.object-meta.xml
<CustomObject>
    <label>VOC</label>
    <nameField>
        <label>VOC Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOC__c/fields/img_file_url2__c.field-meta.xml
<CustomField>
    <fullName>img_file_url2__c</fullName>
    <label>img_file_url2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/VOCImageView_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-24-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class VOCImageView_test {
    @testSetup 
    public static void setup(){
        
    }

    @isTest 
    static void itShould() {
        VOC__c objVOC = TestObjectCreator.objVOC;
        objVOC.img_file_url1__c = 'https://www.naver.com';
        objVOC.img_file_url2__c = 'https://www.naver.com';
        objVOC.img_file_url3__c = 'https://www.naver.com';

        insert objVOC;

        VOCImageView.doInit(objVOC.Id);
    }
}