force-app/main/default/objects/PT__c/PT__c.object-meta.xml
<CustomObject>
    <label>PT</label>
    <nameField>
        <label>PT Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PT__c/fields/ActivityInfo__c.field-meta.xml
<CustomField>
    <fullName>ActivityInfo__c</fullName>
    <label>ActivityInfo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PT__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>PT</relationshipLabel>
    <relationshipName>PT</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PT_tr_test.cls
/************************************************************************************
 * File Name   		    : PT_tr_test.cls
 * Author	  		    : Yooree.Lee
 * Date				    : 2023.01.30
 * Target	  		    : PT_tr.cls
 * Description 		    : PT_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.01.30      Yooree.Lee       Create
 *************************************************************************************/

@IsTest
private class PT_tr_test {
    @IsTest
    static void PT_tr_test() {
        Account objAccount = TestObjectCreator.objHealthAccount;
        insert objAccount;

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objAccount.Id;
        objOpportunity.Name = '영업활동';
        objOpportunity.CloseDate = date.valueOf('2023-01-31');
        objOpportunity.StageName = 'Negotiation';
        insert objOpportunity;

        Test.startTest();

        PT__c objPT = new PT__c();
        objPT.Opportunity__c = objOpportunity.Id;
        objPT.Name = 'PT';
        objPT.StartDateTime__c = Datetime.newInstance(System.now().year(), System.now().month(),System.now().day(),0,0,0);
        objPT.EndDateTime__c = Datetime.newInstance(System.now().year(), System.now().month(),System.now().day() + 1,0,0,0);
        objPT.WorkType__c = '내근';
        objPT.ActivityInfo__c = 'test';
        insert objPT;

        String strPTId = objPT.Id;
        objPT = new PT__c();
        objPT.Id = strPTId;
        objPT.Name = 'PT Edit';
        objPT.StartDateTime__c = Datetime.newInstance(System.now().year(), System.now().month(),System.now().day() +2,0,0,0);
        objPT.EndDateTime__c = Datetime.newInstance(System.now().year(), System.now().month(),System.now().day() +3,0,0,0);
        objPT.WorkType__c = '외근';
        objPT.ActivityInfo__c = 'test2';
        update objPT;
        
        delete objPT;

        Test.stopTest();
    }
}