force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/HeadOfficeLabel__c.field-meta.xml
<CustomField>
    <fullName>HeadOfficeLabel__c</fullName>
    <label>HeadOfficeLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SULabel__c.field-meta.xml
<CustomField>
    <fullName>SULabel__c</fullName>
    <label>SULabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SU__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>377</fullName>
                <label>FS본부)기타</label>
            </value>
            <value>
                <fullName>225</fullName>
                <label>FS개발)개발1팀</label>
            </value>
            <value>
                <fullName>226</fullName>
                <label>FS개발)개발2팀</label>
            </value>
            <value>
                <fullName>227</fullName>
                <label>FS개발)동부개발팀</label>
            </value>
            <value>
                <fullName>228</fullName>
                <label>FS개발)서부개발팀</label>
            </value>
            <value>
                <fullName>229</fullName>
                <label>FS개발)호남개발팀</label>
            </value>
            <value>
                <fullName>232</fullName>
                <label>FS개발)FS개발지원팀</label>
            </value>
            <value>
                <fullName>240</fullName>
                <label>FS개발)개발담당</label>
            </value>
            <value>
                <fullName>353</fullName>
                <label>FS개발)컨세션개발팀</label>
            </value>
            <value>
                <fullName>378</fullName>
                <label>FS개발)병원·레저개발팀</label>
            </value>
            <value>
                <fullName>264</fullName>
                <label>외식남부)외식동부팀</label>
            </value>
            <value>
                <fullName>270</fullName>
                <label>외식남부)외식남부지원</label>
            </value>
            <value>
                <fullName>271</fullName>
                <label>외식남부)외식서부팀</label>
            </value>
            <value>
                <fullName>153</fullName>
                <label>아이누리)아이누리1팀</label>
            </value>
            <value>
                <fullName>300</fullName>
                <label>아이누리)아이누리동부팀</label>
            </value>
            <value>
                <fullName>314</fullName>
                <label>아이누리)아이누리2팀</label>
            </value>
            <value>
                <fullName>338</fullName>
                <label>아이누리)아이누리지원</label>
            </value>
            <value>
                <fullName>363</fullName>
                <label>아이누리)아이누리서부팀</label>
            </value>
            <value>
                <fullName>365</fullName>
                <label>아이누리)아이누리3팀</label>
            </value>
            <value>
                <fullName>246</fullName>
                <label>외식중부)외식중부지원</label>
            </value>
            <value>
                <fullName>247</fullName>
                <label>외식중부)외식3팀</label>
            </value>
            <value>
                <fullName>251</fullName>
                <label>외식중부)외식솔루션영업팀</label>
            </value>
            <value>
                <fullName>348</fullName>
                <label>외식중부)외식2팀</label>
            </value>
            <value>
                <fullName>366</fullName>
                <label>외식중부)외식1팀</label>
            </value>
            <value>
                <fullName>146</fullName>
                <label>원료)원료시너지팀</label>
            </value>
            <value>
                <fullName>151</fullName>
                <label>원료)원료사업부 지원</label>
            </value>
            <value>
                <fullName>184</fullName>
                <label>원료)축산시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>185</fullName>
                <label>원료)그룹시너지팀(푸드빌)</label>
            </value>
            <value>
                <fullName>187</fullName>
                <label>원료)그룹시너지팀(FV기타)</label>
            </value>
            <value>
                <fullName>198</fullName>
                <label>디지털)프레시마켓</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/TeamLabel__c.field-meta.xml
<CustomField>
    <fullName>TeamLabel__c</fullName>
    <label>TeamLabel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/User_tr.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-07-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class User_tr extends TriggerHandler {
    public User_tr() {
        listNew = (List<User>) trigger.new;
        mapOld = (Map<Id, User>) trigger.oldMap;
        listOld = (List<User>) trigger.old;
    }

    /*** TriggerHandler ***/
    private List<User> listNew { get; set; }
    private List<User> listOld { get; set; }
    private Map<Id, User> mapOld { get; set; }

    public override void beforeInsert() {
        doSetRoleName();
    }

    public override void beforeUpdate() {
        doSetRoleName();
    }

    public override void afterUpdate() {
    }

    /***********************************************************************************************************
    *  Trigger  : Before Insert, Before Update
    *  내용     : 레코드 생성, 변경시 UserRole 자동세팅
    ************************************************************************************************************/
    private void doSetRoleName() {
        Map<String, String> mapHeadOfficeNm = CommonUtil.getMapPickListValuetoLabel('User', 'HeadOffice__c');
        Map<String, String> mapSUNm = CommonUtil.getMapPickListValuetoLabel('User', 'SU__c');
        Map<String, String> mapTeamNm = CommonUtil.getMapPickListValuetoLabel('User', 'Team__c');

        List<User> listTarget = new List<User>();

        for(User obj : listNew) {
            if(obj.HeadOffice__c <> null && mapHeadOfficeNm <> null && mapHeadOfficeNm.get(obj.HeadOffice__c) <> null) {
                obj.HeadOfficeLabel__c = mapHeadOfficeNm.get(obj.HeadOffice__c);
            }else {
                obj.HeadOfficeLabel__c = null;
            }

            if(obj.SU__c <> null && mapSUNm <> null && mapSUNm.get(obj.SU__c) <> null) {
                obj.SULabel__c = mapSUNm.get(obj.SU__c);
            }else {
                obj.SULabel__c = null;
            }

            if(obj.Team__c <> null && mapTeamNm <> null && mapTeamNm.get(obj.Team__c) <> null) {
                obj.TeamLabel__c = mapTeamNm.get(obj.Team__c);
            }else {
                obj.TeamLabel__c = null;
            }
        }
    }
}