force-app/main/default/objects/FieldBriefing__c/FieldBriefing__c.object-meta.xml
<CustomObject>
    <label>현장설명회</label>
    <nameField>
        <label>공고명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieldBriefing__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Field_Briefing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FieldBriefing__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FieldBriefing_tr_test.cls
/************************************************************************************
 * File Name   		    : FieldBriefing_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2022.11.21
 * Target	  		    : FieldBriefing_tr.cls
 * Description 		    : FieldBriefing_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2022.11.21      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class FieldBriefing_tr_test {
    @isTest 
    static void itShould() {

        Account objAccount = TestObjectCreator.objHealthAccount;
        insert objAccount;

        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objAccount.Id;
        objOpportunity.Name = '영업활동';
        objOpportunity.CloseDate = date.valueOf('2022-01-01');
        objOpportunity.StageName = 'Proposal';
        insert objOpportunity;


        Test.startTest();
        FieldBriefing__c objFieldBriefing = new FieldBriefing__c();
        objFieldBriefing.Opportunity__c = objOpportunity.Id;
        objFieldBriefing.Name = '현장설명회';
        objFieldBriefing.StartDateTime__c = datetime.valueOf('2022-01-01 15:00:00.000Z');
        objFieldBriefing.EndDateTime__c = datetime.valueOf('2022-01-02 15:00:00.000Z');
        insert objFieldBriefing;

        String strFieldBriefingId = objFieldBriefing.Id;
        objFieldBriefing = new FieldBriefing__c();
        objFieldBriefing.Id = strFieldBriefingId;
        objFieldBriefing.Name = '현장설명회 EDIT';
        update objFieldBriefing;

        Test.stopTest();
    }
}