force-app/main/default/objects/Lead/fields/AuthorizedCapacity__c.field-meta.xml
<CustomField>
    <fullName>AuthorizedCapacity__c</fullName>
    <description>정원</description>
    <label>Authorized Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/KindergartenCode__c.field-meta.xml
<CustomField>
    <fullName>KindergartenCode__c</fullName>
    <description>어린이집코드</description>
    <externalId>true</externalId>
    <label>Kindergarten Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BasePurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePurchasePrice__c</fullName>
    <label>Base Purchase Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CountryOfOriginName__c.field-meta.xml
<CustomField>
    <fullName>CountryOfOriginName__c</fullName>
    <label>원산지</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fm_PriceBookEntryName__c.field-meta.xml
<CustomField>
    <fullName>fm_PriceBookEntryName__c</fullName>
    <formula>PricebookEntry.Product2.Name</formula>
    <label>상품명</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fm_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>fm_ProductCode__c</fullName>
    <formula>Product2.gd_no__c</formula>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/fm_QuantityUnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>fm_QuantityUnitOfMeasure__c</fullName>
    <formula>Text(  Product2.bas_unit_cd__c  )</formula>
    <label>Quantity Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LogisticsCenter__c.field-meta.xml
<CustomField>
    <fullName>LogisticsCenter__c</fullName>
    <label>Logistics Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1000</fullName>
                <label>KX물류센터</label>
            </value>
            <value>
                <fullName>2040</fullName>
                <label>제주FS센터</label>
            </value>
            <value>
                <fullName>2041</fullName>
                <label>제주FC</label>
            </value>
            <value>
                <fullName>2042</fullName>
                <label>제주급식</label>
            </value>
            <value>
                <fullName>2043</fullName>
                <label>제주급식센터(키즈)</label>
            </value>
            <value>
                <fullName>2120</fullName>
                <label>실수요직송센터</label>
            </value>
            <value>
                <fullName>2140</fullName>
                <label>이천)푸드빌센터</label>
            </value>
            <value>
                <fullName>2150</fullName>
                <label>농수가공비축센터</label>
            </value>
            <value>
                <fullName>2170</fullName>
                <label>외부비축창고</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FO 유통</label>
            </value>
            <value>
                <fullName>2230</fullName>
                <label>장성물류센터</label>
            </value>
            <value>
                <fullName>2231</fullName>
                <label>장성물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2240</fullName>
                <label>이천)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2250</fullName>
                <label>양산직수입센터</label>
            </value>
            <value>
                <fullName>2260</fullName>
                <label>양산물류센터</label>
            </value>
            <value>
                <fullName>2261</fullName>
                <label>양산물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2330</fullName>
                <label>장성)아라마크센터</label>
            </value>
            <value>
                <fullName>2340</fullName>
                <label>양산)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2350</fullName>
                <label>대구)아라마크센터</label>
            </value>
            <value>
                <fullName>2360</fullName>
                <label>양산)아라마크센터</label>
            </value>
            <value>
                <fullName>2370</fullName>
                <label>수원2)아라마크센터</label>
            </value>
            <value>
                <fullName>2400</fullName>
                <label>FO중부센터(물류대행)</label>
            </value>
            <value>
                <fullName>2410</fullName>
                <label>FO강남센터(물류대행)</label>
            </value>
            <value>
                <fullName>2420</fullName>
                <label>FO동서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2430</fullName>
                <label>광주외식센터</label>
            </value>
            <value>
                <fullName>2440</fullName>
                <label>FO남서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2450</fullName>
                <label>FO대구센터(물류대행)</label>
            </value>
            <value>
                <fullName>2460</fullName>
                <label>FO부산센터(물류대행)</label>
            </value>
            <value>
                <fullName>2470</fullName>
                <label>FO광주센터(물류대행)</label>
            </value>
            <value>
                <fullName>2480</fullName>
                <label>FO울산센터(물류대행)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HalfOfMonth_PL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProfitMargin__c.field-meta.xml
<CustomField>
    <fullName>ProfitMargin__c</fullName>
    <label>Profit Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TaxTypeName__c.field-meta.xml
<CustomField>
    <fullName>TaxTypeName__c</fullName>
    <label>면세여부</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPriceWithVAT__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceWithVAT__c</fullName>
    <label>Unit Price With VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/HalfOfMonth_PL.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EarlyJan</fullName>
        <label>Early Jan</label>
    </customValue>
    <customValue>
        <fullName>LateJan</fullName>
        <label>Late Jan</label>
    </customValue>
    <customValue>
        <fullName>EarlyFeb</fullName>
        <label>Early Feb</label>
    </customValue>
    <customValue>
        <fullName>LateFeb</fullName>
        <label>Late Feb</label>
    </customValue>
    <customValue>
        <fullName>EarlyMar</fullName>
        <label>Early Mar</label>
    </customValue>
    <customValue>
        <fullName>LateMar</fullName>
        <label>Late Mar</label>
    </customValue>
    <customValue>
        <fullName>EarlyApr</fullName>
        <label>Early Apr</label>
    </customValue>
    <customValue>
        <fullName>LateApr</fullName>
        <label>Late Apr</label>
    </customValue>
    <customValue>
        <fullName>EarlyMay</fullName>
        <label>Early May</label>
    </customValue>
    <customValue>
        <fullName>LateMay</fullName>
        <label>Late May</label>
    </customValue>
    <customValue>
        <fullName>EarlyJun</fullName>
        <label>Early Jun</label>
    </customValue>
    <customValue>
        <fullName>LateJun</fullName>
        <label>Late Jun</label>
    </customValue>
    <customValue>
        <fullName>EarlyJul</fullName>
        <label>Early Jul</label>
    </customValue>
    <customValue>
        <fullName>LateJul</fullName>
        <label>Late Jul</label>
    </customValue>
    <customValue>
        <fullName>EarlyAug</fullName>
        <label>Early Aug</label>
    </customValue>
    <customValue>
        <fullName>LateAug</fullName>
        <label>Late Aug</label>
    </customValue>
    <customValue>
        <fullName>EarlySep</fullName>
        <label>Early Sep</label>
    </customValue>
    <customValue>
        <fullName>LateSep</fullName>
        <label>Late Sep</label>
    </customValue>
    <customValue>
        <fullName>EarlyOct</fullName>
        <label>Early Oct</label>
    </customValue>
    <customValue>
        <fullName>LateOct</fullName>
        <label>Late Oct</label>
    </customValue>
    <customValue>
        <fullName>EarlyNov</fullName>
        <label>Early Nov</label>
    </customValue>
    <customValue>
        <fullName>LateNov</fullName>
        <label>Late Nov</label>
    </customValue>
    <customValue>
        <fullName>EarlyDec</fullName>
        <label>Early Dec</label>
    </customValue>
    <customValue>
        <fullName>LateDec</fullName>
        <label>Late Dec</label>
    </customValue>
    <masterLabel>Half Of Month</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChildCareLeadFileCreateController.cls
/*
* ==================================================================================
*   File Name   : ChildCareLeadFileCreateController.cls
*   Author      : Minje.Kim
*   Date        : 2022.09.29
*   Tester      : ChildCareLeadFileCreateController_test.cls
*   Description : Quote Excel Modal Create
*   Modification Log
* ==================================================================================
*   Ver     Date          Author          Modification
* ==================================================================================
*   1.0     2022.09.29    Minje.Kim       Create
* ==================================================================================
*/

public without sharing class ChildCareLeadFileCreateController {

    /**
     * 미리보기 시 선택가능한 필드 리스트
    */
    public Map<String, String> mapField {
        get {
                List<Map<String, Object>> listFieldMap = CommonUtil.getFieldSet('Lead','LeadItemFileCreate');
                system.debug(' listFieldMap :: ' + listFieldMap);
                Map<String, String> mapTemp= new Map<String, String> ();
                for ( Map<String, Object> objMap : listFieldMap ) {
                    String apiName = String.valueOf(objMap.get('apiName'));
                    String label = String.valueOf(objMap.get('label'));
                    system.debug(' String.valueOf(objMap.get(apiName)) :: ' + String.valueOf(objMap.get('apiName')));
                    system.debug(' String.valueOf(objMap.get(label)) :: ' + String.valueOf(objMap.get('label')));
                    mapTemp.put(apiName , label);
                }
                mapField = mapTemp;
            return mapField;
        }
        set;
    }
    
    /**
     /**
     * 미리보기 시 필수 필드 리스트
    */
    public List<String> listSelectedField {
        get {
            //listSelectedField  = 'Id, Name, Company,  KindergartenCode__c, AddressDetails__c, Phone, FAx, Website,  AuthorizedCapacity__c, AuthorizationDate__c ';
            //if(listSelectedField == null) {
                String strlistSelectedField = 'Company,KindergartenCode__c,AddressDetails__c,Phone,Fax,Website,AuthorizedCapacity__c,AuthorizationDate__c';
                system.debug('strlistSelectedField :: ' + strlistSelectedField );
                listSelectedField = strlistSelectedField.split(',');
                system.debug('listSelectedField :: ' + listSelectedField );
            //}//
            return listSelectedField;
        }
        set;
    }
    
    /**
     * 엑셀 생성 시 Row Span 용 
    */
    public String ExcelColummLength {
        get {
            //if(ExcelColummLength == null) {
                ExcelColummLength = String.valueOf(listSelectedField.size()+2);
            //}
            return ExcelColummLength;
        }
        set;
    }


    /**
     * 견적서 아이템 리스트
    */
    public List<List<Lead>> listLead {
        get {
            listLead = new List<List<Lead>>();
            List<Lead> listTempLead = new List<Lead>();

            //recordId = ApexPages.currentPage().getParameters().get('Id');

            listTempLead= [SELECT  Company, KindergartenCode__c, AddressDetails__c, Phone, Fax, Website, AuthorizedCapacity__c, AuthorizationDate__c
                                        FROM     Lead
                                        LIMIT    10
                                    ];

            system.debug('listTempLead ::::::' + listTempLead );
            
            integer count = 0;
            integer listcount = 0;
            integer totallistsize = listTempLead.size();

            listLead.add(listTempLead);
            /*if (totallistsize == 10000){

                List<QuoteLineItem> listTempLead2 = new List<QuoteLineItem>();
                listTempLead2 = [SELECT   Id, QuoteId, fm_PriceBookEntryName__c, fm_QuantityUnitOfMeasure__c, ProfitMargin__c,
                                                    CountryOfOriginName__c, TaxTypeName__c, fm_ProductCode__c, Product2Id, UnitPriceWithVAT__c, VAT__c,
                                                    PricebookEntryId, ListPrice, UnitPrice, ToLabel(LogisticsCenter__c), ToLabel(Month__c), BasePurchasePrice__c
                                            FROM     QuoteLineItem
                                            WHERE    QuoteId = :recordId
                                            AND      SortOrder > 10000
                                            ORDER BY SortOrder ASC
                                            LIMIT    10000
                                            ];
                                            
                if ( !listTempLead2.isEmpty()){
                    listLead.add(listTempLead2);
                }

            }*/
            system.debug('listLead.size ::::::' + listLead.size() );
            system.debug('[listLead] :: ' + listLead);
            return listLead;
        }
        set;
    }



}