force-app/main/default/objects/STOCK__c/STOCK__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/STOCK__c/fields/isSystemJob__c.field-meta.xml
<CustomField>
    <fullName>isSystemJob__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isSystemJob</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAT_TYP__c.field-meta.xml
<CustomField>
    <fullName>MAT_TYP__c</fullName>
    <label>상품유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>완제품</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>원자재</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>상품코드</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>재고수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MENGE_KG__c.field-meta.xml
<CustomField>
    <fullName>MENGE_KG__c</fullName>
    <label>총중량(KG)</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/P_PSMNG__c.field-meta.xml
<CustomField>
    <fullName>P_PSMNG__c</fullName>
    <label>출고제한수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/STOCKKEY__c.field-meta.xml
<CustomField>
    <fullName>STOCKKEY__c</fullName>
    <externalId>true</externalId>
    <label>CKWMS키</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/U_PSMNG__c.field-meta.xml
<CustomField>
    <fullName>U_PSMNG__c</fullName>
    <label>사용가능수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/WERKS__c.field-meta.xml
<CustomField>
    <fullName>WERKS__c</fullName>
    <label>플랜트</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WERKS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/ZTIMS__c.field-meta.xml
<CustomField>
    <fullName>ZTIMS__c</fullName>
    <label>TIME STAMP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LGORT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>상온 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>냉장 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>냉동 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>원자재 불량 창고</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>제품 장기재고 창고</label>
    </customValue>
    <customValue>
        <fullName>3100</fullName>
        <label>상온 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3200</fullName>
        <label>냉장 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3300</fullName>
        <label>냉동 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3900</fullName>
        <label>제품 불량창고</label>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
        <label>정상품창고</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>불량품창고</label>
    </customValue>
    <customValue>
        <fullName>L091</fullName>
        <label>센트럴키친중부세척센터근태점</label>
    </customValue>
    <masterLabel>저장위치</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WERKS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5000</fullName>
        <label>센트럴키친중부점</label>
    </customValue>
    <customValue>
        <fullName>2600</fullName>
        <label>이천물류센터</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>FS점포</label>
    </customValue>
    <masterLabel>플랜트</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IF_SFDC_SAP_REC_STOCK.cls
/**
 * @description       : 
 * @author            : 안태진(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 06-22-2022
 * @last modified by  : 안태진(tj.ahn@daeunextier.com)
**/
public class IF_SFDC_SAP_REC_STOCK {

    public IF_SFDC_SAP_REC_STOCK() {}

    callCjCkSoapVer_2.sapCkInParameter inputData = new callCjCkSoapVer_2.sapCkInParameter();

    public class Input {
        public List<Stock> header;
    }

    public class Output {
        public Result result;
    }

    public class Result {
        public String resultCode;
        public String resultMessage;
        public String soapCallResult;
    }

    public class Stock{
        public String ZTIMS;
        public String STOCKKEY;
        public String MATNR;
        public String MAT_TYP;
        public String MAKTX;
        public String WERKS;
        public String LGORT;
        public String BATCH;
        public String MENGE;
        public String MENGE_KG;
        public String P_PSMNG;
        public String U_PSMNG;
        public String MEINS;
    }

    public Output callOut() {
            
        List<Stock__C> stockList = new List<Stock__C>(); 

        Result objResult = new Result();
        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = '데이터가 성공적으로 수신 되었습니다.';
        String result = '';

        try {

            inputData.requestMsg = '{"IF_ID" : "CK0005"}';
            callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort soap = new callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort();
            result = soap.callSapCkProcedure(inputData);
            System.debug('=======================result:::'+result);

            if(result == '' || result == null) {
                strStatus = 'ERROR';
                strCode = '0003';
                strMessage = '수신받을 데이터가 없습니다.';
            }else {
                Input input = (Input)JSON.deserialize(result, Input.class);

                if (input.header == null || input.header.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0001';
                    strMessage = '수신받을 데이터가 없습니다.';
                }else {
                    // Map<String, String> mapWerks = CommonUtil.getMapPickListLabel('Stock__C', 'WERKS__c');
                    // Map<String, String> mapLgort = CommonUtil.getMapPickListLabel('Stock__C', 'LGORT__c');
                    // Map<String, String> mapMatTyp = CommonUtil.getMapPickListLabel('Stock__C', 'MAT_TYP__c');
                    Map<String, String> mapMeins = CommonUtil.getMapPickListLabel('Stock__C', 'MEINS__c');

                    if (input.header <> null && input.header.size() > 0) {
                        for (Integer i = 0; i < input.header.size(); i++) {
                            Stock__C obj = new Stock__C();
                            obj.Name = input.header[i].MAKTX;
                            obj.ZTIMS__c = input.header[i].ZTIMS;
                            obj.STOCKKEY__c = input.header[i].STOCKKEY;
                            obj.MATNR__c = input.header[i].MATNR;
                            obj.MAT_TYP__c = input.header[i].MAT_TYP;
                            obj.MAKTX__c = input.header[i].MAKTX;
                            obj.WERKS__c = input.header[i].WERKS;
                            obj.LGORT__c = input.header[i].LGORT;
                            obj.BATCH__c = input.header[i].BATCH;
                            obj.MENGE__c = Decimal.valueOf(input.header[i].MENGE);
                            obj.MENGE_KG__c = Decimal.valueOf(input.header[i].MENGE_KG);
                            obj.P_PSMNG__c = Decimal.valueOf(input.header[i].P_PSMNG);
                            obj.U_PSMNG__c = Decimal.valueOf(input.header[i].U_PSMNG);
                            obj.MEINS__c = input.header[i].MEINS;
                            obj.isSystemJob__c = true;
                            stockList.add(obj);
                        }
                        System.debug(stockList);
                        upsert stockList STOCKKEY__c;
                    }    
                }
            }
        } catch (Exception e) {
            strStatus = 'ERROR';
            strCode = '-1';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage(); 
            System.debug(strMessage);
        } finally {
            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            objResult.soapCallResult = result;

            objOutput.result = objResult;

            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = 'message:::' + strMessage + ':::result:::' + result;
            LogWrapper.responseTime = Datetime.now();
            LogWrapper.requestBody = inputdata.requestMsg;
            LogWrapper.responseBody = result;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);

            IFUtil objIF = new IFUtil('IF_SFDC_SAP_REC_STOCK');
            objIF.setLog(LogWrapper);
        }
        return objOutput;
    }
}