force-app/main/default/objects/STOCK__c/STOCK__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/STOCK__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAT_TYP__c.field-meta.xml
<CustomField>
    <fullName>MAT_TYP__c</fullName>
    <label>상품유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>완제품</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>원자재</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>상품코드</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MENGE__c.field-meta.xml
<CustomField>
    <fullName>MENGE__c</fullName>
    <label>재고수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MENGE_KG__c.field-meta.xml
<CustomField>
    <fullName>MENGE_KG__c</fullName>
    <label>총중량(KG)</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/P_PSMNG__c.field-meta.xml
<CustomField>
    <fullName>P_PSMNG__c</fullName>
    <label>출고제한수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/U_PSMNG__c.field-meta.xml
<CustomField>
    <fullName>U_PSMNG__c</fullName>
    <label>사용가능수량</label>
    <precision>16</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/WERKS__c.field-meta.xml
<CustomField>
    <fullName>WERKS__c</fullName>
    <label>플랜트</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WERKS</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/ZTIMS__c.field-meta.xml
<CustomField>
    <fullName>ZTIMS__c</fullName>
    <label>TIME STAMP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LGORT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>상온 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>냉장 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>냉동 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>원자재 불량 창고</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>제품 장기재고 창고</label>
    </customValue>
    <customValue>
        <fullName>3100</fullName>
        <label>상온 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3200</fullName>
        <label>냉장 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3300</fullName>
        <label>냉동 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3900</fullName>
        <label>제품 불량창고</label>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
        <label>정상품창고</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>불량품창고</label>
    </customValue>
    <customValue>
        <fullName>L091</fullName>
        <label>센트럴키친중부세척센터근태점</label>
    </customValue>
    <masterLabel>저장위치</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/WERKS.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>5000</fullName>
        <label>센트럴키친중부점</label>
    </customValue>
    <customValue>
        <fullName>2600</fullName>
        <label>이천물류센터</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>FS점포</label>
    </customValue>
    <masterLabel>플랜트</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IF_SAP_SFDC_INFO_STOCK.cls
/**
 * @description       : 
 * @author            : 안태진(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 05-27-2022
 * @last modified by  : 안태진
**/
@RestResource(urlMapping= '/sap/info/stock')
global without sharing class IF_SAP_SFDC_INFO_STOCK {
    public IF_SAP_SFDC_INFO_STOCK() {}

    global class Input {
        public List<ZMMT2950> zmmtList;
    }

    global class Output {
        public Result result;
        public ResultData resultData;
    }

    global class Result {
        public String resultCode;
        public String resultMessage;
    }

    global class ResultData {
    }

    global class ZMMT2950{
        public String ztims;
        public String matnr;
        public String mat_typ;
        public String maktx;
        public String werks;
        public String lgort;
        public String batch;
        public String menge;
        public String menge_kg;
        public String p_psmng;
        public String u_psmng;
        public String meins;
    }

    @HttpPost
    global static Output doPost() {
        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = 'Data has been successfully inserted';

        Result objResult = new Result();
        ResultData resultData = new ResultData();

        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        List<Stock__C> stockList = new List<Stock__C>(); 

        String requestBody = '';

        try {
            RestRequest request = RestContext.request;
            requestBody = request.requestBody.toString();
            LogWrapper.requestBody = requestBody;     
            
            if(requestBody == '' || requestBody == null) {
                strStatus = 'ERROR';
                strCode = '-1';
                strMessage = 'request body value does not exist';
            }else {
                Input input = (Input)JSON.deserialize(requestBody, Input.class);

                if (input.zmmtList == null || input.zmmtList.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0001';
                    strMessage = 'release_Hlist is null';
                }else {
                    // Map<String, String> mapWerks = CommonUtil.getMapPickListLabel('Stock__C', 'WERKS__c');
                    // Map<String, String> mapLgort = CommonUtil.getMapPickListLabel('Stock__C', 'LGORT__c');
                    // Map<String, String> mapMatTyp = CommonUtil.getMapPickListLabel('Stock__C', 'MAT_TYP__c');
                    Map<String, String> mapMeins = CommonUtil.getMapPickListLabel('Stock__C', 'MEINS__c');
                    Set<String> releaseNoSet = new Set<String>();

                    if (input.zmmtList <> null && input.zmmtList.size() > 0) {
                        for (Integer i = 0; i < input.zmmtList.size(); i++) {
                            Stock__C obj = new Stock__C();
                            // obj.ZTIMS__c = input.zmmtList.ztims;
                            obj.MATNR__c = input.zmmtList[i].matnr;
                            obj.MAT_TYP__c = input.zmmtList[i].mat_typ;
                            obj.MAKTX__c = input.zmmtList[i].maktx;
                            obj.WERKS__c = input.zmmtList[i].werks;
                            obj.LGORT__c = input.zmmtList[i].lgort;
                            obj.BATCH__c = input.zmmtList[i].batch;
                            obj.MENGE__c = Decimal.valueOf(input.zmmtList[i].menge);
                            // obj.MENGE_KG__c = Decimal.valueOf(input.zmmtList[i].menge_kg);
                            obj.P_PSMNG__c = Decimal.valueOf(input.zmmtList[i].p_psmng);
                            obj.U_PSMNG__c = Decimal.valueOf(input.zmmtList[i].u_psmng);
                            obj.MEINS__c = mapMeins.get(input.zmmtList[i].meins);
                            stockList.add(obj);
                        }
                            insert stockList;
                    }    
                }
            }
        } catch (Exception e){
            strStatus = 'ERROR';
            strCode = '-1';
            strMessage = e.getMessage()+' Line : '+e.getLineNumber();
        }

        objResult.resultCode = strCode;
        objResult.resultMessage = strMessage;
        
        objOutput.resultData = resultData;
        objOutput.result = objResult;        

        LogWrapper.status = strStatus;
        LogWrapper.resultCode = strCode;
        LogWrapper.resultMessage = strMessage;
        LogWrapper.responseTime = Datetime.now();
        LogWrapper.requestBody = requestBody;
        LogWrapper.responseBody = JSON.serialize(objOutput);
        
        IFUtil objIF = new IFUtil('IF_SAP_SFDC_INFO_RELEASE');
        objIF.setLog(LogWrapper);

        return objOutput;
    }
}