force-app/main/default/objects/STOCK__c/STOCK__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고 Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/STOCK__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>변경처리</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Action</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/LGORT__c.field-meta.xml
<CustomField>
    <fullName>LGORT__c</fullName>
    <label>저장위치</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LGORT</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MAT_TYP__c.field-meta.xml
<CustomField>
    <fullName>MAT_TYP__c</fullName>
    <label>상품유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>완제품</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>원자재</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>상품코드</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/MEINS__c.field-meta.xml
<CustomField>
    <fullName>MEINS__c</fullName>
    <label>단위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/STOCKKEY__c.field-meta.xml
<CustomField>
    <fullName>STOCKKEY__c</fullName>
    <externalId>true</externalId>
    <label>CKWMS키</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STOCK__c/fields/xmsgs__c.field-meta.xml
<CustomField>
    <fullName>xmsgs__c</fullName>
    <label>메세지</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/StockChangeLog__c.object-meta.xml
<CustomObject>
    <label>재고변경내역</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>재고변경내역번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StockChangeLog__c/fields/BATCH__c.field-meta.xml
<CustomField>
    <fullName>BATCH__c</fullName>
    <label>배치번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/ChangeQuantity__c.field-meta.xml
<CustomField>
    <fullName>ChangeQuantity__c</fullName>
    <label>변경수량</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/MAKTX__c.field-meta.xml
<CustomField>
    <fullName>MAKTX__c</fullName>
    <label>자재내역</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/MAT_TYP__c.field-meta.xml
<CustomField>
    <fullName>MAT_TYP__c</fullName>
    <label>상품유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>원자재</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>완제품</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/MATNR__c.field-meta.xml
<CustomField>
    <fullName>MATNR__c</fullName>
    <label>상품코드</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/STOCK__c.field-meta.xml
<CustomField>
    <fullName>STOCK__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>재고</label>
    <referenceTo>STOCK__c</referenceTo>
    <relationshipLabel>재고변경내역</relationshipLabel>
    <relationshipName>StockChangeLog</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/STOCKKEY__c.field-meta.xml
<CustomField>
    <fullName>STOCKKEY__c</fullName>
    <label>재고키</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/StockQuantity__c.field-meta.xml
<CustomField>
    <fullName>StockQuantity__c</fullName>
    <label>기존수량</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/stocktakingDate__c.field-meta.xml
<CustomField>
    <fullName>stocktakingDate__c</fullName>
    <label>실사일</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/StockChangeLog__c/fields/zreturn__c.field-meta.xml
<CustomField>
    <fullName>zreturn__c</fullName>
    <label>자재문서번호</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Action.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>983</fullName>
        <label>폐기</label>
    </customValue>
    <customValue>
        <fullName>984</fullName>
        <label>폐기취소</label>
    </customValue>
    <customValue>
        <fullName>947</fullName>
        <label>감모</label>
    </customValue>
    <customValue>
        <fullName>948</fullName>
        <label>역감모</label>
    </customValue>
    <customValue>
        <fullName>945</fullName>
        <label>메뉴개발</label>
    </customValue>
    <customValue>
        <fullName>946</fullName>
        <label>메뉴개발취소</label>
    </customValue>
    <customValue>
        <fullName>9842</fullName>
        <isActive>false</isActive>
        <label>9842</label>
    </customValue>
    <masterLabel>변경처리</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LGORT.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1100</fullName>
        <label>상온 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1200</fullName>
        <label>냉장 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1300</fullName>
        <label>냉동 원자재 창고</label>
    </customValue>
    <customValue>
        <fullName>1900</fullName>
        <label>원자재 불량 창고</label>
    </customValue>
    <customValue>
        <fullName>3000</fullName>
        <label>제품 장기재고 창고</label>
    </customValue>
    <customValue>
        <fullName>3100</fullName>
        <label>상온 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3200</fullName>
        <label>냉장 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3300</fullName>
        <label>냉동 제품 창고</label>
    </customValue>
    <customValue>
        <fullName>3900</fullName>
        <label>제품 불량창고</label>
    </customValue>
    <customValue>
        <fullName>1000</fullName>
        <label>정상품창고</label>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
        <label>불량품창고</label>
    </customValue>
    <customValue>
        <fullName>L091</fullName>
        <label>센트럴키친중부세척센터근태점</label>
    </customValue>
    <masterLabel>저장위치</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BOX</fullName>
    </customValue>
    <customValue>
        <fullName>EA</fullName>
    </customValue>
    <customValue>
        <fullName>G</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>PAK</fullName>
        <label>팩(포장)</label>
    </customValue>
    <customValue>
        <fullName>PAL</fullName>
        <label>팔렛</label>
    </customValue>
    <customValue>
        <fullName>PAL2</fullName>
        <label>팔렛2</label>
    </customValue>
    <masterLabel>단위</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IF_SFDC_SAP_SAND_STOCK.cls
/**
 * @description       : 
 * @author            : 안태진(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 06-22-2022
 * @last modified by  : 안태진(tj.ahn@daeunextier.com)
**/
public with sharing class IF_SFDC_SAP_SAND_STOCK {
    public IF_SFDC_SAP_SAND_STOCK() {}

    public class Output {
        public Result result;
    }

    public class Input{
        public List<headerList> header;
    }

    public class headerList{
        public String xmsgs;
        public String MAT_TYP;
        public String Action;
        public String MAKTX;
        public String LGORT;
        public String StockQuantity;
        public String zreturn;
        public String MEINS;
        public String MATNR;
        public String BATCH;
        public String Stockkey;
        public String stocktakingDate;
        public String ChangeQuantity;
    } 

    public class Result {
        public String resultCode;
        public String resultMessage;
        public String soapCallResult;
    }

    @InvocableMethod(label='Send STOCK to SAP')
    public static void doSendStock(List<Id> listTargetId) {

        Set<Id> setTargetId = new Set<Id>(listTargetId);

        system.debug( 'setTargetId :: ' + setTargetId);
        String resultCode = '';
        String resultMessage = '';
        try{
            IF_SFDC_SAP_SAND_STOCK.Output outputObj = new IF_SFDC_SAP_SAND_STOCK.Output();
            IF_SFDC_SAP_SAND_STOCK ifSTOCK = new IF_SFDC_SAP_SAND_STOCK();
            
            callOut(setTargetId);
            // system.debug('Stock outputObj ::' + outputObj);

            // resultCode = outputObj.result.resultCode;
            // resultMessage = outputObj.result.resultMessage;
        } 
        catch(Exception e){
            resultCode = '-1';
            resultMessage ='CK_InAndOutMgmtController doConfirmData error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')';
            system.debug('CODE :: ' + resultCode + ' : ' + resultMessage);    
        }
    }
    
    @Future(callout=true)
    public static void callOut(Set<Id> idSet) {
        callCjCkSoapVer_2.sapCkInParameter inputData = new callCjCkSoapVer_2.sapCkInParameter();
        List<StockChangeLog__c> headerList = new List<StockChangeLog__c>();
        List<STOCK__c> targetList = new List<Stock__c>();
        List<STOCK__c> stockUpList = new List<Stock__c>();
        Map<String,Object> inputMap = new Map<String,Object>();
        Set<String> stockKeySet = new Set<String>();

        Result objResult = new Result();
        Output objOutput = new Output();
        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = '확정 데이터 전송 성공';
        String result = '';
        String inputString = '';

        try {
            headerList = [
                SELECT StockQuantity__c,
                ChangeQuantity__c,
                Action__c,
                stocktakingDate__c,
                MATNR__c,
                MAT_TYP__c,
                MAKTX__c,
                LGORT__c,
                STOCK__c,
                MEINS__c,
                Batch__c,
                xmsgs__c,
                zreturn__c,
                stockkey__c
                FROM StockChangeLog__c
                WHERE id in:idSet
            ];
            for (StockChangeLog__c obj : headerList) {
                stockKeySet.add(obj.stockkey__c);
                System.debug('=======================obj.stockkey__c:::'+obj.stockkey__c);
            }
            System.debug('===========stockKeySet :::'+stockKeySet);
            inputMap.put('header', headerList);
            inputMap.put('IF_ID', 'CK0006');
            inputString = JSON.serialize(inputMap);
            inputData.requestMsg = inputString;
            System.debug('=============================requestMsg:::'+ inputData.requestMsg);

            callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort soap = new callCjCkSoapVer_2.CalllogisoneSapCkSoapImplPort();
            result = soap.callSapCkProcedure(inputData);
            System.debug('result======================= :::'+result);

            if(result == '' || result == null) {
                strStatus = 'ERROR';
                strCode = '0003';
                strMessage = '확정 데이터 전송 실패';
            }else {
                Input input = (Input)JSON.deserialize(result, Input.class);

                if (input.header == null || input.header.size() < 1) {
                    strStatus = 'ERROR';
                    strCode = '0001';
                    strMessage = '확정 데이터 전송 실패';
                }else {
                    Map<String, String> mapMeins = CommonUtil.getMapPickListLabel('Stock__C', 'MEINS__c');
                    Map<String,Stock__c> targetMap = new Map<String,Stock__c>();

                    targetList=[
                        SELECT Id, xmsgs__c, stockkey__c
                        FROM Stock__c
                        WHERE Stockkey__c in:stockKeySet
                    ];

                    System.debug('===========targetList :::'+targetList);
                    if(!targetList.isEmpty()){
                        for (Stock__c obj : targetList) {
                            targetMap.put(obj.stockkey__c, obj);
                        }
                        System.debug('===========targetMap :::'+targetMap);
                        for (headerList obj : input.header) {
                            Stock__c stockObj = new Stock__c();
                            stockObj = targetMap.get(obj.Stockkey);
                            System.debug('===========stockObj :::'+stockObj);
                            System.debug('===========obj.Stockkey :::'+obj.Stockkey);
                            stockObj.xmsgs__c = obj.xmsgs;
                            stockObj.zreturn__c = obj.zreturn;
                            stockUpList.add(stockObj);
                        }
                        System.debug(stockUpList);
    
                        update stockUpList;
                    }else {
                        strCode = '0004';
                        strMessage = '확정 데이터 전송 실패';
                        strStatus = 'ERROR';
                    }
                }
            }
        } catch (Exception e) {
            strCode = '-1';
            strMessage = e.getLineNumber()+e.getMessage() + e.getStackTraceString(); 
            strStatus = 'ERROR';
            System.debug(strMessage);
        } finally {

            objResult.resultCode = strCode;
            objResult.resultMessage = strMessage;
            objResult.soapCallResult = result;

            objOutput.result = objResult;

            LogWrapper.status = strStatus;
            LogWrapper.resultCode = strCode;
            LogWrapper.resultMessage = 'strMessage:::' + strMessage + ':::soapCallResult:::' + result;
            LogWrapper.responseTime = Datetime.now();
            LogWrapper.requestBody = inputString;
            LogWrapper.responseBody = result;
            System.debug('===========================finally:::'+strMessage+'  status:::'+strStatus+'  code:::'+strCode);
        
            IFUtil objIF = new IFUtil('IF_SFDC_SAP_SAND_STOCK');
            objIF.setLog(LogWrapper);
        }
    }
}