force-app/main/default/objects/Opportunity/fields/ProfitMargin__c.field-meta.xml
<CustomField>
    <fullName>ProfitMargin__c</fullName>
    <label>Profit Margin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/BasePurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePurchasePrice__c</fullName>
    <label>Base Purchase Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LogisticsCenter__c.field-meta.xml
<CustomField>
    <fullName>LogisticsCenter__c</fullName>
    <label>Logistics Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1000</fullName>
                <label>KX물류센터</label>
            </value>
            <value>
                <fullName>2040</fullName>
                <label>제주FS센터</label>
            </value>
            <value>
                <fullName>2041</fullName>
                <label>제주FC</label>
            </value>
            <value>
                <fullName>2042</fullName>
                <label>제주급식</label>
            </value>
            <value>
                <fullName>2043</fullName>
                <label>제주급식센터(키즈)</label>
            </value>
            <value>
                <fullName>2120</fullName>
                <label>실수요직송센터</label>
            </value>
            <value>
                <fullName>2140</fullName>
                <label>이천)푸드빌센터</label>
            </value>
            <value>
                <fullName>2150</fullName>
                <label>농수가공비축센터</label>
            </value>
            <value>
                <fullName>2170</fullName>
                <label>외부비축창고</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FO 유통</label>
            </value>
            <value>
                <fullName>2230</fullName>
                <label>장성물류센터</label>
            </value>
            <value>
                <fullName>2231</fullName>
                <label>장성물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2240</fullName>
                <label>이천)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2250</fullName>
                <label>양산직수입센터</label>
            </value>
            <value>
                <fullName>2260</fullName>
                <label>양산물류센터</label>
            </value>
            <value>
                <fullName>2261</fullName>
                <label>양산물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2330</fullName>
                <label>장성)아라마크센터</label>
            </value>
            <value>
                <fullName>2340</fullName>
                <label>양산)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2350</fullName>
                <label>대구)아라마크센터</label>
            </value>
            <value>
                <fullName>2360</fullName>
                <label>양산)아라마크센터</label>
            </value>
            <value>
                <fullName>2370</fullName>
                <label>수원2)아라마크센터</label>
            </value>
            <value>
                <fullName>2400</fullName>
                <label>FO중부센터(물류대행)</label>
            </value>
            <value>
                <fullName>2410</fullName>
                <label>FO강남센터(물류대행)</label>
            </value>
            <value>
                <fullName>2420</fullName>
                <label>FO동서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2430</fullName>
                <label>광주외식센터</label>
            </value>
            <value>
                <fullName>2440</fullName>
                <label>FO남서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2450</fullName>
                <label>FO대구센터(물류대행)</label>
            </value>
            <value>
                <fullName>2460</fullName>
                <label>FO부산센터(물류대행)</label>
            </value>
            <value>
                <fullName>2470</fullName>
                <label>FO광주센터(물류대행)</label>
            </value>
            <value>
                <fullName>2480</fullName>
                <label>FO울산센터(물류대행)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HalfOfMonth_PL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProfitMargin__c.field-meta.xml
<CustomField>
    <fullName>ProfitMargin__c</fullName>
    <label>Profit Margin</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/UnitPriceWithVAT__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceWithVAT__c</fullName>
    <label>Unit Price With VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BasePurchasePrice__c.field-meta.xml
<CustomField>
    <fullName>BasePurchasePrice__c</fullName>
    <label>Base Purchase Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LogisticsCenter__c.field-meta.xml
<CustomField>
    <fullName>LogisticsCenter__c</fullName>
    <label>Logistics Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1000</fullName>
                <label>KX물류센터</label>
            </value>
            <value>
                <fullName>2040</fullName>
                <label>제주FS센터</label>
            </value>
            <value>
                <fullName>2041</fullName>
                <label>제주FC</label>
            </value>
            <value>
                <fullName>2042</fullName>
                <label>제주급식</label>
            </value>
            <value>
                <fullName>2043</fullName>
                <label>제주급식센터(키즈)</label>
            </value>
            <value>
                <fullName>2120</fullName>
                <label>실수요직송센터</label>
            </value>
            <value>
                <fullName>2140</fullName>
                <label>이천)푸드빌센터</label>
            </value>
            <value>
                <fullName>2150</fullName>
                <label>농수가공비축센터</label>
            </value>
            <value>
                <fullName>2170</fullName>
                <label>외부비축창고</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FO 유통</label>
            </value>
            <value>
                <fullName>2230</fullName>
                <label>장성물류센터</label>
            </value>
            <value>
                <fullName>2231</fullName>
                <label>장성물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2240</fullName>
                <label>이천)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2250</fullName>
                <label>양산직수입센터</label>
            </value>
            <value>
                <fullName>2260</fullName>
                <label>양산물류센터</label>
            </value>
            <value>
                <fullName>2261</fullName>
                <label>양산물류센터(키즈)</label>
            </value>
            <value>
                <fullName>2330</fullName>
                <label>장성)아라마크센터</label>
            </value>
            <value>
                <fullName>2340</fullName>
                <label>양산)푸드빌컨세션센터</label>
            </value>
            <value>
                <fullName>2350</fullName>
                <label>대구)아라마크센터</label>
            </value>
            <value>
                <fullName>2360</fullName>
                <label>양산)아라마크센터</label>
            </value>
            <value>
                <fullName>2370</fullName>
                <label>수원2)아라마크센터</label>
            </value>
            <value>
                <fullName>2400</fullName>
                <label>FO중부센터(물류대행)</label>
            </value>
            <value>
                <fullName>2410</fullName>
                <label>FO강남센터(물류대행)</label>
            </value>
            <value>
                <fullName>2420</fullName>
                <label>FO동서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2430</fullName>
                <label>광주외식센터</label>
            </value>
            <value>
                <fullName>2440</fullName>
                <label>FO남서울센터(물류대행)</label>
            </value>
            <value>
                <fullName>2450</fullName>
                <label>FO대구센터(물류대행)</label>
            </value>
            <value>
                <fullName>2460</fullName>
                <label>FO부산센터(물류대행)</label>
            </value>
            <value>
                <fullName>2470</fullName>
                <label>FO광주센터(물류대행)</label>
            </value>
            <value>
                <fullName>2480</fullName>
                <label>FO울산센터(물류대행)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HalfOfMonth_PL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProfitMargin__c.field-meta.xml
<CustomField>
    <fullName>ProfitMargin__c</fullName>
    <label>Profit Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPriceWithVAT__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceWithVAT__c</fullName>
    <label>Unit Price With VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/HalfOfMonth_PL.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EarlyJan</fullName>
        <label>Early Jan</label>
    </customValue>
    <customValue>
        <fullName>LateJan</fullName>
        <label>Late Jan</label>
    </customValue>
    <customValue>
        <fullName>EarlyFeb</fullName>
        <label>Early Feb</label>
    </customValue>
    <customValue>
        <fullName>LateFeb</fullName>
        <label>Late Feb</label>
    </customValue>
    <customValue>
        <fullName>EarlyMar</fullName>
        <label>Early Mar</label>
    </customValue>
    <customValue>
        <fullName>LateMar</fullName>
        <label>Late Mar</label>
    </customValue>
    <customValue>
        <fullName>EarlyApr</fullName>
        <label>Early Apr</label>
    </customValue>
    <customValue>
        <fullName>LateApr</fullName>
        <label>Late Apr</label>
    </customValue>
    <customValue>
        <fullName>EarlyMay</fullName>
        <label>Early May</label>
    </customValue>
    <customValue>
        <fullName>LateMay</fullName>
        <label>Late May</label>
    </customValue>
    <customValue>
        <fullName>EarlyJun</fullName>
        <label>Early Jun</label>
    </customValue>
    <customValue>
        <fullName>LateJun</fullName>
        <label>Late Jun</label>
    </customValue>
    <customValue>
        <fullName>EarlyJul</fullName>
        <label>Early Jul</label>
    </customValue>
    <customValue>
        <fullName>LateJul</fullName>
        <label>Late Jul</label>
    </customValue>
    <customValue>
        <fullName>EarlyAug</fullName>
        <label>Early Aug</label>
    </customValue>
    <customValue>
        <fullName>LateAug</fullName>
        <label>Late Aug</label>
    </customValue>
    <customValue>
        <fullName>EarlySep</fullName>
        <label>Early Sep</label>
    </customValue>
    <customValue>
        <fullName>LateSep</fullName>
        <label>Late Sep</label>
    </customValue>
    <customValue>
        <fullName>EarlyOct</fullName>
        <label>Early Oct</label>
    </customValue>
    <customValue>
        <fullName>LateOct</fullName>
        <label>Late Oct</label>
    </customValue>
    <customValue>
        <fullName>EarlyNov</fullName>
        <label>Early Nov</label>
    </customValue>
    <customValue>
        <fullName>LateNov</fullName>
        <label>Late Nov</label>
    </customValue>
    <customValue>
        <fullName>EarlyDec</fullName>
        <label>Early Dec</label>
    </customValue>
    <customValue>
        <fullName>LateDec</fullName>
        <label>Late Dec</label>
    </customValue>
    <masterLabel>Half Of Month</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLineItem_tr.cls
/************************************************************************************
 * File Name   		: QuoteLineItem_tr.cls
 * Author	  		: Kim.Minje
 * Date				: 2022.08.24
 * Tester	  		: QuoteLineItem_tr_test.cls
 * Description 		: QuoteLineItem_tr Trigger Handler Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2022.08.24      Minje.Kim       Create
*************************************************************************************/

public with sharing class QuoteLineItem_tr extends TriggerHandler {
    public QuoteLineItem_tr() {
        listNew = (List<QuoteLineItem>) trigger.new;
        mapOld = (Map<Id, QuoteLineItem>) trigger.oldMap;
        listOld = (List<QuoteLineItem>) trigger.old;
    }

    /*** TriggerHandler ***/
    private List<QuoteLineItem> listNew { get; set; }
    private List<QuoteLineItem> listOld { get; set; }
    private Map<Id, QuoteLineItem> mapOld { get; set; }
    
    public override void beforeInsert() {
        doSetOpportunityLineItemSync();
    }

    /***********************************************************************************************************
    *  Trigger  : Before Insert
    *  내용     : 레코드 생성시 Opportunity Line Item Custom Field 싱크
    ************************************************************************************************************/
    private void doSetOpportunityLineItemSync() {        
        List<QuoteLineItem> listTarget = new List<QuoteLineItem>();        
        Set<String> setOpptyLineItemId = new Set<String>();
        
        for(QuoteLineItem obj : listNew) {
            if(obj.OpportunityLineItemId <> null) {
                listTarget.add(obj);
                setOpptyLineItemId.add(obj.OpportunityLineItemId);
            }            
        }
        
        if(!setOpptyLineItemId.isEmpty()) {
            Map<Id, OpportunityLineItem> mapTargetLineItem = new Map<Id, OpportunityLineItem>();
            
            for(OpportunityLineItem objOLI : [
                SELECT	Id
                		,VAT__c
                		,UnitPriceWithVAT__c
                		,LogisticsCenter__c
                		,Month__c
                		,BasePurchasePrice__c
                		,ProfitMargin__c
                FROM	OpportunityLineItem
                WHERE 	Id In:setOpptyLineItemId
                
            ]) {
                mapTargetLineItem.put(objOLI.Id, objOLI);
            }
            
            for(QuoteLineItem obj : listTarget) {
                if(mapTargetLineItem <> null && mapTargetLineItem.get(obj.OpportunityLineItemId) <> null) {
                    OpportunityLineItem objTarget = mapTargetLineItem.get(obj.OpportunityLineItemId);
                    
                    obj.VAT__c = objTarget.VAT__c;
                    obj.UnitPriceWithVAT__c = objTarget.UnitPriceWithVAT__c;
                    obj.LogisticsCenter__c = objTarget.LogisticsCenter__c;
                    obj.Month__c = objTarget.Month__c;
                    obj.BasePurchasePrice__c = objTarget.BasePurchasePrice__c;
                    obj.ProfitMargin__c = objTarget.ProfitMargin__c;
                  
                }
            }
        }
    }
}