force-app/main/default/objects/DecisionProcess__c/DecisionProcess__c.object-meta.xml
<CustomObject>
    <label>품의 이력</label>
    <nameField>
        <label>품의명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DecisionProcess__c/fields/approvedCount__c.field-meta.xml
<CustomField>
    <fullName>approvedCount__c</fullName>
    <label>approvedCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedDate__c.field-meta.xml
<CustomField>
    <fullName>approvedDate__c</fullName>
    <label>approvedDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedUserCode__c.field-meta.xml
<CustomField>
    <fullName>approvedUserCode__c</fullName>
    <label>approvedUserCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedUserName__c.field-meta.xml
<CustomField>
    <fullName>approvedUserName__c</fullName>
    <label>approvedUserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedUserType__c.field-meta.xml
<CustomField>
    <fullName>approvedUserType__c</fullName>
    <label>approvedUserType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocId__c.field-meta.xml
<CustomField>
    <fullName>DocId__c</fullName>
    <label>DocId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocStatus__c.field-meta.xml
<CustomField>
    <fullName>DocStatus__c</fullName>
    <label>DocStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>영업활동</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>DecisionProcess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/totalLineCount__c.field-meta.xml
<CustomField>
    <fullName>totalLineCount__c</fullName>
    <label>totalLineCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRM001</fullName>
                <label>Risk 점검 의뢰서</label>
            </value>
            <value>
                <fullName>CRM002</fullName>
                <label>법인 (사용)인감 신청</label>
            </value>
            <value>
                <fullName>CRM003</fullName>
                <label>사용인감 반출 신청</label>
            </value>
            <value>
                <fullName>CRM004</fullName>
                <label>제안 품의</label>
            </value>
            <value>
                <fullName>CRM005</fullName>
                <label>오픈 품의</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IF_RELAY_INFO__c/IF_RELAY_INFO__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IF_RELAY_INFO</label>
</CustomObject>

force-app/main/default/objects/IF_RELAY_INFO__c/fields/Interface_auth_key__c.field-meta.xml
<CustomField>
    <fullName>Interface_auth_key__c</fullName>
    <label>Interface_auth_key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_RELAY_INFO__c/fields/Interface_id__c.field-meta.xml
<CustomField>
    <fullName>Interface_id__c</fullName>
    <label>Interface_id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/WebserviceType__c.field-meta.xml
<CustomField>
    <fullName>WebserviceType__c</fullName>
    <label>WebserviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BidNoticeSource__c.field-meta.xml
<CustomField>
    <fullName>BidNoticeSource__c</fullName>
    <label>Bid Notice Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BidQualifyRegistCloseDateTime__c.field-meta.xml
<CustomField>
    <fullName>BidQualifyRegistCloseDateTime__c</fullName>
    <description>나라장터 입찰 참가 자격 등록 마감 일시(mapping)</description>
    <label>Bid Qualify Regist Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DecisionProcess_tr_test.cls
/************************************************************************************
 * File Name   		    : DecisionProcess_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2023.06.28
 * Target	  		    : DecisionProcess_tr.cls
 * Description 		    : DecisionProcess_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.06.28      Minje.kim       Create
 *************************************************************************************/


 @IsTest
 private class DecisionProcess_tr_test {
     @TestSetup
     static void DecisionProcess_tr_testSetUp() {
 
         Set<String> setIFId = new Set<String>{'IF_SFDC_IFRESH_REG_APPROVAL'};
 
         List<IFMaster__c> listIF = new List<IFMaster__c>();
 
         for(String str : setIFId) {
             IFMaster__c obj = new IFMaster__c();
             obj.Name = str;
             obj.ContentType__c = 'application/json';
             obj.Endpoint__c = 'https://test.salesforce.com';
             obj.Method__c = 'POST';
             obj.Type__c = 'Outbound';
             obj.WebServiceType__c = 'REST';
 
             listIF.add(obj);
         }
 
         insert listIF;
 
         IF_RELAY_INFO__c objRelayInfo = new IF_RELAY_INFO__c();
         objRelayInfo.Interface_id__c = 'test';
         objRelayInfo.Interface_auth_key__c = 'test';
 
         insert objRelayInfo;
 
         Account objAccount = TestObjectCreator.objHealthAccount;
         insert objAccount;
 
         PricebookEntry objPriceBookEntry = TestObjectCreator.objPricebookEntry;
         insert objPriceBookEntry;
 
         Opportunity objOpportunity = new Opportunity();
         objOpportunity.AccountId = objAccount.Id;
         objOpportunity.Name = '영업활동';
         objOpportunity.CloseDate = date.valueOf('2022-01-01');
         objOpportunity.StageName = 'Proposal';
         objOpportunity.BidNoticeSource__c = 'NotNull';
         objOpportunity.LeadSource = 'NaraMarket';
         objOpportunity.BidQualifyRegistCloseDateTime__c = date.valueOf('2022-01-01');
         insert objOpportunity;
     }
 
     @IsTest
     static void DecisionProcess_tr_test() {
         test.startTest();
 
         try {
             Opportunity objOpportunity = [SELECT Id FROM Opportunity LIMIT 1];
             DecisionProcess__c objDecisionProcess = new DecisionProcess__c();
             objDecisionProcess.Name = '제안 품의';
             objDecisionProcess.DocStatus__c = '임시저장';
             objDecisionProcess.DocId__c = '046B9F0DC91A';
             objDecisionProcess.totalLineCount__c = 2;
             objDecisionProcess.approvedCount__c = 1;
             objDecisionProcess.approvedUserName__c = '김성진님';
             objDecisionProcess.approvedUserType__c = '기안자';
             objDecisionProcess.approvedUserCode__c = '1000000245';
             objDecisionProcess.approvedDate__c = '"2023-01-20 16:01:54';
             objDecisionProcess.Type__c = 'CRM004';
             objDecisionProcess.Opportunity__c = objOpportunity.Id;

             insert objDecisionProcess;

             Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
             delete objDecisionProcess;

         } catch (Exception e) {
             system.debug('DecisionProcess_tr_test  error : ' + e.getMessage() + ' (Line : ' + e.getLineNumber() + ')');
         }
         test.stopTest();
     }

    // err_cd":"성공"
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) { 
            HttpResponse response = newResponse(200);

            return response;
        }
    }

    private static HTTPResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setStatusCode(statusCode);
        response.setBody('{"result":"성공","message":"046B9F0DC91A"}');
        return response; 
    }

 
 }