force-app/main/default/objects/DecisionProcess__c/DecisionProcess__c.object-meta.xml
<CustomObject>
    <label>품의 이력</label>
    <nameField>
        <label>품의명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DecisionProcess__c/fields/approvedCount__c.field-meta.xml
<CustomField>
    <fullName>approvedCount__c</fullName>
    <label>approvedCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedDate__c.field-meta.xml
<CustomField>
    <fullName>approvedDate__c</fullName>
    <label>approvedDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedUserCode__c.field-meta.xml
<CustomField>
    <fullName>approvedUserCode__c</fullName>
    <label>approvedUserCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedUserName__c.field-meta.xml
<CustomField>
    <fullName>approvedUserName__c</fullName>
    <label>approvedUserName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/approvedUserType__c.field-meta.xml
<CustomField>
    <fullName>approvedUserType__c</fullName>
    <label>approvedUserType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocId__c.field-meta.xml
<CustomField>
    <fullName>DocId__c</fullName>
    <label>DocId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocStatus__c.field-meta.xml
<CustomField>
    <fullName>DocStatus__c</fullName>
    <label>DocStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/DocURL__c.field-meta.xml
<CustomField>
    <fullName>DocURL__c</fullName>
    <label>품의서 URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>영업활동</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>DecisionProcess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DecisionProcess__c/fields/totalLineCount__c.field-meta.xml
<CustomField>
    <fullName>totalLineCount__c</fullName>
    <label>totalLineCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApprovalLineAutoUpdate_ba.cls
/*
* ==================================================================================
*   File Name   : ApprovalLineAutoUpdate_ba.cls
*   Author      : Minje.Kim
*   Date        : 2023.01.09
*   Tester      : ApprovalLineAutoUpdate_ba_test.cls
*   Description : ApprovalLineAutoUpdate_ba Controller
*   Modification Log
* ==================================================================================
*   Ver     Date          Author          Modification
* ==================================================================================
*   1.0     2023.01.09    Minje.Kim    Create
* ==================================================================================
*/
public without sharing class ApprovalLineAutoUpdate_ba implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    Map<String, Integer> mapData = new Map<String, Integer>();        

    public ApprovalLineAutoUpdate_ba() {
    }

    /***********************************************************************************************************
    *  Bacth   : Start
    *  내용    : 전자결재 상태 업데이트 대상선정(완료, 회수 제외)
    ************************************************************************************************************/
    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('ApprovalLineAutoUpdate_ba Start !!');

		string strQuery = '';
		strQuery += '  SELECT  Id, Name, DocId__c, DocURL__c, Opportunity__c , DocStatus__c, totalLineCount__c, approvedCount__c, approvedUserName__c, approvedUserType__c, approvedDate__c, approvedUserCode__c  ';
		strQuery += '  FROM    DecisionProcess__c  ';
		strQuery += '  WHERE   DocStatus__c != \'완료\'  ';
		strQuery += '  AND     DocStatus__c != \'회수(기안취소)\'  ';
    
		return Database.getQueryLocator(strQuery);
    }

    /***********************************************************************************************************
    *  Bacth   : execute
    *  내용    : 전자결재 상태 업데이트 진행 ( ApprovalLineUpdateController 컨트롤러의 doUpdateApproval 함수 사용)
    ************************************************************************************************************/
    public void execute(Database.BatchableContext BC, List<DecisionProcess__c> listTarget) {

        if( !listTarget.isEmpty()){
            DecisionProcess__c objDecisionProcess = listTarget[0];
            ApprovalLineUpdateController.doUpdateApproval(objDecisionProcess);
        }
    }

    /***********************************************************************************************************
    *  Bacth   : finish
    *  내용    : 내용 없음
    ************************************************************************************************************/
    public void finish(Database.BatchableContext BC) {
        System.debug('ApprovalLineAutoUpdate_ba finish !!');
    }
}