force-app/main/default/objects/MDMReferenceCode__c/MDMReferenceCode__c.object-meta.xml
<CustomObject>
    <label>MDM 참조코드</label>
    <nameField>
        <label>MDMReferenceCode Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMReferenceCode__c/fields/CODE__c.field-meta.xml
<CustomField>
    <fullName>CODE__c</fullName>
    <externalId>true</externalId>
    <label>CODE</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/GROUPID__c.field-meta.xml
<CustomField>
    <fullName>GROUPID__c</fullName>
    <externalId>true</externalId>
    <label>GROUPID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_KO__c.field-meta.xml
<CustomField>
    <fullName>NAME_KO__c</fullName>
    <label>NAME_KO</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/OrderServiceRequest__c.object-meta.xml
<CustomObject>
    <description>주문 서비스 요청</description>
    <label>OrderServiceRequest</label>
    <nameField>
        <label>OrderServiceRequest__c 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderServiceRequest__c/fields/MDMReferenceCode__c.field-meta.xml
<CustomField>
    <fullName>MDMReferenceCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MDM고객</label>
    <referenceTo>MDMReferenceCode__c</referenceTo>
    <relationshipLabel>OrderServiceRequest</relationshipLabel>
    <relationshipName>OrderServiceRequest</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ReqRecordId__c.field-meta.xml
<CustomField>
    <fullName>ReqRecordId__c</fullName>
    <description>주문시스템레코드ID</description>
    <label>ReqRecordId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/RequestDate__c.field-meta.xml
<CustomField>
    <fullName>RequestDate__c</fullName>
    <description>작성일</description>
    <label>RequestDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/RequestMessage__c.field-meta.xml
<CustomField>
    <fullName>RequestMessage__c</fullName>
    <description>문의접수내용</description>
    <label>RequestMessage</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ResponseDate__c.field-meta.xml
<CustomField>
    <fullName>ResponseDate__c</fullName>
    <description>답변일</description>
    <label>ResponseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ResponseTitle__c.field-meta.xml
<CustomField>
    <fullName>ResponseTitle__c</fullName>
    <description>답변제목</description>
    <label>ResponseTitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R</fullName>
                <label>접수</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>답변완료</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>답변지연</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>접수 제목</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFN_LIF1002_OD001_MD001_TEST.cls
@isTest
public class IFN_LIF1002_OD001_MD001_TEST {

    @TestSetup
    static void makeData(){
        IFN_TestDataFactory.createIfPrograms();

        // MDMReferenceCode__c code = new MDMReferenceCode__c();
        // code.GROUPID__c = 'GROUPID__c';
        // code.CODE__c = '0001';
        // code.NAME_KO__c = 'Test';
        // code.Name = 'Test';
        // insert code;

        // OrderServiceRequest__c osr = new OrderServiceRequest__c();
        // osr.ReqRecordId__c = '1';
        // osr.Status__c = 'R';
        // osr.ResponseDate__c = Date.today();
        // osr.ResponseTitle__c = '1';
        // osr.Title__c = '1';
        // osr.RequestMessage__c = 'a';
        // osr.RequestDate__c = Date.today();
        // osr.MDMReferenceCode__c = code.id;
        // insert osr;
        
    }

    @isTest
    static void test01() {
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        IFN_LIF1002_OD001_MD001.Input reqdata = new IFN_LIF1002_OD001_MD001.Input();
        reqdata.cstTp='외식사업자';  
        reqdata.cstTpCd='food_service_business';
        reqdata.cstNm='1';  
        reqdata.callNo='02-000-0000'; 
        reqdata.bsnsNo='1'; 
        reqdata.cpnNm='1';  
        reqdata.sect='1';   
        reqdata.addr='1';   
        reqdata.agrYn='Y';          
        String strBody = Json.serialize(reqdata);
        req.requestBody = Blob.valueOf(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD001_MD001.doPost();
        
        Test.stopTest();
    }


    @isTest
    static void test02() {
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        IFN_LIF1002_OD001_MD001.Input reqdata = new IFN_LIF1002_OD001_MD001.Input();
        reqdata.cstTp='사업자';  
        reqdata.cstTpCd='food_service_business';
        reqdata.cstNm='1';  
        reqdata.callNo='02-000-0000'; 
        reqdata.bsnsNo='1'; 
        reqdata.cpnNm='1';  
        reqdata.sect='1';   
        reqdata.addr='1';   
        reqdata.agrYn='Y';          
        String strBody = Json.serialize(reqdata);
        req.requestBody = Blob.valueOf(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD001_MD001.doPost();
        
        Test.stopTest();
    }

    @isTest
    static void test03() {
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        IFN_LIF1002_OD001_MD001.Input reqdata = new IFN_LIF1002_OD001_MD001.Input();
        reqdata.cstTp='';  
        reqdata.cstTpCd='';
        reqdata.cstNm='';  
        reqdata.callNo=''; 
        reqdata.bsnsNo=''; 
        reqdata.cpnNm='';  
        reqdata.sect='';   
        reqdata.addr='';   
        reqdata.agrYn='Y';          
        String strBody = Json.serialize(reqdata);
        req.requestBody = Blob.valueOf(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD001_MD001.doPost();
        
        Test.stopTest();
    }


 

}