force-app/main/default/objects/MDMReferenceCode__c/MDMReferenceCode__c.object-meta.xml
<CustomObject>
    <label>MDM 참조코드</label>
    <nameField>
        <label>MDMReferenceCode Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMReferenceCode__c/fields/CODE__c.field-meta.xml
<CustomField>
    <fullName>CODE__c</fullName>
    <externalId>true</externalId>
    <label>CODE</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/GROUPID__c.field-meta.xml
<CustomField>
    <fullName>GROUPID__c</fullName>
    <externalId>true</externalId>
    <label>GROUPID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_KO__c.field-meta.xml
<CustomField>
    <fullName>NAME_KO__c</fullName>
    <label>NAME_KO</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/ParentCode__c.field-meta.xml
<CustomField>
    <fullName>ParentCode__c</fullName>
    <label>ParentCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/ParentGroupId__c.field-meta.xml
<CustomField>
    <fullName>ParentGroupId__c</fullName>
    <label>ParentGroupId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDMReferenceCode_tr_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-27-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class MDMReferenceCode_tr_test {
    @testSetup
	static void setData() {
        MDMReferenceCode__c obj = new MDMReferenceCode__c();
        obj.GROUPID__c = 'TEST';
        obj.Code__c = '001';
        obj.NAME_KO__c = '테스트';
        obj.IsDefault__c = true;
        obj.IsActive__c = true;

        insert obj;
	}
    @isTest 
    static void itShoud() {
        Test.startTest();

        MDMReferenceCode__c obj = new MDMReferenceCode__c();
        obj.GROUPID__c = 'TEST';
        obj.Code__c = '002';
        obj.NAME_KO__c = '테스트2';
        obj.IsDefault__c = true;
        obj.IsActive__c = true;
        obj.ParentCode__c = '001';
        obj.ParentGroupId__c = 'TEST';

        insert obj;

        Test.stopTest();
    }
}