force-app/main/default/objects/MDMReferenceCode__c/MDMReferenceCode__c.object-meta.xml
<CustomObject>
    <label>MDM 참조코드</label>
    <nameField>
        <label>MDMReferenceCode Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderServiceRequest__c/OrderServiceRequest__c.object-meta.xml
<CustomObject>
    <description>주문 서비스 요청</description>
    <label>OrderServiceRequest</label>
    <nameField>
        <label>OrderServiceRequest__c 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderServiceRequest__c/fields/ExtraServiceCategory__c.field-meta.xml
<CustomField>
    <fullName>ExtraServiceCategory__c</fullName>
    <label>부가서비스카테고리</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Finder__c.field-meta.xml
<CustomField>
    <fullName>Finder__c</fullName>
    <description>접수자</description>
    <label>Finder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>담당자</description>
    <label>담당자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OrderServiceRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/MDMReferenceCode__c.field-meta.xml
<CustomField>
    <fullName>MDMReferenceCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MDM고객</label>
    <referenceTo>MDMReferenceCode__c</referenceTo>
    <relationshipLabel>OrderServiceRequest</relationshipLabel>
    <relationshipName>OrderServiceRequest</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ReqRecordId__c.field-meta.xml
<CustomField>
    <fullName>ReqRecordId__c</fullName>
    <description>주문시스템레코드ID</description>
    <label>ReqRecordId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ReqType__c.field-meta.xml
<CustomField>
    <fullName>ReqType__c</fullName>
    <label>ReqType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>샘플요청</fullName>
            </value>
            <value>
                <fullName>부가서비스 요청</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/RequestDate__c.field-meta.xml
<CustomField>
    <fullName>RequestDate__c</fullName>
    <description>작성일</description>
    <label>RequestDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/RequestMessage__c.field-meta.xml
<CustomField>
    <fullName>RequestMessage__c</fullName>
    <description>문의접수내용</description>
    <label>RequestMessage</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ResponseDate__c.field-meta.xml
<CustomField>
    <fullName>ResponseDate__c</fullName>
    <description>답변일</description>
    <label>ResponseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>ResponseMessage__c</fullName>
    <description>답변내용</description>
    <label>ResponseMessage</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ResponseTitle__c.field-meta.xml
<CustomField>
    <fullName>ResponseTitle__c</fullName>
    <description>답변제목</description>
    <label>ResponseTitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Sampleitem1__c.field-meta.xml
<CustomField>
    <fullName>Sampleitem1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>샘플상품1</description>
    <label>요청샘플1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OrderServiceRequest</relationshipLabel>
    <relationshipName>OrderServiceRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Sampleitem2__c.field-meta.xml
<CustomField>
    <fullName>Sampleitem2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>샘플상품2</description>
    <label>요청샘플2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OrderServiceRequest (상품)</relationshipLabel>
    <relationshipName>OrderServiceRequest1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Sampleitem3__c.field-meta.xml
<CustomField>
    <fullName>Sampleitem3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>샘플제품3</description>
    <label>요청샘플3</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OrderServiceRequest (요청샘플3)</relationshipLabel>
    <relationshipName>OrderServiceRequest2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/SampleitemText1__c.field-meta.xml
<CustomField>
    <fullName>SampleitemText1__c</fullName>
    <description>신청샘플상품텍스트1</description>
    <label>SampleitemText1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/SampleitemText2__c.field-meta.xml
<CustomField>
    <fullName>SampleitemText2__c</fullName>
    <description>신청샘플상품텍스트2</description>
    <label>SampleitemText2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/SampleitemText3__c.field-meta.xml
<CustomField>
    <fullName>SampleitemText3__c</fullName>
    <description>신청샘플상품텍스트3</description>
    <label>SampleitemText3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R</fullName>
                <label>접수</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>답변완료</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>답변지연</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>접수 제목</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CJFWOrderService_Res_ManagerAlert_batch.cls
/**
 * @description       : 주문시스템 담당자알림 및 상태변경
 * @author            : 백영주
 * @group             : 
 * @last modified on  : 08-14-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
/***
 * 1. status '접수' '답변지연' 레코드 조회
 * 2. 접수 상태 레코드 접수일 + 10일 = 오늘 에 해당하는경우 답변지연상태로 변경
 * 3. 
 * 
 */
public without sharing class CJFWOrderService_Res_ManagerAlert_batch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {
    public CJFWOrderService_Res_ManagerAlert_batch() {
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        string strQuery = 'SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, RecordTypeId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, LastReferencedDate, Title__c, ReqType__c, RequestMessage__c, SampleitemText1__c, SampleitemText2__c, SampleitemText3__c, ExtraServiceCategory__c, MDMReferenceCode__c, RequestDate__c, Finder__c, Status__c, ResponseDate__c, ResponseTitle__c, Manager__c, ResponseMessage__c, ReqRecordId__c, Sampleitem1__c, Sampleitem2__c, Sampleitem3__c from OrderServiceRequest__c where';
        strQuery += ' WHERE Status__c =\'접수\'';
        strQuery += ' OR Status__c =\'답변지연\'';
        return Database.getQueryLocator(strQuery);
    }
    public void execute(Database.BatchableContext BC, List<OrderServiceRequest__c> listTarget) {
        List<OrderServiceRequest__c> newResList = new List<OrderServiceRequest__c>();
        List<OrderServiceRequest__c> lateResList = new List<OrderServiceRequest__c>();
        // 현재 날짜를 가져옴
        Date today = Date.today();

        // 10일 전 날짜를 계산하여 변수에 저장
        Date targetDate = today.addDays(-10);
        try{
            for(OrderServiceRequest__c OSR : listTarget){
                if(OSR.Status__c == '접수' && OSR.RequestDate__c > targetDate){
                    newResList.add(OSR);
                }else{
                    OSR.Status__c = '답변지연';
                    lateResList.add(OSR);
                }
            }
            update lateResList;
        }catch(exception e){

        }finally{

        }

    }
    public void finish(Database.BatchableContext BC) {
        System.debug('CJFWOrderService_Res_ManagerAlert_batch finish !!');
    }
}