force-app/main/default/objects/MDMReferenceCode__c/MDMReferenceCode__c.object-meta.xml
<CustomObject>
    <label>MDM 참조코드</label>
    <nameField>
        <label>MDMReferenceCode Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MDMReferenceCode__c/fields/CODE__c.field-meta.xml
<CustomField>
    <fullName>CODE__c</fullName>
    <externalId>true</externalId>
    <label>CODE</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/GROUPID__c.field-meta.xml
<CustomField>
    <fullName>GROUPID__c</fullName>
    <externalId>true</externalId>
    <label>GROUPID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDMReferenceCode__c/fields/NAME_KO__c.field-meta.xml
<CustomField>
    <fullName>NAME_KO__c</fullName>
    <label>NAME_KO</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDMReferenceCodeSearch_test.cls
@isTest
public class MDMReferenceCodeSearch_test {
    @TestSetup
    static void makeData(){
        MDMReferenceCode__c code = new MDMReferenceCode__c();
        code.GROUPID__c = 'GROUPID__c';
        code.CODE__c = '0001';
        code.NAME_KO__c = 'Test';
        code.Name = 'Test';
        insert code;
    }

    @IsTest
    static void test_001(){
        Test.startTest();
        MDMReferenceCodeSearch.doInit('GROUPID__c', '0001');
        Test.stopTest();
        
    }

    @IsTest
    static void test_002(){
        MDMReferenceCodeSearch.SearchResult sr = new MDMReferenceCodeSearch.SearchResult();
        sr.strId = '';
        sr.strName = '';
        sr.strGroupId = '';
        sr.strCode = '';
        Test.startTest();
        MDMReferenceCodeSearch.doSearch('GROUPID__c', 'Test');
        Test.stopTest();
        
    }
}