force-app/main/default/objects/ITServiceRequest__c/ITServiceRequest__c.object-meta.xml
<CustomObject>
    <label>CRM 서비스 요청</label>
    <nameField>
        <displayFormat>IR-{00000000}</displayFormat>
        <label>접수번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ITServiceRequest__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <label>요청 유형</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>결함</fullName>
            </value>
            <value>
                <fullName>개선</fullName>
                <label>기능 개선</label>
            </value>
            <value>
                <fullName>UI/UX 개선</fullName>
            </value>
            <value>
                <fullName>데이터 수정</fullName>
            </value>
            <value>
                <fullName>데이터 추출</fullName>
            </value>
            <value>
                <fullName>계정 및 권한</fullName>
            </value>
            <value>
                <fullName>문의</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ITServiceRequest__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>영향도</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>경미</fullName>
            </value>
            <value>
                <fullName>보통</fullName>
            </value>
            <value>
                <fullName>심각</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ITServiceRequest__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>접수 제목</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ITServiceRequest_tr_test.cls
/************************************************************************************
 * File Name   		    : ITServiceRequest_tr_test.cls
 * Author	  		    : Minje.kim
 * Date				    : 2023.02.06
 * Target	  		    : ITServiceRequest_tr.cls
 * Description 		    : ITServiceRequest_tr Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author          Modification
 * ===================================================================================
 * 1.0      2023.02.06      Minje.kim       Create
 *************************************************************************************/

@IsTest
public with sharing class ITServiceRequest_tr_test {
    @isTest 
    static void itShould() {
        Test.startTest();
        
        ITServiceRequest__c objITServiceRequest = new ITServiceRequest__c();
        objITServiceRequest.Title__c = 'CRM 서비스 요청 1';
        objITServiceRequest.RequestType__c = '개선';
        objITServiceRequest.Severity__c = '보통';
        insert objITServiceRequest;
        
        String strServiceContentsId = objITServiceRequest.Id;
        objITServiceRequest.Title__c = 'CRM 서비스 요청 2';
        update objITServiceRequest;
        Test.stopTest();
    }
}