force-app/main/default/objects/IFLog__c/IFLog__c.object-meta.xml
<CustomObject>
    <label>IFLog</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{00000000}</displayFormat>
        <label>IFLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IFLog__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <formula>IF(ISBLANK(IFMaster__r.Endpoint__c), &apos;N/A&apos;, IFMaster__r.Endpoint__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EndPoint</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFLog__c/fields/IFMaster__c.field-meta.xml
<CustomField>
    <fullName>IFMaster__c</fullName>
    <label>IFMaster</label>
    <referenceTo>IFMaster__c</referenceTo>
    <relationshipLabel>IFLog</relationshipLabel>
    <relationshipName>IFLog</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IFLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/WebserviceType__c.field-meta.xml
<CustomField>
    <fullName>WebserviceType__c</fullName>
    <label>WebserviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFN_DELETEIF_DATA_BATCH_TEST.cls
@isTest
public class IFN_DELETEIF_DATA_BATCH_TEST {
    @TestSetup
    static void setup()
    {
       
        Set<String> setIFId = new Set<String>{'IF_HOME_TEST', 'IF_NAVER_TEST'};

        List<IFMaster__c> listIF = new List<IFMaster__c>();

        for(String str : setIFId) {
            IFMaster__c obj = new IFMaster__c();
            obj.Name = str;
            obj.ContentType__c = 'application/json';
            obj.Endpoint__c = 'https://test.salesforce.com';
            obj.Method__c = 'POST';
            obj.Type__c = 'Inbound';
            obj.WebServiceType__c = 'REST';

            listIF.add(obj);
        }

        insert listIF;

        IFLog__c objLog = new IFLog__c();
        objLog.IFMaster__c = listIF[0].Id;
        objLog.Status__c = 'SUCCESS';

        insert objLog;


    }

    @isTest
    static void testOne(){
        Test.startTest();
        Database.executeBatch(new IFN_DELETEIF_DATA_BATCH('IFLog__c',''),1000);
        Test.stopTest();
    }



}