force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c.object-meta.xml
<CustomObject>
    <label>IF_IFRESH_SFDC_VOC_INFO_COMMENT</label>
    <nameField>
        <displayFormat>No-{00000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/BCNR_OPN_YN__c.field-meta.xml
<CustomField>
    <fullName>BCNR_OPN_YN__c</fullName>
    <label>BCNR_OPN_YN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/DLWR_NM__c.field-meta.xml
<CustomField>
    <fullName>DLWR_NM__c</fullName>
    <label>DLWR_NM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRS_BD_NO__c.field-meta.xml
<CustomField>
    <fullName>PRS_BD_NO__c</fullName>
    <label>PRS_BD_NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRS_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>PRS_CL_CD__c</fullName>
    <label>PRS_CL_CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRS_CL_NM__c.field-meta.xml
<CustomField>
    <fullName>PRS_CL_NM__c</fullName>
    <label>PRS_CL_NM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRS_DT__c.field-meta.xml
<CustomField>
    <fullName>PRS_DT__c</fullName>
    <label>PRS_DT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRS_TXT_NM__c.field-meta.xml
<CustomField>
    <fullName>PRS_TXT_NM__c</fullName>
    <label>PRS_TXT_NM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRSR_EMP_NO__c.field-meta.xml
<CustomField>
    <fullName>PRSR_EMP_NO__c</fullName>
    <label>PRSR_EMP_NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/PRSR_NM__c.field-meta.xml
<CustomField>
    <fullName>PRSR_NM__c</fullName>
    <label>PRSR_NM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_COMMENT__c/fields/txt__c.field-meta.xml
<CustomField>
    <fullName>txt__c</fullName>
    <label>txt</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c.object-meta.xml
<CustomObject>
    <label>IF_IFRESH_SFDC_VOC_INFO_DETAIL</label>
    <nameField>
        <displayFormat>No-{00000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c/fields/IsNotVOC__c.field-meta.xml
<CustomField>
    <fullName>IsNotVOC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsNotVOC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_DETAIL__c/fields/VOC_NO__c.field-meta.xml
<CustomField>
    <fullName>VOC_NO__c</fullName>
    <label>VOC_NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_MASTER__c/IF_IFRESH_SFDC_VOC_INFO_MASTER__c.object-meta.xml
<CustomObject>
    <label>IF_IFRESH_SFDC_VOC_INFO_MASTER</label>
    <nameField>
        <displayFormat>No-{00000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_MASTER__c/fields/PRS_TXT_CD__c.field-meta.xml
<CustomField>
    <fullName>PRS_TXT_CD__c</fullName>
    <label>PRS_TXT_CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_MASTER__c/fields/REG_DT__c.field-meta.xml
<CustomField>
    <fullName>REG_DT__c</fullName>
    <label>REG_DT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_MASTER__c/fields/transactionId__c.field-meta.xml
<CustomField>
    <fullName>transactionId__c</fullName>
    <externalId>true</externalId>
    <label>transactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_IFRESH_SFDC_VOC_INFO_MASTER__c/fields/UPD_DT__c.field-meta.xml
<CustomField>
    <fullName>UPD_DT__c</fullName>
    <label>UPD_DT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOC__c/VOC__c.object-meta.xml
<CustomObject>
    <label>VOC</label>
    <nameField>
        <label>VOC Number</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VOC__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>4000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/VOC__c/fields/VOCNumber__c.field-meta.xml
<CustomField>
    <fullName>VOCNumber__c</fullName>
    <externalId>true</externalId>
    <label>VOCNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/VOCComment__c.object-meta.xml
<CustomObject>
    <description>조치이력</description>
    <label>VOC 조치 이력</label>
    <nameField>
        <displayFormat>VoCM-{00000}</displayFormat>
        <label>VOC Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VOCComment__c/fields/ActionDetailCode__c.field-meta.xml
<CustomField>
    <fullName>ActionDetailCode__c</fullName>
    <label>Action Details</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>99</fullName>
                <label>해당사항없음</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>방문</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>직송의뢰</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>현물회수</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>진행문의</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>유선상담</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>현장대응</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>080이관</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/CustomerSideResponder__c.field-meta.xml
<CustomField>
    <fullName>CustomerSideResponder__c</fullName>
    <description>고객측대응자</description>
    <label>Customer Side Responder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/DateofAction__c.field-meta.xml
<CustomField>
    <fullName>DateofAction__c</fullName>
    <description>조치일시</description>
    <label>Date of Action</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>상세내용</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/IsPartnerDisclosure__c.field-meta.xml
<CustomField>
    <fullName>IsPartnerDisclosure__c</fullName>
    <defaultValue>false</defaultValue>
    <description>협력사공개</description>
    <label>Is Partner Disclosure?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/PRS_BD_NO__c.field-meta.xml
<CustomField>
    <fullName>PRS_BD_NO__c</fullName>
    <externalId>true</externalId>
    <label>PRS_BD_NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/RegDT__c.field-meta.xml
<CustomField>
    <fullName>RegDT__c</fullName>
    <label>RegDT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/ResolverName__c.field-meta.xml
<CustomField>
    <fullName>ResolverName__c</fullName>
    <description>조치자명</description>
    <label>Resolver Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/ResolverNumber__c.field-meta.xml
<CustomField>
    <fullName>ResolverNumber__c</fullName>
    <description>조치자 번호</description>
    <label>Resolver Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/SolutionCode__c.field-meta.xml
<CustomField>
    <fullName>SolutionCode__c</fullName>
    <description>방법</description>
    <label>Solution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>99</fullName>
                <label>해당사항없음</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Inbound Call</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Out Call</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>방문</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/UpdDT__c.field-meta.xml
<CustomField>
    <fullName>UpdDT__c</fullName>
    <label>UpdDT</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VOCComment__c/fields/VOC__c.field-meta.xml
<CustomField>
    <fullName>VOC__c</fullName>
    <label>VOC</label>
    <referenceTo>VOC__c</referenceTo>
    <relationshipLabel>VOC Comments</relationshipLabel>
    <relationshipName>VOCComments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IF_IFRESH_SFDC_VOC_INFO_COMMENT_ba.cls
/**
 * @description       : VOC 조치이력 Batch Class
 * @author            : AhnTaeJin(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global with sharing class IF_IFRESH_SFDC_VOC_INFO_COMMENT_ba implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts{
    
    global String transactionId;

    global IF_IFRESH_SFDC_VOC_INFO_COMMENT_ba(String transactionId) {
        this.transactionId = transactionId;
    }
    /***********************************************************************************************************
    *  Bacth   : start
    *  내용    : IF Dummy Object 레코드 조회
    ************************************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = '';
        strQuery += 'SELECT Id, transactionId__c, VOC_NO__c, PRS_BD_NO__c, PRS_DT__c, PRSR_NM__c,';
        strQuery += '   PRSR_EMP_NO__c, PRS_CL_NM__c, PRS_CL_CD__c, PRS_TXT_NM__c, PRS_TXT_CD__c, DLWR_NM__c, BCNR_OPN_YN__c, TXT__c, REG_DT__c, UPD_DT__c';
        strQuery += '   FROM IF_IFRESH_SFDC_VOC_INFO_COMMENT__c';
        strQuery += '   WHERE transactionId__c = \'' + transactionId + '\'' ;
        strQuery += '   AND     IsUpdate__c = false' ;

        System.debug('strQuery: ' + strQuery);
        System.debug('start batch');
        return  Database.getQueryLocator(strQuery);
    }
    /***********************************************************************************************************
    *  Bacth   : execute
    *  내용    : VOC 조치이력 upsert
    ************************************************************************************************************/
    global void execute(Database.BatchableContext bc, List<IF_IFRESH_SFDC_VOC_INFO_COMMENT__c> scope) {
        System.debug('execute batch');
        List<VOCComment__c> upsertVOCCommentList = new List<VOCComment__c>();
        Set<String> vocNoSet = new Set<String>();
        for (IF_IFRESH_SFDC_VOC_INFO_COMMENT__c obj : scope) {
            vocNoSet.add(obj.VOC_NO__c);
        }

        List<VOC__C> vocList = new List<VOC__C>();
        vocList = [
                    SELECT Id, VOCNumber__c
                    FROM VOC__c
                    WHERE VOCNumber__c IN :vocNoSet
        ];

        Map<String, Id> vocMap = new Map<String, Id>();
        for (VOC__c obj : vocList) {
            vocMap.put(obj.VOCNumber__c, obj.Id);
        }

        List<IF_IFRESH_SFDC_VOC_INFO_COMMENT__c> listUpdate = new List<IF_IFRESH_SFDC_VOC_INFO_COMMENT__c>();

        for (IF_IFRESH_SFDC_VOC_INFO_COMMENT__c objDummy : scope) {
            IF_IFRESH_SFDC_VOC_INFO_COMMENT__c objTarget = new IF_IFRESH_SFDC_VOC_INFO_COMMENT__c();
            objTarget.Id = objDummy.Id;

            if(vocMap <> null && vocMap.get(objDummy.VOC_NO__c) <> null){
                VOCComment__c obj = new VOCComment__c();
                obj.ExtId__c = objDummy.VOC_NO__c + '_' + objDummy.PRS_BD_NO__c;
                
                obj.VOC__c = vocMap.get(objDummy.VOC_NO__c);
                obj.VOCNumber__c = objDummy.VOC_NO__c;
                obj.PRS_BD_NO__c = objDummy.PRS_BD_NO__c;
                obj.DateofAction__c = objDummy.PRS_DT__c == null ? null : Datetime.valueOf(objDummy.PRS_DT__c);
                obj.ResolverName__c = objDummy.PRSR_NM__c;
                obj.ResolverNumber__c = objDummy.PRSR_EMP_NO__c;                
                obj.SolutionCode__c = objDummy.PRS_CL_CD__c;                
                obj.ActionDetailCode__c = objDummy.PRS_TXT_CD__c;
                obj.CustomerSideResponder__c = objDummy.DLWR_NM__c;
                obj.IsPartnerDisclosure__c = objDummy.BCNR_OPN_YN__c == '1' ? true : false;
                obj.Description__c = objDummy.TXT__c;
                obj.RegDT__c = objDummy.REG_DT__c <> null ? Datetime.valueOf(objDummy.REG_DT__c) : null;
                obj.UpdDT__c = objDummy.UPD_DT__c <> null ? Datetime.valueOf(objDummy.UPD_DT__c) : null;

                upsertVOCCommentList.add(obj);
            }else {
                objTarget.IsNotVOC__c = true;                
            }

            objTarget.IsUpdate__c = true;
            listUpdate.add(objTarget);
        }

        Savepoint sp = Database.setSavepoint();

        // try {
            if(upsertVOCCommentList <> null && upsertVOCCommentList.size() > 0) {
                upsert upsertVOCCommentList ExtId__c;
            }

            if(listUpdate <> null && listUpdate.size() > 0) {
                update listUpdate;
            }
        // }catch(Exception e) {
        //     Database.rollback(sp);

        //     System.debug('=============================> Error Line '+e.getLineNumber());
        //     System.debug('=============================> Error '+e.getMessage());
        // }
    }
    /***********************************************************************************************************
    *  Bacth   : finish
    *  내용    : 없음
    ************************************************************************************************************/
    global void finish(Database.BatchableContext BC) {
        /*
        IF_DUMMY_DEL_ba master = new IF_DUMMY_DEL_ba('IF_IFRESH_SFDC_VOC_INFO_MASTER__c', this.transactionId);
        Database.executeBatch(master, 200);

        IF_DUMMY_DEL_ba detail = new IF_DUMMY_DEL_ba('IF_IFRESH_SFDC_VOC_INFO_DETAIL__c', this.transactionId);
        Database.executeBatch(detail, 200);

        IF_DUMMY_DEL_ba comment = new IF_DUMMY_DEL_ba('IF_IFRESH_SFDC_VOC_INFO_COMMENT__c', this.transactionId);
        Database.executeBatch(comment, 200);
        */
    }
}