force-app/main/default/objects/CJFW_Survey__c/CJFW_Survey__c.object-meta.xml
<CustomObject>
    <description>[P2] 형식지 유형</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>설명</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/CJFW_SurveyOption__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 객관식 문항</description>
    <label>Survey Option</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>순서</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <description>설문지 문항</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Option</relationshipLabel>
    <relationshipName>Survey_Option</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/CJFW_SurveyQuestion__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 질문</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ{YY}{MM}{DD}{000000}</displayFormat>
        <label>AutoNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/DateType__c.field-meta.xml
<CustomField>
    <fullName>DateType__c</fullName>
    <description>날짜유형 (From/ To) 설정</description>
    <label>Date Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From/To</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/MultipleChoice__c.field-meta.xml
<CustomField>
    <fullName>MultipleChoice__c</fullName>
    <description>객관식 유형</description>
    <label>Multiple Choice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>singular</fullName>
                <label>단수</label>
            </value>
            <value>
                <fullName>plural</fullName>
                <label>복수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>질문명</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>번호(순서)</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>질문유형</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>openended</fullName>
                <label>주관식</label>
            </value>
            <value>
                <fullName>multiple</fullName>
                <label>객관식</label>
            </value>
            <value>
                <fullName>date</fullName>
                <label>날짜</label>
            </value>
            <value>
                <fullName>time</fullName>
                <label>시간</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResponse__c/CJFW_SurveyResponse__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 응답</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyResponse__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Response</relationshipLabel>
    <relationshipName>Survey_Response</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CJFW_SurveyController_TEST.cls
/**
 * @description       : 
 * @author            : sunkyung.choi@dkbmc.com
 * @group             : 
 * @last modified on  : 10-05-2023
 * @last modified by  : sunkyung.choi@dkbmc.com
**/
@isTest
public with sharing class CJFW_SurveyController_TEST {
    
    @TestSetup
    static void makeData(){
        List<User> userList = new List<User>();
        
        String profileName4100 = 'CJFW_아이누리사업부';
        Map<String,Profile> profieMap = COMM_TestDataFactory.getProfileMap(new List<String>{
            profileName4100
        });

        User ibUser = COMM_TestDataFactory.createUser(profieMap.get(profileName4100).Id);
        ibUser.LastName = '테스트Staff';
        userList.add(ibUser);


        insert userList;

        //231005기준 4개 설문지를 생성
        CJFW_Survey_TEST.makeData();

    }
    @isTest
    static void getCurrentUserInfoTest(){

        // 먼저 테스트에 사용할 사용자 레코드를 쿼리
        User testUser = [SELECT Id FROM User WHERE LastName = '테스트Staff' LIMIT 1];

         // System.runAs 블록 내에서 코드를 지정된 사용자 컨텍스트에서 실행합니다.
         System.runAs(testUser) {
            Test.startTest();
            
            // getCurrentUserInfo 메서드를 호출하여 결과를 가져옵니다.
            String result = CJFW_SurveyController.getCurrentUserInfo();
            
            // 여기에서 결과에 대한 검증 논리를 추가합니다.
            
            Test.stopTest();
        }
    }

    @isTest
    static void getSurveyType_Test(){
        Test.startTest();

        Map<String,Object> result = CJFW_SurveyController.getSurveyType();

        List<CJFW_Survey__c> surveyList =  (List<CJFW_Survey__c>) JSON.deserialize(JSON.serialize(result.get('surveyList')), List<CJFW_Survey__c>.class);

        System.assert(surveyList.size() == 4);

        Test.stopTest();
    }

    @isTest
    static void getSurvey_Test() {
        Test.startTest();

        List<CJFW_Survey__c> surveyList = [select id from CJFW_Survey__c where SU__c = '4600'];

        //1. 생성
        Map<String, Object> params = new Map<String, Object>();
        params.put('recordId', surveyList.get(0).id);
        params.put('mode', 'create');
        CJFW_SurveyController.getSurvey(params);

        //2. 수정
        params.put('mode', 'edit');
        CJFW_SurveyResponse__c response = CJFW_Survey_TEST.saveSurveyResponse(surveyList.get(0).id);
        params.put('surveyResponseId', response.id);
        CJFW_SurveyController.getSurvey(params);
        
        Test.stopTest();
    }


    @isTest
    static void saveSurveyResponse_TEST() {
        Test.startTest();

        List<CJFW_Survey__c> surveyList = [select id from CJFW_Survey__c where SU__c = '4600'];
        Map<String, List<CJFW_SurveyOption__c>> questionOptionListMap = new Map<String, List<CJFW_SurveyOption__c>>();
        String surveyId = surveyList.get(0).id;
        for(CJFW_SurveyQuestion__c quest : [
            select                              
                Id
                , Name                  //Auto Num
                , Name__c               //질문명
                , Survey__c             
                , Survey__r.Name        //설문 유형명
                , Survey__r.Description__c
                , Type__c               
                , MultipleChoice__c     
                , Order__c
                , DateType__c
                , (
                    select  
                        Id
                        , Order__c
                        , Name
                        , SurveyQuestion__c
                    from Survey_Option__r
                    order by Order__c, Name
                )
            from CJFW_SurveyQuestion__c       
            where Survey__c = :surveyId
            order by Order__c, Name
        ]) {
            List<CJFW_SurveyOption__c> optionList = new List<CJFW_SurveyOption__c>();

            for(CJFW_SurveyOption__c option : quest.Survey_Option__r) {
                optionList.add(option);
            }
            
            questionOptionListMap.put(quest.id, optionList);
        }
        System.debug(questionOptionListMap);
        Map<String, Object> params = new Map<String, Object>();
        params.put('recordId', surveyId);
        params.put('mode', 'create');
        Map<String,Object> result = CJFW_SurveyController.getSurvey(params);

        Map<String,Object> surveyObj = (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(result.get('survey')));
        
        List<Object> selectedObjList = new List<Object>();
        
        List<Object> questionObjList = (List<Object>)JSON.deserializeUntyped(JSON.serialize(surveyObj.get('questionList')));
        for(Object obj : questionObjList) {
            Map<String,Object> question = (Map<String,Object>) JSON.deserializeUntyped(JSON.serialize(obj));
            String questionId = String.valueOf(question.get('id'));
            String type = String.valueOf(question.get('type'));

            switch on type {
                when 'multiple' {
                    //객관식
                    if(Boolean.valueOf(question.get('isMultipleChoice'))) {
                        //복수선택
                        
                        List<String> selectedList = new List<String>();
                        for(CJFW_SurveyOption__c surveyOption : questionOptionListMap.get(questionId)) {
                            selectedList.add(surveyOption.id);
                        }

                        question.put('selectedValue', selectedList);

                    }else {
                        //단수선택
                        CJFW_Survey.QuestionOption selectedOption;
                        for(CJFW_SurveyOption__c surveyOption : questionOptionListMap.get(questionId)) {
                            selectedOption = new CJFW_Survey.QuestionOption(surveyOption);
                            break;
                        }

                        question.put('selectedValue', selectedOption);
                    }
                }
                when 'date' {
                    //날짜
                    
                    if(Boolean.valueOf(question.get('isFromTo'))) {
                        question.put('selectedValue', new List<Date>{
                            Date.today()
                            ,Date.today().addDays(1)
                        });
                        
                    }else{
                        question.put('selectedValue', Date.today());
                    }
                }when 'time' {
                    //시간
                    if(Boolean.valueOf(question.get('isFromTo'))) {
                        question.put('selectedValue', new List<Time>{
                            Time.newInstance(9, 0, 0, 0)
                            ,Time.newInstance(10, 0, 0, 0)
                        });
                    }
                }when else {
                    //주관식
                    question.put('selectedValue', '주관식 테스트');
                }
            }
            selectedObjList.add(question);
        }

        params.remove('recordId');

        params.put('surveyTypeId', surveyList.get(0).id);
        //System.debug(JSON.serializePretty(selectedObjList));
        params.put('selectedValueList', selectedObjList);
        //1. 생성
        CJFW_SurveyController.saveSurveyResponse(params);


        //2. 수정
        params.put('mode', 'edit');
        CJFW_SurveyController.saveSurveyResponse(params);
        Test.stopTest();
    }
}