force-app/main/default/objects/CJFW_Survey__c/CJFW_Survey__c.object-meta.xml
<CustomObject>
    <description>[P2] 형식지 유형</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyFollowUp__c/CJFW_SurveyFollowUp__c.object-meta.xml
<CustomObject>
    <description>[P2] 연계 질문</description>
    <label>Survey Follow Up</label>
    <nameField>
        <displayFormat>SF{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyFollowUp__c/fields/SurveyOption__c.field-meta.xml
<CustomField>
    <fullName>SurveyOption__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지 선택지</description>
    <label>Survey Option</label>
    <referenceTo>CJFW_SurveyOption__c</referenceTo>
    <relationshipLabel>Survey Follow Up</relationshipLabel>
    <relationshipName>Survey_Follow_Up</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyFollowUp__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지 질문</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Follow Up</relationshipLabel>
    <relationshipName>Survey_Follow_Up</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/CJFW_SurveyOption__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 객관식 문항</description>
    <label>Survey Option</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>순서</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <description>설문지 문항</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Option</relationshipLabel>
    <relationshipName>Survey_Option</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/CJFW_SurveyQuestion__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 질문</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ{YY}{MM}{DD}{000000}</displayFormat>
        <label>AutoNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/DateType__c.field-meta.xml
<CustomField>
    <fullName>DateType__c</fullName>
    <description>날짜유형 (From/ To) 설정</description>
    <label>Date Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From/To</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/MultipleChoice__c.field-meta.xml
<CustomField>
    <fullName>MultipleChoice__c</fullName>
    <description>객관식 유형</description>
    <label>Multiple Choice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>singular</fullName>
                <label>단수</label>
            </value>
            <value>
                <fullName>plural</fullName>
                <label>복수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>질문명</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>번호(순서)</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>질문유형</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>openended</fullName>
                <label>주관식</label>
            </value>
            <value>
                <fullName>multiple</fullName>
                <label>객관식</label>
            </value>
            <value>
                <fullName>date</fullName>
                <label>날짜</label>
            </value>
            <value>
                <fullName>time</fullName>
                <label>시간</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CJFW_Survey_tr.cls
/**
 * @description       :
 * @author            : sunkyung.choi@dkbmc.com
 * @group             :
 * @last modified on  : 10-23-2023
 * @last modified by  : sunkyung.choi@dkbmc.com
**/
public with sharing class CJFW_Survey_tr extends TriggerHandler {
    public CJFW_Survey_tr() {
        system.debug('Suvey Trigger Handler START');
        listNew = (List<CJFW_Survey__c>)Trigger.new;
        listOld = (List<CJFW_Survey__c>)Trigger.old;
        mapNew = (Map<Id, CJFW_Survey__c>)Trigger.newMap;
        mapOld = (Map<Id, CJFW_Survey__c>)Trigger.oldMap;
    }

    /*** TriggerHandler ***/
    private List<CJFW_Survey__c> listNew {
        get;
        set;
    }
    private List<CJFW_Survey__c> listOld {
        get;
        set;
    }
    private Map<Id, CJFW_Survey__c> mapNew {
        get;
        set;
    }
    private Map<Id, CJFW_Survey__c> mapOld {
        get;
        set;
    }

    public override void beforeInsert() {
        doClone();
    }
    public override void afterInsert() {
        doCloneInsert();
    }
    private void doClone() {
        system.debug('doClone  START');
        List<CJFW_Survey__c> newSurveys = listNew;
        System.debug('1111111: >>' + newSurveys);
        for (CJFW_Survey__c newSurvey : newSurveys) {
            newSurvey.Version__c = newSurvey.Version__c + 1;
            newSurvey.ParentSurvey__c = newSurvey.getCloneSourceId();

        }

    }
    private void doCloneInsert() {
        system.debug('doCloneInsert  START');
        List<CJFW_Survey__c> newSurveys = listNew;
        system.debug('22222 : >> ' + newSurveys);

        List < CJFW_SurveyQuestion__c > surveyQuestion = new List < CJFW_SurveyQuestion__c > ();
        List < CJFW_SurveyOption__c > surveyOption = new List < CJFW_SurveyOption__c > ();
        List < CJFW_SurveyFollowUp__c > surveyFollow = new List < CJFW_SurveyFollowUp__c > ();

        Set<Id> originId = new Set<Id>(); // 원본 ID
        Map<Id, Id> surveyIdMap = new Map<Id, Id>(); //새로 생성된 데이터 ID

        Set<Id> questionId = new Set<Id>(); // 원본 questioID
        Map<Id, Id> queCloneMap = new Map<Id, Id>(); // 복제 questioID
        
        Set<Id> optionId = new Set<Id>(); // 원본 optionID
        Map<Id, Id> optCloneMap = new Map<Id, Id>(); // 복제 optionID

        for (CJFW_Survey__c newSurvey : newSurveys) {
            originId.add(newSurvey.getCloneSourceId());
            surveyIdMap.put(newSurvey.getCloneSourceId(), newSurvey.Id);
        }
        List<CJFW_SurveyQuestion__c> originQuestionList = [
            SELECT Id,
            Name,
            Name__c,
            Survey__c,
            Type__c,
            MultipleChoice__c,
            Order__c,
            DateType__c,
            TextType__c FROM CJFW_SurveyQuestion__c WHERE Survey__c IN: originId
        ]; // 원본 Question 저장

        for (CJFW_SurveyQuestion__c originalQuestionChild : originQuestionList) {
            questionId.add(originalQuestionChild.Id);
            CJFW_SurveyQuestion__c newBchild = originalQuestionChild.clone(); // Bchild 레코드 복제
            newBchild.Survey__c = surveyIdMap.get(originalQuestionChild.Survey__c);
            surveyQuestion.add(newBchild);
            System.debug('surveyQuestion :: ' + surveyQuestion);

        }
        insert surveyQuestion;

        for (CJFW_SurveyQuestion__c surq : surveyQuestion) {
            queCloneMap.put(surq.getCloneSourceId(), surq.Id);
        }
        List < CJFW_SurveyOption__c > originOptionList = [
            SELECT Id,
            Name,
            CurrencyIsoCode,
            CreatedDate,
            CreatedById,
            Order__c,
            SurveyQuestion__c FROM CJFW_SurveyOption__c WHERE SurveyQuestion__c IN: questionId
        ]; // 원본 Option 저장

        System.debug('originOptionList>>>>' + originOptionList);

        for (CJFW_SurveyOption__c originOption : originOptionList) {
            optionId.add(originOption.Id);
            CJFW_SurveyOption__c newCchild = originOption.clone();
            newCchild.SurveyQuestion__c = queCloneMap.get(originOption.SurveyQuestion__c);
             
            System.debug('확인 Option 11>>>>' + newCchild.SurveyQuestion__c);
            surveyOption.add(newCchild);
            System.debug('확인 Option 22>>>>' + surveyOption);
        }
        insert surveyOption;
        
        for (CJFW_SurveyOption__c suro : surveyOption) {
            optCloneMap.put(suro.getCloneSourceId(), suro.Id);
        }
        List<CJFW_SurveyFollowUp__c> originFollowList = [
            SELECT Id,
            Name,
            SurveyQuestion__c,
            SurveyOption__c
            FROM CJFW_SurveyFollowUp__c WHERE SurveyQuestion__c IN: questionId AND SurveyOption__c IN: optionId
        ];

        for (CJFW_SurveyFollowUp__c originFollow : originFollowList) {
            CJFW_SurveyFollowUp__c newDchild = originFollow.clone();
            newDchild.SurveyQuestion__c = queCloneMap.get(originFollow.SurveyQuestion__c);
            newDchild.SurveyOption__c = optCloneMap.get(originFollow.SurveyOption__c);
            System.debug('확인 Follow 11>>>>' + newDchild.SurveyQuestion__c);
            System.debug('확인 Follow 12>>>>' + newDchild.SurveyOption__c);
            surveyFollow.add(newDchild);
            System.debug('확인 Follow 22>>>>' + surveyFollow);
        }
        insert surveyFollow;
    }


}