force-app/main/default/objects/CJFW_Survey__c/CJFW_Survey__c.object-meta.xml
<CustomObject>
    <description>[P2] 형식지 유형</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>설명</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyFollowUp__c/CJFW_SurveyFollowUp__c.object-meta.xml
<CustomObject>
    <description>[P2] 연계 질문</description>
    <label>Survey Follow Up</label>
    <nameField>
        <displayFormat>SF{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyFollowUp__c/fields/SurveyOption__c.field-meta.xml
<CustomField>
    <fullName>SurveyOption__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지 선택지</description>
    <label>Survey Option</label>
    <referenceTo>CJFW_SurveyOption__c</referenceTo>
    <relationshipLabel>Survey Follow Up</relationshipLabel>
    <relationshipName>Survey_Follow_Up</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyFollowUp__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지 질문</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Follow Up</relationshipLabel>
    <relationshipName>Survey_Follow_Up</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/CJFW_SurveyOption__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 객관식 문항</description>
    <label>Survey Option</label>
    <nameField>
        <label>Content</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>순서</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyOption__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <description>설문지 문항</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Option</relationshipLabel>
    <relationshipName>Survey_Option</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/CJFW_SurveyQuestion__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 질문</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ{YY}{MM}{DD}{000000}</displayFormat>
        <label>AutoNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/DateType__c.field-meta.xml
<CustomField>
    <fullName>DateType__c</fullName>
    <description>날짜유형 (From/ To) 설정</description>
    <label>Date Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From/To</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/MultipleChoice__c.field-meta.xml
<CustomField>
    <fullName>MultipleChoice__c</fullName>
    <description>객관식 유형</description>
    <label>Multiple Choice</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>singular</fullName>
                <label>단수</label>
            </value>
            <value>
                <fullName>plural</fullName>
                <label>복수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>질문명</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>번호(순서)</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Question</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyQuestion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>질문유형</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>openended</fullName>
                <label>주관식</label>
            </value>
            <value>
                <fullName>multiple</fullName>
                <label>객관식</label>
            </value>
            <value>
                <fullName>date</fullName>
                <label>날짜</label>
            </value>
            <value>
                <fullName>time</fullName>
                <label>시간</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResponse__c/CJFW_SurveyResponse__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 응답</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyResponse__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지</description>
    <label>Survey</label>
    <referenceTo>CJFW_Survey__c</referenceTo>
    <relationshipLabel>Survey Response</relationshipLabel>
    <relationshipName>Survey_Response</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/CJFW_SurveyResult__c.object-meta.xml
<CustomObject>
    <description>[P2] 설문지 결과지</description>
    <label>Survey Result</label>
    <nameField>
        <displayFormat>SR{YY}{MM}{DD}{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/SurveyOption__c.field-meta.xml
<CustomField>
    <fullName>SurveyOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>질문 선택지</description>
    <label>Survey Option</label>
    <referenceTo>CJFW_SurveyOption__c</referenceTo>
    <relationshipLabel>Survey Result</relationshipLabel>
    <relationshipName>Survey_Result</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CJFW_SurveyResult__c/fields/SurveyQuestion__c.field-meta.xml
<CustomField>
    <fullName>SurveyQuestion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>설문지 질문</description>
    <label>Survey Question</label>
    <referenceTo>CJFW_SurveyQuestion__c</referenceTo>
    <relationshipLabel>Survey Result</relationshipLabel>
    <relationshipName>Survey_Result</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/HeadOffice__c.field-meta.xml
<CustomField>
    <fullName>HeadOffice__c</fullName>
    <label>HeadOffice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3000</fullName>
                <label>FS본부</label>
            </value>
            <value>
                <fullName>3001</fullName>
                <label>급식SU</label>
            </value>
            <value>
                <fullName>6000</fullName>
                <label>외식SU</label>
            </value>
            <value>
                <fullName>6001</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>6002</fullName>
                <label>유통SU</label>
            </value>
            <value>
                <fullName>영업전략사업부</fullName>
            </value>
            <value>
                <fullName>Z000</fullName>
                <isActive>false</isActive>
                <label>기타</label>
            </value>
            <value>
                <fullName>1000</fullName>
                <isActive>false</isActive>
                <label>미래성장사업본부</label>
            </value>
            <value>
                <fullName>4000</fullName>
                <isActive>false</isActive>
                <label>상품·마케팅본부</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>유통사업총괄(영업)</label>
            </value>
            <value>
                <fullName>7000</fullName>
                <isActive>false</isActive>
                <label>축육혁신TF</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <isActive>false</isActive>
                <label>해외유통</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SU__c.field-meta.xml
<CustomField>
    <fullName>SU__c</fullName>
    <label>SU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>HeadOffice__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4716</fullName>
                <label>급식SU직속</label>
            </value>
            <value>
                <fullName>4100</fullName>
                <label>아이누리사업부</label>
            </value>
            <value>
                <fullName>4700</fullName>
                <label>급식솔루션사업부</label>
            </value>
            <value>
                <fullName>4705</fullName>
                <label>헬씨누리사업부</label>
            </value>
            <value>
                <fullName>4709</fullName>
                <label>튼튼스쿨사업부</label>
            </value>
            <value>
                <fullName>4710</fullName>
                <label>외식SU직속</label>
            </value>
            <value>
                <fullName>3900</fullName>
                <label>외식남부사업부</label>
            </value>
            <value>
                <fullName>4400</fullName>
                <label>외식중부사업부</label>
            </value>
            <value>
                <fullName>4712</fullName>
                <label>영업본부직속</label>
            </value>
            <value>
                <fullName>4600</fullName>
                <label>원료솔루션사업부</label>
            </value>
            <value>
                <fullName>4714</fullName>
                <label>유통SU직속</label>
            </value>
            <value>
                <fullName>4701</fullName>
                <label>유통중부사업부</label>
            </value>
            <value>
                <fullName>4706</fullName>
                <label>유통남부사업부</label>
            </value>
            <value>
                <fullName>2200</fullName>
                <label>FS전략사업부</label>
            </value>
            <value>
                <fullName>3100</fullName>
                <label>FS개발사업부</label>
            </value>
            <value>
                <fullName>CSC팀</fullName>
            </value>
            <value>
                <fullName>4702</fullName>
                <label>디지털사업부</label>
            </value>
            <value>
                <fullName>3601</fullName>
                <isActive>false</isActive>
                <label>FO미트사업부</label>
            </value>
            <value>
                <fullName>2900</fullName>
                <isActive>false</isActive>
                <label>FS경원사업부</label>
            </value>
            <value>
                <fullName>2203</fullName>
                <isActive>false</isActive>
                <label>FS급식경원사업부</label>
            </value>
            <value>
                <fullName>1901</fullName>
                <isActive>false</isActive>
                <label>FS급식동부사업부</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <isActive>false</isActive>
                <label>FS급식서부사업부</label>
            </value>
            <value>
                <fullName>2201</fullName>
                <isActive>false</isActive>
                <label>FS급식서울사업부</label>
            </value>
            <value>
                <fullName>2204</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래(조정)</label>
            </value>
            <value>
                <fullName>2202</fullName>
                <isActive>false</isActive>
                <label>FS급식직거래지원</label>
            </value>
            <value>
                <fullName>1900</fullName>
                <isActive>false</isActive>
                <label>FS남부운영그룹</label>
            </value>
            <value>
                <fullName>2100</fullName>
                <isActive>false</isActive>
                <label>FS레저운영그룹</label>
            </value>
            <value>
                <fullName>2700</fullName>
                <isActive>false</isActive>
                <label>FS병원운영그룹</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <isActive>false</isActive>
                <label>FS서부사업부</label>
            </value>
            <value>
                <fullName>1800</fullName>
                <isActive>false</isActive>
                <label>FS중부운영1그룹</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CJFW_Survey_TEST.cls
@isTest
public with sharing class CJFW_Survey_TEST {
    
    @testSetup
    static void makeData() {
        //원료솔루션사업부: 4600
        //급식솔루션사업부: 4700
        //아이누리사업부: 4100
        //헬씨누리사업부: 4705

        List<User> userList = new List<User>();
        String adminProfileName = 'System Administrator';

        if('ko'.equals(UserInfo.getLanguage())) {
            adminProfileName = '시스템 관리자';
        }

        Profile adminProfile = getProfile(adminProfileName);
        UserRole adminRole = getUserRole('SFDC_HQ_GM');
        User u = createUser(adminProfile.Id);
        u.LastName = '어드민 사용자';
        u.UserRoleId = adminRole.Id;
        userList.add(u);

        
        Profile pf4600 = getProfile('CJFW_원료솔루션사업부');
        UserRole role4600 = getUserRole('SFDC_6001_4600_Div_BM');
        User u4600 = createUser(pf4600.Id);
        u4600.UserRoleId = role4600.Id;
        u4600.LastName = '원료솔루션사업부 사용자';
        u4600.HeadOffice__c = '6001';
        u4600.SU__c = '4600';
        userList.add(u4600);

        insert userList;
       

        System.runAs(u) {
            List<CJFW_Survey__c> surveyList = new List<CJFW_Survey__c>();
            List<CJFW_SurveyQuestion__c> questionList = new List<CJFW_SurveyQuestion__c>();
            List<CJFW_SurveyOption__c> optionList = new List<CJFW_SurveyOption__c>();
            List<CJFW_SurveyFollowUp__c> followUpList = new List<CJFW_SurveyFollowUp__c>();

            CJFW_Survey__c survey4600 = new CJFW_Survey__c(
                Name = '원료 솔루션 설문지'
                ,Description__c = '원료 솔루션 설문지 설명'
                ,SU__c = '4600'
            );
            surveyList.add(survey4600);

            
            CJFW_Survey__c survey4700 = new CJFW_Survey__c(
                Name = '급식 솔루션 설문지'
                ,Description__c = '급식 솔루션 설문지 설명'
                ,SU__c = '4700'
            );
            surveyList.add(survey4700);

            
            CJFW_Survey__c survey4100 = new CJFW_Survey__c(
                Name = '아이누리 설문지'
                ,Description__c = '아이누리 설문지 설명'
                ,SU__c = '4100'
            );
            surveyList.add(survey4100);

            
            CJFW_Survey__c survey4705 = new CJFW_Survey__c(
                Name = '헬씨누리 설문지'
                ,Description__c = '헬씨누리 설문지 설명'
                ,SU__c = '4705'
            );
            surveyList.add(survey4705);

            insert surveyList;

            
            /*              Label(api)
                Type__c : 
                        주관식(openended)
                        객관식(multiple)
                        날짜(date)
                        시간(time)

                Type__c Dependency Picklist
                    -multiple
                        > MultipleChoice__c :
                                                단수(singular)
                                                복수(plural)
                    -date
                        > DateType__c : 
                                        시작/끝(From/To)
                                        일(Date)
            */
        
            //원료 솔루션 설문지는 연계 질문 x
            CJFW_SurveyQuestion__c question4600_opended = new CJFW_SurveyQuestion__c(
                    Name__c = '1. 첫번째 질문 - 주관식'
                    ,Order__c = 1
                    ,Survey__c = survey4600.Id
                    ,Type__c = 'openended'
            );
            questionList.add(question4600_opended);

            CJFW_SurveyQuestion__c question4600_multiple = new CJFW_SurveyQuestion__c(
                    Name__c = '2. 첫번째 질문 - 객관식 단수'
                    ,Order__c = 2
                    ,Survey__c = survey4600.Id
                    ,Type__c = 'multiple'
                    ,MultipleChoice__c = 'singular'
            );
            questionList.add(question4600_multiple);

            CJFW_SurveyQuestion__c question4600_multiple_plural = new CJFW_SurveyQuestion__c(
                    Name__c = '3. 첫번째 질문 - 객관식 복수'
                    ,Order__c = 3
                    ,Survey__c = survey4600.Id
                    ,Type__c = 'multiple'
                    ,MultipleChoice__c = 'plural'
            );
            questionList.add(question4600_multiple_plural);

            CJFW_SurveyQuestion__c question4600_date = new CJFW_SurveyQuestion__c(
                    Name__c = '4. 첫번째 질문 - 날짜'
                    ,Order__c = 4
                    ,Survey__c = survey4600.Id
                    ,Type__c = 'date'
                    ,DateType__c = 'Date'
            );
            questionList.add(question4600_date);

            CJFW_SurveyQuestion__c question4600_date_FromTo = new CJFW_SurveyQuestion__c(
                    Name__c = '5. 첫번째 질문 - 날짜 From/To'
                    ,Order__c = 5
                    ,Survey__c = survey4600.Id
                    ,Type__c = 'date'
                    ,DateType__c = 'From/To'
            );
            questionList.add(question4600_date_FromTo);

            CJFW_SurveyQuestion__c question4600_time = new CJFW_SurveyQuestion__c(
                    Name__c = '6. 첫번째 질문 - 시간 From/To'
                    ,Order__c = 6
                    ,Survey__c = survey4600.Id
                    ,Type__c = 'time'
            );
            questionList.add(question4600_time);

            /*급식솔루션 사업부 연계 질문  [s]*/
            CJFW_SurveyQuestion__c question4700_multiple = new CJFW_SurveyQuestion__c(
                    Name__c = '1. 첫번째 질문 - 객관식 단수'
                    ,Order__c = 1
                    ,Survey__c = survey4700.Id
                    ,Type__c = 'multiple'
                    ,MultipleChoice__c = 'singular'
            );
            questionList.add(question4700_multiple);

            CJFW_SurveyQuestion__c question4700_multiple_1 = new CJFW_SurveyQuestion__c(
                    Name__c = '1.1 첫번째 질문 - 첫번째 Option 의 Sub 질문'
                    ,Order__c = 1
                    ,Survey__c = survey4700.Id
                    ,Type__c = 'openended'
            );
            questionList.add(question4700_multiple_1);

            CJFW_SurveyQuestion__c question4700_multiple_2 = new CJFW_SurveyQuestion__c(
                    Name__c = '1.2 첫번째 질문 - 첫번째 Option 의 Sub 질문'
                    ,Order__c = 1
                    ,Survey__c = survey4700.Id
                    ,Type__c = 'openended'
            );
            questionList.add(question4700_multiple_2);
            /*급식솔루션 사업부 연계 질문  [e]*/

            insert questionList;

            
            CJFW_SurveyOption__c option_question4600_multiple = new CJFW_SurveyOption__c(
                Name = '첫번째 단수 옵션'
                ,Order__c = 1
                ,SurveyQuestion__c = question4600_multiple.Id
            );
            optionList.add(option_question4600_multiple);

            CJFW_SurveyOption__c option_question4600_multiple_two = new CJFW_SurveyOption__c(
                Name = '두번째 단수 옵션'
                ,Order__c = 2
                ,SurveyQuestion__c = question4600_multiple.Id
            );
            optionList.add(option_question4600_multiple_two);

            CJFW_SurveyOption__c option_question4600_multiple_three = new CJFW_SurveyOption__c(
                Name = '세번쨰 단수 옵션'
                ,Order__c = 3
                ,SurveyQuestion__c = question4600_multiple.Id
            );
            optionList.add(option_question4600_multiple_three);

            CJFW_SurveyOption__c option_question4600_multiple_four = new CJFW_SurveyOption__c(
                Name = '네번쨰 단수 옵션'
                ,Order__c = 4
                ,SurveyQuestion__c = question4600_multiple.Id
            );
            optionList.add(option_question4600_multiple_four);


            CJFW_SurveyOption__c option_question4600_multiple_plural = new CJFW_SurveyOption__c(
                Name = '첫번째 복수 옵션'
                ,Order__c = 1
                ,SurveyQuestion__c = question4600_multiple_plural.Id
            );
            optionList.add(option_question4600_multiple_plural);

            CJFW_SurveyOption__c option_question4600_multiple_plural_two = new CJFW_SurveyOption__c(
                Name = '두번째 복수 옵션'
                ,Order__c = 2
                ,SurveyQuestion__c = question4600_multiple_plural.Id
            );
            optionList.add(option_question4600_multiple_plural_two);

            CJFW_SurveyOption__c option_question4600_multiple_plural_three = new CJFW_SurveyOption__c(
                Name = '세번쨰 복수 옵션'
                ,Order__c = 3
                ,SurveyQuestion__c = question4600_multiple_plural.Id
            );
            optionList.add(option_question4600_multiple_plural_three);

            CJFW_SurveyOption__c option_question4600_multiple_plural_four = new CJFW_SurveyOption__c(
                Name = '네번쨰 복수 옵션'
                ,Order__c = 4
                ,SurveyQuestion__c = question4600_multiple_plural.Id
            );
            optionList.add(option_question4600_multiple_plural_four);

            /*급식솔루션 사업부 연계 질문 - 옵션  [s]*/
            CJFW_SurveyOption__c option_question4700_multiple = new CJFW_SurveyOption__c(
                Name = '첫번째 단수 옵션'
                ,Order__c = 1
                ,SurveyQuestion__c = question4700_multiple.Id
            );
            optionList.add(option_question4700_multiple);

            CJFW_SurveyOption__c option_question4700_multiple_two = new CJFW_SurveyOption__c(
                Name = '두번째 단수 옵션'
                ,Order__c = 2
                ,SurveyQuestion__c = question4700_multiple.Id
            );
            optionList.add(option_question4700_multiple_two);

            CJFW_SurveyOption__c option_question4700_multiple_three = new CJFW_SurveyOption__c(
                Name = '세번쨰 단수 옵션'
                ,Order__c = 3
                ,SurveyQuestion__c = question4700_multiple.Id
            );
            optionList.add(option_question4700_multiple_three);

            CJFW_SurveyOption__c option_question4700_multiple_four = new CJFW_SurveyOption__c(
                Name = '네번쨰 단수 옵션'
                ,Order__c = 4
                ,SurveyQuestion__c = question4700_multiple.Id
            );
            optionList.add(option_question4700_multiple_four);
            /*급식솔루션 사업부 연계 질문 - 옵션  [e]*/
            insert optionList;


            /*급식솔루션 사업부 연계 질문 - 연계  [s]*/
            CJFW_SurveyFollowUp__c followup4700 = new CJFW_SurveyFollowUp__c(
                SurveyQuestion__c = question4700_multiple_1.id,
                SurveyOption__c = option_question4700_multiple.id
            );
            followUpList.add(followup4700);

            CJFW_SurveyFollowUp__c followup4700_two = new CJFW_SurveyFollowUp__c(
                SurveyQuestion__c = question4700_multiple_2.id,
                SurveyOption__c = option_question4700_multiple.id
            );
            followUpList.add(followup4700_two);
            insert followUpList;
            /*급식솔루션 사업부 연계 질문 - 연계  [e]*/

            CJFW_Survey__Share u4600Share = new CJFW_Survey__Share(
                AccessLevel = 'Read'
                ,UserOrGroupId = u4600.Id
                ,ParentID = survey4600.Id
            );

            insert u4600Share;
        }

    }

    @isTest
    static void constructor_Test() {
        test.startTest();
        Map<String, CJFW_Survey__c> surveyMap = new Map<String, CJFW_Survey__c>();

        for(CJFW_Survey__c survey :[
                select id, SU__c from CJFW_Survey__c 
        ]) {
            surveyMap.put(survey.SU__c,  survey);
        }

        //1. 기본
        new CJFW_Survey();

        //2. 원료솔루션사업부: 4600 - 연계질문x
        CJFW_Survey__c survey4600 = surveyMap.get('4600');
        CJFW_Survey survey4600Wrapper = new CJFW_Survey(survey4600.id);

        //3. 급식솔루션 4700 - 연계질문
        CJFW_Survey__c survey4700 = surveyMap.get('4700');
        CJFW_Survey survey4700Wrapper = new CJFW_Survey(survey4700.id);

        for(CJFW_Survey.Question question : survey4700Wrapper.questionList) {
            System.debug(question.content);
        }


        test.stopTest();
    }

    @isTest
    public static void user4600_Execute() {
        test.startTest();
        

        User u4600 =  [select id, LastName from User where LastName = '원료솔루션사업부 사용자' limit 1];

        System.runAs(u4600) {

            List<CJFW_SurveyResponse__c> responseList = new List<CJFW_SurveyResponse__c>();
            List<CJFW_SurveyResult__c> responsResultList = new List<CJFW_SurveyResult__c>();
            System.debug('surveyList :: ');
            System.debug([select id, SU__c, Name from CJFW_Survey__c ]);

            CJFW_Survey__c survey = [select id from CJFW_Survey__c where SU__c = '4600' limit 1];
            
            CJFW_SurveyResponse__c response = new CJFW_SurveyResponse__c();
            response.Survey__c = survey.id;
            response.ResponseDate__c = Date.today();
            responseList.add(response);

            insert responseList;

            for(CJFW_SurveyQuestion__c question :[
                select 
                    id
                    , survey__c
                    , name
                    , Type__c               
                    , MultipleChoice__c     
                    , Order__c
                    , DateType__c
                    , (
                        select  
                            Id
                            , Order__c
                            , Name
                            , SurveyQuestion__c
                        from Survey_Option__r
                        order by Order__c, Name
                    )
                from CJFW_SurveyQuestion__c
                where 
                    Survey__c = :survey.id
                order by Order__c, Name
            ]) {
                CJFW_SurveyResult__c result = new CJFW_SurveyResult__c(
                    SurveyResponse__c = response.id
                    ,SurveyQuestion__c = question.id
                );

                if('openended'.equals(question.Type__c)) {
                    //주관식
                    result.OpenEnded__c = '주관식 답변';
                    responsResultList.add(result);
                }else if('multiple'.equals(question.Type__c)) {
                    //객관식
                    for(CJFW_SurveyOption__c option : question.Survey_Option__r) {

                        if('singular'.equals(question.MultipleChoice__c)) {
                            result.SurveyOption__c = option.id;
                            responsResultList.add(result);
                            break;
                        }else if('plural'.equals(question.MultipleChoice__c)) {
                            CJFW_SurveyResult__c cloneResult = result.clone(false);
                            cloneResult.SurveyOption__c = option.id;
                            responsResultList.add(cloneResult);
                        }
                    }
                }else if('date'.equals(question.Type__c)) {
                    //날짜
                    if('Date'.equals(question.DateType__c)) {
                        result.DateResult__c = Date.today().addDays(1);
                        responsResultList.add(result);
                    }
                    
                    if('From/To'.equals(question.DateType__c)) {
                        CJFW_SurveyResult__c cloneResult = result.clone(false);
                        cloneResult.DateResult__c = Date.today().addDays(2);
                        responsResultList.add(cloneResult);
                    }

                }else if('time'.equals(question.Type__c)) { 
                    //시간

                    result.TimeResult__c = Time.newInstance(9, 0, 0, 0);
                    responsResultList.add(result);

                    CJFW_SurveyResult__c cloneResult = result.clone(false);
                    cloneResult.TimeResult__c = Time.newInstance(10, 0, 0, 0);
                    responsResultList.add(cloneResult);
                }
            }

            insert responsResultList;

            CJFW_Survey resultSurvey = new CJFW_Survey(survey.id , response.id);
            CJFW_Survey.Question resultSurveyQuestion = resultSurvey.questionList.get(0);

            System.assert('주관식 답변'.equals(String.valueOf(resultSurveyQuestion.selectedValue)) , true);
        }

        test.stopTest();
    }

    public static Profile getProfile(String profileName) { 
        Profile pf = [SELECT Id, Name FROM Profile WHERE Name = :profileName LIMIT 1];
        
        return pf;
    }

    public static User createUser(String profileId){
        User user = new User(
            ProfileId = profileId
            , Alias = 'Alias'
            , Username = 'Test@test.com' + System.currentTimeMillis()
            , EmployeeNumber = '998877'
            , Email = 'Test@test.com'
            , FirstName = 'Test'
            , LastName = 'Test'
            , LocaleSidKey = 'en_US'
            , LanguageLocaleKey = 'en_US'
            , EmailEncodingKey = 'UTF-8'
            , TimeZoneSidKey = 'America/Los_Angeles'
            , IsActive = true
            , FederationIdentifier = 'Test' + System.currentTimeMillis()
        );

        return user;
    }

    public static UserRole getUserRole(String roleName) { 
        UserRole role = [SELECT Id, Name, DeveloperName FROM UserRole WHERE DeveloperName = :roleName];
        
        return role;
    }
}