force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/InterfaceId__c.field-meta.xml
<CustomField>
    <fullName>InterfaceId__c</fullName>
    <label>InterfaceId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/WebserviceType__c.field-meta.xml
<CustomField>
    <fullName>WebserviceType__c</fullName>
    <label>WebserviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/OrderServiceRequest__c.object-meta.xml
<CustomObject>
    <description>주문 서비스 요청</description>
    <label>OrderServiceRequest</label>
    <nameField>
        <label>OrderServiceRequest__c 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderServiceRequest__c/fields/CustomerID__c.field-meta.xml
<CustomField>
    <fullName>CustomerID__c</fullName>
    <label>CustomerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ExtraServiceCategory__c.field-meta.xml
<CustomField>
    <fullName>ExtraServiceCategory__c</fullName>
    <label>부가서비스카테고리</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ExtraServiceCategoryCode__c.field-meta.xml
<CustomField>
    <fullName>ExtraServiceCategoryCode__c</fullName>
    <description>주문시스템의 부가서비스내역 코드</description>
    <label>ExtraServiceCategoryCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Finder__c.field-meta.xml
<CustomField>
    <fullName>Finder__c</fullName>
    <description>접수자</description>
    <label>Finder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ReqRecordId__c.field-meta.xml
<CustomField>
    <fullName>ReqRecordId__c</fullName>
    <description>주문시스템레코드ID</description>
    <label>ReqRecordId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ReqType__c.field-meta.xml
<CustomField>
    <fullName>ReqType__c</fullName>
    <label>ReqType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>샘플요청</fullName>
            </value>
            <value>
                <fullName>부가서비스 요청</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/ReqTypeCode__c.field-meta.xml
<CustomField>
    <fullName>ReqTypeCode__c</fullName>
    <description>문의 구분 코드</description>
    <label>ReqTypeCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/RequestDate__c.field-meta.xml
<CustomField>
    <fullName>RequestDate__c</fullName>
    <description>작성일</description>
    <label>RequestDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/RequestMessage__c.field-meta.xml
<CustomField>
    <fullName>RequestMessage__c</fullName>
    <description>문의접수내용</description>
    <label>RequestMessage</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/SampleitemText1__c.field-meta.xml
<CustomField>
    <fullName>SampleitemText1__c</fullName>
    <description>신청샘플상품텍스트1</description>
    <label>SampleitemText1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/SampleitemText2__c.field-meta.xml
<CustomField>
    <fullName>SampleitemText2__c</fullName>
    <description>신청샘플상품텍스트2</description>
    <label>SampleitemText2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/SampleitemText3__c.field-meta.xml
<CustomField>
    <fullName>SampleitemText3__c</fullName>
    <description>신청샘플상품텍스트3</description>
    <label>SampleitemText3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderServiceRequest__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>접수 제목</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IFN_LIF1002_OD002_MD003_TEST.cls
@isTest
public with sharing class IFN_LIF1002_OD002_MD003_TEST {
    @TestSetup
    static void makeData(){
        IFMaster__c ifMaster = new IFMaster__c(
            Name = 'IFN_LIF1002_OD002_MD003',
            InterfaceId__c = 'IFN_LIF1002_OD002_MD003',
            Type__c = 'Inbound',
            WebserviceType__c = 'REST',
            Method__c = 'POST',
            ContentType__c = 'application/json'
        );

        insert ifMaster;

        Date requestDate = IFN_Util.convertDate('2023-08-21');
        Id osrRcdTp = Schema.SObjectType.OrderServiceRequest__c.getRecordTypeInfosByDeveloperName().get('01').getRecordTypeId();

        OrderServiceRequest__c orderServiceReq = new OrderServiceRequest__c(
                            Title__c = '식료품신청'
                        , ReqType__c = '01'
                        , ReqTypeCode__c = '01' 
                        , RequestMessage__c = '식료품신청'
                        , SampleitemText1__c = '샘플상품1'
                        , SampleitemText2__c = '샘플상품2'
                        , SampleitemText3__c = '샘플상품3'
                        , ExtraServiceCategory__c = '가공류'
                        // , ExtraServiceCategoryCode__c = input.ExtSvcCd
                        , CustomerID__c = 'AAA'
                        , RequestDate__c = requestDate
                        , Finder__c = '[36110]세종시'
                        , ReqRecordId__c = '1223334'
                        , RecordTypeId = osrRcdTp
        );

        insert orderServiceReq;
    }

    @isTest
    static void IFN_LIF1002_OD002_MD003_TEST(){
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();

        OrderServiceRequest__c orderServiceReq = [select Id from OrderServiceRequest__c Where ReqRecordId__c = '1223334' Limit 1];

        // Success Test 1
        String strBody = '{"reqId": "1223334","resId": '+ orderServiceReq.Id +'}';
        req.requestBody = Blob.valueof(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD002_MD003.doPost();
        
        // Success Test 2
        strBody = '{"reqId": "1223334"}';
        req.requestBody = Blob.valueof(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD002_MD003.doPost();

        // Error Test 1
        strBody = '';
        req.requestBody = Blob.valueof(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD002_MD003.doPost();

        // Error Test 2
        strBody = '{"dummy1": "1223334","dummy2": '+ orderServiceReq.Id +'}';
        req.requestBody = Blob.valueof(strBody);
        RestContext.request = req;
        RestContext.response = res;
        IFN_LIF1002_OD002_MD003.doPost();

        Test.stopTest();
    }
}