force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/BidDeterminMethod__c.field-meta.xml
<CustomField>
    <fullName>BidDeterminMethod__c</fullName>
    <description>국방전자조달시스템 낙찰자결정방법</description>
    <label>Bid Determin Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidLetterSubmitCloseDateTime__c.field-meta.xml
<CustomField>
    <fullName>BidLetterSubmitCloseDateTime__c</fullName>
    <description>귝방전자조달시스템 입찰서 제출 마감일시</description>
    <label>Bid Letter Submit Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidMethod__c.field-meta.xml
<CustomField>
    <fullName>BidMethod__c</fullName>
    <description>나라장터와 국방전자조달사이트에서 사용하는 입찰 방식</description>
    <label>Bid Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidNoticeName__c.field-meta.xml
<CustomField>
    <fullName>BidNoticeName__c</fullName>
    <description>나라장터와 국방전자조달사이트에서 사용하는 입찰 공고명</description>
    <externalId>true</externalId>
    <label>Bid Notice Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidNoticeNumber__c.field-meta.xml
<CustomField>
    <fullName>BidNoticeNumber__c</fullName>
    <description>나라장터와 국방전자조달사이트에서 사용하는 입찰 공고 번호</description>
    <externalId>true</externalId>
    <label>Bid Notice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidNoticeStatus__c.field-meta.xml
<CustomField>
    <fullName>BidNoticeStatus__c</fullName>
    <description>나라장터와 국방전자조달사이트에서 사용하는 공고 상태명 Picklist Value</description>
    <label>Bid Notice Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidOpenDateTime__c.field-meta.xml
<CustomField>
    <fullName>BidOpenDateTime__c</fullName>
    <description>나라장터와 국방전자조달사이트에서 사용하는 개찰 일시</description>
    <label>Bid Open Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidQualifyRegistCloseDateTime__c.field-meta.xml
<CustomField>
    <fullName>BidQualifyRegistCloseDateTime__c</fullName>
    <description>나라장터 입찰 참가 자격 등록 마감 일시</description>
    <label>Bid Qualify Regist Close Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BidStatus__c.field-meta.xml
<CustomField>
    <fullName>BidStatus__c</fullName>
    <description>국방전자조달시스템 입찰 형태</description>
    <label>Bid Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/bsicExpt__c.field-meta.xml
<CustomField>
    <fullName>bsicExpt__c</fullName>
    <label>bsicExpt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/bsisPrdprcApplcAt__c.field-meta.xml
<CustomField>
    <fullName>bsisPrdprcApplcAt__c</fullName>
    <label>bsisPrdprcApplcAt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/bsisPrdprcOthbcAt__c.field-meta.xml
<CustomField>
    <fullName>bsisPrdprcOthbcAt__c</fullName>
    <label>bsisPrdprcOthbcAt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/BudgetAmount__c.field-meta.xml
<CustomField>
    <fullName>BudgetAmount__c</fullName>
    <description>국방전자조달시스템 예산금액</description>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ContractSignMethod__c.field-meta.xml
<CustomField>
    <fullName>ContractSignMethod__c</fullName>
    <description>나라장터와 국방전자조달사이트에서 사용하는 공고 계약 체결 방법</description>
    <label>Contract Sign Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ContractType__c.field-meta.xml
<CustomField>
    <fullName>ContractType__c</fullName>
    <description>국방전자조달시스템 계약 종류</description>
    <label>Contract Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/excutTy__c.field-meta.xml
<CustomField>
    <fullName>excutTy__c</fullName>
    <label>excutTy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Keyword__c.field-meta.xml
<CustomField>
    <fullName>Keyword__c</fullName>
    <externalId>true</externalId>
    <label>Keyword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/KeywordSub__c.field-meta.xml
<CustomField>
    <fullName>KeywordSub__c</fullName>
    <label>KeywordSub</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/pblancDate__c.field-meta.xml
<CustomField>
    <fullName>pblancDate__c</fullName>
    <label>pblancDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/MilitaryLead.recordType-meta.xml
<RecordType>
    <fullName>MilitaryLead</fullName>
    <active>true</active>
    <businessProcess>Standard Lead Process</businessProcess>
    <description>국방조달 사이트에서 생성 및 업데이트 되는 Lead</description>
    <label>Military Lead</label>
</RecordType>

force-app/main/default/objects/NaramarketKeyword__mdt/NaramarketKeyword__mdt.object-meta.xml
<CustomObject>
    <label>NaramarketKeyword</label>
</CustomObject>

force-app/main/default/objects/NaramarketKeyword__mdt/fields/Keyword_Lv__c.field-meta.xml
<CustomField>
    <fullName>Keyword_Lv__c</fullName>
    <description>검색 키워드 필터 레벨</description>
    <label>Keyword_Lv</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NaramarketKeyword__mdt/fields/Keyword_seq__c.field-meta.xml
<CustomField>
    <fullName>Keyword_seq__c</fullName>
    <description>키워드 조회 순서 시퀀스</description>
    <label>Keyword_seq</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IF_SFDC_DATA_REQ_D2BBID_INFO_DETAIL_ba.cls
/**
 * @description       : IF_SFDC_DATA_REQ_D2BBID_INFO_ba에서 받아온 list에대한 디테일 조회
 * @author            : AhnTaeJin(tj.ahn@daeunextier.com)
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : admin
**/
global with sharing class IF_SFDC_DATA_REQ_D2BBID_INFO_DETAIL_ba implements Database.batchable<IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Items>, Database.Stateful, Database.AllowsCallouts{
    
    IFMaster__c ifMasterObj = [SELECT Id, Name, ContentType__c, Endpoint__c, Method__c FROM IFMaster__c WHERE Name = 'IF_SFDC_DATA_REQ_D2BBID_INFO_DETAIL'];
    List<NaramarketKeyword__mdt> subKeywordList = [SELECT Keyword__c, keyword_seq__c FROM NaramarketKeyword__mdt WHERE Keyword_lv__c = 2 ORDER BY keyword_seq__c ASC];
    Id recordId = Schema.SObjectType.LEAD.getRecordTypeInfosByDeveloperName().get('MilitaryLead').getRecordTypeId();
    
    AssignmentRule AR = [select id from AssignmentRule where SobjectType = 'Lead' and Active = true limit 1];
    Database.DMLOptions dmlOpts = new Database.DMLOptions();

    List<IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Items> inputItemsList = new List<IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Items>();
    Set<String> bidNoticeNumSet = new Set<String>();


    global IF_SFDC_DATA_REQ_D2BBID_INFO_DETAIL_ba(List<IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Items> inputItemsList) {
        this.inputItemsList = inputItemsList;
    }
    /***********************************************************************************************************
    *  Bacth   : start
    *  내용    : 국방부 전자조달 마스터 리턴
    ************************************************************************************************************/
    global Iterable<IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Items> start(Database.BatchableContext bc) {
        return inputItemsList;
    }
    /***********************************************************************************************************
    *  Bacth   : execute
    *  내용    : 국방부 전자조달정보 상세조회 API 호출 및 Lead 생성 
    ************************************************************************************************************/
    global void execute(Database.BatchableContext BC, List<IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Items> scope) {

        IFUtil objIf = new IFUtil('IF_SFDC_DATA_REQ_D2BBID_INFO_DETAIL');
        LogWrapper objWrapper = new LogWrapper();
        dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;
        // dmlOpts.EmailHeader.TriggerUserEmail = true;

        String strStatus = 'SUCCESS';
        String strCode = '0000';
        String strMessage = 'callout success';
        String result = '';
        String getParameter = '';

        LogWrapper LogWrapper = new LogWrapper();
        LogWrapper.requestTime = Datetime.now();


        getParameter += 'getDmstcCmpetBidPblancDetail';
        getParameter += '?demandYear='+ scope[0].demandYear;
        getParameter += '&orntCode='+ scope[0].orntCode;
        getParameter += '&dcsNo=' + scope[0].dcsNo;
        getParameter += '&pblancNo=' + scope[0].pblancNo;
        getParameter += '&pblancOdr=' + scope[0].pblancOdr;
        System.debug(getParameter);

        try {

            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(ifMasterObj.Endpoint__c + getParameter);
            System.debug(request.getEndpoint());
            request.setHeader('content-type', ifMasterObj.ContentType__c);
            request.setMethod(ifMasterObj.Method__c);
            request.setTimeout(110000);
            HttpResponse res = http.send(request);

            if(res.getStatusCode() == 200) {
                String strJSON = XMLParser.xmlToJson(res.getBody());
                result = strJSON;
                System.debug('==================================getBody:::' + strJSON);
                IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Input input = (IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Input) JSON.deserialize(strJSON, IF_SFDC_DATA_REQ_D2BBID_INFO_sc.Input.class);
                String bidNo = '';
                Map<String,Lead> uptLeadMap = new Map<String,Lead>();
                
                if (Integer.valueOf(input.response.body.item.g2bPblancOdr) < 10) {
                    Integer ord = Integer.valueOf(input.response.body.item.g2bPblancOdr);
                    bidNo = (scope[0].demandYear+input.response.body.item.g2bPblancNo+'-0'+ String.valueOf(ord));
                }else {
                    bidNo = (scope[0].demandYear+input.response.body.item.g2bPblancNo+'-'+input.response.body.item.g2bPblancOdr);
                }
                for (Lead obj : [SELECT Id, BidNoticeNumber__c 
                                        FROM Lead 
                                        WHERE BidNoticeNumber__c =: bidNo]) {
                        uptLeadMap.put(obj.BidNoticeNumber__c, obj);
                    }
                
                if (uptLeadMap.get(bidNo) <> null) {
                    Lead uptLead = uptLeadMap.get(bidNo);
                    uptLead.LastName = input.response.body.item.chargerNm;
                    uptLead.Status = 'New';
                    uptLead.MobilePhone = input.response.body.item.chargerCttpc;
                    uptLead.Company = input.response.body.item.ornt;
                    // uptLead.BidNoticeNumber__c = input.response.body.item.pblancNo;
                    uptLead.BidNoticeStatus__c = input.response.body.item.pblancSe;
                    uptLead.BidNoticeName__c = input.response.body.item.bidNm;
                    uptLead.BidMethod__c = input.response.body.item.bidMth;
                    uptLead.ContractSignMethod__c = input.response.body.item.cntrctMth;
                    uptLead.BidStatus__c = input.response.body.item.bidStle;
                    uptLead.ContractType__c = input.response.body.item.cntrctKnd;
                    //판단요구년도 공고번호 판단번호와 나라장터기준 차수를 조합하여 외부키값인 나라장터공고번호를 생성 및 적재
                    if (Integer.valueOf(input.response.body.item.g2bPblancOdr) < 10) {
                        Integer ord = Integer.valueOf(input.response.body.item.g2bPblancOdr);
                        uptLead.BidNoticeNumber__c = scope[0].demandYear+input.response.body.item.g2bPblancNo+'-0'+ String.valueOf(ord);
                    }else {
                        uptLead.BidNoticeNumber__c = scope[0].demandYear+input.response.body.item.g2bPblancNo+'-'+input.response.body.item.g2bPblancOdr;
                    }
                    Datetime dt = Datetime.newInstance(
                        Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(0,4))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(3,5))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(4,6))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(5,7))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(6,8))
                        , 0
                        );
                    uptLead.BidQualifyRegistCloseDateTime__c = dt;
                    dt = Datetime.newInstance(
                        Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(0,4))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(3,5))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(4,6))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(5,7))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(6,8))
                        , 0
                        );
                    uptLead.BidLetterSubmitCloseDateTime__c = dt;
                    dt = Datetime.newInstance(
                        Integer.valueOf(input.response.body.item.opengDt.substring(0,4))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(3,5))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(4,6))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(5,7))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(6,8))
                        , 0
                        );
                    uptLead.BidOpenDateTime__c = dt;
                    if (input.response.body.item.pblancDate <> null && input.response.body.item.pblancDate <> '') {
                        Date d = Date.newInstance(
                            Integer.valueOf(input.response.body.item.pblancDate.substring(0,4))
                            , Integer.valueOf(input.response.body.item.pblancDate.substring(3,5))
                            , Integer.valueOf(input.response.body.item.pblancDate.substring(4,6))
                            );

                        uptLead.pblancDate__c = d;
                    }
                    uptLead.LeadSource = 'Military';
                    uptLead.BudgetAmount__c = input.response.body.item.budgetAmount <> null ? Decimal.valueOf(input.response.body.item.budgetAmount) : null;
                    uptLead.BidDeterminMethod__c = input.response.body.item.sucbidrDecsnMth;
                    uptLead.excutTy__c = input.response.body.item.excutTy;
                    uptLead.bsisPrdprcApplcAt__c = input.response.body.item.bsisPrdprcApplcAt;
                    uptLead.bsicExpt__c = scope[0].bsicExpt <> null ? Decimal.valueOf(scope[0].bsicExpt) : null;
                    uptLead.bsisPrdprcOthbcAt__c = scope[0].bsisPrdprcOthbcAt;
                    uptLead.Keyword__c = scope[0].keyword;
                    uptLead.RecordtypeId = recordId;
                    for (NaramarketKeyword__mdt keyword : subKeywordList) {
                        if (input.response.body.item.bidNm.contains(keyword.Keyword__c)) {
                            uptLead.KeywordSub__c = keyword.Keyword__c;
                            break;
                        }
                    }
                    update uptLead;
                }else {
                    Lead objLead = new Lead();
                    objLead.setOptions(dmlOpts);
                    objLead.LastName = input.response.body.item.chargerNm;
                    objLead.Status = 'New';
                    objLead.MobilePhone = input.response.body.item.chargerCttpc;
                    objLead.Company = input.response.body.item.ornt;
                    objLead.BidNoticeStatus__c = input.response.body.item.pblancSe;
                    objLead.BidNoticeName__c = input.response.body.item.bidNm;
                    objLead.BidMethod__c = input.response.body.item.bidMth;
                    objLead.ContractSignMethod__c = input.response.body.item.cntrctMth;
                    objLead.BidStatus__c = input.response.body.item.bidStle;
                    objLead.ContractType__c = input.response.body.item.cntrctKnd;
                    //판단요구년도 공고번호 판단번호와 나라장터기준 차수를 조합하여 외부키값인 나라장터공고번호를 생성 및 적재
                    if (Integer.valueOf(input.response.body.item.g2bPblancOdr) < 10) {
                        Integer ord = Integer.valueOf(input.response.body.item.g2bPblancOdr);
                        objLead.BidNoticeNumber__c = scope[0].demandYear+input.response.body.item.g2bPblancNo+'-0'+ String.valueOf(ord);
                    }else {
                        objLead.BidNoticeNumber__c = scope[0].demandYear+input.response.body.item.g2bPblancNo+'-'+input.response.body.item.g2bPblancOdr;
                    }
                    Datetime dt = Datetime.newInstance(
                        Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(0,4))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(3,5))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(4,6))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(5,7))
                        ,Integer.valueOf(input.response.body.item.bidPartcptRegistClosDt.substring(6,8))
                        , 0
                        );
                    objLead.BidQualifyRegistCloseDateTime__c = dt;
                    dt = Datetime.newInstance(
                        Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(0,4))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(3,5))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(4,6))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(5,7))
                        ,Integer.valueOf(input.response.body.item.biddocPresentnClosDt.substring(6,8))
                        , 0
                        );
                    objLead.BidLetterSubmitCloseDateTime__c = dt;
                    dt = Datetime.newInstance(
                        Integer.valueOf(input.response.body.item.opengDt.substring(0,4))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(3,5))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(4,6))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(5,7))
                        ,Integer.valueOf(input.response.body.item.opengDt.substring(6,8))
                        , 0
                        );
                    objLead.BidOpenDateTime__c = dt;
                    if (input.response.body.item.pblancDate <> null && input.response.body.item.pblancDate <> '') {
                        Date d = Date.newInstance(
                            Integer.valueOf(input.response.body.item.pblancDate.substring(0,4))
                            , Integer.valueOf(input.response.body.item.pblancDate.substring(3,5))
                            , Integer.valueOf(input.response.body.item.pblancDate.substring(4,6))
                            );
    
                        objLead.pblancDate__c = d;
                    }
                    objLead.LeadSource = 'Military';
                    objLead.BudgetAmount__c = input.response.body.item.budgetAmount <> null ? Decimal.valueOf(input.response.body.item.budgetAmount) : null;
                    objLead.BidDeterminMethod__c = input.response.body.item.sucbidrDecsnMth;
                    objLead.excutTy__c = input.response.body.item.excutTy;
                    objLead.bsisPrdprcApplcAt__c = input.response.body.item.bsisPrdprcApplcAt;
                    objLead.bsicExpt__c = scope[0].bsicExpt <> null ? Decimal.valueOf(scope[0].bsicExpt) : null;
                    objLead.bsisPrdprcOthbcAt__c = scope[0].bsisPrdprcOthbcAt;
                    objLead.Keyword__c = scope[0].keyword;
                    objLead.RecordtypeId = recordId;
                    for (NaramarketKeyword__mdt keyword : subKeywordList) {
                        if (input.response.body.item.bidNm.contains(keyword.Keyword__c)) {
                            objLead.KeywordSub__c = keyword.Keyword__c;
                            break;
                        }
                    }
                    insert objLead;
                }
                        
            }
        } catch (Exception e) {
            strCode = '-1';
            strStatus = 'ERROR';
            strMessage = e.getLineNumber() + e.getStackTraceString() + e.getMessage();
        }
        
        objWrapper.status = strStatus;
        objWrapper.resultCode = strCode;
        objWrapper.resultMessage = strMessage;
        objWrapper.requestBody = getParameter;
        objWrapper.responseBody = result;
        objWrapper.responseTime = Datetime.now();
        
        objIf.setLog(objWrapper);
    }
    /***********************************************************************************************************
    *  Bacth   : finish
    *  내용    : 없음
    ************************************************************************************************************/
    global void finish(Database.BatchableContext BC) {
        System.debug('=============================:::batch finish');
    }
}