force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/WebserviceType__c.field-meta.xml
<CustomField>
    <fullName>WebserviceType__c</fullName>
    <label>WebserviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_SFDC_IFRESH_REG_ACCOUNT_test.cls
/**
 * Created by kw on 2023-01-06.
 */

@IsTest
private class IF_SFDC_IFRESH_REG_ACCOUNT_test {
    @TestSetup
    static void makeData(){
        List<IFMaster__c> listIFMaster = new List<IFMaster__c>();
        List<String> listIF = new List<String>{'IF_SFDC_IFRESH_REG_ACCOUNT'};

        for(String str : listIF) {
            IFMaster__c objIFMaster = new IFMaster__c();

            objIFMaster.Name = str;
            objIFMaster.Type__c = 'Outbound';
            objIFMaster.WebserviceType__c = 'REST';
            objIFMaster.Method__c = 'GET';
            objIFMaster.ContentType__c = 'application/json';
            objIFMaster.Endpoint__c = 'test';

            listIFMaster.add(objIFMaster);
        }

        insert listIFMaster;

        Account objAcc = TestObjectCreator.objSchoolAccount;
        insert objAcc;

    }

    @IsTest
    static void IF_SFDC_IFRESH_SEND_ACCOUNT_test() {
        Account objAcc = [SELECT Id FROM Account LIMIT 1];
        List<String> listTargetAccoutId = new List<String>();
        Set<Id> setUserId = new Set<Id>();
        Map<Id, String> mapCUD = new Map<Id, String>();
        Map<Id, String> mapCUD2 = new Map<Id, String>();
        Set<String> setTargetcustId = new Set<String>();

        listTargetAccoutId.add(objAcc.Id);
        setUserId.add(UserInfo.getUserId());
        mapCUD.put(objAcc.Id,'C');
        mapCUD2.put(objAcc.Id,'U');
        setTargetcustId.add('123');

        Test.startTest();
        IF_SFDC_IFRESH_REG_ACCOUNT.doSend(listTargetAccoutId, setUserId, mapCUD, setTargetcustId);
        IF_SFDC_IFRESH_REG_ACCOUNT.doSend(listTargetAccoutId, setUserId, mapCUD2, setTargetcustId);
        IF_SFDC_IFRESH_REG_ACCOUNT.doSend(null, null, null, setTargetcustId);

        Test.stopTest();

    }
}