force-app/main/default/objects/EDMSFile__c/EDMSFile__c.object-meta.xml
<CustomObject>
    <label>EDMSFile</label>
    <nameField>
        <label>EDMSFileUpload 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDMSFile__c/fields/FileExt__c.field-meta.xml
<CustomField>
    <fullName>FileExt__c</fullName>
    <label>FileExt</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <label>TargetId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>계약서원본</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>사업자등록증</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>인감증명서(개인/법인)</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>법인등기부 등본</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>장려금약정서</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>사용인감계</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>개인정보활용동의서</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>상계처리약정서</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>계약이행완료확인서</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>계약해지합의서</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>관리처등록의뢰서</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/IFMaster__c.object-meta.xml
<CustomObject>
    <label>IFMaster</label>
    <nameField>
        <label>IFMaster Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IFMaster__c/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text/plain</fullName>
            </value>
            <value>
                <fullName>text/xml</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>multipart/form-data</fullName>
            </value>
            <value>
                <fullName>application/vnd.oracle.adf.resourceitem+json</fullName>
            </value>
            <value>
                <fullName>application/x-www-form-urlencoded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IFMaster__c/fields/WebserviceType__c.field-meta.xml
<CustomField>
    <fullName>WebserviceType__c</fullName>
    <label>WebserviceType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MDMRegRequestCustomer__c/MDMRegRequestCustomer__c.object-meta.xml
<CustomObject>
    <label>MDM 고객 등록 및 수정 요청</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>MDMRegRequestCustomer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EDMSFileUpload_test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-29-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
private class EDMSFileUpload_test {
    @testSetup
	static void setData() {

        Set<String> setIFId = new Set<String>{'IF_SFDC_EDMS_FILE_UPLOAD','IF_SFDC_EDMS_FILE_DELETE'};

        List<IFMaster__c> listIF = new List<IFMaster__c>();

        for(String str : setIFId) {
            IFMaster__c obj = new IFMaster__c();
            obj.Name = str;
            obj.ContentType__c = 'application/json';
            obj.Endpoint__c = 'https://test.salesforce.com';
            obj.Method__c = 'POST';
            obj.Type__c = 'Inbound';
            obj.WebServiceType__c = 'REST';

            listIF.add(obj);
        }

        insert listIF;
	}
    @isTest 
    static void itShould() {
        Test.startTest();



        EDMSFileUpload.doInit('test1234');

        String targetId = 'TESTID';
        String strType = '1';

        MDMRegRequestCustomer__c objCustomer = new MDMRegRequestCustomer__c();
        insert objCustomer;
        

        List<EDMSFile__c> listEDMSFile = new List<EDMSFile__c>();
        EDMSFile__c objEDMSFileExcel = new EDMSFile__c();

        objEDMSFileExcel.Name = 'Test.xlsx';
        objEDMSFileExcel.TargetId__c = objCustomer.Id;
        objEDMSFileExcel.Type__c = strType;
        objEDMSFileExcel.fileExt__c = 'xlsx';

        listEDMSFile.add(objEDMSFileExcel);

        EDMSFile__c objEDMSFilePng = new EDMSFile__c();

        objEDMSFilePng.Name = 'Test.png';
        objEDMSFilePng.TargetId__c = objCustomer.Id;
        objEDMSFilePng.Type__c = strType;
        objEDMSFilePng.fileExt__c = 'png';

        listEDMSFile.add(objEDMSFilePng);

        EDMSFile__c objEDMSFileDoc = new EDMSFile__c();

        objEDMSFileDoc.Name = 'Test.doc';
        objEDMSFileDoc.TargetId__c = objCustomer.Id;
        objEDMSFileDoc.Type__c = strType;
        objEDMSFileDoc.fileExt__c = 'doc';

        listEDMSFile.add(objEDMSFileDoc);

        EDMSFile__c objEDMSFilePDF = new EDMSFile__c();

        objEDMSFilePDF.Name = 'Test.pdf';
        objEDMSFilePDF.TargetId__c= objCustomer.Id;
        objEDMSFilePDF.Type__c = strType;
        objEDMSFilePDF.fileExt__c = 'pdf';

        listEDMSFile.add(objEDMSFilePDF);

        EDMSFile__c objEDMSFileEtc = new EDMSFile__c();

        objEDMSFileEtc.Name = 'Test.etc';
        objEDMSFileEtc.TargetId__c = objCustomer.Id;
        objEDMSFileEtc.Type__c = strType;
        objEDMSFileEtc.fileExt__c = 'etc';

        listEDMSFile.add(objEDMSFileEtc);

        insert listEDMSFile;

        EDMSFileUpload.doGetEDMSList(objCustomer.Id, strType);


        ContentVersion objContentVersion = new Contentversion();
        objContentVersion.Title = 'test';
        objContentVersion.PathOnClient = 'test.txt';
        objContentVersion.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert objContentVersion;

        objContentVersion = [
            SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =:objContentVersion.Id
        ];

        System.debug('============> objContentVersion.ContentDocumentId : '+objContentVersion.ContentDocumentId);

        EDMSFileUpload.doCreatedFileURL(objContentVersion.ContentDocumentId);

        Map<String, String> mapParam = new Map<String, String>();


        mapParam.put('recordId', objCustomer.Id);
        mapParam.put('documentId', objContentVersion.ContentDocumentId);
        mapParam.put('strType', '1');
        mapParam.put('downloadUrl', 'test');

        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        EDMSFileUpload.doSendEMDS(mapParam);


        
        // 삭제 테스트 
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock2());
        EDMSFileUpload.FileWrapper objFileWrapper = new EDMSFileUpload.FileWrapper();
        objFileWrapper.SFDCID = objEDMSFileEtc.Id;
        objFileWrapper.downloadURL = 'https://edmsqa2.ifresh.co.kr/edms/znImgsysEncrypt/getFileEnc/101/0F761604E6CD64D39AF9227B8ADCBDB70CB404503031A667535F9C0D31E9A4F1';
        EDMSFileUpload.doDeleteFile(objFileWrapper);
        delete objEDMSFileEtc;

        Test.stopTest();
    }

    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = newResponse(200);

            return response;
        }
    }

    private class HttpCalloutSuccessMock2 implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = newResponse2(200);
            return response;
        }
    }

    private static HTTPResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(statusCode);
        response.setBody('{"download_url":"https://edmsqa2.ifresh.co.kr/edms/znImgsysEncrypt/getFileEnc/101/0F761604E6CD64D39AF9227B8ADCBDB70CB404503031A667535F9C0D31E9A4F1","err_cd":"0000","err_msg_ctt":""}');
        return response;
    }

    private static HTTPResponse newResponse2(Integer statusCode) {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(statusCode);
        response.setBody('{"err_cd":"0000","err_msg_ctt":""}');
        return response;
    }

    
}