force-app/main/default/objects/EDMSFile__c/EDMSFile__c.object-meta.xml
<CustomObject>
    <label>EDMSFile</label>
    <nameField>
        <label>EDMSFileUpload 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDMSFile__c/fields/DownloadURL__c.field-meta.xml
<CustomField>
    <fullName>DownloadURL__c</fullName>
    <label>DownloadURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <label>TargetId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>계약서원본</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>사업자등록증</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>인감증명서(개인/법인)</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>법인등기부 등본</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>장려금약정서</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>사용인감계</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>개인정보활용동의서</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>상계처리약정서</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>계약이행완료확인서</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>계약해지합의서</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>관리처등록의뢰서</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EDMSFileListView_test.cls
@IsTest
public class EDMSFileListView_test {
@TestSetup
static void EDMSFileListView_testSetUp() {
    try{
        EDMSFile__c obj = new EDMSFile__c();
        obj.Name = 'test';
        obj.DownloadURL__c = 'test.com';
        obj.Status__c = 'Success';
        obj.Type__c = '1';
        obj.TargetId__c = 'testTargetId';
        insert obj;

    } catch (Exception e) {
        System.debug('EDMSFileListView_test line : ' + e.getLineNumber());
        System.debug('EDMSFileListView_test message : ' + e.getMessage());
        System.debug('EDMSFileListView_test cause : ' + e.getCause());
    }
}

@IsTest
static void EDMSFileListView_test() {
    Test.startTest();
    System.debug(EDMSFileListView.getDataTable('testTargetId'));
    System.debug(EDMSFileListView.getDataTable(null));
    Test.stopTest();
}
}