force-app/main/default/objects/EDMSFile__c/EDMSFile__c.object-meta.xml
<CustomObject>
    <label>EDMSFile</label>
    <nameField>
        <label>EDMSFileUpload 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EDMSFile__c/fields/DownloadURL__c.field-meta.xml
<CustomField>
    <fullName>DownloadURL__c</fullName>
    <label>DownloadURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/TargetId__c.field-meta.xml
<CustomField>
    <fullName>TargetId__c</fullName>
    <label>TargetId</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDMSFile__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>계약서원본</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>사업자등록증</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>인감증명서(개인/법인)</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>법인등기부 등본</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>장려금약정서</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>사용인감계</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>개인정보활용동의서</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>상계처리약정서</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>계약이행완료확인서</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>계약해지합의서</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>관리처등록의뢰서</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EDMSFileListView.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-08-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class EDMSFileListView {
    /**
     * EDMS File List Init
     * 
     * @param recordId record Id     
     * @return DataWrapper
     *          - strStatus : 상태
     *          - strMessage : 메시지
     *          - listSearchWrapper : 조회결과
     *
    **/
    @AuraEnabled
    public static DataWrapper getDataTable(String recordId) {
        String strStatus = 'SUCCESS';
        String strMessage = '';
        DataWrapper objWrapper = new DataWrapper();
        List<SearchWrapper> listSearchWrapper = new List<SearchWrapper>();
        try {
            if (recordId != null) {
                String strQuery =   '   SELECT      Id, Name, DownloadURL__c, toLabel(Status__c), tolabel(Type__c), LastModifiedBy.Name, FORMAT(LastModifiedDate)';
                strQuery +=         '   FROM        EDMSFile__c';
                strQuery +=         '   WHERE       TargetId__c =: recordId';
                strQuery +=         '   ORDER BY    LastModifiedDate desc';

                System.debug('strQuery : ' + strQuery);
                for(EDMSFile__c objEDMSFile : Database.query(strQuery)) {
                    SearchWrapper objSearch = new SearchWrapper(objEDMSFile);
                    listSearchWrapper.add(objSearch);
                }
            }else {
                strStatus = 'ERROR';
                strMessage = 'RecordId ERROR';
            }
        }catch (Exception e) {
            strStatus = 'ERROR';
            strMessage = e.getMessage() + ' Line : '+e.getLineNumber();
        }

        objWrapper.listSearchWrapper = listSearchWrapper;
        objWrapper.strStatus = strStatus;
        objWrapper.strMessage = strMessage;

        System.debug( 'objWrapper :: '  +  objWrapper);


        return objWrapper;
    }
    public class DataWrapper {
        @AuraEnabled
        public String strStatus {get;set;}
        @AuraEnabled
        public String strMessage {get;set;}
        @AuraEnabled
        public List<SearchWrapper> listSearchWrapper {get;set;}
    }

    public class SearchWrapper {
        @AuraEnabled
        public String id { get; set; }
        @AuraEnabled
        public String name { get; set; }
        @AuraEnabled
        public String status { get; set; }
        @AuraEnabled
        public String type { get; set; }
        @AuraEnabled
        public String LastModifiedUser { get; set; }
        @AuraEnabled
        public Datetime LastModifiedDate { get; set; }
        @AuraEnabled
        public String donwload { get; set; }
        @AuraEnabled
        public String downloadURL { get; set; }

        public SearchWrapper() {
        }

        public SearchWrapper(EDMSFile__c objEDMSFile) {
            this.id = objEDMSFile.Id;
            this.name = objEDMSFile.Name;
            this.status = objEDMSFile.Status__c;
            this.type = objEDMSFile.Type__c;
            this.LastModifiedUser = objEDMSFile.LastModifiedBy.Name;
            this.LastModifiedDate = objEDMSFile.LastModifiedDate;
            this.downloadURL = objEDMSFile.DownloadURL__c;
            this.donwload = '다운로드';
        }
    }
}