force-app/main/default/objects/IF_IFRESH_SFDC_INFO_ORDER_0001__c/IF_IFRESH_SFDC_INFO_ORDER_0001__c.object-meta.xml
<CustomObject>
    <label>IF_IFRESH_SFDC_INFO_ORDER_0001</label>
    <nameField>
        <displayFormat>No-{00000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_IFRESH_SFDC_INFO_ORDER_0001__c/fields/transactionId__c.field-meta.xml
<CustomField>
    <fullName>transactionId__c</fullName>
    <externalId>true</externalId>
    <label>transactionId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_IFRESH_SFDC_INFO_ORDER_0001_DEL_ba.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-19-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global without sharing class IF_IFRESH_SFDC_INFO_ORDER_0001_DEL_ba implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {

    global String transactionId;

    global IF_IFRESH_SFDC_INFO_ORDER_0001_DEL_ba(String transactionId) {
        this.transactionId = transactionId;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery = '';
        strQuery += 'SELECT     Id, transactionId__c';
        strQuery += '   FROM    IF_IFRESH_SFDC_INFO_ORDER_0001__c';        
        strQuery += '   WHERE   transactionId__c =\'' + transactionId + '\'';
        strQuery += '   AND     IsUpdate__c = true' ;

        System.debug('start batch');
        return  Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext bc, List<IF_IFRESH_SFDC_INFO_ORDER_0001__c> scope) {
        delete scope;
    }

    global void finish(Database.BatchableContext BC) {

    }
}